### ISSUE TITLE
panic observed in `needsQuoting`

### ISSUE THREAD

**Issue by ianvernon** [sirupsen/logrus#1003]
I am using logrus v1.4.1. I am observing the following panic periodically:

```
 panic: runtime error: invalid memory address or nil pointer dereference)
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x28e pc=0x12fd8de])
 goroutine 124 [running]:)
 github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).needsQuoting(0xc0000fa730, 0x28e, 0x23cb91, 0x1c))
       /go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:268 +0x4e)
 github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).appendValue(0xc0000fa730, 0xc00934e120, 0x2c78180, 0xc0091e4060))
        /go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:294 +0x6d)
 github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).appendKeyValue(0xc0000fa730, 0xc00934e120, 0x30969b2, 0x6, 0x2c78180, 0xc0091e4060))
       /go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:285 +0x90)
 github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).Format(0xc0000fa730, 0xc003dc61c0, 0xc0000b8510, 0xc000dbcb18, 0x12206b6, 0x302dfe0, 0xc000dbcb18))
       /go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/text_formatter.go:202 +0xa52)
 github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).write(0xc003dc61c0))
       /go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:255 +0x81)
 github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.Entry.log(0xc0000b84e0, 0xc00934e0f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...))
       /go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:231 +0x193)
 github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).Log(0xc003dc6150, 0xc000000004, 0xc000dbcce0, 0x1, 0x1))
       /go/src/github.com/cilium/cilium/vendor/github.com/sirupsen/logrus/entry.go:268 +0xed)
 github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*Entry).Info(...))
```

The line where the panic occurred:
https://github.com/sirupsen/logrus/blob/8bdbc7bcc01dcbb8ec23dc8a28e332258d25251f/text_formatter.go#L268

The only way I can see this being true is if the string gets overwritten to be `nil` while the function is being called. I am unsure how this can happen. No fields in the `TextFormatter`, `Entry`, etc. are being accessed or dereferenced at this line.

**Comment by freeformz** [comment]
What version of Go did this happen with? What platform / os ?
Does cilium use pointers to strings or unsafe to construct strings passed to logrus?

Looking at the stack trace:
```
github.com/cilium/cilium/vendor/github.com/sirupsen/logrus.(*TextFormatter).needsQuoting(0xc0000fa730, 0x28e, 0x23cb91, 0x1c))
```

0xc0000fa730 is the address of the TextFormatter
0x28e is the invalid address of a String (addr=0x28e in the panic header)
...

The string value being passed to needsQuoting is extracted from an `interface{}` (either by type assertion or fmt.Sprint).

This doesn't look right to me and am wondering if it's a bug in Go or a problem in cilium.
it could be I'm not reading the stack trace correctly, but things do line up.

**Comment by ianvernon** [comment]
@freeformz thank you for replying! I will get back to you re: version of Go and platform / OS.

I will paste links to the code path in which this panic occurs and summarize them below.

https://github.com/cilium/cilium/blob/a7bfafb9674b360e36a3c835ffc2fb949faa1f55/daemon/policy.go#L69-L75

which calls 

https://github.com/cilium/cilium/blob/pr/tgraf/eni-ipam/pkg/endpointmanager/manager.go#L400-L406

The panic occurs on line 406.

Collapsing the code and synthesizing the relevant parts here for ease of reading so we don't pull you too far into the weeds of our code:

```
// reasons is populated elsewhere, but its creation and population is protected via a mutex
reason := strings.Join(reasons, ", ")
regenerationMetadata := &regeneration.ExternalRegenerationMetadata{Reason: reason}
log.WithFields(logrus.Fields{"reason": regenMetadata.Reason}).Info("regenerating all endpoints")
...
```

The structure which we dereference `regenerationMetadata`  is localized to the currently running goroutine, as is the `reason` variable, which is the result of a use of `strings.Join`.

Given the above,  I cannot see how the string we pass in via our call to `WithFields` would be corrupted / malformed. Let me know if you need me to give you more context.

**Comment by ianvernon** [comment]
Output of `go version`: ```go version go1.12.7 linux/amd64```

**Comment by freeformz** [comment]
Can you provide instructions to reproduce?

**Comment by ianvernon** [comment]
@freeformz unfortunately, we have not been able to reproduce this. We can close this if you like and reopen if we find a reproducer or see it again.

**Comment by freeformz** [comment]
Thanks. I think that is a good idea.
