### ISSUE TITLE
Can I always use double quotes for all structured log field values?

### ISSUE THREAD

**Issue by montanaflynn** [sirupsen/logrus#1005]
My logging uses a simple grep style for search so when I log the following fields they both show up for search of `user-id=2`. I'd like to make it so all field values are always quoted.

Now:

```
user-id=2 user-agent=Mozilla/5.0
user-id=20 user-agent=Mozilla/5.0
```

What I'd like:

```
user-id="2" user-agent="Mozilla/5.0"
user-id="20" user-agent="Mozilla/5.0"
```

**Comment by pradykaushik** [comment]
You could write a custom formatter that escapes the quotes in the string.
Something like shown below.
```go
package main
  
import (
        "fmt"
        log "github.com/sirupsen/logrus"
        "os"
        "strings"
)

type MyFormatter struct {}

func (f *MyFormatter) Format(e *log.Entry) ([]byte, error) {
        result := []string{}
        for key, value := range e.Data {
                result = append(result, fmt.Sprintf("%s=\"%s\"", key, value))
        }
        result = append(result, e.Message)
        result = append(result, "\n")
        resultString := strings.Join(result, " ")
        return []byte(resultString), nil
}

func main() {
        log.SetFormatter(&MyFormatter{})
        log.SetOutput(os.Stdout)
        log.SetLevel(log.InfoLevel)

        log.WithFields(log.Fields{"testkey": "testvalue"}).Info("test message")
}
```

The output of running the above program is shown below.
```commandline
testkey="testvalue" test message
```

**Comment by montanaflynn** [comment]
@pradykaushik yes that's what I was looking for and ended up doing. It might be nice if the built in https://github.com/sirupsen/logrus/blob/master/text_formatter.go added a bool option to always quoute, similar to this option: 

https://github.com/sirupsen/logrus/blob/master/text_formatter.go#L66

**Comment by pradykaushik** [comment]
> @pradykaushik yes that's what I was looking for and ended up doing. It might be nice if the built in https://github.com/sirupsen/logrus/blob/master/text_formatter.go added a bool option to always quoute, similar to this option:
> 
> https://github.com/sirupsen/logrus/blob/master/text_formatter.go#L66

I agree.

**Comment by freeformz** [comment]
@montanaflynn FWIW: [logfmt](https://www.brandur.org/logfmt) (and [here](https://godoc.org/github.com/kr/logfmt)) allows for `key=value` without quotes, except for when it's needed to ensure the value side is complete.

**Comment by montanaflynn** [comment]
@freeformz thanks, but that's the opposite of what I want. I always want to quote the value for easier parsing / filtering in my log aggregator.
