### ISSUE TITLE
Proposal: Tag to indicate sensitive fields

### ISSUE THREAD

**Issue by Brcrwilliams** [sirupsen/logrus#1007]
Fields are a very useful feature of Logrus. They are excellent for providing additional context for debugging. However, they also increase the risk of accidentally logging secrets.

For example, suppose that you have a web application with a login endpoint.
You may have a data structure for the user data that looks like this:
```go
type User struct {
	Username  string
	Password  string
	Email     string
	FirstName string
	LastName  string
}
```

Then you have a handler that might look something like this:
```go
http.HandleFunc("/login", func(w http.ResponseWriter, r *http.Request) {
	user := new(User)
	body, _ := ioutil.ReadAll(r.Body)
	err := json.Unmarshal(body, user)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	token, err := login(user)
	if err != nil {
		log.WithField("user", user).Info("Authentication failed")
		w.WriteHeader(http.StatusForbidden)
		res, _ := json.Marshal(map[string]string{"error": err.Error()})
		w.Write(res)
		return
	}

	log.WithField("user", user).Info("Successful login")
	w.WriteHeader(http.StatusOK)
	res, _ := json.Marshal(map[string]string{"token": token})
	w.Write(res)
})
```

Now you have an audit history of login events, but you have the problem of passwords showing up in the logs. I would like to be able to tag a field in a struct to indicate that it is a sensitive value like so:
```go
type User struct {
	Username  string
	Password  string `sensitive:"true"`
	Email     string
	FirstName string
	LastName  string
}
```

Logrus could then check for the existence of such a tag and redact the value from fields.

**Comment by pradykaushik** [comment]
I can very much see the use of this. I have question. How easy/difficult would it be to have the same behavior by writing your own `Formatter` that filters out the *sensitive* fields from the provided struct before logging?

**Comment by dgsb** [comment]
Instead of modifying the formatter, you may want to define a specific type for password and sensitive information which could then implement the json.Marshaler interface and the Stringer interface also.

**Comment by pradykaushik** [comment]
> I suppose this feature would need be implemented on the formatter anyway (?).

Possibly. I will work on this a little bit and get back to you @Brcrwilliams .

**Comment by pradykaushik** [comment]
@Brcrwilliams you could use the `-` tag when defining the User struct as shown below.
```go
type User struct {
    Username string `json:"username"`
    Password string `json:"-"` // Note that '-' will make json marshaler completely ignore this field.
    Email string `json:"email"`
    FirstName string `json:"first-name"`
    LastName string `json:"last-name"`
}
```

Now, when you're logging user information, the password field will not show up. Here's an example program for you to test and the corresponding output.

```go
func main() {
	logger := &logrus.Logger{
		Out: os.Stdout,
		Formatter: &logrus.JSONFormatter{
			PrettyPrint: true,
		},
		Level: logrus.InfoLevel,
	}

	// Creating a user.
	user := &User{
		Username:     "johndoe",
		Password: "johndoepassword1234!@#$",
                Email: "johndoe@noreply.com",
                FirstName: "John",
                LastName: "Doe",
	}

	logger.WithFields(logrus.Fields{
		"user": user,
	}).Log(logrus.InfoLevel, "authentication failed!")
}
```

Below is the output when you run the above program.
```command-line
{
  "level": "info",
  "msg": "user information",
  "time": "2019-08-29T20:38:08-04:00",
  "user": {
    "username": "johndoe",
    "email": "johndoe@noreply.com",
    "first-name": "John",
    "last-name": "Doe"
  }
}
```

I'm guessing this is what you were looking for.

**Comment by Brcrwilliams** [comment]
@pradykaushik No, that doesn't work for me because, as I mentioned in my last comment, I still need to be able to encode these fields into JSON for purposes other than logging.

My requirements are:
1. Logs do not contain sensitive data
2. Logs are JSON
3. Sensitive data can still be encoded to JSON

I think I know how to create my own formatter that does this. Thanks for your help.

**Comment by harrisonhjones** [comment]
@Brcrwilliams did you ever create your own logger? I'd love a JSONFormatter with a `redact: bool`-esque feature.
