### ISSUE TITLE
Incorrect JSON output if Panic() called

### ISSUE THREAD

**Issue by rskumar** [sirupsen/logrus#1010]
With logger configured to output JSON formatted log, if `Panic()` is called, it shows StackTraces out of JSON. 
JSON formatting is not consistent this way as it says.

Code: `logrus.WithError(err).Panic("httpserver stopped")`

Output:
```
{"error":"listen tcp :8888: bind: address already in use","level":"panic","msg":"httpserver stopped","pkg":"httpserver","time":"2019-08-28T09:42:52.089"}
panic: (*logrus.Entry) (0xc44ba0,0xc0000de540)

goroutine 44 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000376300, 0xc0000a1d40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/rsk/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2ce
github.com/sirupsen/logrus.(*Entry).Log(0xc0000de4d0, 0x0, 0xc000135d38, 0x1, 0x1)
        /home/rsk/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xed
github.com/sirupsen/logrus.(*Entry).Panic(0xc0000de4d0, 0xc000135d38, 0x1, 0x1)
        /home/rsk/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:306 +0x55
github.com/rsk/xyz/web.(*HttpServer).startService(0xc00035c1a0)
        ...
```

I think stack frames should be either single string or embedded JSON object.

**Comment by freeformz** [comment]
FWIW: Doing so would interfere with tools that expect any panics to stdErr (like [panicparse](https://github.com/maruel/panicparse)).

**Comment by dgsb** [comment]
@rskumar this not the ouput of the logger, but the one of the panic call itself.
If you want to remove that, you'll have to implement a defer function which handle the panic somewhere in your application.

**Comment by dgsb** [comment]
@rskumar can we close this issue ?

**Comment by dgsb** [comment]
duplicates of #1048

**Comment by rskumar** [comment]
Thanks @dgsb for info.

**Comment by mitar** [comment]
I made a proposal to golang to allow formatting panic messages as JSON. I think you might be interested in it: https://github.com/golang/go/issues/40238
