### ISSUE TITLE
when hook is using goroutine, set output to Discard will fail sometimes

### ISSUE THREAD

**Issue by hellflame** [sirupsen/logrus#1012]
version v1.4.2

```golang
type hook struct {
}

func (h *hook) Fire (entry *logrus.Entry) error{
	go func() {
		s, _ := entry.String()
		fmt.Println("here is the msg:", s)
	}()
	return nil
}

func (h *hook) Levels() []logrus.Level {
	return logrus.AllLevels
}

func logger(){
	logrus.SetFormatter(&logrus.JSONFormatter{})
	logrus.AddHook(&hook{})
	logrus.SetOutput(ioutil.Discard)

	logrus.Info("should not appear")

	time.Sleep(2 * time.Second)
}

func main() {
	logger()
}

```

the output is sometimes ok:

```
here is the msg: {"level":"info","msg":"should not appear","time":"2019-09-01T09:53:39+08:00"}
```

but sometimes is not:

```
here is the msg: {"level":"info","msg":"should not appear","time":"2019-09-01T09:53:42+08:00"}
{"level":"info","msg":"should not appear","time":"2019-09-01T09:53:42+08:00"}
```

guess the hook is the problem, but should it trouble the global `logrus` ?

**Comment by freeformz** [comment]
The race condition is [here](https://github.com/sirupsen/logrus/blob/de736cf91b921d56253b4010270681d33fdf7cb5/json_formatter.go#L106-L110) / [here](https://github.com/sirupsen/logrus/blob/de736cf91b921d56253b4010270681d33fdf7cb5/entry.go#L226-L233).

Sometimes when String() is called the entry's buffer is nil, sometimes it's not. When it's the later the message gets serialized into the buffer twice.

**Comment by edoger** [comment]
Entry.Logger.Formatter.Format() needs to be atomic or protected by mutex.

**Comment by dgsb** [comment]
The hook interface is probably not documented enough, but you cannot expect to be able to use this given entry in an async closure, this is incompatible with the lifecycle of the entry.
If a hook want to capture an entry to do something with in a thread, it should duplicate it in the the context of the Hook callback with `Entry.Dup` API
