### ISSUE TITLE
Panic on nil error struct with JSONFormatter

### ISSUE THREAD

**Issue by haikuoliu** [sirupsen/logrus#1018]
Hi,

We will be using logrus in production, our use case is we define a struct that implements `error` interface like `MyError` (see example below), and we want to log `MyError`, but sometimes `MyError` could be nil. Without setting `JSONFormatter`, logrus works fine even if `MyError` is nil, but after setting `JSONFormatter`, the program will panic when `MyError` is nil. Not sure if this is by design, but from a user perspective the behavior shouldn't be changed with `JSONFormatter`.

Is there any plan to fix this or any work around? Thank you!

```
package main

import (
        "github.com/sirupsen/logrus"
)

type MyError struct {
}

func (err MyError) Error() string {
        return ""
}

func main() {
        logrus.SetFormatter(&logrus.JSONFormatter{
                TimestampFormat: "2006-01-02T15:04:05.000",
        })

        var err *MyError
        err = nil
        logrus.WithField("err", err).Info("hello")
}
```

**Comment by matthinrichsen-wf** [comment]
I believe you've run into https://dev.to/pauljlucas/go-tcha-when-nil--nil-hic

Wrapping a nil pointer into an interface (as what happens with `WithField`) nil checks to no longer succeed.

I assume you have functions that return errors, so one way to get around this is to always assign and return the builtin `error` type:

```go
package main

import (
        "github.com/sirupsen/logrus"
)

type MyError struct {
}

func (err MyError) Error() string {
        return ""
}

func main() {
        logrus.SetFormatter(&logrus.JSONFormatter{
                TimestampFormat: "2006-01-02T15:04:05.000",
        })

        err := someFunctionThatMightError()
        logrus.WithField("err", err).Info("hello")

        logrus.WithField("err", err).Info("hello")
}

func someFunctionThatMightError() error {
        if someConditionMet {
                return &MyError{}
        }
        return nil
}
```

**Comment by haikuoliu** [comment]
@majimboo 

Thanks for your explanation, it's really helpful. 

But the thing that I don't understand is, why logrus converts everything that implements the `Error` method to `error` interface. In our case, `MyError` could include something else like below:

```
type MyError struct {
        MyField string
}
```

`MyField` will never be printed by logrus if `MyError` implements `Error` method. In my opinion, a struct can implement `error` interface, but it can implement a lot of other interfaces, if logrus treat it only as `error`, it will lose a lot of other information.

Let me know if it makes sense, thank you!

**Comment by matthinrichsen-wf** [comment]
Ah yes! So this has to do with the fall-thru on the JSON formatters type switch:
https://github.com/sirupsen/logrus/blob/master/json_formatter.go#L60

```go
	for k, v := range entry.Data {
		switch v := v.(type) {
		case error:
			// Otherwise errors are ignored by `encoding/json`
			// https://github.com/sirupsen/logrus/issues/137
			data[k] = v.Error()
		default:
			data[k] = v
		}
	}
```

In this case, since the first (and only) case which `v` satisfies is `case error`. Go doesn't try to find the best matching type - only the first matching type.

Consider, https://play.golang.org/p/aAu33bADSPe, even though I have the explicit type in the type switch, Go finds the `case error` first and falls into that case.

**Comment by haikuoliu** [comment]
@matthinrichsen-wf Thanks! I guess this is by design, we already found a solution from our side, closing this issue.
