### ISSUE TITLE
Use custom getCaller?

### ISSUE THREAD

**Issue by afLnk** [sirupsen/logrus#1020]
In my project, previous log like log_p.Errorf(ctx, args...), and we plan to switch to logrus. But he file and line is incorrect.  I read the codes, is is possible to change the flowing code from:
[https://github.com/sirupsen/logrus/blob/master/entry.go](https://github.com/sirupsen/logrus/blob/master/entry.go):220

```go
if entry.Logger.ReportCaller {
	entry.Caller = getCaller()
}
```
to
```
if entry.Logger.ReportCaller && entry.Caller == nil{
        entry.Caller = getCaller()
}
```

**Comment by freeformz** [comment]
I suggest closing this in favor of #972
