### ISSUE TITLE
Deleting log file (linux)

### ISSUE THREAD

**Issue by LazarenkoA** [sirupsen/logrus#1023]
I create file and sets it in logrus

``` go
tmp, _ := os.OpenFile(filepath.Join(dir, "Log_"+time.Now().Format("15.04.05")), os.O_CREATE|os.O_WRONLY, os.ModeAppend)
logrus.SetOutput(tmp)
```
In Windows, the file cannot be deleted, but in Linux, you can, maybe to create file somehow especially?

![](https://i.imgur.com/jYRTSX8.gif)

**Comment by LazarenkoA** [comment]
As you can see in gif, file is constantly being recorded, but the file was deleted

**Comment by freeformz** [comment]
The program would need to be running as a service via https://godoc.org/golang.org/x/sys/windows/svc,  use windows tools to tell it to reload, and have a [Handler](https://godoc.org/golang.org/x/sys/windows/svc#Handler) that handles a reload request.

That reload request would open a new file, use SetOutput to tell logrus to start logging to the new file, then close the old file.

I don't really write windows programs, so can't offer any more guidance there.

**Comment by freeformz** [comment]
On Linux you would do the same thing, just a different way, but setting up a [signal handler](https://golang.org/pkg/os/signal/) that listens for a signal (like SIGHUP), opens a new file, uses SetOutput to start logging to the new file, then close the old file.

**Comment by LazarenkoA** [comment]
On the contrary, I do not want the Linux file to be deleted, now it is possible

**Comment by freeformz** [comment]
@LazarenkoA Sorry, maybe I don't understand what you want to do then?

**Comment by LazarenkoA** [comment]
I want the file to not be deleted while it is recording

**Comment by freeformz** [comment]
What is deleting the file?

**Comment by LazarenkoA** [comment]
The problem is this.
When my application write logs (using logrus), the user can delete the entire directory where the logs are written. (Linux in otlitsiya from Windows gives it to do)
After the file is deleted (the file that is installed via logrus.SetOutput) a new file is not created and in fact nothing is logged.

**Comment by dgsb** [comment]
I don’t think we can do anything to solve your problem, this how most of
file systems work under Unix like operating system.
A already opened file descriptor can still written without notice even if
the file has been removed.

**Comment by LazarenkoA** [comment]
OK, thanks

**Comment by freeformz** [comment]
Yeah, if the user has permissions to delete the file/dir it would work, but the logging will still continue to the open file descriptor. That is how files under most UNIX operating systems work.

You *could* do something crazy using [fsnotify](https://github.com/fsnotify/fsnotify) to get notified if the file or directory is deleted though, then do *something* in response to that. Something like: re-create the directdory/file and tell logrus to use the newly (re)created file; exit the program with an error; just stop logging; etc.
