### ISSUE TITLE
How to log any type of golang crash

### ISSUE THREAD

**Issue by sriram275** [sirupsen/logrus#1027]
Hi,

Is there a way to log all types of golang crash. Currently golang is crashing but there are no logs in my log file.

Thanks

**Comment by freeformz** [comment]
How is your go program "crashing"? Is it a panic?

**Comment by sriram275** [comment]
No idea, there are no logs to analyze. The only things we can suspect is we are making 2000 post api calls continiously and in golang code we are using **client.Do** for http calls. At somepoint it is crashing and there are no logs. 

Each Api call takes 10-15s to get response. So all calls will be in queue waiting for response from the third party server which we made calls through **client.Do** from golang.

Want to logout any type of crah so not sure wether it is panic..or file descriptors issue ( since we are not closing any connection with defer **response.body.close()** ).

Thanks.

**Comment by freeformz** [comment]
If you suspect it's a panic, then you have to wrap the thing that would panic with a defer'd function that recovers from the panic, logs it and re-panics (or does something else).

Super contrived example: https://play.golang.org/p/5PyUKQARoOR

See also: https://blog.golang.org/defer-panic-and-recover

FWIW: This type of abnormal program execution should be logged / handled by whatever is executing the program and you should not try to handle this type of issue inside of the program itself. At least that is my opinion if I am understanding you correctly.

**Comment by sriram275** [comment]
Yes.
Thanks. Closing this issue.

**Comment by aohanhongzhi** [comment]
maybe you can redirect stdout .for example:

```shell
nohup /home/app/your-go-app >> panic.log  2>&1 &
```
