### ISSUE TITLE
Using Panic Loglevel without Calling Panic

### ISSUE THREAD

**Issue by jonmchan** [sirupsen/logrus#1028]
Is there a way to do make a panic level log entry without calling the panic function? My usecase is that I am writing code to `recover()` from a panic, so I just want to log the panic, not call the panic again.

If I cannot log as panic, I will end up having to log at a lower level, like error which doesn't seem to make sense to me?

Thanks for any help on this.

**Comment by freeformz** [comment]
This is what I came up with (it's not pretty): https://play.golang.org/p/m6_8q4LVf2Q

FWIW: I expected `entry.Println()` to *not* override the set level. I'm not sure that is something that can be changed in the v1 time cycle though, or even if it should since logrus.Println documents the behavior as `at level Info`

**Comment by jonmchan** [comment]
Wow, that's pretty inventive... so let me see if I understand this correctly - you're getting around this by not calling any of the actually logging calls to avoid firing the panic in https://github.com/sirupsen/logrus/blob/master/entry.go#L238. Instead, you're extracting the log to a string and directly putting it into Stderr?

**Comment by freeformz** [comment]
That and it gives you the output like so:
```
time="0001-01-01T00:00:00Z" level=panic recovered=OMG
```

If you didn't care about `level=panic` you could do this instead: https://play.golang.org/p/Zq6d9ENoOi2

Which would give you this:
```
time="2009-11-10T23:00:00Z" level=info recovered=OMG
```

**Comment by freeformz** [comment]
Actually, you can just do this if you don't want the `level=panic`:
https://play.golang.org/p/_okHoycdpJt

```
time="2009-11-10T23:00:00Z" level=info msg=hello recovered=OMG
```

**Comment by freeformz** [comment]
But either way Fatal or Panic will os.Exit(1) or panic(), so if you need `level={fatal,panic}` then you have to go through some hoops to get it. This is probably a "good thing" (™).

**Comment by freeformz** [comment]
I think it's reasonable to have Panic() panic and Fatal() exit. If I were looking at logs and saw something with level=panic or level=fatal, I would assume the process panic'd or exited. The handler above is capturing the panic and treating it like an error and that is what logrus is logging it as.

PS: What is preventing you from using another field to mark these errors as more important than other errors?

**Comment by jonmchan** [comment]
@freeformz:

Point being is I want to log it as a panic, the stacktrace would be all wrong - it would log the recover code rather than where the panic actually was thrown. Also, 2 panics will be unnecessarily thrown.

nothing is preventing me from using another field - which is what I am currently using in production... but isn't the whole point of using logrus - to have structured log entries? If we aren't using the designated fields, it defeats the whole purpose imho.

**Comment by dgsb** [comment]
somehow related to #993 
We cannot change behaviour in v1, so we definitely need to improve the documentation.

**Comment by dgsb** [comment]
panic is supposed to call panic, that's the itended behaviour.
