### ISSUE TITLE
Comment in hooks/test/test.go Package Out of Date

### ISSUE THREAD

**Issue by jonmchan** [sirupsen/logrus#1029]
```
// The Test package is used for testing logrus. It is here for backwards
// compatibility from when logrus' organization was upper-case. Please use
// lower-case logrus and the `null` package instead of this one.
```
https://github.com/sirupsen/logrus/blob/master/hooks/test/test.go#L1-L3

The null package no longer exists? Last seen here:

https://github.com/sirupsen/logrus/blob/acfabf31db8f45a9174f54a0d48ea4d15627af4d/hooks/null/null.go

Probably should remove or update this comment? It seems like this is the only package that exists at the moment for accessing the null logger and test logger.

**Comment by freeformz** [comment]
Thanks for reporting!
