### ISSUE TITLE
Firing a hook only once rather than each time when logging something

### ISSUE THREAD

**Issue by BentCoder** [sirupsen/logrus#1031]
Hi,

Is there a way of firing a hook only once (_e.g. when we boot the app_) rather than firing every when we log something?

Thanks

```go
var o sync.Once

func BootOnce(level uint32) {
	o.Do(func() {
		logrus.SetLevel(logrus.Level(level))
		logrus.SetOutput(os.Stdout)
		logrus.SetFormatter(&logrus.JSONFormatter{
			FieldMap: logrus.FieldMap{
				logrus.FieldKeyMsg: "message",
			},
		})

		logrus.AddHook(defaultFields{
			env: func() string { return env },
		})
	})
}

type defaultFields struct {
	env func() string
}

func (df defaultFields) Levels() []logrus.Level {
	return logrus.AllLevels
}

func (df defaultFields) Fire(e *logrus.Entry) error {
	fmt.Println("Fired")

	e.Data["env"] = df.env()

	return nil
}
```

**current**
```bash
Fired
{.... a log ...}
Fired
{.... another log ...}
Fired
{.... and another log ...}
```

**aim**
```bash
Fired
{.... a log ...}
{.... another log ...}
{.... and another log ...}
```

**Comment by freeformz** [comment]
Write a hook who's Fire function contains a sync.Once.Do() ?

Example: https://play.golang.org/p/m5rvn2gLtmp

**Comment by BentCoder** [comment]
My bad. I didn't make it clear. Once it is fired, the custom field `env` will always be in the logs so not only when it is fired.

**Comment by freeformz** [comment]
There are at least two different ways to do this. I recommend the first one as it sets you up for always injecting the logger and not relying on a global logger.

1. https://play.golang.org/p/bdJIcdz4ca6 : capture the value of logrus.WithField and use that as your logger.
2. https://play.golang.org/p/RLMTH7g9xXA : Have a hook always add a key if the entry doesn't exist already.

**Comment by BentCoder** [comment]
For now I'll go with the second option as it is easier to integrate with the current structure. However, I'll keep the first option in my mind. Thanks for taking time to provide useful answers!
