### ISSUE TITLE
(CVSS 5.9) Vulnerability due to usage of golang.org/x:crypto:0.0.0-20180904163835-0709b304e793 worth looking into?

### ISSUE THREAD

**Issue by TimSatke** [sirupsen/logrus#1035]
DepShield just showed me the vulnerability here: gojisvm/gojis#75

It would be nice if this, if possible, could get a fix in the next version, if you think this is worth fixing.
A dependency upgrade should do the trick.

**Comment by freeformz** [comment]
Current versions of logrus do not use any version of golang.org/x's crypto package.

AFAICT something in this chain is using an old version of logrus:
```console
viper git:(v1.4.0) $ go mod why github.com/sirupsen/logrus                    
# github.com/sirupsen/logrus
github.com/spf13/viper/remote
github.com/xordataexchange/crypt/config
github.com/xordataexchange/crypt/backend/etcd
github.com/coreos/etcd/client
github.com/coreos/etcd/client.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/embed
github.com/tmc/grpc-websocket-proxy/wsproxy
github.com/sirupsen/logrus
```

This appears to be coming from github.com/coreos/etcd

```console
etcd git:(master) $ ack logrus
go.sum
116:github.com/sirupsen/logrus v1.2.0 h1:juTguoYk5qI21pwyTXY3B3Y5cOTH3ZUyZCg1v/mihuo=
117:github.com/sirupsen/logrus v1.2.0/go.mod h1:LxeOpSwHxABJmUn/MG1IvRgCAasNZTLOkJPxbbu5VWo=
```

Which is coming from: github.com/xordataexchange/crypt ... etc

**Comment by freeformz** [comment]
PS: This isn't really a logrus issue (anymore), your downstream dependencies are using older versions of logrus. My suggestion is to upgrade logrus via:

```console
$ go get github.com/sirupsen/logrus
```

Doing this should update both logrus and pflag (or at least it did so for me locally).

**Comment by TimSatke** [comment]
Thanks for the input.
