### ISSUE TITLE
Help, I want display log message in test 

### ISSUE THREAD

**Issue by imjuni** [sirupsen/logrus#1036]
Hello, 

I want logrus log message display in my test.

I create temp repo: https://github.com/imjuni/logrusTest

```
package tools

import (
	"fmt"

	"log"

	"github.com/sirupsen/logrus"
)

// Hello hello function for testing
func Hello(who string) string {
	logrus.Debug("I want disply!! plz")

	// Plz help, I want same behavior
	log.Printf("This log message displayed!")

	return fmt.Sprintf("hello %s!", who)
}
```

log.Printf function display message in my test but logrus message don't display any message. I found many example and article but I can't found valid solution. I set logrus hook for test, but not works.

```
import (
	"testing"

	"github.com/sirupsen/logrus/hooks/test"
	"imjuni.logrustest.com/tools"
)

func TestHello(t *testing.T) {
	test.NewGlobal()

	// log message not displayed
	tools.Hello("world")
}
```

Thank you!

**Comment by pradykaushik** [comment]
Be default the minimum logging level is set to `logrus.InfoLevel`. That is why `logrus.Debug(...)` is not going to log anything as `logrus.DebugLevel` < `logrus.InfoLevel`. Only levels >= than the set level are allowed.
Change `hello_test.go` to the below code and it will work.
```go
package tools_test

import (
        "testing"

        "github.com/sirupsen/logrus/hooks/test"
        "github.com/sirupsen/logrus"
        "imjuni.logrustest.com/tools"
)

func TestHello(t *testing.T) {
        test.NewGlobal()

        // log message not displayed
        logrus.SetLevel(logrus.DebugLevel)
        tools.Hello("world")
}

```

**Comment by imjuni** [comment]
@pradykaushik Thanks you for your answer

I solve my problem via your comment

Add code snippet my project

```
func init() {
	logrus.SetLevel(logrus.DebugLevel)
	logrus.SetFormatter(&logrus.JSONFormatter{})
}
```

after display log message

**Comment by freeformz** [comment]
@imjuni FWIW: For testing I generally recommend creating your own instance of logrus.Logger and setting it's `Out` to a bytes.Buffer, then using the buffer's String() method to capture the output and compare it to expected output. Example: https://play.golang.org/p/oigp-_I_rB_U

This can also be done by managing with the global logger via [`SetOutput`](https://godoc.org/github.com/sirupsen/logrus#SetOutput), but then the tests aren't parallelizable.

**Comment by imjuni** [comment]
@freeformz Thang you for your kindness! I check your example and that is very helpful! Thank you!
