### ISSUE TITLE
WithField does not add fields to log message

### ISSUE THREAD

**Issue by utdrmac** [sirupsen/logrus#1039]
Example:
```
t := log.WithField("option1", "name")
t.WithField("option2", 44)
t.WithField("option3", "nancy")
t.Info("Stuff")
```
Expected Output:
`INFO[0000] Stuff                                         option1=name option2=44 option3=nancy`

Actual Output:
`INFO[0000] Stuff                                         option1=name`

What happened to the other fields? Why were they not appended?

**Comment by utdrmac** [comment]
This produces expected result. This does NOT seem like the intended way to code though:
```
t := log.WithField("option1", "name")
t = t.WithField("option2", 44)
t = t.WithField("option3", "nancy")
t.Info("Stuff")
```
`INFO[0000] Stuff                                         option1=name option2=44 option3=nancy`

**Comment by utdrmac** [comment]
The expected behavior, based on reading the documentation, is that one can call WithField/WithFields repeatedly and they will be appended to the internal slice. Once Info/Error/Warn/etc are called, all queued up fields are displayed and the internal slice is reset.

**Comment by pradykaushik** [comment]
AFAIK this is the intended behavior.
Fields pertain to the message that is currently being logged and should not persist for future logs. This is why [logrus.WithField](https://github.com/sirupsen/logrus/blob/master/entry.go#L110) returns [a new entry that contains the fields to be logged](https://github.com/sirupsen/logrus/blob/master/entry.go#L142). The original entry is left untouched.

The right way to use it would be.
```go
logrus.WithField("key", "value").Info("test message") // single field.
logrus.WithFields(logrus.Fields{key: value, key2: value2}).Info("test message") // multiple fields.
```

**Comment by utdrmac** [comment]
I get that is the intended behavior, but that's not how it is described in the documentation, nor within the code comments for those two functions.

Before I switched to using logrus (it's been 3 days since I started migrating our code), I would have done something like this:

```
var m string
for i := range someSlice {
  m += fmt.Sprintf("another message to add %d", i)
}
log.Println(m)
```

I don't want a separate line for each range-d item. I just want 1 log line, containing all that info. I thought I could just "append" fields using WithField, and then after the range do a .Info() to print out all those fields.
What's the proper way to convert this?

**Comment by pradykaushik** [comment]
Fields are different from messages. Log messages are typically just strings while Fields are key-value pairs.
Typically, if you want to add a bunch of fields to your log message, then you can do this.
```go
var fields = logrus.Fields{}
// assuming key is "key<i>" and value is <i>.
for i := range someSlice {
    fields[fmt.Sprintf("key%s",i)] = i
}
logrus.WithFields(fields).Info("test message")
```

If you just want to concatenate strings to form the log message ( which seems like what you're doing in the example you showed ), it'd suggest just use `bytes.Buffer` as shown below.
```go
var m bytes.Buffer
for i := range someSlice {
  m.WriteString(fmt.Sprintf("another message to add %d\n", i))
}
logrus.Info(m)
```

Does this clarify your question?

**Comment by freeformz** [comment]
@utdrmac 

This is the expected use (more or less): https://play.golang.org/p/DPV8DTCOxIB

Notice how the WithField call is captured as the logger and then passed to another type with that captures context (app=example). This allows types to pass a logger down to other types/packages that is already configured with the appropriate context.

**Comment by freeformz** [comment]
@utdrmac Can you link to the documentation that led you to your conclusion? I want to make sure it's clarified as much as possible.

**Comment by dgsb** [comment]
It's stated here that the log should be issued on the returned entry https://godoc.org/github.com/sirupsen/logrus#WithField
Would you like to have that more emphasized ?

There is also an example in the README on how to use a logger with static field added in the example section https://github.com/sirupsen/logrus/blob/master/README.md#example
Is it clear enough or would you like something different ?

**Comment by utdrmac** [comment]
https://github.com/sirupsen/logrus/blob/67a7fdcf741f4d5cee82cb9800994ccfd4393ad0/logger.go#L103
To me, this implies that I can call WithField alone, repeatedly, and it will continue to append fields until I actually call Debug/Info/Print/etc, at which all fields would be printed on a single output line.

**Comment by dgsb** [comment]
Indeed the documentation on this method is lame.
What about this instead #1060 ?
