### ISSUE TITLE
Failed to write to log, invalid argument

### ISSUE THREAD

**Issue by fcddk** [sirupsen/logrus#1044]
{"level":"error","msg":"get taskList error: dial tcp: lookup tcp/畬: getaddrinfow: The specified class was not found.","time":"2019-10-17 16:22:59","type":"debug"}

package: logrus
code:
func (entry *Entry) write() {
	entry.Logger.mu.Lock()
	defer entry.Logger.mu.Unlock()
	serialized, err := entry.Logger.Formatter.Format(entry)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to obtain reader, %v\n", err)
	} else {
		_, err = entry.Logger.Out.Write(serialized)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to write to log, %v\n", err)
		}
	}
}

**Comment by fcddk** [comment]
dial tcp failed  then  log write

**Comment by fcddk** [comment]
go sync pool.go :  unreadable: unknown or unsupported kind: "invalid"

**Comment by freeformz** [comment]
@fcddk Can you provide a reliable reproducer of this issue? What version of logrus is this with? If it's not with the most recent version, please upgrade and see if it is still a problem.

Thanks!

**Comment by fcddk** [comment]
func (c *MySqlClient) GetUpdaterInfoPage(pageNo int, pageSize int) (infoList []*models.UpdaterInfo, err error) {
	err = c.engine.Table(g.UPDATER_INFO_TABLE).Limit(pageSize, (pageNo-1)*pageSize).Find(&infoList)
	if err != nil {
		log.Error(fmt.Sprintf("get updaterInfo by page error: %s", err.Error()))
		return nil, err
	}
	log.Info(fmt.Sprintf("get updaterInfo by page: %v", infoList))
	return
}
var (
	log = middleware.GetLogger()
)

type Logger struct {
	l *logrus.Logger
}

var (
	logger = InitLogger()
	log    = &Logger{
		l: logger,
	}

	config = utils.GetConfig()
)

**Comment by fcddk** [comment]
then i create a GET request:
db tcp failed,    err occurs and failed to write to log, Failed to write to log, invalid argument.

{"level":"error","msg":"get taskList error: dial tcp: lookup tcp/畬: getaddrinfow: The specified class was not found.","time":"2019-10-17 16:22:59","type":"debug"}
{"level":"info","msg":"get tasks: []","time":"2019-10-17 16:22:59","type":"debug"}
{"level":"error","msg":"get task list failed: dial tcp: lookup tcp/畬: getaddrinfow: The specified class was not found.","time":"2019-10-17 16:22:59","type":"debug"}
{"client_ip":"::1","latency_time(seconds)":0.0119686,"level":"info","msg":"","req_method":"GET","req_uri":"/cms/agent/v1/tasks/page/1/10","status_code":500,"time":"2019-10-17 16:22:59","type":"trace"}
{"level":"error","msg":"get taskList error: dial tcp: lookup tcp/畬: getaddrinfow: The specified class was not found.","time":"2019-10-17 16:23:03","type":"debug"}
{"level":"info","msg":"get tasks: []","time":"2019-10-17 16:23:03","type":"debug"}
{"level":"error","msg":"get task list failed: dial tcp: lookup tcp/畬: getaddrinfow: The specified class was not found.","time":"2019-10-17 16:23:03","type":"debug"}
{"client_ip":"::1","latency_time(seconds)":0.004984,"level":"info","msg":"","req_method":"GET","req_uri":"/cms/agent/v1/tasks/page/1/10","status_code":500,"time":"2019-10-17 16:23:03","type":"trace"}
{"level":"error","msg":"get taskList error: dial tcp: lookup tcp/畬: getaddrinfow: The specified class was not found.","time":"2019-10-17 16:23:16","type":"debug"}
{"level":"info","msg":"get tasks: []","time":"2019-10-17 16:23:16","type":"debug"}
{"level":"error","msg":"get task list failed: dial tcp: lookup tcp/畬: getaddrinfow: The specified class was not found.","time":"2019-10-17 16:23:16","type":"debug"}
{"client_ip":"::1","latency_time(seconds)":0.0029916,"level":"info","msg":"","req_method":"GET","req_uri":"/cms/agent/v1/tasks/page/1/10","status_code":500,"time":"2019-10-17 16:23:16","type":"trace"}
{"level":"error","msg":"get taskList error: dial tcp: lookup tcp/畬: getaddrinfow: The specified class was not found.","time":"2019-10-17 16:23:17","type":"debug"}
{"level":"info","msg":"get tasks: []","time":"2019-10-17 16:23:17","type":"debug"}

**Comment by yinggaozhen** [comment]
@fcddk 你的代码片段排版看上去不太清晰，把代码裹在 `golang` 标签中会不会好一点?

~~~
```golang
// CODE
```
~~~

**Comment by fcddk** [comment]
Should be the old version of the problem, changed the latest version of the code, the code “Failed to write to log, invalid argument” disappears

**Comment by fcddk** [comment]
but i also  want to known the reason of the error "Failed to write to log, invalid argument".

**Comment by freeformz** [comment]
It may be because, if the code above is accurate, `log` could *either* be the result of ` &Logger{...` **or** `middleware.GetLogger()`.

Since that isn't a *complete* reproducer there isn't much more commentary/guidance/troubleshooting I can provide.
