### ISSUE TITLE
What panic log will look like?

### ISSUE THREAD

**Issue by adzimzf** [sirupsen/logrus#1048]
When using the `panic` method to logging, does it print the stack trace?
if it print the stack trace, what will it look like? because stack trace for panic is very important in production.

**Comment by dgsb** [comment]
the logger.Panic method call the builtin panic in the end.
so you can expect to have the usual panic behaviour which may end printing the stack trace if there is no recover somewhere in a defer function.

**Comment by adzimzf** [comment]
Thanks @dgsb ,
What is the best method to print stack trace in Logrus?

**Comment by dgsb** [comment]
@adzimzf if you want to print the stack trace instead you need to implement somewhere in your stack a defer handler which will use a recover()
Then you can retrieve the source point of the panic and print it with logrus.
But beware, it will change the control flow of your program as an unhandled panic stop your program, but it won't if it is recovered in a defer handler.

You can look at this for more information 
https://stackoverflow.com/questions/52103182/how-to-get-the-stacktrace-of-a-panic-and-store-as-a-variable
https://groups.google.com/forum/#!topic/golang-nuts/MB8GyW5j2UY

**Comment by dgsb** [comment]
@adzimzf can we close this issue ?

**Comment by adzimzf** [comment]
thanks

**Comment by mitar** [comment]
I made a proposal to golang to allow formatting panic messages as JSON. I think you might be interested in it: https://github.com/golang/go/issues/40238
