### ISSUE TITLE
Loss precision when log a big float64 value with JSONFormatter

### ISSUE THREAD

**Issue by brotherbin** [sirupsen/logrus#1059]
my code for testing
```golang
package main

import (
	"fmt"
	log "github.com/sirupsen/logrus"
)

func main() {
	log.SetFormatter(&log.JSONFormatter{})
	bigvalue := float64(72059002787201136)
	fmt.Printf("original value: %.0f\n", bigvalue)
	log.WithFields(log.Fields{
		"bigvalue": bigvalue,
	}).Info("testing json format float64")
}
```
the output of logurs is 72059002787201140,  but the original value is 72059002787201136
```
original value: 72059002787201136
{"bigvalue":72059002787201140,"level":"info","msg":"testing json format float64","time":"2019-10-28T21:38:33+08:00"}
```

**Comment by dgsb** [comment]
Hi @brotherbin, thanks for your issue.
We'll check that, but I'm afraid we can't do much on this issue.
We totally rely on the standard lib json encoder for the json formatter, I'm afraid the issue is there.

**Comment by shcabin** [comment]
72059002787201136 > Number.MAX_SAFE_INTEGER
JSON only supports number, no int64

**Comment by brotherbin** [comment]
> 72059002787201136 > Number.MAX_SAFE_INTEGER
> JSON only supports number, no i

**Comment by brotherbin** [comment]
@sohlich I got it, thank you
