### ISSUE TITLE
go.mod上的名字有问题？

### ISSUE THREAD

**Issue by chaser24** [sirupsen/logrus#1061]
go: github.com/ansible-semaphore/semaphore/api imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus

**Comment by dgsb** [comment]
you need to open an issue in the `github.com/ansible-semaphore/semaphore` repository.
The import path they are using is incorrect.
it should be `github.com/sirupsen/logrus` (notice the lower-case s)

**Comment by dgsb** [comment]
@chaser24 did you open an issue at ansible-semaphore/semaphore project for them to update the logrus import path case formatting ?
