### ISSUE TITLE
Using Logrus as log.Logger (ErrorLog) in net/http

### ISSUE THREAD

**Issue by BentCoder** [sirupsen/logrus#1063]
Hi,

Core `net/http` package uses `ErrorLog` to accepts logging package - [here](https://golang.org/pkg/net/http/#Server).  Is there any way of using logrus for it?

[This](https://github.com/sirupsen/logrus#logger-as-an-iowriter) seems a bit superficial to me and I don't understand what `..it is your responsibility to close it.` is supposed to mean. A full example would mean more.

Thanks

**Comment by dgsb** [comment]
`logger.Writer` returns the writer part of a pipe (see https://golang.org/pkg/io/#Pipe). The reader part is kept at logrus side and is read by a go routine which will then write the received data in the logrus.Logger.

Regarding the close part, it means you have to close the returned writer (`writer.Close`) as long as it it not used anymore hence when your server has been closed.
The writer is also closed by a finalizer, but you may want anyway to close it explicitely if you have an intensive use a file descriptor and you do not want to have one open waiting for the gc to run.

**Comment by BentCoder** [comment]
That sounds very cumbersome.
