### ISSUE TITLE
Logging structured error

### ISSUE THREAD

**Issue by pellared** [sirupsen/logrus#1067]
# What
I want to log the error with some contextual data (like a model for which validation has failed) in a structured way. However, I do not want to log it when the error occurs, but in one place where I handle the errors.
Quoting: https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully:
>you should only handle errors once

# Question
How can/should I implement it?

# How I do it now
Currently, I pass the stuff that I want to log and warp it the error. Then I have a custom formatter which unwraps the error and add the stuff into log entry fields. See: https://godoc.org/github.com/logrusutil/v1/errfield#example-package--Basic

**Comment by pradykaushik** [comment]
You could potentially add a hook that accumulates errors, when fired, in a data structure accessible within your codebase. The accumulated errors, along with fields if any, can be logged structurally whenever required.

For more information on hooks
 https://github.com/sirupsen/logrus/blob/master/hooks.go#L3
 https://github.com/sirupsen/logrus/blob/master/hook_test.go

**Comment by rpajak-solarwinds** [comment]
Thank you a lot @pradykaushik 

So far I have created a custom Formatter to do this: https://github.com/go-logrusutil/logrusutil/blob/master/errfield/formatter.go

Any reasons to use the Hook instead? The benefit is there is no need to specify the parent/base formatter. However, it requires implementing `Levels()` instead.

**Comment by pellared** [comment]
Thank you a lot @pradykaushik 

So far I have created a custom Formatter to do this: https://github.com/go-logrusutil/logrusutil/blob/master/errfield/formatter.go

Any reasons to use the Hook instead? The benefit is there is no need to specify the parent/base formatter. However, it requires implementing `Levels()` instead.

**Comment by pradykaushik** [comment]
You had mentioned that you did not want to log the error when it occurs. I figured that you want to analyze the errors separately (possible in a go routine that is run as a cron job). This is why I suggested using Hooks so that you can get access to the errors and store them for later use.

**Comment by gguridi** [comment]
I just want to do my bit... 

I think the easier way is to simply write a function that extracts the fields for logrus:

```go
import (
   "github.com/sirupsen/logrus"
   "github.com/logrusutil/v1/errfield"
)

func GetErrorFields(err error) logrus.Fields {
	var e *errfield.Error
	if errors.As(err, &e) {
                 //e.Fields are map[string]interface{} the same as logrus.Fields
		return e.Fields.(logrus.Fields)
	}
        return logrus.Fields{}
}

func main () {
   logrus.WithFields(GetFields(err)).WithError(err).Error("crash")
}

```
