### ISSUE TITLE
Is it possible to write logs in StdErr + file

### ISSUE THREAD

**Issue by xoco70** [sirupsen/logrus#1068]
Hi, 

As my app runs inside container, it is very practical to do: 

```
kubectl get logs ...
```

But it is also needed to store logs into a file, and have a bit more logs here. Is it possible to do it with logrus?

**Comment by wangsongyan** [comment]
io.MultiWriter

**Comment by MinweiShen** [comment]
Code example in https://github.com/sirupsen/logrus/issues/1069

**Comment by dgsb** [comment]
For duplicating log output to a file:
* `io.Multiwriter` can do the trick indeed
* you can also try this hook https://github.com/rifflock/lfshook

But if you are in a kubernetes environment, I strongly suggest you set up a log collecting system (ELK stack for example).
