### ISSUE TITLE
formatted data being sent to syslog

### ISSUE THREAD

**Issue by phemmer** [sirupsen/logrus#107]
When using the packaged syslog hook, the data being sent to syslog uses the format sent to the default destination. This means that syslog is receiving a payload with the severity level in the message content, when it already has severity as part of the syslog headers. It has a timestamp when syslog has a timestamp. It has ANSI color escape codes, and alignment formatting.

Basically each output destination needs its own formatter.

**Comment by phemmer** [comment]
The model I think that makes most sense is an interface such as:

    logger.AddOutput("syslog",
      logrus_syslog.NewSyslogOutput("udp","localhost:514", syslog.LOG_INFO, "",
        &logrus.TextFormatter{
          DisableColors: true,
          DisableTimestamp: true,
        }
      )
    )

The default formatter would be automatically added, and equivalent to:

    logger.AddOutput("stdout",
      logrus_iowriter.NewIOWriter(os.Stdout,
        &logrus.TextFormatter{}
      )
    )

The idea is that each output would be added with a name (so that it could be identified later to change or remove it), and where the message will be sent to.
The formatter is part of the destination, and not the logger or even the registered "output" we just created. This is because for some logging destinations, formatting doesn't make sense. For example, if you're logging to a database, you wouldn't format the message at all, the fields would go in as is.

**Comment by janeczku** [comment]
Just bumped into this issue as well. Here a sample line from a syslog logfile:
```
Oct 15 01:21:42 local0.error localhost go-dnsmasq[5258]: \x1b[31mFATA\x1b[0m[0000] listen udp 127.0.0.1:53: bind: permission denied
```

The timestamp and severity in the msg text duplicate information already available in syslog's structured data fields. Additionally, ANSI escape codes are printed in the syslog message which makes them less readable and require extra work to parse them.

Since we only want `entry.Data` and `entry.Message` in the syslog msg string i don't think there is any reason to invoke the `logger.formatter` in the first place. There are only so many ways one can format a string consisting of one text string and some optional key:value pairs:
```
"This is the message key1=value key2=value"
```

**Comment by Sirupsen** [comment]
The fundamental problem here, is that formatters and hooks are really the same thing. The 1.0 design will address this issue, unless someone has a shorter term solution.

**Comment by ctradu** [comment]
One can get rid of the colors in syslog by using `DisableColors` set to False.
Also, there is an other issue, inherited from the standard syslog module, the name of the logging process is suffixed with [pid].
In my opinion this should be configurable at logging init.

**Comment by janeczku** [comment]
> One can get rid of the colors in syslog by using DisableColors set to False.

So to disable colors one has to set DisableColors to False? Really? :smirk:

**Comment by ctradu** [comment]
@janeczku Thanks for spotting the mistake. Fix it.
Anyway, the core issue here is that we were not able to use logrus due to its behaviour described above by @phemmer .

**Comment by janeczku** [comment]
@phemmer so DisableColors is behaving as it should or is this another issue thats needs fixing? :confused:

**Comment by ctradu** [comment]
I can confirm it is working properly:
This is how I receieve messages on the syslog end:
```
time="2015-12-11T11:49:03Z" level=info msg="overall update results" batch=0 fail=0 not-found=0 success=0
```

**Comment by kkirsche** [comment]
I'm seeing this now:

```
2017-03-17T17:40:11.117046+00:00 HOSTNAME.REDACTED Watchdog Send[8767]: #033[34mINFO#033[0m[0030] Packet sent                                   #033[34mcustomer_ip#033[0m=REDACTED #033[34mfunction#033[0m="sendICMP()" #033[34mpop#033[0m=TEST #033[34msrc_ip#033[0m=REDACTEDIP
```

**Comment by kkirsche** [comment]
So the solution should be to use disablecolors?
