### ISSUE TITLE
Add `CallerFormatter` to TextFormatter`

### ISSUE THREAD

**Issue by hu13** [sirupsen/logrus#1071]
Currently, we can only format caller info as here
https://github.com/sirupsen/logrus/blob/master/text_formatter.go#L270?

I understand that we can format how `fileVal + " " + funcVal` looks by just modifying `fileVal` and `funcVal` themselves from when they are returned from `CallerPrettyfier()`.

I think it is cleaner to offer an option to provide `CallerFormatter(fileVal, funcVal string) -> (callerInfo string)`. Any thought?

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
