### ISSUE TITLE
Level is ignored in Entry

### ISSUE THREAD

**Issue by ghost** [sirupsen/logrus#1073]
I have noticed that when an entry is being used, the log level is compared with the underlying logger, not the entry itself. Which means that once the logger has been set to certain level, there is no way to override when needed, but it can be only set globally. The logging level is used in entry just when the actual logging is being done, beside that not really.

I think this:
```
func (entry *Entry) Info(args ...interface{}) {
	if entry.Logger.IsLevelEnabled(InfoLevel) {
		entry.log(InfoLevel, fmt.Sprint(args...))
	}
}
```

should be refactored into
```
func (entry *Entry) Info(args ...interface{}) {
	if entry.Level <= InfoLevel {
		entry.log(InfoLevel, fmt.Sprint(args...))
	}
}
```

**Comment by kaedys** [comment]
(Entry).Level is something Hooks can use to check the level of the entry.  It isn't even set until the Entry actually fires.  The Level at the point in code you highlight will either be completely unset (ie. default value, which is 0, or PanicLevel), if the Entry is brand new, or will be whatever is left over in that field from the last usage, if the Entry was pulled for re-use from the pool.  That field does _not_ reflect whether a particular level should be logged or not, that setting is set in the Logger, not the Entry.

**Comment by gguridi** [comment]
> Which means that once the logger has been set to a certain level, there is no way to override when needed, but it can be only set globally.

Just to add that this is totally intentional. A logging level shouldn't be modified for a logger. If different logging levels are needed then different loggers must be created.

**Comment by kaedys** [comment]
Kinda makes me wish there was some form of "const" specifier for struct fields, that permits that field to be set on instantiation of the struct, but blocks it from being altered thereafter.  Ya, you can make that happen with unexported structs and exported interfaces (which isn't a bad model, I often prefer it), but it adds a lot of extra method overhead for the various getters and setters for all of the fields, and the documentation of them.

Maybe it would just be worth adding to the documentation on the Level field in the Logger that it isn't safe the change the log level of a Logger once it is in use.

**Comment by dgsb** [comment]
@kaedys I'm not sure to understand what isn't safe in changing the level ? We do have an API for that.

**Comment by dgsb** [comment]
When several level are needed, several logger needs to be used.
