### ISSUE TITLE
Logrus doesn't follow package naming convention

### ISSUE THREAD

**Issue by phemmer** [sirupsen/logrus#108]
All of the sub-packages in logrus are prefixed with `logrus_`. The [GO convention](https://golang.org/doc/effective_go.html#package-names) states that package names should be a single word, and the name of the directory they are in. Thus `hooks/papertrail/papertrail.go` would be `package papertrail`.

Yes, this is convention, and not hard requirement, but I just wanted to bring it up since changing things like this becomes more difficult once logrus goes 1.0.

**Comment by Sirupsen** [comment]
Yeah, but it shouldn't be named just `papertrail` either I think.

**Comment by Sirupsen** [comment]
@phemmer any ideas on this?

**Comment by phemmer** [comment]
Dunno. I personally don't see anything wrong with naming the package 'papertrail' (et al.). What are your reservations against it?

**Comment by stevvooe** [comment]
Is this relevant any longer?
