### ISSUE TITLE
stack trace in error field

### ISSUE THREAD

**Issue by pashaosipyants** [sirupsen/logrus#1081]
https://github.com/sirupsen/logrus/blob/67a7fdcf741f4d5cee82cb9800994ccfd4393ad0/json_formatter.go#L64

Consider 
`data[k] = fmt.Sprintf("%+v", err)`

instead of
`data[k] = v.Error()`

not to loose stack trace when using github.com/pkg/errors

**Comment by pashaosipyants** [comment]
Any updates/thoughts?

**Comment by pashaosipyants** [comment]
@markphelps 
Still relevant enhancement, not stale.
Any updates/thoughts?

**Comment by danielyaa5** [comment]
+1
