### ISSUE TITLE
Failed to write to log, invalid argument

### ISSUE THREAD

**Issue by xieccc** [sirupsen/logrus#1084]
In windows, I use it to write log, the code is as follows
```

logClient := logrus.New()
fileName := path.Join(“”, "gin.log")
src, err := os.OpenFile(fileName, os.O_APPEND|os.O_WRONLY, os.ModeAppend)
if err!= nil{
	fmt.Println("err", err)
}

logClient.Out = src

logClient.SetLevel(logrus.DebugLevel)

logWriter, err := rotatelogs.New(
	fileName+"%Y-%m-%d-%H-%M.log",
	rotatelogs.WithLinkName(fileName),
	rotatelogs.WithMaxAge(7*24*time.Hour),
	rotatelogs.WithRotationTime(24*time.Hour),
)

writeMap := lfshook.WriterMap{
	logrus.InfoLevel:  logWriter,
 	logrus.FatalLevel: logWriter,
	logrus.DebugLevel: logWriter,
	logrus.WarnLevel:  logWriter,
	logrus.ErrorLevel: logWriter,
	logrus.PanicLevel: logWriter,
}

lfHook := lfshook.NewHook(writeMap, &logrus.JSONFormatter{})

logClient.AddHook(lfHook)

logClient.Infof("1234")
logClient.Info("123")
```

But I got some errors as follows. What can I do?
```
Failed to write to log, invalid argument
Failed to write to log, invalid argument
```

**Comment by nanfeng** [comment]
> In windows, I use it to write log, the code is as follows
> 
> ```
> 
> logClient := logrus.New()
> fileName := path.Join(“”, "gin.log")
> src, err := os.OpenFile(fileName, os.O_APPEND|os.O_WRONLY, os.ModeAppend)
> if err!= nil{
> 	fmt.Println("err", err)
> }
> 
> logClient.Out = src
> 
> logClient.SetLevel(logrus.DebugLevel)
> 
> logWriter, err := rotatelogs.New(
> 	fileName+"%Y-%m-%d-%H-%M.log",
> 	rotatelogs.WithLinkName(fileName),
> 	rotatelogs.WithMaxAge(7*24*time.Hour),
> 	rotatelogs.WithRotationTime(24*time.Hour),
> )
> 
> writeMap := lfshook.WriterMap{
> 	logrus.InfoLevel:  logWriter,
>  	logrus.FatalLevel: logWriter,
> 	logrus.DebugLevel: logWriter,
> 	logrus.WarnLevel:  logWriter,
> 	logrus.ErrorLevel: logWriter,
> 	logrus.PanicLevel: logWriter,
> }
> 
> lfHook := lfshook.NewHook(writeMap, &logrus.JSONFormatter{})
> 
> logClient.AddHook(lfHook)
> 
> logClient.Infof("1234")
> logClient.Info("123")
> ```
> 
> But I got some errors as follows. What can I do?
> 
> ```
> Failed to write to log, invalid argument
> Failed to write to log, invalid argument
> ```

do u have resolved this problem?

**Comment by nanfeng** [comment]
@xieccc 
hello
do u have resolved this problem?

**Comment by xieccc** [comment]
yes

**Comment by xieccc** [comment]
@nanfeng 
yes

**Comment by asinverse** [comment]
Hello @xieccc,
I got the same error as you.
Could you please tell me how you fixed the issue ?

Thank you,

**Comment by xieccc** [comment]
@asinverse 
Before this program writes to log, make sure the log file has been created.

**Comment by asinverse** [comment]
Thank you @xieccc. It works.
But, it's strange that once the app is run, the log file is changed to a link and the error appears again if I re-run the app.

**Comment by xieccc** [comment]
@asinverse 
If it add a link to log file, this is normal. 
Because if you need to split the log, the file name will be different. Conversely, if you use a link, you can change the file what the link points to. In this case, there is no need to change the written file name , only the link.

**Comment by asinverse** [comment]
@xieccc 
I change the code
`src, err := os.OpenFile(fileName, os.O_APPEND|os.O_WRONLY, os.ModeAppend)`
to
`src, err := os.OpenFile(fileName, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)`

then, the error goes away completely. Also, we don't need to pre-create the log file.

**Comment by xieccc** [comment]
@asinverse okay, I used this before app run.
```
_, err := PathExists(logPath)
if err != nil {
	os.MkdirAll(logPath, os.ModePerm)
}
```

PathExists:
```
func PathExists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, err
}
```
