### ISSUE TITLE
logrus.Info and logrus.Infoln difference

### ISSUE THREAD

**Issue by fenggolang** [sirupsen/logrus#1085]
logrus.Warn and logrus.Warnln difference？ 

I try to use logrus.xx and logrus.xxln, the output is the same, and they all wrap.

![image](https://user-images.githubusercontent.com/16982786/71543186-8bcf8180-29ab-11ea-9f22-9b5172896a4b.png)

**Comment by patrickbahr** [comment]
Hi there, I'm new to this repo but as far as I can tell, the only difference between the log.xx and log.xxln methods is that the xxln methods uses an implementation of Sprintln. You can check the Sprintln implementation here: https://github.com/sirupsen/logrus/blob/67a7fdcf741f4d5cee82cb9800994ccfd4393ad0/entry.go#L399-L406

The Sprintln method works kinda the same way as the Println, as in if you pass more than one argument to it, it'll add a space between them. 
Example:
https://play.golang.org/p/QWfjOHIWpk_J

You can check that this is working as intended by looking at this test case:
https://github.com/sirupsen/logrus/blob/67a7fdcf741f4d5cee82cb9800994ccfd4393ad0/logger_test.go#L49-L69

**Comment by dgsb** [comment]
These *ln interface are only implemented to be compatible with the standard log package so that logrus can easily be switched in place of it without any code changes at package consumer side.
