### ISSUE TITLE
package-level exported logger doesn't seem to be responding to SetOutput(ioutil.Discard)

### ISSUE THREAD

**Issue by c4milo** [Sirupsen/logrus#109]
When running tests I would like to disable any kind of logging. For some reason the package-level exported logger doesn't seem to be responding to `SetOutput(ioutil.Discard)` and still sends stuff to my stdout.

**Comment by phemmer** [comment]
I actually did something involving this the other day. Works fine for me:

```
# cat test.go
package main

import (
	"github.com/Sirupsen/logrus"
	"io/ioutil"
	"os"
)

func main() {
	logrus.Print("one")
	logrus.SetOutput(ioutil.Discard)
	logrus.Print("two")
	logrus.SetOutput(os.Stdout)
	logrus.Print("three")
}

# go run test.go
INFO[0000] one                                          
INFO[0000] three                                        
```

**Comment by c4milo** [comment]
it might be an issue on my end then. Thanks!.
