### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by markphelps** [sirupsen/logrus#1095]
👋 I just wanted to say thanks for creating such a great library! It is a joy to use and I prefer to use Logrus over other loggers in all my personal and work projects.

Just wondering if this project is still being actively maintained?

It seems the last commit was over 3 months ago and that most of the issues/PRs since then have gone stale/had no responses from the maintainers.

Are you looking for other maintainers to help out?

**Comment by sirupsen** [comment]
Yes, would you like to help?

**Comment by markphelps** [comment]
I would yes, how can I help

**Comment by mostfamiliar** [comment]
I'm also interested in contributing!

**Comment by lynncyrin** [comment]
👋 I'd also be interested in being a collaborator! I've had a PR merged in already https://github.com/sirupsen/logrus/pull/977, and I'm also a maintainer for https://github.com/urfave/cli. Lots of people use `logrus` and `urfave/cli` in similar contexts ^^

**Comment by markphelps** [comment]
Closing as it's now addressed in the README:

> Logrus is in maintenance-mode. We will not be introducing new features. It's simply too hard to do in a way that won't break many people's projects, which is the last thing you want from your Logging library (again...).

> This does not mean Logrus is dead. Logrus will continue to be maintained for security, (backwards compatible) bug fixes, and performance (where we are limited by the interface).

**Comment by seriouz** [comment]
Why you don't make branches with multiple flavours?
