### ISSUE TITLE
Unable to suppress tty output after log.SetOutput(file)

### ISSUE THREAD

**Issue by holyxiaoxin** [sirupsen/logrus#1097]
Is there a way to suppress output to tty? 

I can't find a way to suppress it even after `log.SetOutput(file)` and redirecting outputs to `/dev/null`.

**Comment by dgsb** [comment]
It should work. Can you provide a code sample which exhibits your issue ?

**Comment by bl-ue** [comment]
Maybe this issue should be closed now.

**Comment by dgsb** [comment]
Stale, no feedback from OP
