### ISSUE TITLE
Getting "import cycle not allowed" starting with Go 1.13.8 (incl 1.14)

### ISSUE THREAD

**Issue by stasica** [sirupsen/logrus#1101]
While the library works with v1.13.7, it will not build with v1.13.8 or v1.14.

import cycle not allowed
package main
        imports github.com/sirupsen/logrus
        imports github.com/sirupsen/logrus

**Comment by dgsb** [comment]
Can you provide some code sample which exhibits the issue you are facing ?
It's quite hard to understand what is not working for you

**Comment by stasica** [comment]
I was able to resolve the issue.  While it's unclear why the issue showed up in 1.13.8 and 1.14 but not 1.13.7 I'm unsure, but it's good to close.
