### ISSUE TITLE
PipeWriter closing is non-deterministic

### ISSUE THREAD

**Issue by drewwells** [sirupsen/logrus#1111]
I encountered an issue with the PipeWriters in a unit test. The test fails some of the time b/c nothing has been written out to os.Stdout after the writer has been closed. I looked into the code and noticed that a scanner is running in an un-synchronized go routine. The documentation says to close the pipewriter, but it looks like it is being closed in the runtime.Finalizer.

https://github.com/sirupsen/logrus/blob/master/writer.go#L51

**Comment by rogpeppe** [comment]
The "right" solution to this issue, as I see it, would be to avoid the pipe entirely (this can end up with log messages being inappropriately reordered in addition to the issue reported here), and use a custom writer instead.

Something like this (compiled but not tested):

```
func (entry *Entry) WriterLevel(level Level) io.Writer {
	return &linePrinter{
		entry: entry,
		level: level,
	}
}

type linePrinter struct {
	entry *Entry
	level Level
	buf   []byte
}

func (w *linePrinter) Write(buf []byte) (int, error) {
	buf0 := buf
	for len(buf) > 0 {
		i := bytes.IndexByte(buf, '\n')
		switch {
		case i == -1:
			// No line terminator. Save it for the next write.
			// Technically, without any kind of flush mechanism,
			// this data could be discarded when the logger is
			// discarded, but this should never be a problem in
			// practice - we don't want to end up with
			// unterminated lines in our log anyway.
			w.buf = append(w.buf, buf...)
			return len(buf), nil
		case len(w.buf) == 0:
			// No previous incomplete line, so just print the
			// buffer directly.
			// In practice, this is the case that will always happen
			// because log writers always write a single
			// line at a time.
			w.entry.Log(w.level, buf[0:i])
		default:
			// Join with previous incomplete line before printing.
			w.buf = append(w.buf, buf[0:i]...)
			w.entry.Log(w.level, w.buf)
			w.buf = w.buf[:0]
		}
		buf = buf[i+1:]
	}
	return len(buf0), nil
}
```

However, this can't be done without breaking the logrus API because the public API exposes `*io.PipeWriter` directly, and I don't think there's a way to make closing a pipe writer into a synchronous operation that waits for the reader side to close before returning.

**Comment by rogpeppe** [comment]
Actually, one way to work around this would be to deprecate the existing Writer methods and add functions instead. For example:

```
func LoggerWriter(logger *Logger, level Level) io.Writer {
	return EntryWriter(NewEntry(logger), level)
}

func EntryWriter(entry *Entry, level Level) io.Writer {
	return &linePrinter{
		entry: entry,
		level: level,
	}
}
```

Regardless, the above could be a reasonable workaround that can be implemented by clients outside of logrus without needing any buy-in from logrus maintainers.

**Comment by rogpeppe** [comment]
On second thoughts, all that logic in `linePrinter` is unnecessary and potentially counterproductive (it's not unknown for log entries to have multiple lines). In our workaround code, I'm going for this (again it's untested):

```
// Writer returns a writer that logs each write
// to the given Logger at the given level.
func Writer(logger *logrus.Logger, level logrus.Level) io.Writer {
	return EntryWriter(logrus.NewEntry(logger), level)
}

// Entry is like Writer but logs to the given entry instead of a logger.
func EntryWriter(entry *logrus.Entry, level logrus.Level) io.Writer {
	return &linePrinter{
		entry: entry,
		level: level,
	}
}

type linePrinter struct {
	entry *logrus.Entry
	level logrus.Level
}

func (w *linePrinter) Write(buf []byte) (int, error) {
	n := len(buf)
	if len(buf) == 0 {
		return 0, nil
	}
	if buf[len(buf)-1] == '\n' {
		buf = buf[0 : len(buf)-1]
	}
	w.entry.Log(w.level, string(buf))
	return n, nil
}
```
