### ISSUE TITLE
Add custom data in log

### ISSUE THREAD

**Issue by alannaidon** [sirupsen/logrus#1114]
I'm using Logrus to make the logging on the system. The thing is, I'm not sure how to keep the data I'm already using AND create custom fields to it.

```
package log

import("github.com/sirupsen/logrus" ...)

var formatter logrus.Formatter

formatter = &logrus.TextFormatter{
            TimestampFormat:        configurationFile.TimestampFormat,
            DisableTimestamp:       configurationFile.Timestamps,
            DisableLevelTruncation: configurationFile.DisableLevelTruncation,
            FullTimestamp:          true,
            ForceColors:            true,
            // I Belive I need to change something here
}
```  

Today I have the following output:

```
time="2020-01-16 09:21:54" level=info msg="server initialized"
```
I need:
```
field="value" time="2020-01-16 09:21:54" level=info msg="server initialized"
```   

Tried to work with [Custom Fields](https://github.com/sirupsen/logrus#default-fields) but didn't work

Is it something possible to achieve? Even better if I could change in a single place and result in every log.

**Comment by rbUUbr** [comment]
hey there! I would like to help you! Could you please describe why you didn't success with custom fields? could you provide the code? also, there is FieldMap feature, if you need to add fields for *all* logs

**Comment by alannaidon** [comment]
Hi @rbUUbr  Thanks for your reply.

I used _Custom Fields_, but the info just didn't show on log.

I'm workig on a project made bt someone else. Now I need to create new features and change a few things. I'm studying the code for a while and the one thing I couldn't understand is HOW logrus output to a file everything that is outputed to the console.  
I know I can specify the level that I want to save to log file {debug, info, warn, error, fatal}, but how exactly this output goes to a _file.log_.   Could you perphaps show me some light?

Thank you !

**Comment by dgsb** [comment]
@alannaidon did you solve your issue ? can we close it ?

**Comment by alannaidon** [comment]
> @alannaidon did you solve your issue ? can we close it ?

Hi! Sorry for the delay with the reply I was working in another project.

Is there a way to add custom fields with logrus only?  
If no, then yes, you can close it. Thanks guys.

**Comment by dgsb** [comment]
To add specific fields you can use this api https://github.com/sirupsen/logrus/blob/42baed85eb233bfc674562af0ef6e99c45f5f384/logger.go#L112 on a per trace basis

```go
myLogger.WithField("a_field_name", "and_its_associated_value).Info("some important traces")
```
