### ISSUE TITLE
Cross compiling doesn't work

### ISSUE THREAD

**Issue by haarts** [sirupsen/logrus#112]
I'm using [goxc](https://github.com/laher/goxc) to cross compile my project. Doing so now results in:

```
../../Sirupsen/logrus/text_formatter.go:28: undefined: IsTerminal
[goxc:xc] 2015/01/16 20:50:30 'go' returned error: exit status 2
[goxc:xc] 2015/01/16 20:50:30 Error: exit status 2
[goxc:xc] 2015/01/16 20:50:30 Have you run `goxc -t` for this platform (amd64p32,nacl)???
```

This error is repeated for every platform.

I'm using c6a969a0de65e41b666c5dd015b3988b47cd940b and Go 1.4 on Ubuntu 14.04.
Running `goxc` in the `examples/basic` directory is enough to reproduce the problem. I have ran `goxc -t` of course and I know this worked previous to introducing logrus.

**Comment by Sirupsen** [comment]
What are you cross compiling to?

**Comment by haarts** [comment]
All of them. :) Goxc compiles to the craziest platforms. But none of them succeed at the moment.

**Comment by Sirupsen** [comment]
Did you ever find a solution to this?

**Comment by haarts** [comment]
I have had some luck with:
```
$ goxc -bc="windows,linux,darwin"
```
This specifies 'build constraints'. And yielded binaries for the three platforms. I'm unsure why constraining the platforms works since an unconstrained builds builds for these platforms as well.

The bug seems more `goxc` related, this issue I'd close.

**Comment by labkode** [comment]
The cross compilation only fails for these architectures.
 ```
[goxc:xc] 2015/04/07 21:32:25 Have you run `goxc -t` for this platform (386,netbsd)???
[goxc:xc] 2015/04/07 21:32:25 Have you run `goxc -t` for this platform (amd64,netbsd)???
[goxc:xc] 2015/04/07 21:32:25 Have you run `goxc -t` for this platform (arm,netbsd)???
[goxc:xc] 2015/04/07 21:32:25 Have you run `goxc -t` for this platform (386,dragonfly)???
[goxc:xc] 2015/04/07 21:32:25 Have you run `goxc -t` for this platform (amd64,dragonfly)???
[goxc:xc] 2015/04/07 21:32:25 Have you run `goxc -t` for this platform (386,plan9)???
[goxc:xc] 2015/04/07 21:32:25 Have you run `goxc -t` for this platform (amd64,solaris)???
[goxc:xc] 2015/04/07 21:32:26 Have you run `goxc -t` for this platform (amd64p32,nacl)???
[goxc:xc] 2015/04/07 21:32:26 Have you run `goxc -t` for this platform (386,nacl)???
[goxc:xc] 2015/04/07 21:32:26 Have you run `goxc -t` for this platform (arm,nacl)???
```

The error is always this:
`../../Sirupsen/logrus/text_formatter.go:29: undefined: IsTerminal`

**Comment by cgag** [comment]
I just ran into problems trying to compile for dragonfly, I think it's from terminal_notwindows only explicitly listing "// +build linux darwin freebsd openbsd".  I think it might be possible to fix it just by adding the remaining OSes to this list. 

https://github.com/Sirupsen/logrus/blob/master/terminal_notwindows.go

**Comment by Sirupsen** [comment]
@cgag mind doing that? :)

**Comment by cgag** [comment]
I'll give it a shot at some point soon.  If anyone else wants to do it, feel free to preempt me.

**Comment by cgag** [comment]
I aded support for the other BSDs (dragonflybsd and netbsd) https://github.com/Sirupsen/logrus/pull/203

I couldn't build the toolchain using gox for nacl, and plan9 says it doesn't support Termios or TIOCGETA.

**Comment by 0xE0F** [comment]
@Sirupsen I added support for the Solaris OS: #289 

It also hasn't SYS_IOCTL, so terminal_notwindows.go was inapplicable.

**Comment by dgsb** [comment]
This issue has been pretty inactive since several years. If some cross-compiling issue accurs again, I suggest create a dedicated issue for the specific os/arch tuple.
