### ISSUE TITLE
Is it safe to use master version?

### ISSUE THREAD

**Issue by maxifom** [sirupsen/logrus#1121]
I want to use go1.14 with logrus, but current release version report caller is bugged (always shows log.Println functions instead of real functions)
So I am asking: Is it safe to use master version in production and why no releases are made since a long time ago?

**Comment by markphelps** [comment]
@maxifom [v1.5.0](https://github.com/sirupsen/logrus/releases/tag/v1.5.0) was released last week that should fix this issue
