### ISSUE TITLE
Overly-aggressive mutex locks

### ISSUE THREAD

**Issue by markphelps** [sirupsen/logrus#1122]
Mutex locking added in #1047 is too aggressive. 

Re this comment:

> This lock is far too aggressive. It locks the entire logger, rather than a single entry as I believe it should.

_Originally posted by @flimzy in https://github.com/sirupsen/logrus/pull/1047#issuecomment-605093920_

More context:

> I looked at it briefly before posting my comment, and it wasn't immediately obvious the proper solution. It looks like we need to add a mutex to the Entry type, and lock it in WithFields and in fireHooks, but my first attempt lead to a deadlock.

> While working on that, I ran into what may be other overly-aggressive locks which could be relaxed, too, but it's tricky to do that with confidence, without tests covering all possible races (which are incredibly hard to test).

**Comment by xialu4820723** [comment]
@flimzy is right. I updated dependencies just now, then my service get blocked during 
start up. I turns out updating entry in hook caused a deadlock
![WXWorkCapture_15855788086642](https://user-images.githubusercontent.com/16009684/77924679-8ea57f80-72d6-11ea-923a-a332b5e7111a.png)

**Comment by saschagrunert** [comment]
I can confirm this. We updated logrus to 1.5.0 and got a deadlock. Commenting out these lines would resolve the issue:
https://github.com/cri-o/cri-o/blob/5716cbc3a2ae08ab221402fbd0c3f20ebf61d416/internal/log/hook_filename.go#L50-L58

**Comment by markphelps** [comment]
Ok, I see two main options, please let me know what you all think or if there are any better options:

1. Revert https://github.com/sirupsen/logrus/pull/1047 as it introduced the aggressive mutex locks and create a new release `v1.5.1`. This will mean that we reintroduce the bug fixed however: https://github.com/sirupsen/logrus/issues/1046

2. Fix forward by introducing a mutex on the `logger.Entry` itself, however @flimzy mentioned this lead to deadlocks when trying this approach. @flimzy could you provide some sample code to reproduce this deadlock with moving the mutex to the `Entry`?

Thoughts?

**Comment by saschagrunert** [comment]
Im in favor of moving forward since I think the intention of the original PR was the right one. 👍

**Comment by markphelps** [comment]
I chose to [revert](https://github.com/sirupsen/logrus/pull/1131) since no forward fix has been proposed and several users are reporting deadlocks since updating to `1.5.0`

If anyone has a potential fix for #1046 please open an PR against it
