### ISSUE TITLE
Update Log Path of file when using lfshook

### ISSUE THREAD

**Issue by alannaidon** [sirupsen/logrus#1123]
I'm using [lfshook](https://github.com/rifflock/lfshook) alongisde with `Logrus` and I found myself in a situation where I need to replace/update the path of `warn` logs.  
Is it possible to do so in runtime??  

This is how I set the path for each `level` of log. I need to UPDATE the `WARN` level in a certain point of the execution.
```
pathMap := MakePath(
      fileLevel,
      absolutePath,
      logPath,
)

log.Hooks.Add(lfshook.NewHook(
			pathMap,
			&logrus.TextFormatter{
				TimestampFormat:        config.Logging.TimestampFormat,
				DisableTimestamp:       !config.Logging.Timestamps,
				DisableLevelTruncation: config.Logging.DisableLevelTruncation,
				FullTimestamp:          true,
				DisableColors:          true,
			},
		))

------------------------------------
func MakePath(minLevel logrus.Level, fpath, logPath string) lfshook.PathMap {
	pm := lfshook.PathMap{}

	for _, lvl := range logrus.AllLevels {
		if lvl <= minLevel {
			pm[lvl] = fpath
		}
		pm[logrus.WarnLevel] = logPath + "/logs/teste.log"
	}

	return pm
}
```  

I need to update the path for `logrus.WarnLevel` in a different file. Is is possible?

**Comment by dgsb** [comment]
This issue should be opened on rifflock/lfshook repository instead of this one
