### ISSUE TITLE
use custom formatter  formating gorm log 

### ISSUE THREAD

**Issue by Turing-Chu** [sirupsen/logrus#1125]
when I define my formatter for gorm log , the entry.Message field's value like the following. It contains sql, file, line, used time, query statement, [] 16. 

Now I still try to find out why it like this.

#### version info
- go: version go1.13.4 darwin/amd64
- logrus: 1.4.2
- gorm: 1.9.11

```
sql{YourCallerFilePath}:{Line}{usedTime}ms{Query}[] 16

// exampe
sql/Users/A/B/C/D.go:34580.463646msSELECT * FROM YOUR_TABLE_NAME[] 16
```

**Comment by Turing-Chu** [comment]
after I use debug, i find the following information: 

```
entry.go:266-268
func (entry *Entry) Log(level Level, args ...interface{}) {
	if entry.Logger.IsLevelEnabled(level) {
		entry.log(level, fmt.Sprint(args...))
	}
}

the args: type: []interface{}
0: "sql"
1: "/Users/xxxx/xxx.go:100"
2: 78950332  (used time the same to 80.463646ms )
3: SELECT DISTINCT A AS a,B AS b FROM `t`   ORDER BY b DESC
4: nil
5: 16

after call "entry.log(level, fmt.Sprint(args...))"  the Message field the same to above

**Comment by Turing-Chu** [comment]
in the gorm , i find the following code

 ```
func (s *DB) slog(sql string, t time.Time, vars ...interface{}) {
	if s.logMode == detailedLogMode {
		s.print("sql", fileWithLineNum(), NowFunc().Sub(t), sql, vars, s.RowsAffected)
	}
}
```


so,  gorm passing an array with type []interface{}, and logrus calling fmt.Sprint(args...), then the message output like above.

**Comment by dgsb** [comment]
hello @Turing-Chu.

It's not quite clear from your issue, what are you trying to do ?

**Comment by dgsb** [comment]
If you want to have each paramater of the gorm print in a dedicated field, I guess you need to write a wrapping function/struct somehow

**Comment by Turing-Chu** [comment]
thanks for your answer.
