### ISSUE TITLE
Sprintf for logrus.Entry?  [question]

### ISSUE THREAD

**Issue by arashout** [sirupsen/logrus#1126]
Hi this is probably a dumb question but is it possible to somehow have logrus.Entry return a string instead of writing to `stdout`?       
      
Something like this:
`var s = logger.WithFields({"request-id": 123, "service": "datahandling"}).Sprint("Some message to a string with fields")`
     
The reason I want to do this is so that I can return Error messages with the logger fields included in them.      
Could I get some guidance on if that is a bad idea?     
    
I think it's possible to get this functionality with a custom function if you pass an `io.Writer` to the logrus instance but I would prefer not to do that.

Again this isn't really an issue, more of a question how to implement this and why I should/shouldnt?

**Comment by arashout** [comment]
So I assume this isn't possible? The closest thing I found is code like this:
```go
package main

import (
	"bytes"
	"fmt"

	log "github.com/sirupsen/logrus"
)

func main() {
	memLog := &bytes.Buffer{}
	log.SetOutput(memLog)

	log.WithFields(log.Fields{
		"animal": "walrus",
		"number": 1,
		"size":   10,
	}).Info("A walrus appears")

	fmt.Println(memLog)
}
```

But I don't want to change StandardOutput of the base `Logrus.Logger`

**Comment by dgsb** [comment]
@arashout there is nothing available to do what you need. You can use `io.MultiWriter` to not completely replace the standard output.

You can use the `Entry.String` method to retrieve the string with formatted fields but you will miss the log message itself and the hooks won't be called.

**Comment by arashout** [comment]
Okay understood, thanks @dgsb .

If anyone else is wondering the closest thing got to what I need was to write a custom function for extracting the `Fields` to `string` which I could later encode into an error message.

```go
func LogFieldsToString(logger *logrus.Entry) string {
	var b bytes.Buffer
	for k, v := range logger.Data {
		// According to the documentation https://golang.org/src/bytes/buffer.go?s=6050:6107#L170
		// Error is always nil, so we ignore it
		// nolint
		_, _ = b.WriteString(fmt.Sprintf(`%s="%+v" `, k, v))
	}
	return b.String()
}
```

Demo
```go
func TestLogFieldsToString(t *testing.T) {
	rq := require.New(t)
	logger := logrus.NewEntry(logrus.New())

	logger = logger.WithFields(logrus.Fields{"key": "value", "1": 2})
	output := LogFieldsToString(logger)

	rq.Contains(output, `key="value" `)
	rq.Contains(output, `1="2" `)

	logger = logger.WithField("next", mock{A: "AField", b: "field b"})
	output = LogFieldsToString(logger)
	rq.Contains(output, `key="value" `)
	rq.Contains(output, `1="2" `)
	rq.Contains(output, `next="{A:AField b:field b}" `)
}

```
