### ISSUE TITLE
Appengine Managed VMs

### ISSUE THREAD

**Issue by skriptble** [Sirupsen/logrus#113]
Logrus won't compile when using AppEngine Managed VM's because it's missing the IsTerminal() function, since there is a build flag on the terminal_notwindows.go file. Removing this flag allows it compile. The package won't run on regular app engine anyway since there are other syscalls.
Is there any reason to keep this build flag?

**Comment by Sirupsen** [comment]
No, feel free to submit a PR to remove it.

**Comment by Sirupsen** [comment]
https://github.com/Sirupsen/logrus/commit/0b189e019aabcec0af8e433b10b3073ad9382b44
