### ISSUE TITLE
Prevent escaping special chars

### ISSUE THREAD

**Issue by BentCoder** [sirupsen/logrus#1135]
Hi,

This is how the log looks like `... "path":"/api/v1/users?page=1\u0026limit=3" ...` which comes from `http.Request..RequestURI`. How do we prevent logrus from escaping the special chars so the the log reads `... "path":"/api/v1/users?page=1&limit=3" ...` ?

Thanks

**Comment by pradykaushik** [comment]
I tested couple of scenarios and seems like special characters are not getting escaped and are showing up unencoded (the way you want it).

Note that I'm using the latest version of logrus.
Below is the test code that I wrote.

```go
package logrus

import (
    "os"
    "testing"
)

func TestEscapeSpecialChar(t *testing.T) {
	l := &Logger{
		Out:          os.Stdout,
		Formatter:    &TextFormatter{},
		Level:        InfoLevel,
	}

	l.WithField("path1", "/api/v1/users?page=1&limit=3").Log(InfoLevel)
	l.WithField("path2", "/api/v1/users?page=1\u0026limit=3").Log(InfoLevel)
}
```

I ran the code using the command - `go test -v -run TestEscapeSpecialChar`. Below is the output.

```commandline
=== RUN   TestEscapeSpecialChar
INFO[0000]                                               path1="/api/v1/users?page=1&limit=3"
INFO[0000]                                               path2="/api/v1/users?page=1&limit=3"
--- PASS: TestEscapeSpecialChar (0.00s)
PASS
ok  	github.com/sirupsen/logrus	0.574s
```

As you can see, '&' is not being encoded in either scenarios in the log messages.

Can you provide more information on how you are logging the strings using logrus?

**Comment by BentCoder** [comment]
Thanks @pradykaushik I didn't realise there was such feature. My version was old.

**Comment by fhajiyev** [comment]
@pradykaushik yes, I received the answer on StackOverflow yesterday (regarding `DisableHTMLEscape`) but I forgot to close the issue, sorry for that. Thanks for assistance!
