### ISSUE TITLE
Errors in fields are empty when using JSONFormatter 

### ISSUE THREAD

**Issue by shilov** [Sirupsen/logrus#114]
JSONFormatter seems to have trouble with errors passed to `log.Fields`

    log.SetFormatter(&log.JSONFormatter{})
    err := errors.New("this will come up as {}")
    log.WithFields(log.Fields{
      "err": err,
    }).Warn("the error field will be empty")

The code above will output out the following:

    {"err":{},"level":"warning","msg":"the error field will be empty","time":"2015-01-16T20:51:40-08:00"}

The TextFormatter works as expected so this issue is specific to the JSONFormatter as far as I can tell.

**Comment by pzduniak** [comment]
You're feeding an empty struct into a JSON marshaller, you need to use `err.Error()` to have errors stored as strings.

**Comment by shilov** [comment]
Don't know how I missed that. Thanks for pointing it out!

**Comment by Sirupsen** [comment]
Thanks @pzduniak :)
