### ISSUE TITLE
Passing around an *Entry for using default fields

### ISSUE THREAD

**Issue by arthurvaverko** [sirupsen/logrus#1141]
Is it really okay performance wise to create a single entry that will be passed around the context so that I can add new fields ?

what about using the entryPool ? 

I tried creating a custom formatter that always adds my fields but that failed with a deadlock due to the entry mutex being locked ..

**Comment by dgsb** [comment]
The usual way to add default fields is indeed to add an entry with these and to pass them around.
What are you trying to achive exactly ?

**Comment by arthurvaverko** [comment]
Im trying to set a common request id field .. client ip field etc from inside a middleware .. 

Then I want these fields to persists for all logs of that current request ..

So i guess I create an entry .. set the fields .. and pass it into the `Request.Context()` 

This way I can retrieve the entry from other midllewares or from the http handler ..

**Comment by dgsb** [comment]
@arthurvaverko that's the most easy way to do it, create an entry with all default fields and pass it along.

**Comment by arthurvaverko** [comment]
Okay .. got it .. thanks!
