### ISSUE TITLE
cannot load ！

### ISSUE THREAD

**Issue by wangcc7** [sirupsen/logrus#1147]
build github.com/sirupsen/logrus/hooks/syslog: cannot load github.com/sirupsen/logrus/hooks/syslog: no Go source files

Please give me some help, thanks~

**Comment by wangcc7** [comment]
import (
	"fmt"
	log "github.com/sirupsen/logrus"
	logrus_syslog "github.com/sirupsen/logrus/hooks/syslog"
	"github.com/thinkeridea/go-extend/exnet"
	"log"
	"log/syslog"
)

**Comment by dgsb** [comment]
what is the issue exactly ?

**Comment by dgsb** [comment]
Not enough information to understand the issue

**Comment by KEMonster** [comment]
I have seen that have a comment on the top of github.com/sirupsen/logrus/hooks/syslog/syslog.go
// +build !windows,!nacl,!plan9

Maybe it can not build in windows？
