### ISSUE TITLE
my test code can be run in git-bash,but can not run in window10 cmd, have some err in logrus?

### ISSUE THREAD

**Issue by olongfen** [sirupsen/logrus#1148]
```golang
package main

import (
	log "github.com/sirupsen/logrus"
	"time"
)

var (
	l = log.New()
)

func main() {
	go dd()
	time.Sleep(time.Second * 5)
}

func dd() {

	log.Print("aaaaaaaaaaaaaaaaaa")
}
```

1. git-bash output:

![image](https://user-images.githubusercontent.com/44766084/83345753-43950080-a349-11ea-9e6b-8a20356b38bb.png)

2.  cmd ouput:

![image](https://user-images.githubusercontent.com/44766084/83345766-5d364800-a349-11ea-8c85-7d758875d5be.png)

**Comment by dgsb** [comment]
This error has been fixed a few weeks ago. Can you try to upgrade the version of logrus you are using ?

**Comment by olongfen** [comment]
thanks, i try get this package @master, my code can do work

**Comment by dgsb** [comment]
I strongly suggest that you do use a tagged version. The last one is the `1.6.0`
