### ISSUE TITLE
log just for specific user

### ISSUE THREAD

**Issue by masoodbayati** [sirupsen/logrus#1149]
Hi, How can i have debug log just for specific user?

**Comment by dgsb** [comment]
There is nothing in logrus for doing that, you need to handle that at package consumer side.

**Comment by mohsensamiei** [comment]
Hi guys
In [this pull request](https://github.com/sirupsen/logrus/pull/1150)
I want to force some log entry to logging regardless of its level
So we can pass force for custom users

**Comment by dgsb** [comment]
Why not using a specific logger with a different level for a specific user instead ?

**Comment by mohsensamiei** [comment]
> Why not using a specific logger with a different level for a specific user instead ?
> We try to avoid changing the package public interface for specific narrow use case in order to reduce the maintenance load.

because with this approach we need to have if block for switch between loggers
but I got idea, we could have a function for switch between loggers 

thanks bro

**Comment by dgsb** [comment]
> but I got idea, we could have a function for switch between loggers

Indeed, that's the way to go
