### ISSUE TITLE
Hook doesn't respect logger's custom formatter

### ISSUE THREAD

**Issue by droslean** [sirupsen/logrus#1153]
In case when the formatter mutates the log message, it doesn't change from `hook`'s message.

This can be considered as a blocker when users need to tests their actual outputs.

Here is an example:
https://play.golang.org/p/IquUoBnj-gJ

**Comment by droslean** [comment]
cc @dgsb

**Comment by pradykaushik** [comment]
[Hooks are fired](https://github.com/sirupsen/logrus/blob/master/entry.go#L237) before [Formatter is invoked](https://github.com/sirupsen/logrus/blob/master/entry.go#L247). I believe is this is why you don't see the formatted message in the hook.

**Comment by droslean** [comment]
We should have a way to allow formatter to be shown in the hook.

**Comment by utdrmac** [comment]
Came here for this. I'm trying to log to two locations and both locations get the same format. Why can't I use different formatters for different outputs when using io.Multiwriter?

Since this project is "dead", I'm guessing we can't expect new features to fix things like this?

**Comment by utdrmac** [comment]
Ping. Keepalive
