### ISSUE TITLE
Is there a way to specify different log level for different log writer?

### ISSUE THREAD

**Issue by evanchaoli** [sirupsen/logrus#1154]
I want to log to both stdout and file, but with different log level, for example, apply "error" level to stdout, and "debug" level to file. Is there a way to archive that?

**Comment by pradykaushik** [comment]
1. you could call `SetLevel(...)` and then call `log.Log(...)`.
2. When instantiating the logger, you can set the level to a higher level (DEBUG). After this, if you want to log to stdout you can use `log.Error(...)` and if you want to log to file you can use `log.Debug(...)`.
3. If you just want to make one call to Log(...) and expect this behavior, then you may have to chain multiple loggers using COR and have each logger log to its corresponding destination (stdout or file) if the log level is within range.

**Comment by ridv** [comment]
This may also be an alternative if I understood the question correctly:
https://github.com/nritholtz/stdemuxerhook

**Comment by gguridi** [comment]
I think the easier way to achieve this is the use of hooks (note the code is untested):

```go
import (
     "github.com/rifflock/lfshook"
)

logrus.SetOutput(ioutil.Discard)

logrus.AddHook(&writer.Hook{
	Writer: os.Stdout,
	LogLevels: []log.Level{
                 // Levels that we want to log into the console.
	 	log.DebugLevel,
        },
})

logrus.AddHook(&lfshook.NewHook(
	lfshook.PathMap{
		logrus.InfoLevel:  "/var/log/info.log",
		logrus.ErrorLevel: "/var/log/error.log",
	},
        &logrus.JSONFormatter{},
))
```

If lfshook or any of the available [hooks](https://github.com/sirupsen/logrus/wiki/Hooks) that exists do not match your needs you can always write your own hook that will write to the file you want only for the levels that you decide. Upon registration, the logs tell logrus for which levels they want to log messages.
