### ISSUE TITLE
Amending log line

### ISSUE THREAD

**Issue by InfRandomness** [sirupsen/logrus#1155]
Hi, I have a question about logrus

I am coding an application in go that uses logrus but I'd like to amend the logs line logrus prints by adding [DONE] after the logged task is done.

Is there any way to do that with logrus, if yes, how to do it ?

**Comment by pradykaushik** [comment]
Can you explain what you mean by “logged task is done”?
Also, if you want to change how the log message looks then you might want to write a custom formatter.
If you want to add a field, say `status=Done` then you can do so by just calling `.WithField(...)` before you call `Log(...)`.

**Comment by InfRandomness** [comment]
What I meant by "logged task is done" is, in your code, calling log.Debug("Launching x service") then calling the function that launches the x service and adding to the log line "Launching x service" "[DONE]" to it

**Comment by pradykaushik** [comment]
AFAIK I don't think there's a way for you to update the log once persisted.
However, I also don't think that's the best way to go about things. It would be better to just add another log signalling the successful launch of the service as this would also preserve the timestamp of the launch initiation.

You can use [Fields](https://github.com/sirupsen/logrus/blob/master/logrus.go#L10) to attach status updates to the service that will then get logged as key=value pairs along with the log message.

```go
l.WithFields(Fields{"status": "launching", "service": "X"}).Log(InfoLevel, "Service Status")
service.Launch() // dummy code to launch the service.
l.WithFields(Fields{"status": "done", "service": "X"}).Log(InfoLevel, "Service Status")
```
Below is how the log will look assuming you're assuming the TextFormatter.
```commandline
INFO[2020-07-12T19:49:17-04:00] Service Status                                service=X status=launching
INFO[2020-07-12T19:49:17-04:00] Service Status                                service=X status=done
```

**Comment by InfRandomness** [comment]
Sweet, it's even better, thanks a lot.
