### ISSUE TITLE
Where are the log outputs stired?

### ISSUE THREAD

**Issue by aggarwalanubhav** [sirupsen/logrus#1156]
Hi @sirupsen,

I used the logrus API in my CLI application. I want to know where the log outputs are stored or printed?

**Comment by markphelps** [comment]
@aggarwalanubhav ,

Logrus defaults the output to STDERR, but you can change this by calling [SetOutput](https://godoc.org/github.com/sirupsen/logrus#SetOutput):

```go
  // Output to stdout instead of the default stderr
  // Can be any io.Writer, see below for File example
  log.SetOutput(os.Stdout)
```
