### ISSUE TITLE
Logrus ampersand character escaped

### ISSUE THREAD

**Issue by fhajiyev** [sirupsen/logrus#1159]
Hello,
I have created the following question on stackoverflow, could you please have a look:
https://stackoverflow.com/questions/63010085/logrus-escaping-ampersand-character

So the problem is that ampersand is converted into its unicode hex value (I haven't yet checked other special characters, currently this one is needed only). Is there a way to display it as a character itself, rather than its hex value?
Thank you

**Comment by pradykaushik** [comment]
Does the solution provided in issue #1135 resolve this?

**Comment by fhajiyev** [comment]
@pradykaushik 

> Does the solution provided in issue #1135 resolve this?

oh yes, I received the answer on StackOverflow yesterday (regarding DisableHTMLEscape) but I forgot to close the issue, sorry for that. Thanks for assistance!
