### ISSUE TITLE
Caller Tracing - getPackageName on callerInitOnce (wrong package returned)

### ISSUE THREAD

**Issue by JustDaile** [sirupsen/logrus#1165]
In entry.go line 175
`logrusPackage = getPackageName(runtime.FuncForPC(pcs[1]).Name())` 

Causes an issue where **getPackageName** during the **callerInitOnce** function can be something other than _github.com/sirupsen/logrus_. This breaks the caller tracing entirely.. 

I added some logs to debug and here is an abstraction of the events

### During initialization 

> creating new logger instance
> Call to getPackageName            # returns **runtime** as package name
> Call to getPackageName (again) # returns github.com/sirupsen/logrus

After the initialization of **logrusPackage** call tracing then looks for the first package name that doesn't match the one set during init. However there is a chance that this package could be something other than _github.com/sirupsen/logrus_
In such as case all attempts to find the caller will return logrus.entry as the caller.

Setting logrusPackage = "_github.com/sirupsen/logrus_" fixes this completely. So the issue is getPackageName in some circumstances can return the incorrect package.. Something other than _github.com/sirupsen/logrus_.

**Comment by JustDaile** [comment]
Just going to ignore this issue?

**Comment by gguridi** [comment]
@JustDaile The line you are mentioning seems related to version 1.4.x of logrus.

I think the issue you're having was fixed as part of the #1102 and should have been released as part of logrus 1.5.0. Can you confirm if you are having issues with the latest version of logrus?

**Comment by JustDaile** [comment]
Yes, my mistake I hadn't updated and was still on 1.4
updated to latest and is resolved. 

Thanks
