### ISSUE TITLE
Excuse me.  Log printing line number, function name and other information problems

### ISSUE THREAD

**Issue by NickEric** [sirupsen/logrus#1166]
I have a problem.  When printing the log, in my project,  SetReportCaller(true);
![image](https://user-images.githubusercontent.com/68672695/91379161-99981800-e854-11ea-90c3-aeba0e0c2a7f.png)

Displayed on windows10 console.
![image](https://user-images.githubusercontent.com/68672695/91378813-ecbd9b00-e853-11ea-8efe-77f36d375ca8.png)

Displayed on LINUX or CentOS 7 console.
![image](https://user-images.githubusercontent.com/68672695/91378879-0fe84a80-e854-11ea-8fd2-107f7575b88c.png)

The number of lines, function name, location, etc. are the same as the printed content. This is not right. There is no D disk in CentOS system.

Why is this problem? How can I modify it?

**Comment by Sata51** [comment]
This is not related to logrus. Go generate a single binary with references to file path and this info includes the `$GOPATH`.

You can add the `trimpath` flag at build time to remove the `$GOPATH` part from the log like this :

```
go build -gcflags "all=-trimpath=$GOPATH"
```

**Comment by dgsb** [comment]
This prints the source path options at the build time.
So that depends on your build options.

**Comment by NickEric** [comment]
> This prints the source path options at the build time.
> So that depends on your build options.

ok, I get it. Thank you for your reply

**Comment by NickEric** [comment]
> This is not related to logrus. Go generate a single binary with references to file path and this info includes the `$GOPATH`.
> 
> You can add the `trimpath` flag at build time to remove the `$GOPATH` part from the log like this :
> 
> ```
> go build -gcflags "all=-trimpath=$GOPATH"
> `That's a great suggestion. Thank you.
