### ISSUE TITLE
[Question] Extracting full error into a variable

### ISSUE THREAD

**Issue by BentCoder** [sirupsen/logrus#1167]
Hi,

Just wondering if this is possible. By the way, I have hooks attached to the logger.

Thanks

```go
message := logrus.WithContext(r.Context()).Warning(err)
fmt.Println(message)
```

So the content of the `message` variable would be what logrus would log.
For instance: `{"env":"dev","level":"error","message":"context deadline exceeded","request_id":"338a6e89","request_method":"GET","time":"2020-07-11T22:07:47+01:00"}`

**Comment by pradykaushik** [comment]
[Warning(...)](https://github.com/sirupsen/logrus/blob/master/entry.go#L307) doesn't return anything so don't know what you're getting at.
Can you elaborate on this a little more?

**Comment by BentCoder** [comment]
I know it doesn't return anything. I was asking if we could somehow extract the message into a variable instead of outputting it. Maybe there was a flag, arg, method etc. that I am not aware of.

**Comment by gguridi** [comment]
Logrus as a logging library is not intended to be used as a formatter. Therefore it doesn't have methods to achieve that.

Said that, if I had to implement that behaviour, and not being responsible for what I'm about to say nor the consequences of implementing this... I would use channels:

```go
package main

import (
  "fmt"
  "github.com/sirupsen/logrus"
)

type Hook struct {
	Writer    chan string
	LogLevels []logrus.Level
}

func (hook *Hook) Fire(entry *logrus.Entry) error {
	line, err := entry.String()
	if err != nil {
                fmt.Printf("error: %+v", err)
		return err
	}
	hook.Writer <- line
	return nil
}

func (hook *Hook) Levels() []logrus.Level {
	return logrus.AllLevels
}

func main() {
 	hook := Hook{Writer: make(chan string, 1)}
  	logrus.SetFormatter(&logrus.JSONFormatter{})
  	logrus.AddHook(&hook)
  	logrus.WithContext(context.Background()).Warning("This is a warning")
  	logged := <- hook.Writer
	fmt.Printf("Logged: %s", logged)
}
```

Things to consider with this:
- Don't do it. Seriously. Use a function to custom format the message before doing this.
- If you don't read a message from the channel for each message you or someone writes in the logger, you'll get a deadlock... you can increase the buffer but that's just gonna buy you some time.
- If there's concurrent logging happening you might end up with a message that's not what you just wrote in the logger.

**Comment by gguridi** [comment]
I just discovered that you can use the test hook for that purpose:

```go
package main

import (
  "fmt"
  "github.com/sirupsen/logrus"
   logrus_test "github.com/sirupsen/logrus/hooks/test"
)

func main() {
	logrus.SetFormatter(&logrus.JSONFormatter{})
 	hook := logrus_test.NewGlobal()
   	logrus.AddHook(hook)
  	logrus.WithContext(context.Background()).Warning("This is a warning")
  	logged, _ := hook.LastEntry().String()
        // Prevent the test hook to keep storing all the logs.
	hook.Reset()
	fmt.Printf("Logged: %s", logged)
}
```
