### ISSUE TITLE
make err

### ISSUE THREAD

**Issue by chaseSpace** [sirupsen/logrus#1170]
```
go: github.com/metaverse/truss/cmd/truss imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
```

**Comment by chaseSpace** [comment]
version 0.1.0

**Comment by abenettt** [comment]
This is an error of `github.com/metaverse/truss` and not `logrus`. The version `0.1.0` of `github.com/metaverse/truss` still uses [`dep`](https://github.com/golang/dep), which has been deprecated with the release of go modules in `go v1.11`. Import paths have to be lowercase only and this has not been the case in the ` 0.1.0` release of `github.com/metaverse/truss`. If you look at the repository now, they have migrated to go modules and have updated their import paths so you should ask the maintainer to create a new release or use the library from it's main branch.

**Comment by chaseSpace** [comment]
thanks
