### ISSUE TITLE
Add module casing change workaround to README

### ISSUE THREAD

**Issue by abursavich** [sirupsen/logrus#1176]
I've been bitten by this several times and it's always maddening, but it can be fixed with a module replace directive:

`replace github.com/Sirupsen/logrus => github.com/sirupsen/logrus v1.6.0`

It would be helpful to users if this hack was called out in the README.

**Comment by dgsb** [comment]
Would this work in recursive module dependencies ?
The official position on this old topic if for package consumer is to fix their import rule.
We know this has been a sad bug for many users, but there is not many solution to provide beyond this one.
