### ISSUE TITLE
Sumologic Hook

### ISSUE THREAD

**Issue by mmarinm** [sirupsen/logrus#1177]
Existing Sumologic hook [sumorus](https://github.com/doublefree/sumorus) referenced in [Wiki Page](https://github.com/sirupsen/logrus/wiki/Hooks) is not working and beside that it is synchronous.

I wrote improved async version that is uploading to Sumologic either on interval or in batch, I would like to share it with your community.  [sumologrus](https://github.com/mmarinm/sumologrus)

Let me know If you want me to include it in Wiki Page, I'll open PR.

**Comment by dgsb** [comment]
Feel free to add your hooks in the list here https://github.com/sirupsen/logrus/wiki/Hooks
