### ISSUE TITLE
Q: log only configured severity

### ISSUE THREAD

**Issue by ivanjaros** [sirupsen/logrus#1178]
Logrus can be configured to log only specific severity, in which case it uses it as a number and logs anything with that value and lowe(or higher, don't remember). Which means that if I want to use `debug` logging I will see `info`, `warn`, `error`... and so on.

Is there a way to elimitante this and log only the specific severity or a list, instead of this "range"?

I presume I would have to write a wrapper for the writer but I'd prefer to have this in the library already, if possible.

**Comment by dgsb** [comment]
The log level, as implied by its name, is a level not a mask of authorized trace capabilities.
There is no builtin easy way to do what you are trying to achieve

**Comment by ivanjaros** [comment]
there could be a simple flag for this https://github.com/sirupsen/logrus/blob/d131c24e23baaa812461202af6d7cfa388e2d292/logger.go#L374

instead if >= it would use =

**Comment by gguridi** [comment]
I think logging only one level goes against the philosophy behind logging systems. It's a very particular case that IMHO shouldn't be supported by the logging library itself but implemented by whoever needs it.

With logrus is fairly easy to implement that behaviour using hooks (not tested though):

```go
package main

import (
	"io/ioutil"
	log "github.com/sirupsen/logrus"
)

func main() {
    // Remove the standard output of the logger.
    log.SetOutput(ioutil.Discard)

    // Add a hook that will log only one level into the Stdout
    log.AddHook(&writer.Hook{
	Writer: os.Stdout,
	LogLevels: []log.Level{
	 	log.DebugLevel,
        },
    })    
}
```

If the `Writer` hook that comes with logrus is not enough (there's a PR to add a Formatter to the hook) then we just need a bit more of code to create a custom Hook from scratch (not a lot of code involved in my opinion).
