### ISSUE TITLE
DisableSorting randomizes display order

### ISSUE THREAD

**Issue by utdrmac** [sirupsen/logrus#1179]
Here is my logging code:

```
log.SetFormatter(&log.TextFormatter{
		FullTimestamp:  true,
		DisableSorting: true,
	})
...
log.WithFields(log.Fields{
		"Priority":  priority,
		"Level":     level,
		"CurrentTS": time.Now().UTC().Format(time.RFC3339),
	}).Info("Slot found")
```

Here is the output, about 30s apart.

```
INFO[2020-09-26T20:01:38Z] Slot found           Level=753966 CurrentTS="2020-09-26T20:01:38Z" Priority=55
...
INFO[2020-09-26T20:02:08Z] Slot found           Priority=54 Level=753967 CurrentTS="2020-09-26T20:02:08Z"
```

Notice how the fields are in different order, despite the order in the log line. I have sorting disabled because I want the fields displayed in the order that I've put in the .WithFields() line. How do I enforce this order?

**Comment by phuslu** [comment]
I also suffer it as it is a hard thing before, now I rewrote another logging to resolve this issue.
It use a hand-writing json parser (performant & order-kept) https://github.com/phuslu/log/blob/master/json.go
The console writer output is always keeping the original(same as source code) order.

![](https://user-images.githubusercontent.com/195836/90043818-37d99900-dcff-11ea-9f93-7de9ce8b7316.png)

**Comment by dgsb** [comment]
We cannot easily ensure the fields are displayed in the order they are added. The data struct used is a map which does not guarantee the key order when browsing it.
The best alternative for you is to implement a custom sorting function to meet your need: https://github.com/sirupsen/logrus/blob/6699a89a232f3db797f2e280639854bbc4b89725/text_formatter.go#L65
