### ISSUE TITLE
Tag v1.6.1 (and v1.7.0 ?) releases

### ISSUE THREAD

**Issue by thaJeztah** [sirupsen/logrus#1181]
A number of changes were merged to master since the latest v1.6.0 release; https://github.com/sirupsen/logrus/compare/v1.6.0...6699a89a232f3db797f2e280639854bbc4b89725

In an effort to reduce the dependency tree in various projects, I'd like to see a release with https://github.com/sirupsen/logrus/pull/1088 included (which removes github.com/konsorten/go-windows-terminal-sequences as a dependency)

However, there's also some changes that were merged after that which look to be adding new functionality, so would require the "minor" version to be updated (to follow SemVer semantics);

- https://github.com/sirupsen/logrus/pull/1077 Add support for freebsd/arm64
- https://github.com/sirupsen/logrus/pull/1142 Function log
- https://github.com/sirupsen/logrus/pull/1144 Update doc for new logger 
- https://github.com/sirupsen/logrus/pull/1145 Add an API to plug a custom buffer free item mangement system

Projects may want to reduce changes and opt for only getting the first change, so my proposal would be to:

- tag commit 0de04f1584680e1bb99dc041eee3125fc0fd010c  as v1.6.1 (diff since v1.6.0: https://github.com/sirupsen/logrus/compare/v1.6.0...0de04f1584680e1bb99dc041eee3125fc0fd010c)
- tag 6699a89a232f3db797f2e280639854bbc4b89725 as v1.7.0 (current master, diff since v1.6.0: https://github.com/sirupsen/logrus/compare/v1.6.0...6699a89a232f3db797f2e280639854bbc4b89725)

@dgsb @markphelps @tklauser happy to hear your thoughts 👍

**Comment by tklauser** [comment]
Thanks for proposing this @thaJeztah, I'd appreciate a new release as well. Especially one including #1088 to reduce dependencies.

**Comment by dgsb** [comment]
Let's tag master with a minor bump. I'll do that this week.

**Comment by dgsb** [comment]
The new tag is available https://github.com/sirupsen/logrus/releases/tag/v1.7.0

**Comment by thaJeztah** [comment]
Thanks!
