### ISSUE TITLE
kafka hook

### ISSUE THREAD

**Issue by rwy-aha-QWQ** [sirupsen/logrus#1189]
I have a problem.When I  use custom kafka-hook：
 got：
![image](https://user-images.githubusercontent.com/34903942/95834310-614e8980-0d6f-11eb-8607-24fe5eb14d87.png)

expected：
 {"appid":10,"evt":"","ext":[],"lvl":"error","msg":"\<nil\>","src":"main.go:13","tm":"2020-10-13 15:24:47.438"}
 {"appid":10,"evt":"","ext":[],"lvl":"error","msg":"\<nil\>","src":"main.go:14","tm":"2020-10-13 15:26:45.298"}
why have blank lines in the log？

**Comment by dgsb** [comment]
Does the problem still occur when the kafka hook is removed ?

**Comment by rwy-aha-QWQ** [comment]
> Does the problem still occur when the kafka hook is removed ?

I have not try.  But  I try to  use
[https://github.com/tracer0tong/kafkalogrus](url)   or 
[https://github.com/gfremex/logrus-kafka-hook](url)
the same problem would still occu.

**Comment by dgsb** [comment]
Sure but these hooks does not really belong to the logrus project.
If you can't reproduce the issue when removing these hooks, the problem will probably be located in this software layer.
You should then reach these project to raise an issue.

**Comment by gguridi** [comment]
@rwy-aha-QWQ There's no much information to get what's wrong... but my first impression is that you're simply sending a `nil` value to the logger. Logrus or the hooks (that I know) won't try to format `nil` values as empty strings. If you need that behaviour you will have to preprocess the message before sending it to the logger or create a custom JSONFormatter. 

This code will print `"msg":"<nil>"` and it's totally the expected behaviour:
```golang
l := logrus.New()
l.SetFormatter(&logrus.JSONFormatter{})
l.SetOutput(os.Stdout)
l.Info(nil)
fmt.Println("\u003cnil\u003e")
```

**Comment by rwy-aha-QWQ** [comment]
> @rwy-aha-QWQ There's no much information to get what's wrong... but my first impression is that you're simply sending a `nil` value to the logger. Logrus or the hooks (that I know) won't try to format `nil` values as empty strings. If you need that behaviour you will have to preprocess the message before sending it to the logger or create a custom JSONFormatter.
> 
> This code will print `"msg":"<nil>"` and it's totally the expected behaviour:
> 
> ```go
> l := logrus.New()
> l.SetFormatter(&logrus.JSONFormatter{})
> l.SetOutput(os.Stdout)
> l.Info(nil)
> fmt.Println("\u003cnil\u003e")
> ```

sry,I  edited it.The problem is that each log has a blank line.

**Comment by dgsb** [comment]
I don't understand what's the issue. Can we have a code sample without a kafka hook which exhibit the unexpected output ?

**Comment by rwy-aha-QWQ** [comment]
> I don't understand what's the issue. Can we have a code sample without a kafka hook which exhibit the unexpected output ?

```
func (hook *KafkaHook) Fire(entry *logrus.Entry) error {
	b, err := hook.formatter.Format(entry)
	if err != nil {
		return err
	}
	fmt.Println(b) 
	tmp := strings.Replace(string(b),"\n","",-1)
	value := sarama.ByteEncoder(tmp)
	topics := hook.topics
	for _, topic := range topics {
		hook.producer.Input() <- &sarama.ProducerMessage{
			Topic: topic,
			Value: value,
		}
		//hook.producer.SendMessage(&sarama.ProducerMessage{Topic: topic,Value: value})
	}
	return nil
}
```
output：  
![image](https://user-images.githubusercontent.com/34903942/96062800-2ceee080-0ec9-11eb-81ab-cf4689eb0799.png)

If not  use  ``` tmp := strings.Replace(string(b),"\n","",-1) ```
output: 
![image](https://user-images.githubusercontent.com/34903942/96062975-86efa600-0ec9-11eb-8e56-bd78cc4d5862.png)

**Comment by rwy-aha-QWQ** [comment]
It  seemed   I  have  got  the  answer：
logrus:   json_formatter.go
![image](https://user-images.githubusercontent.com/34903942/96074376-1ea9c000-0edb-11eb-84c9-498b2665677c.png)

json:   stream.go
![image](https://user-images.githubusercontent.com/34903942/96074433-413bd900-0edb-11eb-8510-7308a5a57a74.png)
