### ISSUE TITLE
fireHooks lock system and became very lag.(open too many file)

### ISSUE THREAD

**Issue by Detail0805** [sirupsen/logrus#1193]
![abcd](https://user-images.githubusercontent.com/29973842/97578512-ddadc180-1a2b-11eb-89bf-03d52e995290.jpg)

I am using ELK and make a tcp connection to my logstash.

Today my ELK is crash down and I found my server will slowly by this code.

When logrus try to do this:

               fmt.Fprintf(os.Stderr, "Failed to fire hook: %v\n", err)

My linux file is open too much.

I know I can rewrite fire and levels function make it return nil.

I just 4-5 log / second.

**Comment by dgsb** [comment]
We need more context to understand what your problem is.

**Comment by Detail0805** [comment]
> We need more context to understand what your problem is.
> Which hooks are you using, a code sample, etc ...

The code is in the entry.go 259 line (version tag v1.7.0).

My scenario is when elk is disconnected, this code will cause my operating system to open the file repeatedly.

Because ELK log is very huge. The file will open to many and let server crash down.

I think no one thought that the log server would be disconnected.

My suggestion is to use rate limit algorithm to solve.

**Comment by dgsb** [comment]
We have changed the locking system in v1.8.1
