### ISSUE TITLE
TextFormatter completely different format with colors off

### ISSUE THREAD

**Issue by utdrmac** [sirupsen/logrus#1194]
When colors are enabled within the TextFormatter, the output is neatly formatted using spaces and padding. When colors are disabled, the output completely changes. No padding, no spacing, way more quotes. Essentially, disabling colors turns the output into a line of K/V pairs.

The first two lines below are with colors enabled, output saved to file using Writer hook. The last two lines have colors disabled. Note the huge difference in formatting.

```
ESC[33mWARNESC[0m[2020-10-29T15:25:06Z] Shutting things down...       ESC[36mLevelESC[0m=836595 ESC[36mMaxPriorityESC[0m=4
ESC[36mINFOESC[0m[2020-10-29T15:25:06Z] Database closed               ESC[36mCurrentTSESC[0m="2020-10-29T03:58:50Z" ESC[36mLevelESC[0m=836596

time="2020-10-29T15:25:10Z" level=info msg="Connected to RPC server" Host="http://127.0.0.1:18732"
time="2020-10-29T15:25:10Z" level=debug msg="Loaded Network Constants" BlocksPerCycle=2048
```

The formatting should NOT change by simply disabling colors. The expected output with colors disabled should match the SAME FORMAT as with colors enabled.

Expected when colors off:
```
WARN[2020-10-29T15:25:06Z] Shutting things down...       Level =836595 MaxPriority=4
INFO[2020-10-29T15:25:06Z] Database closed               CurrentTS="2020-10-29T03:58:50Z" Level=836596
```
This is the same format as colors on, except missing the color sequences

**Comment by laojianzi** [comment]
https://github.com/sirupsen/logrus/blob/cd4bf4ef8de16b243cce0e062742feb34128648b/text_formatter.go#L203-L222

The biggest difference is that these fixed keys

If these fixed keys are not present, or if the fixed keys are present in color printing, I think it is possible to keep the formatting consistent.

**Comment by utdrmac** [comment]
Yea, I fixed this on my own branch. Didn't bother to PR it as this project is dead, unlikely to get merged.

**Comment by dgsb** [comment]
@utdrmac I may find a spare time to merge a few MR if you provide one

**Comment by utdrmac** [comment]
@dgsb https://github.com/sirupsen/logrus/pull/1254
