### ISSUE TITLE
Log only the current module, not the imported ones

### ISSUE THREAD

**Issue by alessiosavi** [sirupsen/logrus#1196]
### Scenario:
`module_A` use `logrus` as logging framework
`my_current_module` use `logrus` as logging framework

`my_current_module` is the module that I'm developing on my machine. In order to have some method, i import `module_A` and call some function.

Is it possible to enable the logger only for the current package (`my_current_module`)?

**Comment by dgsb** [comment]
There is nothing which allows to do that. Most of the time module provider provide an interface to give the logger to be used by the consumed module.
You should check if there is something similar in the module you are using.
