### ISSUE TITLE
Is there a way to get access to the current *http.Request in middleware? 

### ISSUE THREAD

**Issue by jeberly** [Sirupsen/logrus#120]
The title says it all, "Is there a way to get access to the current *http.Request in middleware?", Ideally, I would like to print out IP address, etc in fields.

**Comment by Sirupsen** [comment]
What I'd recommend doing in this case is use `WithFields` to generate a `logrus.Entry` with default fields, it looks something like this:

```go
request_logger := log.WithFields(logrus.Fields{"ip": request.RemoteAddr})
# .. stuff

request_logger.WithFields(logrus.Fields{ ... }).Info("something happened")
```

When you log with `WithFields` it actually returns a new `logrus.Entry`. Entries are not logged until you call one of the logging level methods, you can keep inheriting as deep as you like.

You can probably use reflection or something to do it automatically, but I'd strongly discourage that.

Have a good weekend!
