### ISSUE TITLE
FieldLogger doesn't support IsLevelEnabled

### ISSUE THREAD

**Issue by koote** [sirupsen/logrus#1204]
Hi team, given that FieldLogger is the abstraction of Logger and Entry, can we also add this function in FieldLogger interface? Thanks!

**Comment by dgsb** [comment]
We cannot merely do that. Adding a new method to an interface is a non-backward compatible modification.

**Comment by dgsb** [comment]
Usually in go, we'd rather define the interface at the consumer side. This interface is not going to evolve in the next releases.

**Comment by koote** [comment]
Is it OK to add `IsLevelEnabled` and `SetLevel` in `Entry` while `FieldLogger` interfacer remains changed?

**Comment by koote** [comment]
> Usually in go, we'd rather define the interface at the consumer side. This interface is not going to evolve in the next releases.
Thanks! Is it OK to add IsLevelEnabled and SetLevel in Entry while FieldLogger interfacer remains changed?

**Comment by koote** [comment]
> Usually in go, we'd rather define the interface at the consumer side. This interface is not going to evolve in the next releases.

If `FieldLogger` cannot be changed for backward compatibility, can we add a new interface?

```
type ExFieldLogger interface {
    FieldLogger
    SetLevel(level Level)
    IsLevelEnabled(level Level) bool
}
```

**Comment by dgsb** [comment]
This interface  could easily be added at consumer side.

**Comment by dgsb** [comment]
A patch for `Entry.IsLevelEnabled` would be welcome.
