### ISSUE TITLE
Add Notice level

### ISSUE THREAD

**Issue by smithwinston** [Sirupsen/logrus#121]
It would be nice to have an additional level between Info and Warning `Notice`.  I tend to use logging as follows:

  * `Notice`: System start/stop, significant-but-normal events
  * `Info`: Detail: User connected, transaction applied etc.
  * `Debug`: In depth debugging/tracing, e.g. packet dumps

I usually would have the default log level set to Notice and have Errors, Fatal and Panic logged to a remote server for analysis.

**Comment by Sirupsen** [comment]
This is a pretty narrow use case, and not something that's come up before. It won't be added to Logrus for now. Thanks for the suggestion!

**Comment by kellydunn** [comment]
I would also like to see this Log level be introduced into `logrus`.  I too, like to use `Notice` for errors that aren't as critical and not uncommon to see in a normal workflow.  `Warning` and `Error` are usually too severe, and `Notice` is helpful.

**Comment by Sirupsen** [comment]
@kellydunn it's planned for 1.x that you can add any logging levels you want, as levels will simply become fields, and formatters will support that field or they won't.

**Comment by jonhoo** [comment]
@Sirupsen: is more information about 1.x available somewhere?

**Comment by Sirupsen** [comment]
@jonhoo not yet, I'm still thinking about it. But it'll be much more customizable, msg, levels etc. won't be special, and center around Go contexts (see the package).

**Comment by jonhoo** [comment]
@Sirupsen sounds great. Being able to have multiple debug levels, and being able to use the logging library sensibly in two different packages that are both used simultaneously, are two of my biggest concerns atm.

**Comment by iigorr** [comment]
+1 for customizable log levels. A generic `Log(Level, string)` would fit in nicely IMHO.
As for "fixed" levels I'd have 2 suggestions:
#1:
```Verbose

**Comment by sleaze** [comment]
Did this ever happen?
