### ISSUE TITLE
Why didn't my log file print out correctly

### ISSUE THREAD

**Issue by xiaxichen** [sirupsen/logrus#1211]
logrus version 1.4.2
go version 1.15.2
```
package logger

import "github.com/sirupsen/logrus"

var Log *logrus.Logger

func init() {
	Log = logrus.New()
	Log.SetFormatter(&logrus.TextFormatter{
		FullTimestamp: true,
	})
	Log.SetReportCaller(true)
	Log.Info("start Log！")
}
```
log
```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/xiaxichen/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/___go_build_learn_zinx_zinx_myDemo_ZinxV0_6_server learn_zinx/zinx/myDemo/ZinxV0.6/server #gosetup
/private/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/___go_build_learn_zinx_zinx_myDemo_ZinxV0_6_server
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() start Log！                                   
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() reload config success!                       
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() &{<nil> 127.0.0.1 9000 ZinxDemo V0.6 1000 2048} 
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() Add Api MsgId=0 ; success!                   
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Add Router success!                          
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() Add Api MsgId=1 ; success!                   
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Add Router success!                          
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() [Zinx] Config &{TcpServer:<nil> Host:127.0.0.1 TcpPort:9000 Name:ZinxDemo Version:V0.6 MaxConn:1000 MaxPackageSize:2048} 
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() [Zinx] final Config &{Name:ZinxDemo IPVersion:tcp4 IP:127.0.0.1 Port:9000 MsgHandler:0xc0000b0070 ServerVersion:V0.6} 
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() [Start] Server listener at IP 127.0.0.1 ,Port 9000, is starting! 
INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() strat Zinx server success ! ZinxDemo listening... 
```

**Comment by xiaxichen** [comment]
but when i debuf for goland .
It's going to show up.
```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/xiaxichen/go #gosetup
/usr/local/go/bin/go build -o /private/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/___1go_build_learn_zinx_zinx_myDemo_ZinxV0_6_server -gcflags all=-N -l learn_zinx/zinx/myDemo/ZinxV0.6/server #gosetup
/Applications/GoLand.app/Contents/plugins/go/lib/dlv/mac/dlv --listen=0.0.0.0:52512 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec /private/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/___1go_build_learn_zinx_zinx_myDemo_ZinxV0_6_server --
API server listening at: [::]:52512
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1103.0.22
 for x86_64.
Got a connection, launched process /private/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/___1go_build_learn_zinx_zinx_myDemo_ZinxV0_6_server (pid = 6752).
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/logger/log.go:13 learn_zinx/zinx/logger.init.0() start Log！                                   
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/utils/globalobj.go:48 learn_zinx/zinx/utils.GlobalObj.Reload() reload config success!                       
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/utils/globalobj.go:49 learn_zinx/zinx/utils.GlobalObj.Reload() &{<nil> 127.0.0.1 9000 ZinxDemo V0.6 1000 2048} 
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/znet/msgHandler.go:33 learn_zinx/zinx/znet.(*MsgHandle).AddRouter() Add Api MsgId=0 ; success!                   
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/znet/Server.go:80 learn_zinx/zinx/znet.(*Server).AddRouter() Add Router success!                          
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/znet/msgHandler.go:33 learn_zinx/zinx/znet.(*MsgHandle).AddRouter() Add Api MsgId=1 ; success!                   
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/znet/Server.go:80 learn_zinx/zinx/znet.(*Server).AddRouter() Add Router success!                          
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/znet/Server.go:36 learn_zinx/zinx/znet.(*Server).Start() [Zinx] Config &{TcpServer:<nil> Host:127.0.0.1 TcpPort:9000 Name:ZinxDemo Version:V0.6 MaxConn:1000 MaxPackageSize:2048} 
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/znet/Server.go:37 learn_zinx/zinx/znet.(*Server).Start() [Zinx] final Config &{Name:ZinxDemo IPVersion:tcp4 IP:127.0.0.1 Port:9000 MsgHandler:0xc0000b8070 ServerVersion:V0.6} 
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/znet/Server.go:38 learn_zinx/zinx/znet.(*Server).Start() [Start] Server listener at IP 127.0.0.1 ,Port 9000, is starting! 
INFO[2020-12-06T14:32:49+08:00]/Users/xiaxichen/Learn_zinx/zinx/znet/Server.go:52 learn_zinx/zinx/znet.(*Server).Start.func1() strat Zinx server success ! ZinxDemo listening... 
```

**Comment by xiaxichen** [comment]
my go env
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xiaxichen/Library/Caches/go-build"
GOENV="/Users/xiaxichen/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xiaxichen/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xiaxichen/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xiaxichen/Learn_zinx/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/go-build668651071=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by LOFTERART** [comment]
Try  latest version...

**Comment by LOFTERART** [comment]
> logrus version 1.4.2
> go version 1.15.2
> 
> ```
> package logger
> 
> import "github.com/sirupsen/logrus"
> 
> var Log *logrus.Logger
> 
> func init() {
> 	Log = logrus.New()
> 	Log.SetFormatter(&logrus.TextFormatter{
> 		FullTimestamp: true,
> 	})
> 	Log.SetReportCaller(true)
> 	Log.Info("start Log！")
> }
> ```
> 
> log
> 
> ```
> GOROOT=/usr/local/go #gosetup
> GOPATH=/Users/xiaxichen/go #gosetup
> /usr/local/go/bin/go build -o /private/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/___go_build_learn_zinx_zinx_myDemo_ZinxV0_6_server learn_zinx/zinx/myDemo/ZinxV0.6/server #gosetup
> /private/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/___go_build_learn_zinx_zinx_myDemo_ZinxV0_6_server
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() start Log！                                   
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() reload config success!                       
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() &{<nil> 127.0.0.1 9000 ZinxDemo V0.6 1000 2048} 
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() Add Api MsgId=0 ; success!                   
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Add Router success!                          
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() Add Api MsgId=1 ; success!                   
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Add Router success!                          
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() [Zinx] Config &{TcpServer:<nil> Host:127.0.0.1 TcpPort:9000 Name:ZinxDemo Version:V0.6 MaxConn:1000 MaxPackageSize:2048} 
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() [Zinx] final Config &{Name:ZinxDemo IPVersion:tcp4 IP:127.0.0.1 Port:9000 MsgHandler:0xc0000b0070 ServerVersion:V0.6} 
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() [Start] Server listener at IP 127.0.0.1 ,Port 9000, is starting! 
> INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() strat Zinx server success ! ZinxDemo listening... 
> ```

Try latest version...

**Comment by xiaxichen** [comment]
> > logrus version 1.4.2
> > go version 1.15.2
> > ```
> > package logger
> > 
> > import "github.com/sirupsen/logrus"
> > 
> > var Log *logrus.Logger
> > 
> > func init() {
> > 	Log = logrus.New()
> > 	Log.SetFormatter(&logrus.TextFormatter{
> > 		FullTimestamp: true,
> > 	})
> > 	Log.SetReportCaller(true)
> > 	Log.Info("start Log！")
> > }
> > ```
> > 
> > 
> > log
> > ```
> > GOROOT=/usr/local/go #gosetup
> > GOPATH=/Users/xiaxichen/go #gosetup
> > /usr/local/go/bin/go build -o /private/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/___go_build_learn_zinx_zinx_myDemo_ZinxV0_6_server learn_zinx/zinx/myDemo/ZinxV0.6/server #gosetup
> > /private/var/folders/qk/tgc9vq6j6lbgwlsxgb4lyyd40000gn/T/___go_build_learn_zinx_zinx_myDemo_ZinxV0_6_server
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() start Log！                                   
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() reload config success!                       
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() &{<nil> 127.0.0.1 9000 ZinxDemo V0.6 1000 2048} 
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() Add Api MsgId=0 ; success!                   
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Add Router success!                          
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() Add Api MsgId=1 ; success!                   
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() Add Router success!                          
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() [Zinx] Config &{TcpServer:<nil> Host:127.0.0.1 TcpPort:9000 Name:ZinxDemo Version:V0.6 MaxConn:1000 MaxPackageSize:2048} 
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() [Zinx] final Config &{Name:ZinxDemo IPVersion:tcp4 IP:127.0.0.1 Port:9000 MsgHandler:0xc0000b0070 ServerVersion:V0.6} 
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314 github.com/sirupsen/logrus.(*Entry).Logf() [Start] Server listener at IP 127.0.0.1 ,Port 9000, is starting! 
> > INFO[2020-12-06T14:34:27+08:00]/Users/xiaxichen/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 github.com/sirupsen/logrus.(*Logger).Log() strat Zinx server success ! ZinxDemo listening... 
> > ```
> 
> Try latest version...

thanks ！
