### ISSUE TITLE
Unnecessary info printed

### ISSUE THREAD

**Issue by dakyskye** [sirupsen/logrus#1216]
```go
var logger = logrus.New()

logger.SetLevel(logrus.DebugLevel)
logger.ReportCaller = true
logger.SetFormatter(&logrus.TextFormatter{DisableTimestamp: false, ForceQuote: true})
```
this is my logger instance.

When I do `logger.WithField("foo", "bar").Debug("test")` I get `DEBU[0000]/path/to/program.go:line package/function() test fields.foo="bar" foo="bar"`. 

My question is why do I need what the value of field `foo` is twice? I'd be perfectly fine with just one.
![image](https://user-images.githubusercontent.com/32128756/103468222-41c46d00-4d70-11eb-82b2-5667c97a9e52.png)

**Comment by dgsb** [comment]
This is very unlikely.
I cannot reproduce the issue https://play.golang.org/p/Ec6ejlkQFtD

What version are you using ?
Can you provide a simple buildable example which exhibits the bug ?
I suspect you somehow add 2 fields with these 2 different names

**Comment by dakyskye** [comment]
It is weird I can't reproduce it either. The output format on go playground is absolutely different from my local one (yet logger configs are the same). Let me push my code where it's reproducible and I'll update you.

**Comment by dakyskye** [comment]
Okay, [this](https://github.com/dakyskye/dxhd/blob/rewrite/logger/logger.go) is my logger module and [this](https://github.com/dakyskye/dxhd/blob/rewrite/app/cli.go#L59) is my issue.

**Comment by dgsb** [comment]
Sorry, I don't have time to debug your application.
A bug in logrus causing this behaviour is very unlikely.
Can you provide a reproducible test case ?

**Comment by dakyskye** [comment]
I will try to provide one when I get time 👍
