### ISSUE TITLE
how to add custom level?

### ISSUE THREAD

**Issue by hongliu9527** [sirupsen/logrus#1221]
I need to add a custom level to logrus, and this level will not influence by the level set by logger.SetLevel() function, need some help.

**Comment by dgsb** [comment]
There is no such feature of custom log level in logrus. What are you trying to achive ?

**Comment by dgsb** [comment]
Can we close this issue ?

**Comment by hongliu9527** [comment]
> Can we close this issue ?

We, Use trace as custom level, Close it please
