### ISSUE TITLE
pls upd the mod link in go.mod

### ISSUE THREAD

**Issue by Shane-XB-Qian** [sirupsen/logrus#1222]
// i actually didnot use this, but looks soar and tidb using this.. better to correct it..
// since this is just a tiny correction, so no plan to open pr, but just a msg here.. fyi................

```log
github.com/XiaoMi/soar/advisor imports
	github.com/pingcap/tidb/ast imports
	github.com/pingcap/tidb/util/types imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.7.0: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
```

**Comment by dgsb** [comment]
You should open a ticket in the repository which imports the incorrect path.
This has been debated a lot already.

**Comment by Shane-XB-Qian** [comment]
On 21/02/04 05:29AM, David Bariod wrote:
> You should open a ticket in the repository which imports the incorrect path.
> This has been debated a lot already.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sirupsen/logrus/issues/1222#issuecomment-773303576

I think here itself matched the case would be better, it's regardless what they imported,
I think normally user just followed the repo the case the name.

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
um... interesting, i just noticed your/this repo name is in lower case..
// so you are right..
