### ISSUE TITLE
Fix GitHub releases descriptions

### ISSUE THREAD

**Issue by dolmen** [sirupsen/logrus#1224]
This is about https://github.com/sirupsen/logrus/releases

The following releases have broken changelog:
* v1.7.0 is not formatted like other releases
* v1.6.0 says nothing
* v1.4.2 says nothing

**Comment by dgsb** [comment]
The source of truth is supposed to be in this file
https://github.com/sirupsen/logrus/blob/master/CHANGELOG.md
Does its content sounds clear enough ?

**Comment by dgsb** [comment]
I don't have time to fix past releases descriptions, we'll try to keep think consistent for the next ones
