### ISSUE TITLE
No timediff/timestamp in logs from go test

### ISSUE THREAD

**Issue by lootek** [sirupsen/logrus#1235]
The time field is missing in Go test output (there's neither the full timestamp nor the 4-digit time diff), I don't set any special things besides lowering the log level to trace for the particular test.

I noticed this behavior after upgrading logrus from 1.7.0 to 1.7.1, the same also applies to v1.8.0.

Sometimes the time field is present for some time and then disappears randomly after few dozens of log lines.

I use Go 1.15 if that matters

expected (v1.7.0)
```
=== RUN   TestFoo
time="2021-02-18T14:06:52+01:00" level=trace msg="foo"
```

buggy (v1.7.1 and v1.8.0)
```
=== RUN   TestFoo
level=trace msg="foo"
```

OR

```
=== RUN   TestFoo
time="2021-02-18T14:06:52+01:00" level=trace msg="foo"
(...)
level=trace msg="bar"
```

**Comment by dgsb** [comment]
I didn't see anything yet which could be the source of the behaviour. Would you mind sharing a trimmed down test case which would exhibit this bug ?

**Comment by dgsb** [comment]
@lootek how can we reproduce the issue ?

**Comment by lootek** [comment]
@dgsb yeah, sorry for not replying, just too much regular work
I'm trying to reproduce this with some minimal code stub but with no success yet. Nonetheless I'm still experiencing this issue in the project I work on, but unfortunately it's not open source... 
I'll do my best to return to you with some code in a week or so.

**Comment by lootek** [comment]
lol, I've spent some time debugging this and that was caused by an edge-case race on our side, sorry for the confusion, closing.
