### ISSUE TITLE
Extra space output when use logrus.WithFields()

### ISSUE THREAD

**Issue by praisethejack** [sirupsen/logrus#1237]
```
defer logrus.WithFields(logrus.Fields{
		"key": 14,
		"obj": "SafeHostLogStrategy",
	}).Info("Updated")
```
I use WithFields as above, but why there are so many space after "Updated"?
The following is output.
Is there any way to get rid of those space?
```
INFO[2021-02-19T15:35:11+08:00] Updated                                       key=14 obj=SafeHostLogStrategy
```

**Comment by dgsb** [comment]
There is a padding on the message field when the text formatter is configured in colored mode which is there since a very long time
https://github.com/sirupsen/logrus/blob/f104497f2b2129ab888fd274891f3a278756bcde/text_formatter.go#L280
You may desactivate the colored mode if you want to get rid of that.

**Comment by praisethejack** [comment]
> There is a padding on the message field when the text formatter is configured in colored mode which is there since a very long time
> https://github.com/sirupsen/logrus/blob/f104497f2b2129ab888fd274891f3a278756bcde/text_formatter.go#L280
> 
> 
> You may desactivate the colored mode if you want to get rid of that.

thx, OK, it work.

How ever, after I set DisableColors to true as following：
```
	logrus.SetFormatter(&logrus.TextFormatter{
		DisableTimestamp: false,
		FullTimestamp:    true,
		//DisableColors:    true, // this
	})
```
The new log format looks like this:
```
# this is DisableColors: false(defalut)

[root@master falcon7d_tmp]# ./hbs -c hbs.json 
INFO[0000] read config file:hbs.json successfully       
time="2021-02-22T16:25:04+08:00" level=info msg="cache begin"
time="2021-02-22T16:23:24+08:00" level=info msg=Updated key=14 obj=SafeHostLogStrategy

# this is DisableColors: true

[root@master falcon7d_tmp]# ./hbs -c hbs.json 
INFO[0000] read config file:hbs.json successfully       
INFO[2021-02-22T16:41:04+08:00] cache begin                                  
INFO[2021-02-22T16:41:04+08:00] Updated                                       key=14 obj=SafeHostLogStrategy
```
How can I do to make the log look like this?
```
INFO[2021-02-22T16:41:04+08:00] Updated key=14 obj=SafeHostLogStrategy
```

**Comment by dgsb** [comment]
It seems you can't with the current `TextFormatter` implementation.
