### ISSUE TITLE
Invalid year shown when using custom timestamp formatter containing 2020 year 

### ISSUE THREAD

**Issue by reversekick** [sirupsen/logrus#1242]
time="4040-03-04 18:38:12.673130" level=info msg="Current Connectivity state SUCCESS"

This how it logs --the details are captured in https://play.golang.org/p/MwIcUG74NBD

**Comment by 2rigor** [comment]
You should use the provided timestamp (Jan-2 2006), changing only the order to get different formats. but you should not use other dates (timestamps) to express the format. I agree it's not very clear. It's not related to logrus, but rather to [go's time.format](https://golang.org/src/time/format.go?s=16082:16124#L10)

**Comment by reversekick** [comment]
Interesting --never thought there would be restriction of such a kind -- it would have been nice if they had taken the format in string "YYYY--MM-dd HH:mm:ss"  like is done in Java https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html.

**Comment by reversekick** [comment]
Can we add in the documentation of TimestampFormat that the string must contain the date starting with year 2006 as in  2006-01-02 15:04:05 ? and that no other date string will work other than the one starting with 2006 and mention this restriction is due to  to go's time.format & provide reference & close this issue. 

This way nobody else will run into this issue.

**Comment by dgsb** [comment]
We will add a comment stating that the format is the same than `time.Format` and `time.Parse` from the standard library

**Comment by dgsb** [comment]
fixed by 7a997b928
