### ISSUE TITLE
How to generate a log identifier

### ISSUE THREAD

**Issue by sfl0r3nz05** [sirupsen/logrus#1243]
Hello logrus experts,

I am working on creating a trust system on logs obtained from logrus. At the moment, as you can see in the image I can generate logs for my use case.
![image](https://user-images.githubusercontent.com/6643905/110347862-543d7a00-8031-11eb-9504-175f5d83ca4d.png)

However, once these logs have been collected, I need to send them to an ELK infrastructure, for this reason, I need an identifier for each logs that will allow me to map them into a secure system. For instance:

![image](https://user-images.githubusercontent.com/6643905/110348221-b302f380-8031-11eb-9ac5-9b077868dc87.png)

Could I get some default identifier through Logrus, for each log generated?

Thanks in advance,

Santiago.

**Comment by dgsb** [comment]
We don't have any native unique identifier per log in logrus internal.
You could use a hook to generate an uuid though and add it to a field of each trace.

**Comment by sfl0r3nz05** [comment]
Thanks @dgsb.

In this regard, is there any way to ensure that this uuid is really unique and not just random or do you consider providing external storage (e.g., db) for it?

**Comment by dgsb** [comment]
uuid are considered safe enough regarding unicity/collision in distributed systems.

**Comment by sfl0r3nz05** [comment]
Thanks @dgsb. I will close the issue.
