### ISSUE TITLE
Can we make BufferPool bind to Logger?

### ISSUE THREAD

**Issue by edoger** [sirupsen/logrus#1247]
Sometimes we need to specify different buffer pools for different loggers. The current version makes it impossible for us to do so!

like: 
```
Logger.SetBufferPool(pool BufferPool)
```

The advantage of this is that loggers for different purposes can use different buffers.
```
type LimitBufferPool struct {
    pool *sync.Pool
    cap int
}

func (p *LimitBufferPool) Put(buf *bytes.Buffer) {
    if buf.Cap() > p.cap {
        return
    }
    p.pool.Put(buf)
}

func (p *LimitBufferPool) Get() *bytes.Buffer {
    return p.pool.Get().(*bytes.Buffer)
}
```

**Comment by dgsb** [comment]
That could be practical indeed. The trick though is too make the implementation so that it doesn't break application which does not set this field upon static declaration of a logger.
A pull request would be most welcome.

**Comment by edoger** [comment]
I'll implement it by the end of the weekend.

**Comment by edoger** [comment]
link #1253

**Comment by edoger** [comment]
The feature has been implemented.
