### ISSUE TITLE
Support for json.RawMessage in logrus TextFormatter

### ISSUE THREAD

**Issue by alexus1024** [sirupsen/logrus#1248]
If I want to log json as field, I call
`log.WithField("data", json.RawValue(dataBytes))`

It works great with json formatter - It just adds json to output without excess screening (`\"`).

But if I use text formatter it looks like this:
`data="[5b 22 66 69 78 6d 65 22 2c 20 22 70 6c 65 61 73 65 22 5d]"`
as if I used just `log.WithField("data", dataBytes)`  where dataBytes is []byte

I expect in case if json.RawValue used, TextFormatter should output bytes as a string: `data="[\"fixme", \"please\"]"` for example before. Don't sure about screening in this case, but it is not so important for text log.

PS: json.RawValue here is from standard encoding\json package

**Comment by dgsb** [comment]
I guess you mean `json.RawMessage` instead of `json.RawValue`.

the JSONFormatter use a json.Encoder to format all fields, indeed he is able to correctly encode it.
However the TextFormatter expect fields to be `fmt.Sprint`able.
Here is the offending line: https://github.com/sirupsen/logrus/blob/fdf1618bf7436ec3ee65753a6e2999c335e97221/text_formatter.go#331

Not sure what we should do here.

**Comment by alexus1024** [comment]
> I guess you mean json.RawMessage instead of json.RawValue.
Yes, my mistake

**Comment by alexus1024** [comment]
My current workaround:
```golang
// JSONRawMessage is like a json.RawMessage but Sprit outputs valid string for it, not bytes.
// For example logrus.WithField("key", JSONRawMessage{}) will output normal text with both JSON and Console formatter.
type JSONRawMessage json.RawMessage

func (m JSONRawMessage) String() string {
	return string(m)
}

// MarshalJSON returns m as the JSON encoding of m.
func (m JSONRawMessage) MarshalJSON() ([]byte, error) { // nolint:unparam // interface implementation
	<copied from RawMessage>
}

// UnmarshalJSON sets *m to a copy of data.
func (m *JSONRawMessage) UnmarshalJSON(data []byte) error {
	<copied from RawMessage>
}



```

**Comment by dgsb** [comment]
@alexus1024 it seems you've found the perfect workaround for your use case, can we close this issue ?

**Comment by alexus1024** [comment]
Workaround works.  But maybe it is possible to remove the need in this workaround completely. 
I will accept any maintainer's decision )
