### ISSUE TITLE
Possibly misleading statement in documentation

### ISSUE THREAD

**Issue by bentcoder** [sirupsen/logrus#1262]
> Logrus is a structured logger for Go (golang), **_completely API compatible with the standard library logger._**

This statement sounds like a logrus instance can be used to satisfy signature below which is not the case.

```go
package main

import (
	"log"
	"github.com/sirupsen/logrus"
)

func main() {
	test(logrus.New())
}

func test(log *log.Logger) {
}
```

**Comment by dgsb** [comment]
well `log.Logger` isn't an interface so indeed it cannot be given a logrus instance as parameter. IIRC the logging functions are all implemented in logrus, the configuration part aren't.

What would you suggest to change this sentence to in order to better reflect the current state of logrus ?

**Comment by arusso** [comment]
Even if you don't interpret it as being an interface and instead you take it at face value -- you can swap out stdlib `log` with `logrus`, that would be incorrect. Consider the `Output` function (introduced in Go1.5):

Using stdlib:

```
package main

import (
  //log "github.com/sirupsen/logrus"
  "log"
)

func main() {
  log.Output(2, "foo")
}

// Output:
// > go run main.go
// 2021/09/17 15:46:02 foo
```

Using logrus:

```
package main

import (
  log "github.com/sirupsen/logrus"
  //"log"
)

func main() {
  log.Output(2, "foo")
}
 
// > go run main.go
// # command-line-arguments
// ./main.go:9:2: undefined: logrus.Output
```
