### ISSUE TITLE
nothing written to logstash!

### ISSUE THREAD

**Issue by mohammadinasab-dev** [sirupsen/logrus#1265]
Hello,

I'm testing your library just like your example but nothing written in LogStash/Elasticsearch until I add a one second time delay before the program ended!
here the code it is:
```
func main() {
	log := logrus.New()
	conn, err := net.Dial("tcp", "127.0.0.1:8911")
	if err != nil || conn == nil {
		log.Fatal(err)
	}
	hook := logrustash.New(conn, logrustash.DefaultFormatter(logrus.Fields{"type": "myappName"}))

	log.Hooks.Add(hook)
	ctx := log.WithFields(logrus.Fields{
		"method": "main",
	})
	ctx.Info("Hello World in print again!")

	time.Sleep(1 * time.Second)
}
```
I'll appreciate if anybody can help

**Comment by dgsb** [comment]
I don't know this hook, but it probably writes asynchronously, what's why the sleep makes appear the data in elasticsearch

**Comment by mohammadinasab-dev** [comment]
hi @dgsb 
the hook is here ( https://github.com/bshuster-repo/logrus-logstash-hook)
I didn't find anything about the manner of sending files in logrus to ES (sync or async), but I think it should send it synchronously because of the philosophy of logging through ELK ! but as you said "what's why the sleep makes appear the data in elasticsearch"?!

**Comment by mohammadinasab-dev** [comment]
and here the logstash configuration is:
```
input{
    tcp{
       host => "127.0.0.1"
       port => 8911
       mode => server
       codec => json
    }
}

filter{
    json{
        source => "message"
    }
}
output{
    elasticsearch{
	hosts => "http://localhost:9200/"
	index => "j-06-json"
    }
}
```

**Comment by dgsb** [comment]
@mohammadinasab-dev you should ask your question to the logrustash hook repository, because it is unlikely that it is related to logrus.

**Comment by mohammadinasab-dev** [comment]
@dgsb tnx for your attention and I'll check it again in a couple of future days and I'll share my solution, and about 'logrustash hook repository' i'll do,
