### ISSUE TITLE
Logrus crashes on terminal check

### ISSUE THREAD

**Issue by purplefox** [sirupsen/logrus#1275]
Hi, 

We integrated logrus into our application but it crashes when running. We are using 1.8.1. It appears to be doing a terminal check that it's not running on app engine, and the crash occurs in a syscall. Here is the stack trace:

```
runtime.systemstack_switch at asm_amd64.s:350
runtime.libcCall at sys_libc.go:49
syscall.syscall at sys_darwin.go:23
:1
golang.org/x/sys/unix.ioctl at zsyscall_darwin_amd64.go:690
golang.org/x/sys/unix.IoctlGetTermios at ioctl.go:73
github.com/sirupsen/logrus.isTerminal at terminal_check_bsd.go:11
github.com/sirupsen/logrus.checkIfTerminal at terminal_check_notappengine.go:13
github.com/sirupsen/logrus.(*TextFormatter).init at text_formatter.go:106
github.com/sirupsen/logrus.(*TextFormatter).Format.func1 at text_formatter.go:196
sync.(*Once).doSlow at once.go:68
sync.(*Once).Do at once.go:59
github.com/sirupsen/logrus.(*TextFormatter).Format at text_formatter.go:196
github.com/sirupsen/logrus.(*Entry).write at entry.go:279
```

OS is MacOS Big Sur 11.5.2
Go version is 1.17
AMD64 arch

Any thoughts on what might be causing this?

**Comment by purplefox** [comment]
I believe Apple has made security changes in Big Sur, and perhaps now applications are no longer allowed by default to make certain syscalls - e.g. this one to get terminal properties.

**Comment by anajavi** [comment]
I believe the golang.org/x/sys should be updated to version v0.0.0-20210817190340-bfb29a6856f2 when using go 1.17.

The crash went away for me when I added to go.mod:
```
golang.org/x/sys v0.0.0-20210817190340-bfb29a6856f2 // indirect
```

More info: https://github.com/Homebrew/homebrew-core/pull/83413

Maybe the logrus go.mod should be updated?

**Comment by purplefox** [comment]
Thanks, this works

**Comment by machinae** [comment]
An easier solution that fixed it for me is upgrading the sys dependency:
`go get -u golang.org/x/sys`
It will set go.mod and go.sum to the correct version.
