### ISSUE TITLE
Modify entry in Hook

### ISSUE THREAD

**Issue by Soulou** [sirupsen/logrus#13]
Good evening,

Here is a sample of what I'd like to do http://play.golang.org/p/Wwoo0eW0x5 (Currently, `e.Data["test"] = "changed" doesn't change anything to the output.)

Basically my question is, should a hook be able to modify the data of the entry? I think that yes, a hook should be like a middleware and should be able to filter things.

**Comment by lbyte00** [comment]
@sirupsen hi, I couldn't find anything about the question that I have. Do hooks have some running sequences or they run randomly? For example, if I want to modify an entry in one hook, what If there's already 'fired' hooked with the unmodified yet entry?


Currently, I want to solve the problem with sensitive information inside logs and to do so I need to modify the entry and the only general way to do it in logrus as I see is hooks, or am I wrong?
But if my 'masker' hook doesn't run as the first hook in sequence it means that other hooks will leak the sensitive information.

**Comment by Wauchy** [comment]
Can you skip specific endpoints for logging somehow?
