### ISSUE TITLE
Bug: Errors with nil value trigger nil pointer dereference panic in JSON formatter

### ISSUE THREAD

**Issue by JensSkipr** [sirupsen/logrus#1304]
First of all, thanks for the amazing library! Unfortunately, below bug is triggering a nil pointer dereference panic.

Considering code:
```go
package main

import (
	log "github.com/sirupsen/logrus"
)

type GenericError struct{}

// Error converts the error into a string
func (e GenericError) Error() string {
	return "test"
}

func main() {
	var genErr *GenericError
	log.SetFormatter(&log.JSONFormatter{})
	log.WithField("error", genErr).Info("Test") // Same for .WithError(genErr)
}
```
Will return:
```
panic: value method main.GenericError.Error called using nil *GenericError pointer

goroutine 1 [running]:
main.(*GenericError).Error(0x0)
	<autogenerated>:1 +0x39
github.com/sirupsen/logrus.(*JSONFormatter).Format(0xc00001a080, 0xc00007c150)
	/tmp/gopath383329124/pkg/mod/github.com/sirupsen/logrus@v1.8.1/json_formatter.go:70 +0x174
github.com/sirupsen/logrus.(*Entry).write(0xc00007c150)
	/tmp/gopath383329124/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:279 +0x56
github.com/sirupsen/logrus.(*Entry).log(0xc000068f60, 0x4, {0xc000018068, 0x4})
	/tmp/gopath383329124/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:251 +0x1f7
github.com/sirupsen/logrus.(*Entry).Log(0xc00007c0e0, 0x4, {0xc000068f60, 0x4b6060, 0x0})
	/tmp/gopath383329124/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Info(...)
	/tmp/gopath383329124/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:310
main.main()
	/tmp/sandbox3248861311/prog.go:19 +0x9b

Program exited.
```
Go Playground example: https://go.dev/play/p/6DFobtugSz2

Seems issue got introduced by fix for https://github.com/sirupsen/logrus/issues/137

**Comment by scila1996** [comment]
Hi @JensSkipr 

It's not a bug. Let me explain for you !

at

```
var genErr *GenericError
```

You were created a "Pointer of GenericError struct type". So follow golang document !

> The default value or zero-value of a pointer is always nil. Or you can say that an uninitialized pointer will always have a nil value.

at line

```
log.WithField("error", genErr).Info("Test") // Same for .WithError(genErr)
```

You passed `genErr` to second parameter of `WithField` method and expected to call method `Error()`. But previous, you were created a pointer variable and no initialize it and `genErr` still always `nil`. And you can not pass a nil pointer to `WithField` method !

**But**

If you pass `genErr` as "Pointer of Pointer of GenericError" like this

```
log.WithField("error", &genErr).Info("Test") // Same for .WithError(genErr)
```

it will work as you expect !!!

**Comment by JensSkipr** [comment]
@scila1996 thanks for checking my bug report. But I don't really agree it isn't a bug (unless the documentation strictly states this is not supported).

The provided code was a simplified version to be easy to replicate. But we actually have following situation:
```go
package main

import (
	log "github.com/sirupsen/logrus"
)

type GenericError struct{}

// Error converts the error into a string
func (e GenericError) Error() string {
	return "test"
}

func main() {
	log.SetFormatter(&log.JSONFormatter{})
	result, genErr := doSomething()
	if genErr != nil || !result.OK {
		log.WithError(genErr).WithField("result", result).Info("Test")
	}
}

type Result struct {
	OK    bool
	Error string
        // Data fields omitted 
}

func doSomething() (*Result, *GenericError) { // We're aware it is against Golang guidelines to return a specific error type
	return &Result{false, "test error"}, nil
}
```

So, expected result is `error` is just logged as `nil`. But since https://github.com/sirupsen/logrus/blob/79c5ab66aa2ce7d9ff7b3c437ebc22fcc519a967/json_formatter.go#L65-L73 is forcing the `.Error` call, it will throw a panic instead.

Therefore, I would like to suggest adding a `if v == nil` before the `switch` or inside `case error` to shield from this situation.

**Comment by scila1996** [comment]
`nil` are mean variable is not initialized, does not to treat is as a value. Panic occurred can be significant for debug or unit testing before build or run app.

**Comment by JensSkipr** [comment]
Fix implemented in our code using:
```go
// Error converts the error into a string
func (e GenericError) Error() string
	if e == nil {
		return ""
	}
	return "test"
}
```
