### ISSUE TITLE
Sanitize log entries from user input

### ISSUE THREAD

**Issue by stevenvegt** [sirupsen/logrus#1307]
Our project uses Githubs [CodeQL](https://codeql.github.com/) for security scanning. Today it came up with `2 high severity security vulnerabilities`, namely `Log entries created from user input`.

More information on this here:https://codeql.github.com/codeql-query-help/csharp/cs-log-forging/

It triggers this error both on the `Debugf("userinput=%s", userinput)` as with the `log.Logger().WithFields(map[string]interface{}{"userinput": userinput)` methods.

It seems an issue which came up after the log4j incident. The article advises to sanitize the data. As an example removing new lines is given.

What's your view on this? Is there an advised method of sanitizing or is it already part of the logrus lib?

**Comment by lucasgonze** [comment]
I logged this feature request to address the same CodeQL scan:
https://github.com/sirupsen/logrus/issues/1313

I'll close that in favor of this.

**Comment by lucasgonze** [comment]
In relation to sanitizing user input for logs, I documented threats:
https://writing.gonze.com/32410/blog-on-logs

**Comment by stevenvegt** [comment]
I like your approach with a callback. Perhaps even chain them.

As your blog explains, logging looks trivial but can be tricky, if there are "best practices" it would be nice to provide a few  standard sanitizers like `WithMaxLogSize`, `WithNewlinesRemoved`, and perhaps other things like escaping characters?

**Comment by titpetric** [comment]
Aside for using %q to resolve the issue with user-supplied input, i'm finding the TTY formatter doesn't escape \r\n while the non-tty one does. The non-tty behavior is desired:

```
time="Mar 17 18:30:21" level=warning msg="%s warnf: \rhel\nlo\n"
time="Mar 17 18:30:21" level=warning msg="%v warnf: \rhel\nlo\n"
time="Mar 17 18:30:21" level=warning msg="%q warnf: \"\\rhel\\nlo\\n\""
time="Mar 17 18:30:21" level=info msg="info\nmessage" field_text="\rhel\nlo\n"
time="Mar 17 18:30:21" level=info msg="TextFormatter.Format param: bar\nxxx" code=foo
```

tty:

```
helN[Mar 17 18:30:53] %s warnf: 
lo                            
helN[Mar 17 18:30:53] %v warnf: 
lo                            
WARN[Mar 17 18:30:53] %q warnf: "\rhel\nlo\n"                      
INFO[Mar 17 18:30:53] info
message                                  field_text="\rhel\nlo\n"
INFO[Mar 17 18:30:53] TextFormatter.Format param: bar
xxx           code=foo
```

expected tty output:

```
WARN[Mar 17 18:30:53] %s warnf: \rhel\nlo\n
WARN[Mar 17 18:30:53] %v warnf: \rhel\n\lo\n
WARN[Mar 17 18:30:53] %q warnf: "\rhel\nlo\n"                      
INFO[Mar 17 18:30:53] info\nmessage                                  field_text="\rhel\nlo\n"
INFO[Mar 17 18:30:53] TextFormatter.Format param: bar\nxxx           code=foo
```

Maybe the textformatter thing is my bad, as I'm directly setting the entry.Message value from it's output. Perhaps there is a function like .Message(newMessageBody) which does escaping for this?

**Comment by lucasgonze** [comment]
If you share your code I will attempt to provide helpful feedback.

**Comment by titpetric** [comment]
https://github.com/TykTechnologies/tyk/pull/3923
https://github.com/TykTechnologies/tyk/pull/3923/files#diff-894630a7ed925c7768a861c4465bc9ad393f7937df7cac5c77ab123c03921aee

**Comment by titpetric** [comment]
I did figure out the workaround to avoid the CVE is to set `DisableColors: true`. What is a reasonable timeframe to a fix, since the issue is known for a while now?
