### ISSUE TITLE
jsonFormatter doesn't work correctly with field in lowercase

### ISSUE THREAD

**Issue by nacimgoura** [sirupsen/logrus#1314]
Hello,
thank you for this work.
I encounter a bug in its use when logging for json.
When I want to log a struct and the fields start with a lower case they don't appear in the logs. But when the fields start with a capital letter they appear correctly. I share with you an example link: https://go.dev/play/p/V0FILasBXhT

Thanks you!

**Comment by jaedle** [comment]
Hey @nacimgoura :wave: 

Just an user, not a maintainer of this repo.

I guess this is the default behavior of go: On Serialization private Fields are missing. [This](https://go.dev/play/p/TEC6l-oKdD-) is an example for the `json`-package.
