### ISSUE TITLE
How can I hide the keys in the output?

### ISSUE THREAD

**Issue by krutztq** [sirupsen/logrus#1317]
I am using github.com/sirupsen/logrus v1.8.1 and want to write a custom logfile. The current output is:
`time="Wed, 16 Feb 2022 15:12:22 UTC" level="info" msg="test message"`

How can I reduce the output to the following?
`Wed, 16 Feb 2022 15:12:22 UTC info test message`

**Comment by Depetrol** [comment]
I'm having the same problem
have you found a solution yet?

**Comment by krutztq** [comment]
No, as this issue is a imperfection I use it as it is.
