### ISSUE TITLE
FieldLogger interface is dependent on Entry struct

### ISSUE THREAD

**Issue by Rutori** [sirupsen/logrus#1329]
In **logrus.FieldLogger** interface methods **WithField**, **WithFields** and **WithError** return ***logrus.Entry** which is too specific, if we assume that we will always be using the returned value as an instance of **logrus.FieldLogger**, e.g. 
`logger.WithField(foo, bar).Error(err)`

I suggest changing the return type of the mentioned methods to **FieldLogger**

**Comment by dgsb** [comment]
We cannot do that, it's a major non-backward compatible change.
