### ISSUE TITLE
Escape characters in the logs. How can I fix this? Thank you.

### ISSUE THREAD

**Issue by hkhk367** [sirupsen/logrus#1334]
I am using the following configuration, but I found that there are escape characters in the logs.
For example:
{"file":"C:/project/stress_test/ManageWB.go:91","func":"main.GetWBList","level":"error","msg":"Get \"https://www.google.com\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","time":"02 Jun 22 15:50 PDT"}
{"file":"C:/project/stress_test/main.go:36","func":"main.InitConfigJson","level":"info","msg":"Read config.json \u0026{map[das_addr_for_manage_doc:nws.zoomdev.us das_secret_for_manage_doc:ckoOHjpMawTxKFdfZ0Ak8FrZx4njc486 das_time_out_ms:3 owner_uid:ku5r5aGiRPa6wQ55D5L6RA report_interval_ms:10 task_id:123]}","time":"02 Jun 22 15:50 PDT"}

I guess I need to make the logs to UTF-8, how should I do that? Thank you.

The following are parts of my codes that relate to logrus.

```go
package main

import (
	"github.com/mattn/go-colorable"
	"github.com/sirupsen/logrus"
	"github.com/snowzach/rotatefilehook"
	"stress_test/rotatefilehooksinglelevel"
	"time"
)

func InitLogger() {
	var logLevel = logrus.InfoLevel

	rotateFileHook, err := rotatefilehook.NewRotateFileHook(rotatefilehook.RotateFileConfig{
		Filename:   "logs/log.log",
		MaxSize:    2000, // megabytes
		MaxBackups: 3,
		MaxAge:     28, //days
		Level:      logLevel,
		Formatter: &logrus.JSONFormatter{
			TimestampFormat: time.RFC822,
		},
	})

	if err != nil {
		logrus.Fatalf("Failed to initialize file rotate hook: %v", err)
	}

	logrus.SetLevel(logLevel)
	logrus.SetOutput(colorable.NewColorableStdout())
	logrus.SetFormatter(&logrus.TextFormatter{
		ForceColors:     true,
		FullTimestamp:   true,
		TimestampFormat: time.RFC822,
	})
	logrus.SetReportCaller(true)
	logrus.AddHook(rotateFileHook)


}
func init() {
	InitLogger()
}
func main() {
	logrus.Info("info")
	logrus.Debug("Debug")
	logrus.Warn("warning")
	logrus.Error("error")
}
```

**Comment by thaJeztah** [comment]
I think you may be able to disable these (`\u0022` is `&`) if you set the `DisableHTMLEscape` option on the JSON formatter; https://github.com/sirupsen/logrus/blob/fdf1618bf7436ec3ee65753a6e2999c335e97221/json_formatter.go#L34-L35

That said, it's not uncommon to escape characters using their unicode string (part of the JSON spec: https://datatracker.ietf.org/doc/html/rfc7159#section-7)

**Comment by hkhk367** [comment]
Thank you @thaJeztah for your help. It works.

**Comment by thaJeztah** [comment]
Awesome!
