### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by nathanejohnson** [sirupsen/logrus#1338]
Please tag a new release to catch, among others, https://github.com/sirupsen/logrus/pull/1333

**Comment by abrar71** [comment]
Please tag a new release

**Comment by DoingTheNeedful** [comment]
Please tag a new release.   This has been fixed #1333 has been resolved for a month and a half, and surely tagging is quick.

**Comment by nathanejohnson** [comment]
Thanks for tagging the new release!
