### ISSUE TITLE
SetReportCaller only returns logrus log file instead of where the error occured

### ISSUE THREAD

**Issue by mateusmlo** [sirupsen/logrus#1342]
This is my func that instantiates a new logrus:
```go
func NewLogger() *StdLogger {
	baseLogger := logrus.New()
	stdLogger := &StdLogger{baseLogger}

	if beego.AppConfig.String("runmode") != "dev" {
		stdLogger.SetOutput(os.Stdout)
		stdLogger.SetLevel(logrus.DebugLevel)
	} else {
		stdLogger.SetLevel(logrus.InfoLevel)
	}

	stdLogger.SetReportCaller(true)
        // prettyfier based on an official example
	stdLogger.Formatter = &logrus.JSONFormatter{
		PrettyPrint: true,
		CallerPrettyfier: func(f *runtime.Frame) (string, string) {
			s := strings.Split(f.Function, ".")
			funcname := s[len(s)-1]
			_, filename := path.Split(f.File)
			return funcname, filename
		},
	}

	return stdLogger
}
```

From it, I defined a few other log functions such as this one for common errors:
```go
func (log *StdLogger) LogError(arg string) {
	log.Errorf(commonError.message, arg)
}
```

However, the `file` and `func` properties on the logs will only refer to my log package itself, that is, the very LogError func above instead of where I captured it with an `err != nil` check. I'm currently on go 1.18, logrus@latest, saw a buch of other resolved issues where this problem seems to have been solved, but it's happening to me nonetheless.

**Comment by ysk229** [comment]
Sembra che questo livello di avvolgimento della libreria di classi sia la causa di questo problema, l'hai risolto per favore?

**Comment by ysk229** [comment]
After debugging, the constant knownLogrusFrames=7 in yywrentry.go can be changed to

**Comment by agclqq** [comment]
> 

Have you found a solution to this problem?
