### ISSUE TITLE
`entry.Log(logrus.FatalLevel, "fatal level")` doesn't call `logger.Exit(1)`

### ISSUE THREAD

**Issue by dlsrb6342** [sirupsen/logrus#1345]
* I found a bug that `entry.Log` doesn't call `logger.Exit(1)`. 
* If I call `entry.Log` with `logrus.FatalLevel`, system doesn't exit.

**Comment by fatelei** [comment]
in `entry.log` only `level <= PanicLevel` will lead to panic

<img width="788" alt="image" src="https://user-images.githubusercontent.com/961094/183575173-f6f35592-47d4-4991-be77-6216ae19fe1a.png">

`FatalLevel` is bigger than `PanicLevel`

<img width="991" alt="image" src="https://user-images.githubusercontent.com/961094/183575150-da24b599-5217-4ee2-bc27-25cca80e953e.png">

**Comment by dlsrb6342** [comment]
I mean `System.Exit(1)` not panic. As second picture that you attatched, `FatalLevel` should calls `logger.Exit(1)`

**Comment by fatelei** [comment]
> I mean `System.Exit(1)` not panic. As second picture that you attatched, `FatalLevel` should calls `logger.Exit(1)`

I have check the code，this is a [demo](https://goplay.tools/snippet/wWIW2R-NrMO)，work as expect.

**Comment by dlsrb6342** [comment]
check this [demo](https://goplay.tools/snippet/GVTSbpQl0BK). 
As I described in issue, I call `entry.Log(log.FatalLevel, "fatal")` but it didn't call `System.Exit(1)`

**Comment by fatelei** [comment]
i read the code
- call `entry.Fatal` this function will call `entry.logger.Exit`
- call `entry.Log`, this function only panic when `level <= PanicLevel`,  so it with `FatalLevel` will not exit program.

Maybe this is by design @sirupsen

Anyway, if this is a bug, i can fix it

**Comment by dgsb** [comment]
This is not a bug. It works as documented:

```
~/src/logrus$ go doc . Entry.Log
package logrus // import "github.com/sirupsen/logrus"

func (entry *Entry) Log(level Level, args ...interface{})
    Log will log a message at the level given as parameter. Warning: using Log
    at Panic or Fatal level will not respectively Panic nor Exit. For this
    behaviour Entry.Panic or Entry.Fatal should be used instead.

```
