### ISSUE TITLE
When I output to the file in Win10, the color was broken

### ISSUE THREAD

**Issue by d630200x** [sirupsen/logrus#1347]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/45569808/186653659-11516f00-9eab-4122-9809-c64de5a7552c.png">

Here is my code

<img width="838" alt="image" src="https://user-images.githubusercontent.com/45569808/186654248-1b01f8a6-a28e-4653-bbd9-b33d327af243.png">

Am I wrong?

**Comment by edoger** [comment]
@d630200x Colors are only available for console terminals, files are not.
