### ISSUE TITLE
Split log file accroding to date ,level or other automatically！

### ISSUE THREAD

**Issue by imotai** [Sirupsen/logrus#135]
I think this function is very usefull,Do we have a plan to support it.
Then the log files will look like "xxx.log.2015-02-25 xxx.log.wf.2015-02-25"
"xxx.log.2015-02-25" will include "INFO level logs"
"xxx.log.wf.2015-02-25" will include "WARN and FATAL level logs"

**Comment by MaikuMori** [comment]
As for rotation (date) there is a clue in `README.md`

>Log rotation is not provided with Logrus. Log rotation should be done by an external program (like logrotate(8)) that can compress and delete old log entries. It should not be a feature of the application-level logger.

As for outputting to different files based on level (and probably other fields) can be done using custom output or using hooks.

**Comment by Sirupsen** [comment]
Thanks for your suggestion! But no, I don't think log rotation should be a deep concern for the logger at this time.
