### ISSUE TITLE
How to not print prefixs, such as time=, level=, msg=.

### ISSUE THREAD

**Issue by huchen2021** [sirupsen/logrus#1377]
Hi, all:

Does any know how to print prefixs, such as time=, level=, msg=. 

For example, My log is as followed:
```

time="2023-03-14 07:25:36" level=info msg="AddNic Request" Module=Announcer NIC=ens160
time="2023-03-14 07:25:36" level=info msg="AddNic Request" Module=Announcer NIC=ens192
time="2023-03-14 07:25:36" level=info msg="AddNic Request" Module=Announcer NIC=cnio0
```
And I want it likes as followed:
```
info 2023-03-14 07:25:36  AddNic Request Module=Announcer NIC=ens160
info 2023-03-14 07:25:36 AddNic Request Module=Announcer NIC=ens192
info 2023-03-14 07:25:36 AddNic Request Module=Announcer NIC=cnio0
```

How can I do this?

**Comment by oshoval** [comment]
Hi
Interested as well, may I ask please if you found how already?

**Comment by huchen2021** [comment]
@oshoval Yes, I found the answer. Add "ForceColors:     true," into logrus.TextFormatter works.
If you don't do this set up.
When output is TTY, it print log with the second format.
When output is not TTY, it print log with the first one.

**Comment by oshoval** [comment]
@huchen2021 
Interesting thanks

with colors (INFO has color)
```
DEBUG A : hack/pman/rules.txt                      
INFO RESULT  
```

without colors
```
level=debug msg="A : hack/pman/rules.txt"
level=info msg=RESULT
```

would be even better if we could not use colors, and declare the prefix (or non at all) ourselves imho :)

**Comment by marcosox** [comment]
Forcing the colors will maintain the same format, but will include the color escape chars into the file. This because the format is hardcoded in the two separate code branches for color/no color.

**Comment by oshoval** [comment]
I did something like this for non debug mode
it can be changed to non ForceColors, and to update Write according the tags of DebugLevel to omit the tags as well 
possibly


```
func configLogger(debug bool) {
	logrus.SetOutput(&OutputSplitter{})

	logrus.SetFormatter(&logrus.TextFormatter{DisableTimestamp: true})
	if debug {
		logrus.SetLevel(logrus.DebugLevel)
		logrus.SetFormatter(&logrus.TextFormatter{DisableLevelTruncation: true, ForceColors: true, DisableTimestamp: true})
	}
}

func (splitter *OutputSplitter) Write(p []byte) (n int, err error) {
	if bytes.Contains(p, []byte("level=error")) || bytes.Contains(p, []byte("level=fatal")) {
		return os.Stderr.Write(p)
	}
	return os.Stdout.Write(p)
}
```
