### ISSUE TITLE
can't build for wasm (go 1.21 rc)

### ISSUE THREAD

**Issue by imjasonh** [sirupsen/logrus#1394]
The upcoming Go 1.21 release includes support for compiling to Web Assembly (wasm): https://tip.golang.org/doc/go1.21#wasm

You can try out the RC:

```
$ go install golang.org/dl/go1.21rc2@latest
$ go1.21rc2 download
$ go1.21rc2 version
go version go1.21rc2 darwin/arm64
```

However, I've found that anything I try to build that depends on logrus fails when building for Wasm:

```
GOOS=wasip1 GOARCH=wasm go1.21rc2 build
# github.com/sirupsen/logrus
../../go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/terminal_check_notappengine.go:13:10: undefined: isTerminal
```

(source here: https://gist.github.com/imjasonh/1ca7e1bd0d95d5c54b8550c50fb557bd)

This isn't a big deal for now, because it's still an RC, but it could be nice to figure out how to avoid this dependency for wasm builds.

**Comment by imjasonh** [comment]
I suspect we'd just need something like this, but for wasm: https://github.com/sirupsen/logrus/blob/master/terminal_check_js.go

**Comment by imjasonh** [comment]
Aaaaand you're already on it. https://github.com/sirupsen/logrus/commit/7165f5e779a587f37fff841ecbae4d6bce9a2aa1

Thank you! 😄

**Comment by HarikrishnanBalagopal** [comment]
Hi, I am running into this issue when compiling with TinyGo for WASI target

```
$ tinygo build -o main.wasm -target=wasi main.go

tinygo:wasm-ld: error: /var/folders/dt/y3srs7vs6pz9bqwrbjwt38pc0000gp/T/tinygo4119433949/main.o: undefined symbol: golang.org/x/sys/unix.Syscall
failed to run tool: wasm-ld
error: failed to link /var/folders/dt/y3srs7vs6pz9bqwrbjwt38pc0000gp/T/tinygo4119433949/main: exit status 1
```


```go
package main

import "github.com/sirupsen/logrus"

func main() {
	logrus.Infof("start")
	logrus.Infof("done")
}
```
