### ISSUE TITLE
Feature: Add slog compatibility layer

### ISSUE THREAD

**Issue by flimzy** [sirupsen/logrus#1401]
I know this project is in maintenence mode, but I think it would be worth making an exception to the "no new features" rule to add a simple `slog` compatibility layer, as the alternative is some minor chaos when others create competing implementations, and inevitably abandon them.

This could take one, or even two, forms:

- A `slog` hook for Logrus
- A Logrus handler for `slog`

I would be happy to take this on and write the code (I have a partial implementation already completed for a client I'm working with).

**Comment by ripienaar** [comment]
Would love to see this accepted in core logrus also.

**Comment by flimzy** [comment]
I've begun work on this, and intend to create a PR before too long.
