### ISSUE TITLE
Configuration file support

### ISSUE THREAD

**Issue by oryband** [sirupsen/logrus#142]
I'd like to have logging configuration files built-in logrus. The goal is to be able to configure logging without having to recompile.
### Action Items
- Strike a balance between configurability and simplicity. The extreme configurablity case would probably be [log4j](http://logging.apache.org/log4j/2.x/manual/configuration.html)'s and [seelog](https://github.com/cihub/seelog/wiki/Example-config)'s. But we don't have to go that far. i.e. prefer _yaml_ or _json_ file formats instead of _xml_, and offer only a part of the above's options.
- The options I would personally like are:
  - Control the outputs e.g. stdout, a single file, several files, etc.
  - Control each output's format e.g. json, logstash, plain text, etc.
  - Control which log levels are printed to each output
- Have a default simple and sane configuration without having to do anything.

**Comment by bolshoy** [comment]
:+1:

**Comment by Sirupsen** [comment]
Can you explain your use-cases more @oryband and @bolshoy? Does how you log change that often?

**Comment by oryband** [comment]
@Sirupsen see the urls above. The point is to configure logrus outside of our app's source.

**Comment by Sirupsen** [comment]
I understand the use case here. This is nice for e.g. precompiled binaries (e.g. Docker). It sucks if you have to recompile Docker to change it to log to JSON.

**Comment by oryband** [comment]
@Sirupsen that's exactly what we are trying to achieve - saving the cost of recompiling on every change to the log mechanism.

**Comment by Sirupsen** [comment]
This may be considered into core in 1.x series, but is currently not very requested. Will keep this issue open to keep tracking the need. Fortunately it can be implemented by users on top of Logrus.

**Comment by Huangsir** [comment]
+1

**Comment by jtkelley** [comment]
+1

**Comment by AidHamza** [comment]
+1

**Comment by Colstuwjx** [comment]
+1

**Comment by svarogg** [comment]
+1

**Comment by startover** [comment]
+1

**Comment by iplon** [comment]
+1

**Comment by nomuna** [comment]
+1

**Comment by Ei5enheim** [comment]
+1

**Comment by dmathieu** [comment]
I'm going to add a :-1: partly because I don't think anyone else against this would say anything here.
If you want to configure logrus from XML, there's nothing preventing you from doing that in another package.

**Comment by ckawasaki-isp** [comment]
+1

**Comment by lanmingle** [comment]
+1

**Comment by dgsb** [comment]
It's not quite if it is up to a common library to force its configuration file format to a given application

**Comment by dgsb** [comment]
There are already external package which allows to configure logrus through a configuration file:
* https://github.com/heirko/go-contrib/tree/master/logrusHelper
* https://github.com/gogap/logrus_mate

**Comment by ogerardin** [comment]
I may be wrong but it seems none of these packages allow the complete de-correlation of log production and log usage.
The application code should only be responsible for log production, i.e. when, what message, what level, what fields, etc. 
The decision to actually consider or not a message for a given package/level, where to log it, how to format it, etc. should be completely external to the application code, ideally in a configuration file.

**Comment by dgsb** [comment]
logrus_mate allows to configure a logger through a config string or the content of a config file

**Comment by ogerardin** [comment]
> logrus_mate allows to configure a logger through a config string or the content of a config file

True! Unfortunately the doc is very confusing and you have to look in the example directory for an actual meaningful example of an external config file,..

Anyway, I still wish it was done natively by logrus for more consistency.

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
