### ISSUE TITLE
custom automatic entries

### ISSUE THREAD

**Issue by cryptix** [Sirupsen/logrus#144]
Hi,

i'd like to see a way to add custom automatic [entries](https://github.com/Sirupsen/logrus#entries) to a logger.

My use case would be having a `module=$modname` pair in all logs that originate from a certain part of a system. Currently (afaict) you would have to `.WithFields()` all over the place and hope not to forget it.

If there is interest for this, i'd be fine to stroll through the code and come up with a PR but i'd like some discussion about api how the api should look and some guiding suggestions before.

**Comment by Sirupsen** [comment]
You can already do this, for example:

```go
loggerWithSomeField = log.WithField("module", modname)

loggerWithSomeField.WithField("some other field", "test").Info("I'll have two fields in addition to the defaults!")
```

**Comment by cryptix** [comment]
Oh perfect! Thanks!
