### ISSUE TITLE
Why doesn't the text formatter include the time?

### ISSUE THREAD

**Issue by nicholasf** [Sirupsen/logrus#150]
Quick question. 

The time field appears when I use the JSONFormatter but it doesn't for the TextFormatter. Is there are particular reason why?

I'm now adding some code to ensure the time is logged for text ...

Cheers,
Nicholas

**Comment by Sirupsen** [comment]
Hi @nicholasf 

By default the time showed is the offset from the beginning of execution, those are the numbers you see on the left. You can use `FullTimestamp` and `DisableTimestamp` for more control.

**Comment by Sirupsen** [comment]
@nicholasf did that resolve it?

**Comment by nicholasf** [comment]
Hi Sirupsen.

Thanks for following up. No. I experimented and the time property does not appear when I use default TextFormatter. It does appear with the JSONFormatter. I'll try to post some code later today to discuss.

**Comment by Sirupsen** [comment]
Ya, I don't understand exactly what you're saying—an example would be great!

**Comment by Eazynow** [comment]
We got it working using the following (when logrus is aliased as log): `log.SetFormatter(&log.TextFormatter{FullTimestamp: true})`

**Comment by nicholasf** [comment]
Thanks @Eazynow - that works.
