### ISSUE TITLE
Extending JSONFormatter data JSON serialization (Patch advice)

### ISSUE THREAD

**Issue by cep21** [Sirupsen/logrus#151]
I want to write a patch to solve the below problem: Would this be accepted?

I have a structure with a function pointer field.  Whenever I run

    logrus.WithField("item", item)....

It fails using JSONFormatter with

    Failed to obtain reader, Failed to marshal fields to JSON, json: unsupported type: datum.LifetimeFunc

This is because it cannot be serialized into JSON.  This is a common object that I would like to log in multiple places.  It would be great if JSONFormatter supported something like the following

type LogFormattable interface {
  LogFormat() interface{}
}

Then, inside Format() for JSONFormatter, it could check if the object implements LogFormattable and if so, use LogFormat() rather than the object itself in the JSON log.

Does this sound reasonable?  If so, I could get a pull request up shortly.

**Comment by cep21** [comment]
As an extra issue, it would be great if I could trigger some kind of callback on log formatting issues inside Entry.log() rather than them going to stderr.  This has caused issues in production code where untracked error logs were getting dropped.

**Comment by Sirupsen** [comment]
What about if you pass a function as a value to a field, it gets executed? That makes sense in general, because expensive values (e.g. for debugging or lower debugging levels) would then only be computed when needed.

**Comment by cep21** [comment]
I really like that.  It requires reflection packages though, right?  Would reflection on every field slow down logrus too much, or would that be acceptable?

**Comment by Sirupsen** [comment]
We're already checking types, which in my experience is fairly cheap. I've wanted this in Logrus for some time, because it seems expected and would solve a number of people's performance problems (and being able to do crazy, fancy things). It shouldn't be hard to do, but it would have to come with a benchmark to proof it doesn't slow down Logrus extensively. I don't think it would, because it wouldn't do extra allocations. Let me know if you want to work on this.

**Comment by cep21** [comment]
I'll work on that patch.  It requires changing both the json and stdout formatter.  You feel trying to cast into a ```func() string``` is better than implementing a type?

**Comment by cep21** [comment]
Hi,

Before I work on this I wanted to clarify the use of func() rather than interface?  One option is something like this:


```go
type Loggable interface {
    Logged() interface {}
}

type F func() interface{}

func (f F) Logged() interface {} {
  return f()
}

...
```

Then code can look like this:
```go
log.WithField("complex", complexItem).Info("Hi")
```

And I don't need to remember to cast out complex item.  People can add inline functions with:

```go
log.WithField("complex", logrus.F( func() interface{} {return ....}).Info("HI")
```

We can also go with your recommendation of func(), but then I need to remember to write this when I log something:

```go
log.WithField("complex", complexItem.Logged),Info("Hi")
```

**Comment by Sirupsen** [comment]
Let's merge this with https://github.com/Sirupsen/logrus/issues/207
