### ISSUE TITLE
SetLevel is only defined for the default logger, not on Instances

### ISSUE THREAD

**Issue by GuyMorgan** [Sirupsen/logrus#153]
The Readme suggest this should be possible.
```
You can set the logging level on a `Logger`, then it will only log entries with
that severity or anything above it:
```
...but the code shows  SetLevel to be an exported function without a receiver.
```
exported.go
30:// SetLevel sets the standard logger level.
31:func SetLevel(level Level) {
```

Logging levels are missing from the stdlib log which is why I picked up logrus, am I missing something?

**Comment by Sirupsen** [comment]
On instances you can access the variable directly with `Level =`.

**Comment by GuyMorgan** [comment]
Yup, but that's a (minor) inconsistency in the API.  #155 (docs) for your consideration.
