### ISSUE TITLE
write to file

### ISSUE THREAD

**Issue by anth1y** [Sirupsen/logrus#156]
Excuse the newb question but I truly enjoy using logrus and we are about to ship our product to production  but I have not yet figured out how to write to file. for example how do i write to /var/log/$app using logrus.

thanks in advance

**Comment by Sirupsen** [comment]
Use `log.SetOutput()` with a file handler, anything that implements `io.Writer` is good.

```go
f, err := os.OpenFile(filename, os.O_WRONLY | os.O_CREATE, 0755)
if err != nil {
    # handle
}
logrus.SetOutput(f)
```

**Comment by anth1y** [comment]
Thanks much appreciated!

**Comment by Sirupsen** [comment]
If you're using the text formatter you may have to pass `DisableColors` (see the docs) if you're running from a TTY.

**Comment by Sirupsen** [comment]
Sorry that this is a little confusing, it could probably be documented better. It's much more common to log to stdout/stderr in my experience, and have something pick it up.

**Comment by anth1y** [comment]
I agree but where I currently am we log to both /var/log/app.log & then
logstash picks it up from there. But I agree ;).

**Comment by Sirupsen** [comment]
:) enjoy logrus 


![emoji](https://cloud.githubusercontent.com/assets/97400/6763069/33bf90d2-cf44-11e4-8cb9-2a80d6d8e23d.png)

**Comment by wangkirin** [comment]
Hi @Sirupsen , how to make logs both print on screen and save to local file?

**Comment by krak3n** [comment]
@wangkirin take a look at the LFS hook: https://github.com/rifflock/lfshook

**Comment by meetme2meat** [comment]
@sirupsen When I'm trying to discard the logs (for testing purpose) using

`logrus.SetOutput(ioutil.Discard)`

It does not work and I still see the error on `STDOUT`. 

Any idea ?

**Comment by MMulthaupt** [comment]
Do we not have to register an exit handler to make sure the file is closed, as well as explicitly call `logrus.Exit(0)` to make sure it is called at the end of `main()`?

```
var logFile *os.File

func main() {
    logFile, _ = os.OpenFile("app.log", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
    logrus.SetOutput(io.MultiWriter(os.Stderr, logFile))
    logrus.RegisterExitHandler(closeLogFile)
    // ...
    logrus.Exit(0)
}

func closeLogFile() {
        if logFile != nil {
            logFile.Close()
        }
}
```

**Comment by blaskovicz** [comment]
To simplify @MMulthaupt 's usage, I did the following (which includes generating a new timestamp per run):

```golang
        package main

        import (
          "time"
          "os"
          "path/filepath"
           log "github.com/sirupsen/logrus"
        )

        cwd, err := os.Getwd()
	if err != nil {
		log.Fatalf("Failed to determine working directory: %s", err)
	}
        runID := time.Now().Format("run-2006-01-02-15-04-05")
	logLocation := filepath.Join(cwd, runID + ".log")
	logFile, err := os.OpenFile(logLocation, os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		log.Fatalf("Failed to open log file %s for output: %s", logLocation, err)
	}
	log.SetOutput(io.MultiWriter(os.Stderr, logFile))
	log.RegisterExitHandler(func() {
		if logFile == nil {
			return
		}
		logFile.Close()
	})
	log.WithFields(log.Fields{"at": "start", "log-location": logLocation}).Info()
        // perform actions
	log.Exit(0)
```

**Comment by freeformz** [comment]
@Farit-Biktimirov You would have to have logrotate HUP the process and register a signal handler to respond to that signal and close the file, open a new one, and then call SetOutput to start using the new file.
