### ISSUE TITLE
time formats should use nanosecond resolution

### ISSUE THREAD

**Issue by stevvooe** [Sirupsen/logrus#161]
The log formatters, such as json and text, are using the RFC3339. For example, from `JSONFormatter`:

```
data["time"] = entry.Time.Format(time.RFC3339)
```

This only provides 1 second granularity on timestamps. These formatter should either use `RFC3339Nano` by default or allow the user to configure it.

Something like this would be acceptable:

```
type JSONFormatter struct {
    TimestampLayout string
}
```

Let me know if this is okay and I can drop a PR.

**Comment by stevvooe** [comment]
Filed a PR in #162. Let me know if we need changes.

**Comment by shilov** [comment]
I think the current `time.RFC3339` is a sensible default. Either way, custom formatting has recently been added to the TextFormatter, but not the JSONFormatter.

**Comment by Sirupsen** [comment]
Agree with @shilov

**Comment by stevvooe** [comment]
@Sirupsen `time.RFC3339` only provides second level resolution, which was very surprising for service-level logging. I would like to better understand why this is considered sensible. It seems problematic for most use cases where log message ordering is required for debugging or logs that are only machine parsed.

I'll update the PR with a different default.

**Comment by Sirupsen** [comment]
You know what @stevvooe, I think you're right. Most people use the text formatter in development which has second resolution, but for production—especially in a concurrent environment—millisecond/nanosecond precision seems reasonable.

**Comment by Sirupsen** [comment]
Although I'm afraid some JSON parsers may get crazy on this, as some libraries try to infer timestamps..

**Comment by stevvooe** [comment]
@Sirupsen I'm okay with maintaining compatibility for the default. We may want to make a note for users in the README to avoid the surprise. Albeit, it would be nice to have a default that doesn't remove granularity.

**Comment by Sirupsen** [comment]
I'll open a new issue on the nanosecond issue. I think it makes sense as a default for the non-TTY ones.

**Comment by stevvooe** [comment]
@Sirupsen Agreed. We had also discussed following "Layout" over "Format" for the name of these fields. Either way, #162 fixes our issue.
