### ISSUE TITLE
Rename timestamp format to layout

### ISSUE THREAD

**Issue by sirupsen** [sirupsen/logrus#165]
Consistent with standard library. Gathering this for 1.0 must have changes, although I may break the compatibility before. Because of how Godep has emerged most people don't update very often so it's not as big of a deal anymore as it once was.

\cc @stevvooe

**Comment by stevvooe** [comment]
@Sirupsen Let me know and I can throw a PR your way. What's the timeline on 1.0?

**Comment by Sirupsen** [comment]
Not sure, still gathering feedback. It'll be rewriting the code base with all the things I've learned. There are a few fundamental flaws in how people use Logrus vs how it works (see issues). I don't think the API will change much. Let me know if there are larger changes you'd like to discuss.

**Comment by stevvooe** [comment]
@Sirupsen Sounds good. I'll just let you take a look at `https://godoc.org/github.com/docker/distribution/context` to see how we are integrating logrus.

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
