### ISSUE TITLE
log.Printf() and log.Infof append a newline to the output

### ISSUE THREAD

**Issue by heipei** [sirupsen/logrus#167]
I just started using logrus by replacing the import for log. Previously I had used log.Printf("bla\n") to log messages, but logrus appends an extra \n so that there is an empty line after each log message. What am I missing? If this is supposed to be API-compatible, this should behave differently.

**Comment by shearn89** [comment]
I would also be interested in this, would be nice to be able to print progress messages without a newline.

**Comment by omeid** [comment]
+1 I would love this feature too. Perhaps this can be built as a formatter?

**Comment by Sirupsen** [comment]
You're right, with the text formatter this is not API-compatible, this is rather inherent to field-logging the way I see it.

**Comment by Sirupsen** [comment]
This has come up again. I'm thinking we should escape the character instead. It doesn't make sense with the current formatters to actually do a newline.

**Comment by nomuna** [comment]
Looks like a duplicate of #167, if I am not mistaken.

**Comment by nomuna** [comment]
Looks like a duplicate of #278.

**Comment by universam1** [comment]
I'd like to see this #674 674 as an option
