### ISSUE TITLE
Incomplete comment for Logger.Level field

### ISSUE THREAD

**Issue by ahmetb** [sirupsen/logrus#175]
### `type Logger`:

> ![image](https://cloud.githubusercontent.com/assets/159209/7580637/d468d32e-f82d-11e4-8404-aa418ed40a8c.png)

(branch: master)

**Comment by aybabtme** [comment]
thanks @ahmetalpbalkan, seems like an easy fix. Want to submit a PR?

**Comment by ahmetalpbalkan** [comment]
@aybabtme problem is I don't know the rest

**Comment by dmathieu** [comment]
This has been fixed in 00386b3fbd637582f90cb17482dc3087646c0ac2.
