### ISSUE TITLE
Question: why no colors for Debug level?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Sirupsen/logrus#176]
![image](https://cloud.githubusercontent.com/assets/159209/7581160/583749e6-f834-11e4-89cf-a555be895d86.png)

What's the reason `Debug` level does not print colors for the fields? `log.TextFormatter{ForceColors:true}` does not change the behavior. I couldn't find anything in the readme or the docs so is it a bug or a feature?

**Comment by Sirupsen** [comment]
This is a feature :-) The colour is gray. This is because those log lines are usually less important.

https://github.com/Sirupsen/logrus/blob/master/text_formatter.go#L97-98

**Comment by ahmetalpbalkan** [comment]
aaah my term colors fooled me, thanks!

**Comment by Sirupsen** [comment]
Ya, that's the tough part about choosing the colours :(
