### ISSUE TITLE
Make logrus.Fields an implementable interface

### ISSUE THREAD

**Issue by Volox** [sirupsen/logrus#207]
I think it would be better if `log.WithFields` accept as input an interface so everyone can implement such interface if needed.

For example by now if I have a simple structure and i want to use it with the `WithFields` method I must create a _wrapper_ that returns a `logrus.Fields` struct or write the attributes manually.

Sample Options struct:

``` go
type Options struct {
    Paginate bool
    Count    uint
    MaxPages uint
}

// Wrapper function can became the implementation of the interface
func (o *Options) ToFields() (fields log.Fields) {
    fields = make(log.Fields)
    fields["paginate"] = o.Paginate
    fields["count"] = o.Count
    fields["maxpages"] = o.MaxPages
    return
}
```

Given that struct we need to do either:

``` go
// With the wrapper
log.WithFields(options.ToFields()).Info( "Test" )
```

OR

``` go
// Manual entries
log.WithFields(log.Fields{
    "paginate": options.Paginate,
    "count": options.Count,
    "maxpages": options.MaxPages,
}).Info( "Test" )
```

But if we have the interface we can simply write:

``` go
log.WithFields(options).Info( "Test" )
```

**Comment by Sirupsen** [comment]
This is a great idea and solves a bunch of problems people have asked for in the past at the right level of abstraction.

**Comment by ryanfaerman** [comment]
@Sirupsen Do you mind if I take a shot at tackling this?

**Comment by Sirupsen** [comment]
@ryanfaerman sure!

**Comment by alecha** [comment]
I'm also interested in this feature, how can we do to don't break the existing function calls?

**Comment by noxiouz** [comment]
@alecha  we can add implementation of Fields interface to logrus.Fields and change signature. It would not break compatibility, I think.

**Comment by ryanfaerman** [comment]
That's the approach I'm taking. Creating an interface and then having Fields be a default implementation of said interface.

**Comment by alecha** [comment]
I've created a simple interface in my PR, let me know if this is a good approach ;)

**Comment by taybin** [comment]
Any updates on this?

**Comment by dgsb** [comment]
This issue is 5 years old. No plan for logrus 2 yet. Closing.
