### ISSUE TITLE
Syslog handler should support writing to /dev/log

### ISSUE THREAD

**Issue by wrouesnel** [Sirupsen/logrus#211]
A common use case of the syslog handler is running a program on a system which has a normal, local, syslog instance which may not be listening on any network ports.

The syslog hook should ideally allow defaulting or writing to the local /dev/log socket on unix-likes so program data can be collected locally and (potentialy) exported over the network.

**Comment by Sirupsen** [comment]
PRs welcome :)

**Comment by devopstaku** [comment]
According to https://golang.org/src/log/syslog/syslog.go
While call ` func Dial(network, raddr string, priority Priority, tag string)`
if `network ` is empty, it will cal `unixSyslog()`( Try to connect "/dev/log", "/var/run/syslog", "/var/run/log" )

So while I want to make syslog hook writing to the local , I just use hook as 
```
hook, err := logrus_syslog.NewSyslogHook("", "", syslog.LOG_DEBUG, TAG)
```
Is it what @wrouesnel want ?

**Comment by wrouesnel** [comment]
Sounds right and plays nicely with flag args too. I wound up hard coding /dev/log previously so I guess this just need to be mentioned in the docs.

On 9 September 2015 12:24:01 am AEST, Owen <notifications@github.com> wrote:
>According to https://golang.org/src/log/syslog/syslog.go
>While call ` func Dial(network, raddr string, priority Priority, tag
>string)`
>if `network ` is empty, it will cal `unixSyslog()`( Try to connect
>"/dev/log", "/var/run/syslog", "/var/run/log" )
>
>So while I want to make syslog hook writing to the local , I just use
>hook as 
>```
>hook, err := logrus_syslog.NewSyslogHook("", "", syslog.LOG_DEBUG, TAG)
>```
>Is it what @wrouesnel want ?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Sirupsen/logrus/issues/211#issuecomment-138578947

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Sirupsen** [comment]
Any of you mind sending a PR?

**Comment by devopstaku** [comment]
I will be glad to send a PR today.
