### ISSUE TITLE
Context logging does show debug messages after info

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [Sirupsen/logrus#222]
Please look at this code:
	logrus.SetLevel(logrus.DebugLevel)
	var l = logrus.WithField("module", "test")
	l.Debug("1")
	l.Debug("2")
	l.Info("3")
	l.Debug("4")
	l.Debug("5")
	l.Info("6")

4 and 5 are not logged

**Comment by Sirupsen** [comment]
I think this is related to https://github.com/Sirupsen/logrus/pull/214 which doesn't seem ideal because it creates more object. I'll take a deeper look at this, thanks for reporting.

**Comment by Sirupsen** [comment]
aa3ad346e42c2150c4d71f3b15dcf3d6041d9bef should fix this

**Comment by Sirupsen** [comment]
Confirmed locally. Closing.

**Comment by nikolaybobrovskiy** [comment]
Great. Thank you.
