### ISSUE TITLE
entry.log silently sets loglevel.

### ISSUE THREAD

**Issue by miekg** [Sirupsen/logrus#223]
When printing an entry with a certain loglevel, the loglevel is set to the level of the thing you called:

https://github.com/Sirupsen/logrus/blob/master/entry.go#L75

If you do a `Warnf` and then `Infof` the latter won't show up.

Is this by design?

**Comment by Sirupsen** [comment]
Do you happen to be on 0.8.4? This should be fixed in 0.8.5

**Comment by Sirupsen** [comment]
https://github.com/Sirupsen/logrus/issues/222

**Comment by miekg** [comment]
Yes, that fixes it. Thanks.

**Comment by Sirupsen** [comment]
Sorry about that, it's an embarrassing bug and fortunately it only existed in a release for a short duration. Thanks a lot for reporting @miekg!
