### ISSUE TITLE
Hooks should probably fire asynchronously.

### ISSUE THREAD

**Issue by dradtke** [Sirupsen/logrus#243]
Especially if an application is using a hook that posts to a remote service, the act of posting to that service shouldn't slow down response times. This would require refactoring the hook firing mechanism to return a channel of potential errors rather than an error, and then fire hooks in their own goroutines.

**Comment by alecha** [comment]
+1

**Comment by Sirupsen** [comment]
I'm of the opinion this is up to the hook. This is too surprising to be a default.

**Comment by Sirupsen** [comment]
I'm going to close this for now and watch the discussion on this closely and possibly bring it up again.
