### ISSUE TITLE
Use hooks with gopkg.in

### ISSUE THREAD

**Issue by gureedo** [Sirupsen/logrus#250]
I've get logrus as http://gopkg.in/Sirupsen/logrus.v0 and main API works fine, but when I try to use hooks like syslog I've got errors like this
```
../../../gopkg.in/Sirupsen/logrus.v0/hooks/syslog/syslog.go:5:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/opt/go/src/github.com/Sirupsen/logrus (from $GOROOT)
	/home/gureedo/work/go/src/github.com/Sirupsen/logrus (from $GOPATH)
```
So current implementation does not allow use of gopkg.in

**Comment by Sirupsen** [comment]
gopkg.in is not officially supported
