### ISSUE TITLE
Parsing log levels - variable representations

### ISSUE THREAD

**Issue by JReyLBC** [Sirupsen/logrus#252]
It would be useful to improve the ParseLogLevel() logic to include strings of any case, including numerical representations of log levels.

A possible implementation could be:

```go
func ParseLogLevel(l string) (logrus.Level, error) {
	switch strings.ToUpper(l) {
	default:
		return 0, errors.New("ParseLogLevel: invalid level")
	case "DEBUG", "5":
		return logrus.DebugLevel, nil
	case "INFO", "4":
		return logrus.InfoLevel, nil
	case "WARN", "3":
		return logrus.WarnLevel, nil
	case "ERROR", "2":
		return logrus.ErrorLevel, nil
	case "FATAL", "1":
		return logrus.FatalLevel, nil
	case "PANIC", "0":
		return logrus.PanicLevel, nil
	}
}
```

This would particularly be helpful for handling environment variables in application level code, where users might not necessarily have the exact case right, or may decide it to be more intuitive to use an integer value instead of a string value in their env variable.

I can issue a pull request for this if you think it's a good idea.

**Comment by Sirupsen** [comment]
This hasn't come up enough to be integrated into core.
