### ISSUE TITLE
SetLevelAsInt() - Set log level using an integer value

### ISSUE THREAD

**Issue by JReyLBC** [Sirupsen/logrus#253]
It's often useful to be able to safely set the log level as a integer, instead of explicitly specifying, casting, etc. to a logrus.Level.

An example use case could be setting the log level based on a user's input on the command line. The level needs to be validated before being set. 

A possible implementation could be something like this:

```go
func SetLevelAsInt(l int) error {
	switch l {
	default:
		return errors.New("SetLevelAsInt: given debug level is out of range")
	case 5:
		logrus.SetLevel(logrus.DebugLevel)
		return nil
	case 4:
		logrus.SetLevel(logrus.InfoLevel)
		return nil
	case 3:
		logrus.SetLevel(logrus.WarnLevel)
		return nil
	case 2:
		logrus.SetLevel(logrus.ErrorLevel)
		return nil
	case 1:
		logrus.SetLevel(logrus.FatalLevel)
		return nil
	case 0:
		logrus.SetLevel(logrus.PanicLevel)
		return nil
	}
}
```

I can issue a pull request for this if you think it's a good idea.

**Comment by Sirupsen** [comment]
We're sticking to strings for now.
