### ISSUE TITLE
Move papertrail out of core

### ISSUE THREAD

**Issue by Sirupsen** [Sirupsen/logrus#262]
I'm working on getting all custom hooks and formatters out of core and maintained by the people who actually use them.

@al3x @polds @txgo do one of you mind owning the Papertrail logrus hook and submit a PR to remove it from the repository and add it to the README?

**Comment by polds** [comment]
Working on it: https://github.com/polds/logrus-papertrail-hook Will finish and do PR probably tonight.

**Comment by Sirupsen** [comment]
@polds <3<3
