### ISSUE TITLE
Move Bugsnag out of core

### ISSUE THREAD

**Issue by Sirupsen** [Sirupsen/logrus#263]
I'm working on moving all 3rd party hooks and formatters out of core to keep core as small as possible.

@ConradIrwin @burke @BlakeMesdag do one of you mind claiming this under a personal / company repository (in the case of Bugsnag who it'd make sense maintained this) and submitting a PR to logrus to remove it and reference it in the README?

**Comment by csfrancis** [comment]
I'll own this.

**Comment by csfrancis** [comment]
I've moved Bugsnag out: https://github.com/Shopify/logrus-bugsnag.

**Comment by BlakeMesdag** [comment]
Thanks @csfrancis, I hadn't had a chance to do anything with this yet.
