### ISSUE TITLE
`Logger` interface doesn't have `WithError`

### ISSUE THREAD

**Issue by gchpaco** [Sirupsen/logrus#277]
I'm trying to make loggers for subcomponents with `NewLogger`, which works great, except that they don't have the `WithError` interface forcing some circumlocutions.  This would be convenient to have.

**Comment by Sirupsen** [comment]
Would you mind submitting a PR?

**Comment by gchpaco** [comment]
Sure, I can do that.

**Comment by nickcarenza** [comment]
thanks for this @gchpaco
