### ISSUE TITLE
Proposal: modify Formatter.Format(*Entry) ([]byte, error) declaration

### ISSUE THREAD

**Issue by d2r2** [Sirupsen/logrus#288]
Please, consider to change Formatter.Format(*Entry) ([]byte, error) interface method, adding "disableColors bool" argument, like this: Formatter.Format(entry *Entry, disableColors bool) ([]byte, error). New argument will expand behavior of Format method, giving possibility to use Formatter not only for Logger.Out object, but for custom Hook handler as well. In this case Formatter may be used to prepare strings for output to the file (without terminal coloring tags).

**Comment by dolmen** [comment]
Colors are only something relevant for the `TextFormatter` while the `Formatter` interface is generic.
`disableColors` would be irrelevant for most formatters but would add runtime cost to all.

**Comment by dolmen** [comment]
You could use a `disableColors` field that would be used by some formatters and some hooks and ignored by your other hooks and formatters.

**Comment by Sirupsen** [comment]
Agree with @dolmen
