### ISSUE TITLE
Specify time in UTC or specified time zone

### ISSUE THREAD

**Issue by markcampanelli-wf** [Sirupsen/logrus#293]
It is important to be able to specify that all times be logged in a specified timezone or in UTC. This allows straightforward comparisons of logs from different programs. Apparently, the TimestampFormat variable does not allow one to set the timezone.

Perhaps the In function from the standard Go time library could be leveraged to return times in a particular location on the line https://github.com/Sirupsen/logrus/blob/master/entry.go#L84.

**Comment by dolmen** [comment]
The output timezone selection is a job for formatters.
The API allows you to write your own formatter instead of the default `TextFormatter`.

**Comment by aybabtme** [comment]
Closing, I agree with @dolmen's comment.
