### ISSUE TITLE
ElasticSearch v2 does not supports field names that contains dots when importing using logstash formatter

### ISSUE THREAD

**Issue by lonnc** [sirupsen/logrus#297]
See https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots

Affected file: logrus/formatters/logstash/logstash.go 

Currently if a log message that includes keys which match either 'level', 'type' or 'message' get rewritten to 'fields.level', 'fields.type' or 'fields.message' respectively. This resultant json message fails on importing into ElasticSearch v2.

**Comment by Sirupsen** [comment]
\cc @stevvooe

**Comment by stevvooe** [comment]
@Sirupsen @lonnc Sounds like the API version has changed. The conventions of doing "fields.x" is from logstash. 

Has the logstash specification been updated to address the changes in the elasticsearch API?
Do you have a suggested fix here?

**Comment by lonnc** [comment]
To be consistent with current implementation you could do something like:

entry.Data["fields"] = map[string]string{"x": "The Original Message"}

or just replace "fields.x" with "fields_x".

However given implications of issue #300 (caused by elasticsearch v2 now being strict on field types) might want to be consistent with whatever is decided there.

**Comment by stevvooe** [comment]
@lonnc This is going to take more effort to look at. We still need to maintain compat with those using v1 formats, as well.

@Sirupsen Would you mind making a label for logstash issues and I'll take them on when we pull out the formatter?

**Comment by lonnc** [comment]
@stevvooe I believe that the first option ```entry.Data["fields"] = map[string]string{"x": "The Original Message"}``` would retain compatibility with v1 format, although this would need verification.

**Comment by aybabtme** [comment]
@stevvooe I've added a label for the bug.
