### ISSUE TITLE
Suppress duplicate logs

### ISSUE THREAD

**Issue by ch-acctg** [Sirupsen/logrus#304]
I have a feature request:

Many go based systems utilize logrus which is great, but well...  it often makes duplicate log entries and they can easily grow large and in some environments it effects IO as well.  It would be nice if this could be suppressed in some way up here in the logging system.

Thanks!

**Comment by aybabtme** [comment]
I think those are application bugs, and I don't think this logger should be compensating for applications duplicating log events.

**Comment by drscre** [comment]
Having some ready-made way to throttle or deduplicate log messages (at least adjacent) would be nice when same error happens very often (i.e. when some server has to drop incoming packet because they are arriving too fast and prints a warning every time packet is dropped)
