### ISSUE TITLE
TextFormatter does not treat msys git bash shell as tty

### ISSUE THREAD

**Issue by jerrodrurik** [sirupsen/logrus#306]
https://github.com/Sirupsen/logrus/blob/master/text_formatter.go#L73

This seems to be source of the error.

**Comment by Sirupsen** [comment]
PR welcome

**Comment by aybabtme** [comment]
@jerrodrurik if you have a patch for this, I'll be happy to review it.

**Comment by aarongreenlee** [comment]
@jerrodrurik, would you be open to submitting a pull-request?

**Comment by tommyshem** [comment]
I have done some tests in the msys git bash on windows and the isTerminal is returning false.
The runtime.GOOS is returning ="windows" which is correct as it is windows.

Not sure how to test for bash on windows.

He could try the forceColors flag to force the colour output on so it does not check for tty, not sure if it would work being bash on windows and not sure how to turn the forceColors flag on.

code snippet from the same file line 37.
https://github.com/Sirupsen/logrus/blob/master/text_formatter.go#L36

**Comment by tommyshem** [comment]
Got it working on the msys git bash terminal by putting the force flag on as a temp fix.
Code below.

` var log = logrus.New()`

` func main() { `

      var testf = new(logrus.TextFormatter)
       testf.ForceColors = true
       log.Formatter = testf

      `log.Errorf("runtime system = " + runtime.GOOS)`
`}`
`

**Comment by tommyshem** [comment]
Found this on Issue #172 

// import this library 
 import "github.com/shiena/ansicolor" 

 // force colors on for TextFormatter 
 log.Formatter = &logrus.TextFormatter{ ForceColors: true, }
 
 // then wrap the log output with it 
 log.Out = ansicolor.NewAnsiColorWriter(os.Stdout)

**Comment by chappjc** [comment]
@tommyshem Thanks for the tip.  Another option:

``` go
import "github.com/mattn/go-colorable"

log.Formatter = &logrus.TextFormatter{ForceColors: true}
log.Out = colorable.NewColorableStdout()
```

**Comment by sirupsen** [comment]
Thanks for the workaround @mattn and @chappjc, I've added this to the README in feda234

**Comment by cup** [comment]
https://github.com/sirupsen/logrus/issues/306
https://github.com/sirupsen/logrus/issues/379
https://github.com/sirupsen/logrus/issues/763
