### ISSUE TITLE
Logger vs. Entry: provide interface 

### ISSUE THREAD

**Issue by benma** [Sirupsen/logrus#308]
Hi

I wanted to have a logger as an argument to a function, but I don't necessarily care whether it is a `Logger` or an `Entry`, as both provide the same functions (`Info`, `Debug`, `WithFields`, ...), and I want the caller to decide the context of the logging.

It is a bit weird to take an `Entry`, and have the caller pass `logrus.NewEntry(logger)` instead of just `logger`.

I expected there to be an interface that can be used in place.

**Comment by abourget** [comment]
I wanted to have the Writer() function on an Entry, but that,s a difference between the Logger and Entry.

**Comment by benma** [comment]
I am not sure what you mean. There should be an interface that has all the common functions (`Info`, `Debug`, `WithFields`, etc.).

**Comment by little-arhat** [comment]
@abourget @benma see #320 for possible solution
