### ISSUE TITLE
AppEngine integration

### ISSUE THREAD

**Issue by 9uuso** [sirupsen/logrus#310]
Hi,

I tried to use a database driver with my application today, which relies on this logger. I wanted to have my app run on Google App Engine, but I noticed that the only thing which is standing on my way is the use of `syscall` package. Looking at the code, I noticed that the original `terminal_linux.go` file is based on Go's official `ssh/terminal` repo. However, now that I took a look at `ssh/terminal`, they have updated it to use [hard-coded constants for linux](https://github.com/golang/crypto/blob/c8b9e6388ef638d5a8a9d865c634befdc46a6784/ssh/terminal/util_linux.go). In the end, I was able to get logrus build on appengine with [some modifications](https://github.com/9uuso/logrus/commit/28716abd1d1bcca1ce279e04ef63aede463352c8).

Declaration of `IsTerminal()` in `terminal_appengine.go` is clearly a hack and I don't have any idea whether I may app may have side-effects from it.

Since the tests pass and the program compiles on Darwin and AppEngine, I was wondering if you could give me an opinion whether there could be chance for some hack like this to get into the main project? I'd imagine that at least some people on upstream projects could find the hack welcome.

If you are fine with the idea, I can make a PR of it.

**Comment by Sirupsen** [comment]
Fine with me!

**Comment by sirupsen** [comment]
https://github.com/sirupsen/logrus/issues/343
