### ISSUE TITLE
Add Fingerprint and Tags to support customize event grouping and tags for Sentry

### ISSUE THREAD

**Issue by hongshibao** [Sirupsen/logrus#319]
Hi Simon,

Sentry has concepts like Fingerprint and Tags to support customize event grouping and tags (https://docs.getsentry.com/hosted/learn/rollups/#customize-grouping-with-fingerprints). I found these two were very helpful for event classification and statistics in my project, where I sent logs to Sentry server using Sentry Hooks for Logrus.
So I think it would be nice if Logrus (and also the Sentry Hook for Logrus) can support customize Fingerprint and Tags, by, e.g. adding two functions WithFingerprint() and WithTags().
I have implemented them in my own project. I can send a PR if you are fine with the idea.

Thanks.

**Comment by aybabtme** [comment]
hey @hongshibao, thanks for the idea. I think this sort of custom behavior is best left to custom hooks and formatters. This is how we do at @digitalocean in our custom sentry error handler, and I think it works well while keeping `logrus` more general.
