### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by Unknwon** [Sirupsen/logrus#322]
Hi thanks for the great package!

Just cannot find doc anywhere about the meaning of `[0000]` in the log output `INFO[0000]`, would you mind explain in the README a bit?

**Comment by Sirupsen** [comment]
It's the relative timestamp from process start :) This is really useful during development I've found.

**Comment by Unknwon** [comment]
Thanks for the response!

So what is the unit of this timestamp?

**Comment by Sirupsen** [comment]
Seconds if I remember correctly.

**Comment by Unknwon** [comment]
Got it, thanks again! :beers:

**Comment by Unknwon** [comment]
A quick follow up question, will this number be reset to 0 after 9999?

**Comment by Sirupsen** [comment]
Nope, it'd probably just expand to 5 characters. I haven't run into that in development

**Comment by Unknwon** [comment]
Hmm, the README says `Logrus has no notion of environment.`, so I assume a long running process will eventually have very very large value on this number?

**Comment by Sirupsen** [comment]
yes but typically you don't have processes that long for that long in development with a tty. if you do, you might want another formatter.

**Comment by Unknwon** [comment]
Ah! I see. So if I start as service (e.g. systemd), the number will not be shown, is that correct?

**Comment by Sirupsen** [comment]
yes
