### ISSUE TITLE
Is it possible to log a data struct or JSON object so we don't have to enumerate/list the fields?

### ISSUE THREAD

**Issue by edwindvinas** [Sirupsen/logrus#338]
Hi,

Thanks for sharing the nice logger.
I just want check if this has a functionality to log a JSON or a data struct?

Example:
	  log.WithFields(&jsonObject).Info("A JSON object is logged from mongodb!")
          log.WithFields(&tableStruct).Info("A data struct is logged from datastore!")

Best Regards,
Edwin

**Comment by aybabtme** [comment]
You'll need to pass a `logrus.Field{"name": &jsonObject}` and then that `jsonObject` will be printed as JSON _if_ you use the JSONFormatter.

**Comment by RongxinZhang** [comment]
@aybabtme Is there an example that you can show? I just tried the below and the response was a bunch on weird encoding: 

please advise:

#### Logger:
```go
jsonStr := []string{"1", "2", "3"}
jsonObj, _ := json.Marshal(jsonStr)
fmt.Println(string(jsonObj))

log.WithFields(log.Fields{
  "json": &jsonObj, 
}).Info("message")
```

#### Result:
```shell
{"json":"WyIxIiwiMiIsIjMiXQ==","level":"info","msg":"message","time":"2016-05-06T15:07:52-07:00"}
```

**Comment by aybabtme** [comment]
do:
```go
jsonStr := []string{"1", "2", "3"}
log.WithFields(log.Fields{
  "json": jsonStr, 
}).Info("message")
```

**Comment by mlsaito** [comment]
You can display the actual map without having to convert it to JSON:

**Logger:**

```
// Get HTTP GET parameters as a map
getParameters, _ := url.ParseQuery(r.URL.RawQuery)

log.WithFields(logrus.Fields{
  "getParameters": getParameters,
}).Info("Request received!")
```

**Result:**

`{"get_parameters":{"from":["verify"],"text":["SampleMessage!"],"to":["819092096281"]},"level":"info","msg":"Request received!","time":"2018-04-12 17:32:48"}`

If you use `logrus.Field{"name": &jsonObject}` it wouldn't display the actual value as @RongxinZhang mentioned.

And if you convert the JSON to a string, you'll have a lot of escape characters which isn't really JSON and is not friendly with services such as Loggly:

```
// Get HTTP GET parameters as a map
getParameters, _ := url.ParseQuery(r.URL.RawQuery)
getParametersJson, err := json.Marshal(getParameters)

log.WithFields(logrus.Fields{
  "getParameters": string(getParametersJson),
}).Info("Request received!")
```

**Result:**

`{"getParameters":"{\"from\":[\"verify\"],\"text\":[\"SampleMessage!\"],\"to\":[\"819092096281\"]}","level":"info","msg":"Request received!","time":"2018-04-12 16:05:18"}`

**Comment by landron** [comment]
I needed json for `json:"-"`, but I cannot switch (at least now) to JSONFormatter. So I ended overwriting String() for the struct.
Initial problem: https://stackoverflow.com/questions/65230227/how-to-print-struct-verbosely-with-hiding-some-fields
