### ISSUE TITLE
you can't replace your log imports everywhere with log "github.com/Sirupsen/logrus"

### ISSUE THREAD

**Issue by wangtongphp** [Sirupsen/logrus#340]
you can't replace your log imports everywhere with log "github.com/Sirupsen/logrus",
 example: 
logger := log.New(os.Stdout, "logger: ", log.Lshortfile)  //undefined: logrus.Lshortfile; 
logger := log.New(os.Stdout, "logger: ", log.Lshortfile)  //too many arguments in call to logrus.New,  

Did I do something wrong ?

**Comment by aybabtme** [comment]
No, the constructors are different since they support different features. In places where you use the global logger, you can blindly replace `log` with `github.com/Sirupsen/logrus` but otherwise, this is normal.
