### ISSUE TITLE
How to detect syslog via tcp connection loss

### ISSUE THREAD

**Issue by sksastry** [Sirupsen/logrus#345]
If the tcp connection associated with syslog hook goes down, what is the best way to detect this?  Ideally, I'd like to trap the connection loss via a callback, close/destroy the existing hook and recreate a new hook.  Please suggest.

**Comment by aybabtme** [comment]
You can make a custom hook that will reconnect/panic/etc if the connection dies.

**Comment by RongxinZhang** [comment]
@sksastry Hitting the same problem. Did you implement a reconnection tool? If so how?
