### ISSUE TITLE
Does not support SetPrefix()

### ISSUE THREAD

**Issue by tobyroworth** [sirupsen/logrus#352]
SetPrefix() is not available https://golang.org/pkg/log/#SetPrefix which prevents a straight swap

This also seems to be the case for SetOutput() and SetFlags()

**Comment by dgsb** [comment]
SetOutput has been introduced since this issue has been opened. The usual way for the prefix is to use a dedicated field for it.
The purpose is not to be compatible with the initialization path, but rather for the path where traces are issued.
I suggest we close this issue.

**Comment by tobyroworth** [comment]
I believe my use case, back when I filed the issue, involved using SetPrefix when issuing logs, rather than during init, and when switching to logrus, this was something I had to rewrite.

This should be unnecessary for a library that claims  to be _"completely API compatible with the standard library logger."_ If certain methods aren't supported, it isn't _completely_ compatible, and this should be reworded in the docs.

**Comment by dgsb** [comment]
@tobyroworth I guess your usage of the SetPrefix function is rather uncommon. Anyhow, if you provide a PR implementing this call, I would happily merge it.

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
