### ISSUE TITLE
Is it possible to configure the log levels to be ints rather than strings?

### ISSUE THREAD

**Issue by gfarrell** [sirupsen/logrus#355]
We export all our logs to logstash via filebeat, and all our other systems have logging libraries which use ints for the log level rather than strings. Can this be done with logrus?

**Comment by louy2** [comment]
Sometimes I feel configurations are asked too often. It's open source!

Just change `Level.String()` at [logrus.go:60](https://github.com/Sirupsen/logrus/blob/master/logrus.go#L16) to this:

```go
func (level Level) String() string {
    return strconv.FormatUint(uint64(level), 10)
}
```

**Comment by eexit** [comment]
@louy2 Yep but it'd be nice to have this embedded into the lib directly without having to hack into it.

**Comment by louy2** [comment]
@eexit Recently got involved into functional programming and now my stance regarding configuration has become "the interface should be designed to take a function in the first place".

Well, in this case the canonical way is probably PR a new formatter.

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
