### ISSUE TITLE
Windows terminal

### ISSUE THREAD

**Issue by krzysztofantczak** [sirupsen/logrus#357]
Hi,

Windows terminal detection seems to failing when using things like mintty. It 100% supports colorized output, but in your lib it fallbacks to plaintext.

**Comment by changwuf31** [comment]
Maybe this will work for you https://github.com/Sirupsen/logrus/issues/172#issuecomment-147143824

**Comment by sirupsen** [comment]
Yeah, that's the workaround.

https://github.com/sirupsen/logrus#formatters
