### ISSUE TITLE
problem when run code from readme file

### ISSUE THREAD

**Issue by akangaziz** [Sirupsen/logrus#362]
### Error When Run Code from readme file

`sh-3.2# go run a.go

./a.go:5: imported and not used: "github.com/mataharimall/api-seller/vendor/github.com/sohlich/elogrus"
./a.go:15: undefined: NewElasticHook`

### you need to change this code to:

`
package main
import (
	"github.com/Sirupsen/logrus"
	"github.com/sohlich/elogrus"
	"gopkg.in/olivere/elastic.v3"
)

func main() {
	log := logrus.New()
	client, err := elastic.NewClient(elastic.SetURL("http://localhost:9200"))
	if err != nil {
		log.Panic(err)
	}
	hook, _ := elogrus.NewElasticHook(client, "localhost", logrus.DebugLevel, "mylog")
	log.Hooks.Add(hook)

	log.WithFields(logrus.Fields{
		"name": "joe",
		"age":  42,
	}).Error("Hello world!")
}
`
### and this is what you'll get:

`sh-3.2# go run a.go
ERRO[0001] Hello world!                                  age=42 name=joe`

**Comment by Sirupsen** [comment]
Closed for lack of description, please re-open a well-formatted issue with a more accurate description of your problem. 🙂
