### ISSUE TITLE
log to file and tty at the same time

### ISSUE THREAD

**Issue by tianjipeng** [Sirupsen/logrus#363]
Hi, is there any solution  logging to file and tty at the same time?

**Comment by Sirupsen** [comment]
You can write a hook that does it :)

**Comment by tommiv** [comment]
Sorry for necroposting, but there is an easier way, if you don't care about separate loglevel/format of tty and file output:

```go
logFile, err := os.OpenFile(
    "/path/to/log.txt",
    os.O_WRONLY | os.O_CREATE | os.O_APPEND,
    0755,
)

if err != nil {
  // panic here
}

logOutput := io.MultiWriter(os.Stdout, logFile)
log.SetOutput(logOutput)
```
