### ISSUE TITLE
Make name of time field configurable

### ISSUE THREAD

**Issue by algermissen** [sirupsen/logrus#366]
Hi,

are there any plans to allow for the time field name to be configurable, in stead of being hard-coded as `time`?

I am in an environment where the agreement is on calling the timestamp `@timestamp` so I would like to change to that field name when setting up the logger.

Jan

**Comment by stuart-warren** [comment]
if json is ok there is a logstash json formatter:
```
import (
    log "github.com/Sirupsen/logrus"
    "github.com/Sirupsen/logrus/formatters/logstash"
)
...
log.SetFormatter(&logstash.LogstashFormatter{})
...
```

**Comment by malnor** [comment]
"github.com/Sirupsen/logrus/formatters/logstash" does not exist. The JSONFormatter format works fine for logstash except for the actual naming of the time field. It would help to have a specific formatter for logstash or be able to change the name of the time field.

**Comment by stuart-warren** [comment]
Seems to have been moved to it's own repo.
See: https://github.com/bshuster-repo/logrus-logstash-hook

**Comment by adamtulinius** [comment]
It would still be nice to easily change the name of the time field (and possible the format of the time field), without having to write an entire new formatter.

**Comment by adamtulinius** [comment]
Looks like it is actually possible to change the name of the "time"-field in the JSONFormatter: https://github.com/sirupsen/logrus/blob/master/json_formatter.go#L32

**Comment by algermissen** [comment]
That helps - thanks for the information!
