### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by RongxinZhang** [sirupsen/logrus#373]
@Sirupsen 
Was logging information through: https://github.com/Sirupsen/logrus

However, I am getting this in the logs
`Failed to fire hook: write tcp 10.0.0.212:45992->10.0.4.98:5000: write: connection timed out`
Then this:
`Failed to fire hook: write tcp 10.0.0.212:45992->10.0.4.98:5000: write: broken pipe`

This is weird, as it happens consistently after 8 logs.

No error is being thrown.

Have you seen this error before? Great to get some advice / pointers.

**Comment by RongxinZhang** [comment]
Is there a way to log to logstash without using plugins or hooks?

**Comment by RongxinZhang** [comment]
Seems like sometimes logstash would disconnect. What is the recommended way for reconnection with logstash?

**Comment by sirupsen** [comment]
Can you raise this issue in https://github.com/bshuster-repo/logrus-logstash-hook? Thanks!
