### ISSUE TITLE
High level of contention in Logger mutexes

### ISSUE THREAD

**Issue by NZKoz** [sirupsen/logrus#376]
We use logrus in a handful of high traffic services and find ourselves having to be extremely careful about  where we make logger calls otherwise the services can end up blocking inside [Entry#log](https://github.com/Sirupsen/logrus/blob/4b6ea7319e214d98c938f12692336f7ca9348d6b/entry.go#L101)and causing some grief.  Given we're just emitting them to the docker host over UDP, this contention often ends up needlessly blocking as 

I figure there are multiple ways of fixing this, so let's ask before sending patches.  

Ideally we could have our own implementation of `Logger` which maintained its own internal mutexes, or used buffered channels, ring buffers or ... something similar.  Under critical I'd rather drop messages than drop requests, though that's probably not true of all services.

However if there was another approach you'd prefer we take I'm happy to take a look.

**Comment by chancez** [comment]
Just wanted to point out the stdlib logger does this too. Is there any reason you can't simply wrap https://github.com/Sirupsen/logrus/blob/master/logrus.go#L112? You could implement your own synchronization around Logrus that drops messages if there's too many coming in.

**Comment by NZKoz** [comment]
100% agree that stdlib does it.

The downside of implementing FieldLogger is the amount of duplication involved if you want to do it correctly.  Could do a simple delegated implementation but then I'd be buffering a bunch of messages that were going to be discarded, leading me to drop messages which were intended for output in favour of messages that were going to be dropped anyway.

Alternatively I could do all the level checks in each func, which is hardly the end of the world but pretty brittle too?

If logger was an interface though, I could push our own implementation in which did what we need with messages that were intended for display.

Maybe there's something I could do with Hooks instead?

**Comment by aarongreenlee** [comment]
@NZKoz Have you thought about a possible solution that could be exercised via Hooks? We would like to make as much use of Hooks as possible.

**Comment by sirupsen** [comment]
@NZKoz does https://github.com/sirupsen/logrus/pull/370 resolve this for you? It introduces a way to disable locking.

**Comment by sirupsen** [comment]
I'm trying to clean a bit here, we'll re-open if it doesn't!

**Comment by NZKoz** [comment]
Sorry for the silence, this notification got binned with the millions of rails ones that flow my way too 😄 

Yep, that's great.

**Comment by sirupsen** [comment]
Maybe I'll see you at Railsconf this year then :)
