### ISSUE TITLE
[Windows 10]: TTY not detected.

### ISSUE THREAD

**Issue by LukasMa** [sirupsen/logrus#379]
_OS_: Windows 10 Pro 64bit
_Go version_: 1.6

On windows logrus always prints the text in the _logfmt_ format to stdout. It seems that it does not detect the tty. I tried it with msysgit, cmd and powershell.

**Comment by aarongreenlee** [comment]
Thanks for reporting this issue.

**Comment by tommyshem** [comment]
See issue #172 and #306(comment) for some ideas to get it working with a walk around.
Also look at this github project https://github.com/mattn/go-colorable

**Comment by sirupsen** [comment]
Does https://github.com/sirupsen/logrus/pull/471 fix this?

**Comment by cup** [comment]
https://github.com/sirupsen/logrus/issues/306

https://github.com/sirupsen/logrus/issues/379
https://github.com/sirupsen/logrus/issues/763
