### ISSUE TITLE
go build github.com/Sirupsen/logrus: /usr/local/go/pkg/tool/linux_386/compile: signal: trace/breakpoint trap

### ISSUE THREAD

**Issue by winer632** [sirupsen/logrus#386]
[root@localhost mu]# go get -u  github.com/Sirupsen/logrus
go build github.com/Sirupsen/logrus: /usr/local/go/pkg/tool/linux_386/compile: signal: trace/breakpoint trap
[root@localhost mu]# 
[root@localhost mu]# go version
go version go1.6.2 linux/386
[root@localhost mu]# 
[root@localhost mu]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@localhost mu]# 
[root@localhost mu]# uname -a
Linux localhost.localdomain 2.6.32-042stab113.21 #1 SMP Wed Mar 23 11:05:25 MSK 2016 i686 i686 i386 GNU/Linux
[root@localhost mu]#

**Comment by livc** [comment]
The same as yours, do you solve it ?

**Comment by winer632** [comment]
换了centos7就好了

**Comment by livc** [comment]
@winer632 我刚刚也好了，说出来我自己都不信……VPS换个机房就好了……

**Comment by sirupsen** [comment]
I'm going to close this for now. Haven't seen it surface much since. I'm guessing a bad Go build?
