### ISSUE TITLE
Failures of firing log hooks can potientially cause performance degradation

### ISSUE THREAD

**Issue by sunzl1989** [sirupsen/logrus#389]
We installed a Kafka logger as a log hook in our servers. 

During a recent incidence, a sudden increase of traffic overwhelmed the Kafka logger, and resulted in failures of firing the hook, which triggered the following code path: https://github.com/Sirupsen/logrus/blob/master/entry.go#L96-L100

```
    if err := entry.Logger.Hooks.Fire(level, &entry); err != nil {
        entry.Logger.mu.Lock()
        fmt.Fprintf(os.Stderr, "Failed to fire hook: %v\n", err)
        entry.Logger.mu.Unlock()
    }
```

Due to the large amount of traffic, the logging to os.Stderr quickly became the bottleneck of the whole service, caused lock contention, and led to more cascading failures. 

Is there a better way to log the failures of log hooks? Can you provide an option to disable it?

**Comment by sirupsen** [comment]
Did the Kafka logger fail fast? I think it'd be reasonable to circuit break the logging of failing to fire the hook, however, I'd also be concerned about the hooks not failing fast enough (although that should be resolved in the hook, likely not logrus).

WDYT?

cc @zstyblik

**Comment by zstyblik** [comment]
Hello @sirupsen,

thank you for cc and apologies for late reply. Unfortunately, I'm not familiar with logrus internals nor the big picture. Also, I can speak only for myself.
As for our hook, we're quite happy with circuit-breaking it inside the hook itself. Which means that errors inside the hook are hidden from logrus, if needed be. But that's my $0.02USD and what works for me doesn't have to work for others.

Cheers.
