### ISSUE TITLE
Thread safety with multiple Logger instances

### ISSUE THREAD

**Issue by zwass** [sirupsen/logrus#391]
From my reading of the code, it seems that thread safety is achieved by using a `sync.Mutex`. As far as I can tell, there is no synchronization between multiple `Logger` instances. Could an API be added like `func (logger *Logger) UseMutex(mu *sync.Mutex)` so that a mutex could be shared across loggers?

I'm happy to submit a PR if this is something the maintainers would be interested in.

**Comment by zwass** [comment]
@Sirupsen? Anybody? Is this repo still maintained?

**Comment by aarongreenlee** [comment]
Please do submit a pull request. They are always welcome in just about any
open source project :)

**Comment by zwass** [comment]
Thanks @aarongreenlee. I take it this seems like a reasonable API addition to you?

**Comment by aarongreenlee** [comment]
Yes. This package is used in plenty of apps that could benefit from your
proposal. Thanks!

**Comment by Niondir** [comment]
Hi, same issue here. I receive Logs from other started apps that I like to forwards with another formatter and thus another logger. But thread safety is not given between 2 loggers.

Setting the Mutext would be nice.

**Comment by Niondir** [comment]
In the meantime it might be enough to share a threadsafe output.

For me it looks like this:

```
var Output = &ThreadsafeWriter{
	Writer: color.Output,
	Mutex: &sync.Mutex{},
}

type ThreadsafeWriter struct {
	Writer io.Writer
	Mutex  *sync.Mutex
}

func (w ThreadsafeWriter) Write(p []byte) (n int, err error) {
	w.Mutex.Lock()
	n, err = w.Writer.Write(p)
	w.Mutex.Unlock()
	return
}
```

Just set it on all the loggers that should be synced: `logrus.SetOutput(simulator.Output)`

**Comment by stevvooe** [comment]
@zwass Is the issue that there is no synchronization between the destination output? I think @Niondir's solution is correct: if you hand the writer to multiple loggers, the writer needs to be threadsafe.

**Comment by zwass** [comment]
We have moved off of logrus, which is why I never got around to doing this. The solution proposed by @Niondir does look like it would do what we need.

**Comment by stevvooe** [comment]
@zwass What are you using now?

**Comment by zwass** [comment]
We bought pretty heavily into go-kit and are using the logger it provides (https://github.com/go-kit/kit/tree/master/log). We are currently doing pretty minimal logging, and this has been sufficient.

**Comment by Niondir** [comment]
There is one small glitch with my solution. It seems (at least in colored mode) that long log messages get a line break. The second line is than not always synchronized with the related first line. But that's a minor issue for me yet.
