### ISSUE TITLE
[macOS] Failed to fire syslog hook: no buffer space available

### ISSUE THREAD

**Issue by sanpingz** [sirupsen/logrus#392]
When I'm using the syslog hook, I got the following error on the screen, and lost logs in system log:

```
Failed to fire hook: write unixgram ->/private//var/run/syslog: write: no buffer space available
```

Looks like my log messages are too long. Can we just truncate log if they are too long?

**Comment by dgsb** [comment]
@sanpingz can you provide more information ? It's not clear if the issue is specific to the osx platform
