### ISSUE TITLE
Syslog: No output with example from README.md

### ISSUE THREAD

**Issue by juRiii** [sirupsen/logrus#395]
Hi,

as you see, I have used the Example from [here](https://github.com/Sirupsen/logrus/blob/master/hooks/syslog/README.md).

But there is no output in `/var/log/system.log`.
What am I missing here?

<img width="1440" alt="screen shot 2016-08-15 at 14 47 10" src="https://cloud.githubusercontent.com/assets/1895950/17664864/3a2715ba-62f7-11e6-8583-f188b32d4194.png">

**Comment by bclermont** [comment]
by default, macOS write log entries in `/var/log/system.log` for level `syslog.LOG_ NOTICE` and higher.

try `log.Warning` instead of `log.Info`

**Comment by thalesfsp** [comment]
@bclermont I think that it should be in the README.md :)

**Comment by stevvooe** [comment]
@thalesfsp Should the readme document all locations of where syslog might end up? That really seems like it should be on the onus of the user to figure out, given that they've selected syslog. The ultimate destination of syslog is very system specific.

If you feel strongly, please submit a PR with a syslog example.

**Comment by dmathieu** [comment]
I completely agree with @stevvooe's comment.
Closing this as stale for that reason.
