### ISSUE TITLE
Logs received by hooks are filtered out by the "global" log level.

### ISSUE THREAD

**Issue by pasinskim** [sirupsen/logrus#401]
This is not exactly a bug, but rather the design choice I guess. The issue I am having is that I am using a custom logging hook to do some extra logging. The log level in my application is set to `warning`. I can not change it to anything less verbose as the application is working on embedded device and the number of I/O operations really matters. 
The problems is that I am using some logging hook, and in some specific cases I wan it to log some `debug` level logs. The problem is that logs are filtered out very early, when calling some specific logging function (see this as example: https://github.com/Sirupsen/logrus/blob/master/entry.go#L138). Later on, when calling `log()` function (https://github.com/Sirupsen/logrus/blob/master/entry.go#L90) all the logs below certain "global" level are already filtered out and hooks are not receiving those.

I am wondering, what is your take on moving the filtering bit higher. I was thinking that you can do it in `log()` function after calling `Entry.Logger.Hooks.Fire()`. This way each hook should do own filtering, but we won't use any logs that specific hook should receive.

Let me know, what you think. If this is something of interest I would be more than happy to add some PR which will fix the issue.

**Comment by SvenDowideit** [comment]
I too would like to have a log to file hook that has everything in it (lots of debug info), while the normal log level isn't "all".

Instead, I'm going to set the global log level to Debug, have logrus writing the verbose log file, and then implement the filtering in a ShowToUserHook which filters. (this may be a better approach anyway?)

**Comment by dgsb** [comment]
@pasinskim is this issue is still relevant to you, we can not change this behaviour it would have too much impact, and I'm not quite sure this use case is relevant to all users.
But if your traces and the associated hooks are so important maybe the trace itself  is not set at the correct level ?
