### ISSUE TITLE
How to use Fileds in logfile

### ISSUE THREAD

**Issue by AnotherGoogleFan** [sirupsen/logrus#410]
For example, log.Fileds{"test": "test"}.Info("xxx")  can output something I want.
But I want to see it ini log file,  not terminate.
How can I do that?

**Comment by Mercede5** [comment]
io.stdout->file

**Comment by stevvooe** [comment]
@AnotherGoogleFan Have you tried setting `Logger.Out` to a file?

Typically, most people tend to set logging to stderr, since that is a standard.

**Comment by sirupsen** [comment]
https://github.com/sirupsen/logrus/pull/471 adds a readme entry to log to a file
