### ISSUE TITLE
how to show time fields in default format

### ISSUE THREAD

**Issue by Laily123** [Sirupsen/logrus#415]
I used default format to print log, but there is only log level info, log msg which I wrote and some fields I added, but where is the time field, isn't it added automatically?

**Comment by daniel-huckins** [comment]
kind of, it shows how long the program has been running. can set a new formatter to show the full timestamp
```go
logrus.Info("duration")

formatter := &logrus.TextFormatter{
    FullTimestamp: true,
}
logrus.SetFormatter(formatter)
logrus.Info("timestamp")
```
output
```sh
INFO[0000] duration                                     
INFO[2016-09-23T21:55:52-04:00] timestamp
```

**Comment by Laily123** [comment]
@daniel-huckins that's what I want, thank you!!!
