### ISSUE TITLE
go 1.5- can' t use gopkg.in/gemnasium/logrus-airbrake-hook.v2

### ISSUE THREAD

**Issue by usk81** [Sirupsen/logrus#424]
gopkg.in/gemnasium/logrus-airbrake-hook.v2 is used in examples/hook/hook.go, and dependent package ( gopkg.in/airbrake/gobrake.v2 ) uses http.StatusTooManyRequests, but http.StatusTooManyRequests is defined go 1.6+.
Because go 1.5- can't use airbrake hook.

<img width="994" alt="travis" src="https://cloud.githubusercontent.com/assets/2009893/19269458/ae20e7ae-8ff5-11e6-9bdf-55837db3a785.png">

**Comment by stevvooe** [comment]
@usk81 This is a problem with the upstream package. As of airbrake 2.0.9, they've fixed this problem. Closing.
