### ISSUE TITLE
Multiple output writers depending on log level

### ISSUE THREAD

**Issue by aybabtme** [sirupsen/logrus#43]
`glog` has this nice feature where it can log to `stderr` on top of logging to its normal output, if a certain threshold is met: 

See flag `-stderrthreshold=ERROR` in [`glog`](http://godoc.org/github.com/golang/glog).

Something like that would be very useful.

**Comment by cirocosta** [comment]
Just in case anyone needs to do something like "write all logs to a file but if a log is > ERR, log to stderr" (which seems to fit this question), here comes an example using hooks:
https://gist.github.com/cirocosta/0ca74af1d9700aad5ec40425ef587640
