### ISSUE TITLE
Characters are escaped based on TTY in TextFormatter

### ISSUE THREAD

**Issue by fdawg4l** [sirupsen/logrus#431]
The `TextFormatter` will escape `\t` and `\n` if `Out` is not a TTY.  The only way to avoid this and maintain the formatting is to set `ForceColors`, but this will result in non TTY Out instances to include the escaped color color codes.  

I have a change that splits this escaping and terminal checking out of `Format()` and allows the user to set the appropriate values directly or use the helper to create a Formatter bases on the terminal with the appropriate values set.

**Comment by markphelps** [comment]
Closing since #432 was closed
