### ISSUE TITLE
logrus.Flusher interface

### ISSUE THREAD

**Issue by gravis** [sirupsen/logrus#435]
I don't want hooks to block logging, and therefore my app. I tend to create hooks which will fire entries in go routines. In this case, if the program exits before the routine is finished, some entries are lost. I need to call a `Flush` func to make sure we wait until the queue is empty (ex: https://github.com/gemnasium/logrus-graylog-hook/blob/master/graylog_hook.go#L108)

That said, I wonder if we could add a `logrus.Flusher` interface in logrus.
If the hook implements this interface, `logrus.Flush()` would call `hook.Flush()` for each of these hooks.

This would simplify using several hooks with the same behavior. Otherwise, I'd have to call `Flush()` for each of them.

I'd like some feedback before working on a PR ;)

**Comment by sirupsen** [comment]
When would `logrus.Flush()` be called? At exit-time, or after calling `hook.Fire()` on each hook?

**Comment by gravis** [comment]
At exit-time. The goal is the put entries in channels to save logging time. Unfortunately, we need to wait these entries before exiting, hence the flush.

**Comment by sirupsen** [comment]
This might be pretty clean with [`alt_exit.go`](https://github.com/sirupsen/logrus/blob/master/alt_exit.go). There could be a default exit handler that loops through all hooks and if they implement `io.Flusher`, it'll call `Flush()` on them by default. What do you think?

**Comment by gravis** [comment]
I didn't know that part of logrus, thanks for pointing it out. 
AFAIK, there's no`io.Flusher` interface :)
We have 2 choices here:
- Alter the `Exit` function to call Flush on all hooks if implemented
- Let the hooks register a `Flush` handler on exit

I'll have to update code in both cases :)

**Comment by sirupsen** [comment]
Yeah, what leans me towards (2) is that this issue has been open since October (sorry), and no-one else has pitched in. We can revisit this at a later time, where (1) may become desirable. You could implement (2) yourself in such a way you traverse through all the hooks and call `Flush()` if implemtned.

**Comment by gravis** [comment]
No worries. There's another issue actually: We need to make sure the `Flush` method is called when the program exits. Otherwise, the channel could still have entries, and they will be lost. I first thought alt_exit. We could use `signal.Notify`, but it won't work if the program exits by itself.
The only to achieve this is to add a defer function in the main function. That's actually what I'm already doing to flush the hooks... If you have a better idea, I'm all ears :))

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
