### ISSUE TITLE
REAMDE: overriding the standard library logger

### ISSUE THREAD

**Issue by nathany** [sirupsen/logrus#438]
Would it be useful to add these examples to the README?

Use Logrus for any logging done with the standard library log package, especially useful for chatty third-party packages.

```go
logger := logrus.New()
logger.Formatter = &logrus.JSONFormatter{}
// use logrus for standard log output:
log.SetOutput(logger.Writer())
```

Alternatively, the standard library logging can be discarded entirely with the following:

```go
log.SetOutput(ioutil.Discard)
```

From https://github.com/gocql/gocql/issues/766#issuecomment-257715015

**Comment by sirupsen** [comment]
Great idea! Done in 080ca65
