### ISSUE TITLE
Add a "none" log level to disable logging completely on a particular logger

### ISSUE THREAD

**Issue by fasaxc** [sirupsen/logrus#441]
Sometimes I want to disable a particular logger completely via configuration, how about adding a `NoneLevel` constant that maps to `-1`? 

Use case is that my app logs to various targets via different loggers and users may want to completely disable a particular target.

**Comment by fasaxc** [comment]
I'm happy to put up a PR if you like the idea.

**Comment by ngortheone** [comment]
Wont hurt to have such option IMHO

**Comment by dgsb** [comment]
@fasaxc it it still matters to you, a PR would be appreciated. We need to be careful about the Fatal and Panic call which imo should still panic and exit when the logger tracelevel is set to this NoneLevel.
There was another issue requested for the same feature but with a MuteLeve, I'm not sure which name is the best though.

**Comment by fasaxc** [comment]
D'oh, looks like Level is defined as a `uint32` so we can't use `-1`.  Making `NoneLevel == 0` and moving `PanicLevel` to `1` could work but it would be a breaking change :-/

Maybe this desire could be handled with a separate `Logger.SetEnabled(bool)` method?

**Comment by dgsb** [comment]
We can't change the value of the level in a v1 release/branch, it can have too many unexpected behaviour. A boolean would be backward compatible indeed, if the default value can keep the current behaviour.

**Comment by mdiez19** [comment]
Its not perfect, but if I run `logrus.SetLevel(50)` it silences the log. I'm sure it probably unintentionally silences everything i.e. fatal errors but that's the tradeoff.

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
