### ISSUE TITLE
Fill error field automatically in entries if the fist item in args ...interface{} is an error

### ISSUE THREAD

**Issue by ihrwein** [Sirupsen/logrus#448]
I use `log.Errorln(err)` a lot, but it doesn't fill the `error` field in `Fields`. `logrus-airbrake-legacy-hook` tries to use [that error field](https://github.com/gemnasium/logrus-airbrake-legacy-hook/blob/master/airbrake.go#L33) to report more precise error types. If it's not available, it creates a new error with `errors.New(...)`. So all errors reported trough airbrake will have `*errors.errorString` type.

If you think that this is a valuable feature, I can add it to logrus.

**Comment by stevvooe** [comment]
The arguments of `Errorln(err)` are destined for the message. Detecting this as an error and repeating it in the `err` field would be a little unexpected and quite fragile.

Just get in the habit of using `logrus.WithError(err).Error("more about what happened")`. It works much better and makes errors a lot easier to trace, especially when used with pkg/errors.

Thanks for the suggestion!
