### ISSUE TITLE
Single responsibility violations

### ISSUE THREAD

**Issue by bgaifullin** [sirupsen/logrus#460]
logger should not call exit and panic in any case, because this will violate singe responsibility pattern.

I want to use logger.Fatal to mark some messages in log as critical, but I do not expected that my application will exit after this call.
The same behaviour is applicable for panic.
IMO: this should be only severity of log message, not more.

**Comment by cstockton** [comment]
In Go, if you call a method with the name [Panic](https://golang.org/pkg/log/#Logger.Panic), you should expect your application to panic.

**Comment by bonds0097** [comment]
This is a convention of the standard library and I wouldn't expect this to change.

**Comment by bgaifullin** [comment]
Ok, What about moving this behaviour to hooks and allow for clients to disable this behaviour if they want it?
Or at least introduce one additional severity 'CRITICAL', to mark messages which is critical for system, but without exiting from application.

**Comment by stevvooe** [comment]
@bgaifullin This issue seems "religious" in nature. `Fatal` and `Panic` follow the Go standard library conventions. Use `Error` to report critical issues.
