### ISSUE TITLE
Multiple formatters?

### ISSUE THREAD

**Issue by heartles** [sirupsen/logrus#461]
It would be nice to have multiple formatters depending on the hook being used. The use case I have for this would be having nice, pretty colored logs available in the output TTY, while having uglier JSON/other formatted logs be sent to our tools on the back end.

My thought is that this could be implemented as making formatters a property of a logging hook, rather than a logger.

**Comment by sirupsen** [comment]
Can you use a hook instead? In reality, the dichotomy between formatter and hooks is somewhat confusing, but I'd rather not break backwards compatibility.
