### ISSUE TITLE
TextFormatter for non tty terminals

### ISSUE THREAD

**Issue by undiabler** [sirupsen/logrus#466]
- everything works fine in terminal (local/ssh)
- I get logfmt output when running my program via supervisord
- `log.SetFormatter(&log.TextFormatter{})` seems do nothing

how can I skip auto checks and get textFormatter for non tty terminals?

**Comment by undiabler** [comment]
Solved myself. 
It seems confusing but with `log.SetFormatter(&log.TextFormatter{ForceColors: true})` everything works as expected. 

Now I have new question. Is it realy good to overrite check if we run program in tty with ForceColors flag?
What about situation when we want normal output (not logfmt) but without colorls. Now it is impossible. 

Better way is:
- leveled variable for color
-- auto check if can use colors
-- enable colors manual
-- disable colors manual
- leveled variable for output
-- auto check temrinal (logfmt style/simple output)
-- simple output manual
-- logfmt output manual

**Comment by sirupsen** [comment]
https://github.com/sirupsen/logrus/pull/471 likely fixes this
