### ISSUE TITLE
Provide the implementation as a custom io.Writer

### ISSUE THREAD

**Issue by ant0ine** [Sirupsen/logrus#47]
Hi,

Is there a possibility or a plan to provide the Logrus implementation as a custom io.Writer that can be used in conjonction with the standard library logger ?

https://godoc.org/github.com/Sirupsen/logrus#StdLogger is nice but it still makes the package depend on Logrus, only to get the interface.

I'm discussing the issue here: https://github.com/ant0ine/go-json-rest/issues/62

Thanks,

Antoine

**Comment by phemmer** [comment]
I'm in favor of logrus implementing the `io.Writer` interface. The reason for this is that many libraries use the default logger (e.g. `log.Println("foo")`). By allowing us to set the default logger to send to logrus, we can take advantage of logrus's hooks. This can be very important if the we are using the hooks to send to multiple destinations.

**Comment by Sirupsen** [comment]
#103 implemented this!

Thanks @phemmer :heart:
