### ISSUE TITLE
Changing format and adding default fields

### ISSUE THREAD

**Issue by uswami** [sirupsen/logrus#479]
I want to change format of logger, I see key value pairs every time is there any way I can change that.
Also I want to add default fields for all log messages like "filename" of the file from where logger has been called.
Could you please help me with that

**Comment by bbrks** [comment]
Hi @uswami, please see [this example in the readme](https://github.com/sirupsen/logrus#default-fields) for implementing default fields.

[Custom formatters are supported](https://github.com/sirupsen/logrus#formatters), but what do you want to see instead of KV pairs?

**Comment by dgsb** [comment]
closing, no feedback from op.
