### ISSUE TITLE
Logrus keeps overwriting the previous log

### ISSUE THREAD

**Issue by adred** [sirupsen/logrus#483]
I set the output to a file:
```
logrus.SetOutput(logPath)
```
The problem is it keeps overwriting the previous log when there's a new one. Is there a way to prevent this? Can it also be set so that it only writes until it reaches a certain number lines and then create another log file to write into?

Sorry if this is pretty obvious or this only litters the Issues section; feel free to remove this of that's the case.

**Comment by leighmcculloch** [comment]
What is the type of `logPath`? `logrus.SetOutput` takes an `io.Writer`, not a `string` path.

Assuming that `logPath` is a file opened, and each run is overwriting the file, chances are you are `os.OpenFile`ing the file with `O_CREATE` as one of the options. This will be opening the file and setting the current position to the beginning, so any writes happen at the beginning of the file.

Instead you want to open the file in append mode with `O_APPEND`, so you start writing at the end:

```go
package main

import (
    "os"

    "github.com/sirupsen/logrus"
)

func main() {
    file, err := os.OpenFile("example.log", os.O_APPEND|os.O_WRONLY, 0666)
    if err == nil {
        logrus.SetOutput(file)
    } else {
        logrus.Info("Failed to log to file, using default output")
    }

    logrus.WithFields(logrus.Fields{
        "animal": "walrus",
    }).Info("A walrus appears")
}
```

I've made some assumptions about the other code ahead of the code you included in the issue. If this doesn't resolve your issue, can you include all the setup code?

Doc references:
 * `logrus.SetOutput`: https://godoc.org/github.com/sirupsen/logrus#SetOutput
 * `os.OpenFile`: https://godoc.org/os#OpenFile
 * `os.O_CREATE`/`os.O_APPEND`/`os.O_WRONLY`: https://godoc.org/os#pkg-constants

**Comment by adred** [comment]
Thank you! I didn't know about `OpenFile()` options.
