### ISSUE TITLE
How can I keep requestID in all functions invoked by single API request?

### ISSUE THREAD

**Issue by choi2k** [sirupsen/logrus#488]
Hi all, I am using iris to develop a web api and would like to log the request flow by assiging the requestID to each API request. 

I notice there is a way to pass "requestID" using "WithFields" method but it seems I have to pass the log entry to all other method invoked by the API if I want to keep the requestID in the logs located in other method... 

```javascript
func Method(c *iris.Context) {
        theLogger = logrus.New()
	theLogger.WithFields(logrus.Fields{
		"requestID":  "xxx",
	}).Info("It is okay with requestID");
       OtherMethod()
}

func OtherMethod() {
	logrus.Info("Request ID won't be here");
}
```

Is there a way to keep the requestID ?

**Comment by malud** [comment]
Sure, pass the context to OtherMethod. Thats the case context is made for. Assuming the RequestId is shipped with the context.

**Comment by choi2k** [comment]
@malud Umm.. Is it possible to keep the "requestID" without pass the context to OtherMethod?  I have several methods that would be invoked by this API. It would be a bit messy if I pass the context to every method I have called..

**Comment by stevvooe** [comment]
@choi2k I just store the logger or request id in https://golang.org/pkg/context/. The pattern we use is a part of https://github.com/containerd/containerd/blob/master/log/context.go. We also employ a similar technique in https://github.com/docker/distribution.

I am unsure if iris is compatible with the main context package.

**Comment by dmathieu** [comment]
Closing this, as it's not a specific outstanding request.
