### ISSUE TITLE
nil pointer dereference when accessing hook returned by test.NewNullLogger and using debug log level

### ISSUE THREAD

**Issue by mohanraj-r** [sirupsen/logrus#489]
```go
func main() {
	tlog, hook := test.NewNullLogger()
        // commenting the following statement results in a 'nil pointer dereference'
	// tlog.Level = log.DebugLevel
	tlog.Debug("Test debug")  // Changing the log level to Warn or Error doesn't result in an error
	fmt.Println(hook.LastEntry().Message)  // nil pointer error occurs on this line
	return
}
```

Output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x213c]
```

Setting either the log level explicitly to debug or logging with a level above debug works fine.

**Comment by obihann** [comment]
Exact same issue myself.

**Comment by maxlinc** [comment]
FWIW I am seeing this issue with `NewNullLogger` and `NewGlobal`.

When I try `NewLocal` I'm getting a vendor error:
```
cannot use tlog (type *"github.com/maxlinc/omitted/vendor/github.com/Sirupsen/logrus".Logger) as type *"github.com/Sirupsen/logrus" in argument to test.NewLocal
```

**Comment by deepch** [comment]
you can try

type DevNull struct{}

func (DevNull) Write(p []byte) (int, error) {
	return len(p), nil
}

l := log.New(new(DevNull), "", 0)

**Comment by shentaosky** [comment]
Same problem confuse me.

**Comment by rsyed83** [comment]
Just curious, what would you expect the behavior to be?  I was able to reproduce with logging an Info level Entry, but explicitly setting the logger to Warn:

```
	tlog.Level = logrus.WarnLevel
	tlog.Info("Test info")
```

The hook hasn't received any Entries (as expected), and its `LastEntry` would be `nil`.

**Comment by dgsb** [comment]
Normal behaviour, test code is incorrect, closing.
