### ISSUE TITLE
What is the purpose of logrus.Entry.Level? Not worked for me.

### ISSUE THREAD

**Issue by PumpkinSeed** [sirupsen/logrus#495]
I would like to get some information about this struct element, because I tried to use it and nothing happend. I checked the source and got the solution, I have to modify the Entry.Logger.Level, because: 

```
func (entry *Entry) Info(args ...interface{}) {
	if entry.Logger.Level >= InfoLevel {
		entry.log(InfoLevel, fmt.Sprint(args...))
	}
}
```

But I still don't understand the purpose of the Entry.Level element.

**Comment by DmitriyMV** [comment]
This is used by hooks so they could find out the level at `func (hook *MyHook) Fire(entry *logrus.Entry) error` method.
