### ISSUE TITLE
Issue in setting multiple level for Logrus

### ISSUE THREAD

**Issue by ghost** [sirupsen/logrus#497]
how to set level for all level except info level in Logrus?

**Comment by 0xE0F** [comment]
I believe there is no easy way to do it.
The level constants are not bit masks and the logger's code check it just by regular equal operator (the same way as syslog do, for instance).

**Comment by DmitriyMV** [comment]
We solved it using hooks with custom levels and writing the results to the specific destination. Not the best solution, but it works.

**Comment by dgsb** [comment]
@ghost indeed levels are levels not bitmask. Can we close this issue ?

**Comment by dgsb** [comment]
Logrus levels are indeed levels not bitmask, there is no way to easily to do that.
