### ISSUE TITLE
export Lock to User

### ISSUE THREAD

**Issue by git-hulk** [sirupsen/logrus#501]
hi @sirupsen 

We use hook to rotate the log file, it works fine. But message may be lost while update the new writer without lock the writer.

It's good idea or possible to export  `Logger's` Lock  to user?  other suggestions?

**Comment by drscre** [comment]
Another option might be adding a Logger.SetOut() method which changes output with locked mutex

**Comment by git-hulk** [comment]
yeah, it make sense

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
