### ISSUE TITLE
Provide a means for custom io.Writer's to pass the new `IsTerminal` call.

### ISSUE THREAD

**Issue by bbuck** [sirupsen/logrus#502]
I originally implemented an io.Writer to process special color codes that my application uses, but since this change I've discovered I can probably handle this fine via hooks. Although I still have issues with this change -- it's breaking a core concept of my application which is multiple log targets. For those I take advantage of io.MultiWriter to group more than one io.Writer which can't be cast as an *os.File to be determined to be a "terminal." It would be great if you added a logrus.Terminaler (that's probably a terrible name, just a quick example) interface that would let custom io.Writer types determine if they, themselves are a terminal or not.

To be clear, I'm not asking for any kind of reversion, but an interface that would let custom writers tell logrus if they are a "terminal" or not.

I originally commented on https://github.com/sirupsen/logrus/issues/478 but I don't feel like the comment is getting visibility. To be clear, **I'm fine with the addition of the `IsTerminal` method**. I'm just asking for some means to allow custom `io.Writer` implementations to pass the test, as in my case I use `io.MultiWriter` to wrap a terminal and file and want terminal behavior or, also provide a wrapper around standard outputs and want to allow them to also pass the test.

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
