### ISSUE TITLE
Logger.SetLevel

### ISSUE THREAD

**Issue by ChimeraCoder** [sirupsen/logrus#503]
It appears that we can't (safely) configure the loglevels of loggers *except* for the standard logger. 

For the standard logger, we can use the `logrus.SetLevel` method, which protects the level with a mutex, but this mutex is unexported. So if we set `var log = logrus.New()` in our application (which is [recommended in the docs](https://godoc.org/github.com/sirupsen/logrus#New)), we actually can't configure the log level.

The only other thing we can do is to call `SetLevel` on the standard logger and *then* assigning it:

```go

var log *logrus.Logger

func init(){
    logrus.SetLevel(logrus.DebugLevel)
    log = logrus.StandardLogger()
}
```

but that's a bit clumsier, and it also means we're restricted to just using the standard logger.

Am I missing an alternative?

**Comment by flashmob** [comment]
:+1:  Had a similar situation.

Perhaps instead `logrus.New()` try instantiating logger on your own:

```go
&log.Logger{
    Out: os.Stderr,
    Formatter: new(log.TextFormatter),
    Hooks: make(log.LevelHooks),
    Level: log.DebugLevel,
}
```

**Comment by ChimeraCoder** [comment]
Unfortunately that doesn't work for us, because we need to be able to set the log level based on the configuration file that's passed. The only way to do that and also preserve the `var log *logrus.Logger` declaration as a drop-in replacement for the standard library `log` is to have `SetLevel`. Otherwise, it still introduces a race condition.


@sirupsen I'm happy to put together a PR for this if it's something you're interested in adding.

**Comment by flashmob** [comment]
Yes, that's still a limitation - can't change the log level after it has been set,.

Would be interested in testing out your PR too.

**Comment by sirupsen** [comment]
This makes sense, feel free to propose a PR upstream.

**Comment by DmitriyMV** [comment]
@ChimeraCoder @sirupsen 
because #512  had been merged - maybe it will make sense to change from `func (logger *Logger) setLevel(level Level)` to `func (logger *Logger) SetLevel(level Level) {` to make this method publicly available? Any downsides?

**Comment by dmathieu** [comment]
This has shipped 🎉

**Comment by sirupsen** [comment]
🎉
