### ISSUE TITLE
Write to a log file in a Particular format

### ISSUE THREAD

**Issue by harshitdx29** [sirupsen/logrus#518]
I have written my own logger wrapper using Logrus and set the Formatter of logger to TextFormatter and Out to a file. How can I change the format of how logs are written to file. It was completely different in stdout.

**Comment by rfay** [comment]
If you want the same format when writing to a file as you have going to stdout, then in the formatter
myFormatter.isTerminal = true

You'll force it to assume that it's connected to a terminal.

**Comment by dgsb** [comment]
@harshitdx29 there should not that much difference beside the colored output. Can you elaborate a little more, as what did you see in the file and what did you expect to see ?

**Comment by dgsb** [comment]
no feedback on the problem, closing.
