### ISSUE TITLE
Formatter for Google Container Engine (Kubernetes with Fluentd)

### ISSUE THREAD

**Issue by balboah** [sirupsen/logrus#520]
I created a modified formatter of the `JSONFormatter`. It outputs the expected key value pairs so that GCP logging automatically picks it up with the correct severity level.

I saw that there are also plugins specifically for Stackdriver and Fluentd, but in this case no target hosts or credentials are necessary. Only the expected JSON format.

In case you would like to link it, that might be helpful to others.
If you think its already covered, just close this issue.

The formatter with an example can be found at https://github.com/joonix/log

**Comment by dmathieu** [comment]
Thank you Johnny. I'm adding your link.
