### ISSUE TITLE
documentation: Logger.Level documentation is incomplete

### ISSUE THREAD

**Issue by Bo0mer** [sirupsen/logrus#521]
The documentation for `Level` is incomplete[1]:
```
	// The logging level the logger should log at. This is typically (and defaults
	// to) `logrus.Info`, which allows Info(), Warn(), Error() and Fatal() to be
	// logged. `logrus.Debug` is useful in
```
[1] https://github.com/sirupsen/logrus/blob/master/logger.go#L25-L28

**Comment by dmathieu** [comment]
@sirupsen do you remember what you wanted to add there?
If not, I'll remove the unfinished sentence.

**Comment by sirupsen** [comment]
What a cliffhanger... 

Let's remove that unfinished sentence, I don't think it brings value 👍 

Thanks @Bo0mer

**Comment by dmathieu** [comment]
Thank you for reporting this @Bo0mer
