### ISSUE TITLE
Logging Fatal to multiple hooks fails after logging to the first hook

### ISSUE THREAD

**Issue by sargun** [sirupsen/logrus#522]
I have a PR here: https://github.com/sirupsen/logrus/pull/491 

Right now, if you have multiple hooks at the failure level, and they each fire, unfortunately, it'll bail out on the first one.

**Comment by dgsb** [comment]
@sargun are you talking about the same thing that #408 ?  Or is it something specific to the Fatal level which does not behave as expected ?
