### ISSUE TITLE
Debug function doesn't output

### ISSUE THREAD

**Issue by robks** [sirupsen/logrus#523]
I'm on release 0.11.5.
logger.Warn, and logger.Info are working fine.
logger.Debug  - no output

```go
        // ...
	fmt.Println("Level is", level)  // debug
	fmt.Printf("%v\n", reflect.TypeOf(logger))  //=>  *logrus.Entry
	switch level {
	case "debug":
		logger.Debug(msg)   //=> no output
	case "info":
		logger.Info(msg)   //=> good
	case "warn":
		logger.Warn(msg)  //=> good
        // ...
	}
```

**Comment by Patagonicus** [comment]
Hi!

I don't think this is a bug, but it's a bit hard to tell without more context. If you don't change it the StandardLogger is set to the InfoLevel, so debug messages are not printed. I have written an example at [Patagonicus/logrus-523](https://github.com/Patagonicus/logrus-523) that shows that behavior. The test method is basically your snippet, but I've also added a method that shows the current level of a logger (the interface EntryLogger doesn't have a method for that, but if it is an Entry or a Logger you can get it from the struct).

There's also a line that changes the level to debug so the debug message gets printed. Just uncomment that line and run the example again to see the change.

Hope that helps!

P.S.: I've tested the behavior with 0.11.5 and the current master.

**Comment by dgsb** [comment]
@robks how did you configure the logger you are using ? At which trace level did you set the logger ?

**Comment by dgsb** [comment]
Closing due to no feedback, probably a misconfiguration.

**Comment by AhmedAbouelkher** [comment]
I have the exact issue right now, even when testing with [Patagonicus/logrus-523](https://github.com/Patagonicus/logrus-523)
