### ISSUE TITLE
Move to organization repo?

### ISSUE THREAD

**Issue by evalphobia** [sirupsen/logrus#525]
The package naming is still confusing, how about to move logrus to other organization repository in a couple of months?

@nazieb already suggested [go-logrus](https://github.com/go-logrus) for this purpose insted of `logrus`,  which is already taken. 
https://github.com/sirupsen/logrus/pull/384#issuecomment-288254053
(I did not notice [go-logrus](https://github.com/go-logrus), I sent invitation for `get-logrus` to you @sirupsen. Ignore it.)

@nazieb
Would you send [go-logrus](https://github.com/go-logrus) member invitation to @sirupsen ?

Ref: https://github.com/sirupsen/logrus/pull/384 https://github.com/sirupsen/logrus/issues/451

**Comment by nazieb** [comment]
invitation sent.

do I need to invite you as well, @evalphobia?

**Comment by AkihiroSuda** [comment]
@sirupsen 
WDYT? This seems good solution for the sirupsen-Sirupsen issue.

**Comment by sirupsen** [comment]
It's too late, unfortunately. We can't do another rename at this point :(
