### ISSUE TITLE
Unsafe escaping of log data

### ISSUE THREAD

**Issue by kpcyrd** [sirupsen/logrus#531]
I've noticed the output of a program appeared to be broken with logrus, this seems to be due to [appendValue][1].

```
	case string:
		if !f.needsQuoting(value) {
			b.WriteString(value)
		} else {
			fmt.Fprintf(b, "%s%v%s", f.QuoteCharacter, value, f.QuoteCharacter)
		}
```

It seems %v doesn't sufficiently escape the string, I think the else branch should be replaced with:
```
			fmt.Fprintf(b, "%q", value)
```

[1]: https://github.com/sirupsen/logrus/blob/67bca5dc4fe4e689c042885ca5b09e1df1356979/text_formatter.go#L171-L189

**Comment by seiffert** [comment]
I think that I'm experiencing the same issue. I'm adding a field with a `"` character in its value and this `"` is not being escaped in logfmt output.

**Comment by kpcyrd** [comment]
@seiffert I wrote a short program to verify the bug is fixed, it appears the behaviour of `%q` is still not correctly duplicated:

```
~/logrus-verify$ cat foo.go 
package main

import (
	"log"
	logrus "github.com/sirupsen/logrus"
)

func main() {
	stuff := "test\"\xff\xff\xff\xff\x30\x00\x00\x00\x00test\xee\x81\x9a"

	log.Printf("test: %q\n", stuff)

	logrus.WithFields(logrus.Fields{
		"animal": "walrus",
		"stuff": stuff,
	}).Info("A bug was verified")
}
~/logrus-verify$ go run foo.go 
2017/07/11 23:27:27 test: "test\"\xff\xff\xff\xff0\x00\x00\x00\x00test\ue05a"
INFO[0000] A bug was verified                            animal=walrus stuff="test\"����0test"
~/logrus-verify$ 
```

**Comment by dmathieu** [comment]
I've pinged @bbrks, who introduced the QuoteCharacter option in #484 to discuss removing it, as
that option is substentially increasing the complexity of the formatter.

**Comment by seiffert** [comment]
Hi @kpcyrd,
You're right and I'm able to reproduce this: https://play.golang.org/p/JWfN3X7h3W

I'm not sure what `%q` does internally to be honest. The [docs](https://golang.org/pkg/fmt/) state that it returns "a double-quoted string safely escaped with Go syntax". Almost the same is done by `strconv.QuoteToASCII` which also applies quoting. 

With #575, my intention was to fix the quoting issue (quotes in strings not being escaped correctly). If we can find a way to escape strings exactly like `%q` without using `%q` (because of the `QuoteCharacter` feature), I'd be happy to integrate it!

**Comment by kpcyrd** [comment]
After I had some issues with an outdated `logrus.a` (I'm still not good with golang) I could verify the bugfix works for my logging-binary-data usecase :) Thanks!

One more thing that you might want to keep in mind is that the log message and keys are currently not safe. Those are theoretically less likely to contain non-hardcoded data tho:
```go
package main

import (
	"log"
	logrus "github.com/sirupsen/logrus"
)

func main() {
	stuff := "test\"\xff\xff\xff\xff\x30\x00\x00\x00\x00test\xee\x81\x9a"

	log.Printf("test: %q\n", stuff)

	logrus.WithFields(logrus.Fields{
		"animal": "walrus",
		"stu\xff": stuff,
	}).Info("A bug\nwas verified")
}
```

Output:
```
2017/07/17 06:04:21 test: "test\"\xff\xff\xff\xff0\x00\x00\x00\x00test\ue05a"
INFO[0000] A bug
was verified                            animal=walrus stu�="test\"\xff\xff\xff\xff0\x00\x00\x00\x00test\ue05a"
```

**Comment by dmathieu** [comment]
Thank you @kpcyrd. I've opened another issue with this problem, and will be looking into it soon.
