### ISSUE TITLE
error coming after "make build" command

### ISSUE THREAD

**Issue by prashantvidja** [sirupsen/logrus#551]
Hello

Below error coming when I fire "make build" command
My git version 1.7.12.4 and go version go1.8 linux/amd64
error:
```
"can't load package: package ./archive: found packages fetch (fetch_orm.go) and main (insert_gorm.go) in /opt/app/cdr-pusher/archive
src/github.com/ssdb/gossdb/test.go:7:2: local import "./ssdb" in non-local package
make: *** [get] Error 1"
```

Help, please...

Thanks

**Comment by dmathieu** [comment]
Hi,

This doesn't appear to be an issue with logrus itself.
It would appear you have two files (`fetch_orm.go` and `insert_orm.go`) which have two different package names.

Go enforces you to have the same package name for all files in the same package.
See https://golang.org/doc/code.html#PackageNames
