### ISSUE TITLE
Splunk HEC

### ISSUE THREAD

**Issue by posito** [sirupsen/logrus#552]
Hello, 
Logrus is pretty awesome.
Splunk supports something called [HEC](http://dev.splunk.com/view/event-collector/SP-CAAAE6M).

You send the message through HTTP with your token and that's pretty much it.  

Is there an option of near future to support it ? Or maybe provide an example on how to send the logs from logrus to a HTTP endpoint ?

**Comment by posito** [comment]
@sirupsen  could you give a hand **pretty** please

**Comment by sirupsen** [comment]
@posito you can write a hook for this :)
