### ISSUE TITLE
Panicf and Panicln do not explicitly panic

### ISSUE THREAD

**Issue by tiziano88** [sirupsen/logrus#554]
Compare:

```go
func (entry *Entry) Panic(args ...interface{}) {
	if entry.Logger.level() >= PanicLevel {
		entry.log(PanicLevel, fmt.Sprint(args...))
	}
	panic(fmt.Sprint(args...))
}
```

```go
func (entry *Entry) Panicf(format string, args ...interface{}) {
	if entry.Logger.level() >= PanicLevel {
		entry.Panic(fmt.Sprintf(format, args...))
	}
}
```

```go
func (entry *Entry) Panicln(args ...interface{}) {
	if entry.Logger.level() >= PanicLevel {
		entry.Panic(entry.sprintlnn(args...))
	}
}
```

Note that it's clear from the code that `Panic` always panics, but not so for `Panicf` and `Panicln`, even though in practice `entry.Logger.level() >= PanicLevel` is always true because `PanicLevel` is currently defined as `0`. I think it would be worth it to make all three explicitly panic, to avoid ambiguities and also enable the compiler potentially do some more clever flow analysis in the future (e.g. to determine that such calls always panic, even though that does not currently happen).

**Comment by mkorolyov** [comment]
Actually, `entry.log(PanicLevel, ...)` will panic itself,  so explicit panic here looks excess.

Another question that `entry.log(PanicLevel, ...)` will panic with msg like:
`panic: (*logrus.Entry) (0xddc300,0xc42019e700)` bc of the code inside the `log` func
`if level <= PanicLevel {
		panic(&entry)
	}`

while we have formatted err msg at that place, why it is not used?

**Comment by dgsb** [comment]
@tiziano88 PanicLevel is the lowest trace level and the condition is always true. We can argue whether if it will be true in the future or if the condition is relevant, but basically the code is correct.
