### ISSUE TITLE
Testing logger is unable to be used because the package path appears to be invalid.

### ISSUE THREAD

**Issue by smashedtoatoms** [sirupsen/logrus#558]
I am on the latest build and am getting the following error while testing:

```cannot use fakeLogger (type *"redacted/repo/automation/vendor/github.com/sirupsen/logrus".Logger) as type *"redacted/repo/automation/vendor/github.com/Sirupsen/logrus".Logger in field value```

It looks like the package path has the wrong case, but when I manually changed it, it didn't seem to make a difference.  There may be something else going on, but that was what I noticed.

**Comment by sirupsen** [comment]
Please update to 1.0.0

See also https://github.com/sirupsen/logrus/issues/553#issuecomment-306591437

**Comment by smashedtoatoms** [comment]
Perfect, sorry to bother you.  You're doing great work.
