### ISSUE TITLE
Is it 1.0 or not?

### ISSUE THREAD

**Issue by AlekSi** [sirupsen/logrus#559]
README says:
> Please note the Logrus API is not yet stable (pre 1.0).

But there is a `v1.0.0` tag. 😕

**Comment by glibsm** [comment]
The `v1.0.0` tag is a recent development, see #553 for more information.
Looks like the README just hasn't been updated yet to reflect the change.

**Comment by sirupsen** [comment]
I'll update the README, good eye!

**Comment by sirupsen** [comment]
https://github.com/sirupsen/logrus/commit/3d4380f53a34dcdc95f0c1db702615992b38d9a4
