### ISSUE TITLE
Need log rate limitation

### ISSUE THREAD

**Issue by kaoet** [sirupsen/logrus#560]
Users should be able to specify the maximum log rate, to prevent the screen be filled with the same log message.

Eg.
```go
if connectionFailed {
    log.WithRateLimit(1 * time.Second).Warn("connection error")
}
```

I think it's possible to maintain a separate rate limiter for each `log.Info/Warn/Error` invocation using `runtime.Caller()` and a global `caller position -> rate limiter` dictionary.

**Comment by sirupsen** [comment]
You can do this in a custom formatter/hook.

**Comment by MichaHoffmann** [comment]
When doing it in a Formatter one still has the overhead of the whole logging pipeline. Couldn't that be problematic situations with many log calls?
