### ISSUE TITLE
"github.com/sirupsen/logrus/hooks/null"   removed  but readme not updated

### ISSUE THREAD

**Issue by galiri** [sirupsen/logrus#569]
the code example for testing  in the readme is for code that has been removed. FYI 

e.g  logger, hook := null.NewNullLogger()

**Comment by dmathieu** [comment]
Hey,

This logger is now available [here](https://github.com/sirupsen/logrus/blob/master/hooks/test/test.go#L43). So you need to require `github.com/sirupsen/logrus/hooks/test`, but it should still be working.

Note that the readme is requiring the proper package.
