### ISSUE TITLE
Rename back to Sirupsen/logrus

### ISSUE THREAD

**Issue by mcandre** [sirupsen/logrus#570]
Ay, a lot of projects are now broken after changing the casing of this project's git repository name. Docker/Moby, for example, can no longer be installed via glide, due to the Sirupsen/logrus 404.

**Comment by vearutop** [comment]
Yes, original rename was a perfect failure.

**Comment by elaijuh** [comment]
Any ETA? I was just gliding again and again and again

**Comment by vearutop** [comment]
@elaijuh adding lowercase package and `repo` to your `glide.yaml` may fix the problem
```
- package: github.com/sirupsen/logrus
  version: master
- package: github.com/Sirupsen/logrus
  repo: https://github.com/sirupsen/logrus.git
  version: 10f801ebc38b33738c9d17d50860f484a0988ff5
```

**Comment by elaijuh** [comment]
i was seeing this

`[ERROR]	Update failed for github.com/sirupsen/logrus: The Remote does not match the VCS endpoint`

**Comment by dobegor** [comment]
@vearutop it won't help if you are running OS with case-insensitive filesystem (macOS by default and Windows are).

**Comment by sirupsen** [comment]
See answer here https://github.com/sirupsen/logrus/issues/566#issuecomment-313932685 as well.

I feel powerless, guilty, and deeply ashamed. I have not worked enough with Go, and thus this decision was not taken with enough care. This is the root of why this has gone awry. At this point, a revert will make things worse. For the record, the original proposal was in this PR: https://github.com/sirupsen/logrus/pull/384. I am actively engaging now with prospective maintainers who can provide better stewardship of Logrus.

I hope, at least, this will serve a greater lesson to the Go community and never happen again. This was, unfortunately, bound to happen at some point that someone would be careless enough to do what was done here.

**Comment by VojtechVitek** [comment]
Ugh, I have big issues even with golang/dep

```
error while exporting github.com/sirupsen/logrus: /var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/.gitignore already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/.travis.yml already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/CHANGELOG.md already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/LICENSE already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/README.md already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/alt_exit.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/alt_exit_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/doc.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/entry.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/entry_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/examples/basic/basic.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/examples/hook/hook.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/exported.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/formatter.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/formatter_bench_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/hook_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/hooks.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/hooks/syslog/README.md already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/hooks/syslog/syslog.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/hooks/syslog/syslog_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/hooks/test/test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/hooks/test/test_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/json_formatter.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/json_formatter_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/logger.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/logger_bench_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/logrus.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/logrus_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/terminal_appengine.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/terminal_bsd.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/terminal_linux.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/terminal_notwindows.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/terminal_solaris.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/terminal_windows.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/text_formatter.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/text_formatter_test.go already exists, no checkout
/var/folders/hr/5zb8r0yx4sv4_1dc0rlccflm0000gn/T/dep105205437/github.com/sirupsen/logrus/writer.go already exists, no checkout
```

**Comment by bschwind** [comment]
@sirupsen Don't feel bad. If Go had a reasonable module system and an official package manager this likely wouldn't have been an issue at all. Most languages just don't have these kinds of issues.

**Comment by ledio** [comment]
ETA on the rename?  Already lost several hrs trying to "migrate" to the lowercase, but no luck so far...

**Comment by VojtechVitek** [comment]
@ledio there won't be any renaming back, see [this comment](https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276). 

Steps to fix your codebase:
- `rm -rf vendor/github.com/Sirupsen/logrus`
- `rm -rf $GOPATH/src/vendor/github.com/Sirupsen/logrus`
- Mass rename `"github.com/Sirupsen/logrus"` imports to `"github.com/sirupsen/logrus"` everywhere in you codebase (verify with `git grep "github.com/Sirupsen/logrus"`)
- `git commit` (this is important - git doesn't recognize upper->lower renames on Win/MacOS - you need to remove the directory first and commit it)
- fetch the new `github.com/sirupsen/logrus` vendor dependency using your dependency manager and `git add` it, `git commit`

Good luck!

**Comment by cstockton** [comment]
@dmathieu in case you never saw this thread- you should read through this and look at the timelines to understand the consequences of breaking import paths and the time it takes for them to fully propagate.

**Comment by sirupsen** [comment]
I'm closing this issue.

**Comment by mraxus** [comment]
Thanks for being honest and open with your decision @sirupsen. It's not easy being famous =-)

For my company, we have several projects and helper libs that uses this lib. We updated all the libs and projects from upper to lower. Then remove those projects from the go PATH (they'll just be reimported/downloaded when running `go get` again) and that solved it.

**Comment by richard-mauri** [comment]
I too am dealing with fallout from this issue.
I am trying to go (1.13.3) build gitlab.com/msvechla/vaultbeat with GO111MODULE=on
This project does not yet have a go.mod (I am trying to push this frontier)
It's unclear how to fix this.

go: gitlab.com/msvechla/vaultbeat imports
	github.com/elastic/beats/libbeat/cmd/instance imports
	github.com/elastic/beats/libbeat/autodiscover/providers/docker imports
	github.com/elastic/beats/libbeat/common/docker imports
	github.com/docker/docker/api imports
	github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus
