### ISSUE TITLE
Text-Formatter not Quoting non-string Values

### ISSUE THREAD

**Issue by seiffert** [sirupsen/logrus#582]
Hi,
I've noticed that all values that aren't `string`s or `error`s are written to the output buffer without any quoting. This causes issues when a value is e.g. a `time.Time` struct:

```
msg="..." updated_at=2017-07-12 14:24:59 +0000 UTC foo=bar
``` 

From such a log line, logfmt parsers extract fields like `"14:24:59": true` and `"+0000": true` and so on.

Currently, these values are written [like this](https://github.com/sirupsen/logrus/blob/10e5e38b53df0f5f80e72a929c01af6c84d7f847/text_formatter.go#L187): 

```go
fmt.Fprint(b, value)
```

My suggestion is to first string-encode the value using `fmt.Sprint` into a variable and then apply the regular and optional quoting. Will send a PR soon.

**Comment by dmathieu** [comment]
Good idea! It would also probably be a good opportunity to use `b.WriteString` and be consistent in that method.
