### ISSUE TITLE
Use logrus.Logger in httputil.ReverseProxy.ErrorLog ?

### ISSUE THREAD

**Issue by kedare** [sirupsen/logrus#588]
Hello,

I'm trying to use logrus as logger for httputil.ReverseProxy.

It's expecting a log.Logger type, I've been searching without success on how do to that.

Any hint ? Is there a way to get a log.Logger from logrus ?

You can see the type there : https://golang.org/pkg/net/http/httputil/#ReverseProxy

Thanks

**Comment by dmathieu** [comment]
Mathieu,

Unfortunately, I'm afraid this doesn't seem to be possible today.
`log.Logger` is a struct, not an interface. So it can't be anything else than an actual Go logger.

**Comment by kedare** [comment]
The best way to allow this would be to fix the ReverseProxy type to get an interface instead of the specific struct so ?

**Comment by dmathieu** [comment]
Basically, yes.

**Comment by kedare** [comment]
Thanks for the info, I published in issue on the Go repository if you want to follow that :)

**Comment by bartlettc22** [comment]
It's a workaround but you could accomplish this with your own standard logger that writes to logrus.  Something like:

```
type logrusErrorWriter struct{}

func (w logrusErrorWriter) Write(p []byte) (n int, err error) {
	logrus.Errorf("%s", string(p))
	return len(p), nil
}

func main() {
  director := func(req *http.Request) {
    req.URL.Host = "google.comxyz"
  }
  
  errorLogger := log.New(logrusErrorWriter{}, "", 0)
  proxy := httputil.ReverseProxy{
    Director: director,
    ErrorLog: errorLogger,
  }
  ...
}
```

Outputs
```
ERRO[0003] http: proxy error: dial tcp: lookup google.comxyz on 10.0.0.1:53: no such host
```
