### ISSUE TITLE
How to Load log config from file and output file,function,line number?

### ISSUE THREAD

**Issue by LiuYang1206** [sirupsen/logrus#590]
like seelog ,support rollingfile 
```
<seelog>
    <outputs formatid="main">
        <console/>
       <filter levels="debug,info,warn,error">
        <buffered size="10000" flushperiod="1000">
            <rollingfile type="date" filename="./logs/oauthshow.log" datepattern="2006.01.02" maxrolls="50"/>
        </buffered>
        </filter>
    </outputs>
    <formats>
        <format id="main" format="[%Level] %Time %Date %File[%Line]%FuncShort  %Msg %n"/>
    </formats>
</seelog>
```

**Comment by LiuYang1206** [comment]
Nicely color-coded And Field is awesome, i want to repalce seelog in some go projects

**Comment by dmathieu** [comment]
I'm afraid there is no internal way to load log config from xml. Frankly, that seems weird.

As for rolling your log files, there is no way to do this either. You'd have to implement this in your own package.
But that seems strange too. Your logs really shouldn't be sent to a file. How do you find a request among multiple servers if all logs are on the file system?
See https://12factor.net/logs
