### ISSUE TITLE
undefined: windows.Syscall

### ISSUE THREAD

**Issue by AndreKR** [sirupsen/logrus#599]
I'm on

> ```
> go version go1.8 windows/amd64
> ```
> 
and even just downloading logrus causes:
> ```
> src\github.com\sirupsen\logrus\terminal_windows.go:78: undefined: windows.Syscall
> ```

I'm pretty sure my Go installation is not modified and according to https://godoc.org/golang.org/x/sys/windows there is in fact no function `Syscall()` in `golang.org/x/sys/windows`. I don't understand where it's supposed to come from.

**Comment by AndreKR** [comment]
Seriously, I have no idea how this could ever have worked.

The same error happens on AppVeyor:
https://ci.appveyor.com/project/AndreKR/logrus/build/4

@sirupsen I prepared a PR with an `appveyor.yml`: https://github.com/sirupsen/logrus/pull/600. If you would sign in with your GitHub account on https://www.appveyor.com and simply add sirupsen/logrus as a project (no further settings necessary) we would have automated tests on Windows like we already have with Travis for Linux.

**Comment by AnotherGoogleFan** [comment]
Yes, I got the same problem as this issue.

**Comment by dmathieu** [comment]
Hum, yeah we removed the usage of `syscall` yesterday, and it seems I broke windows at the same time.
Thanks for the appveyor setup, it looks like a good idea.

**Comment by dmathieu** [comment]
Looks like the windows API is different from the unix one, when it was the same with syscall.
I don't have easy access to a windows machine. Do one of you want to try fixing this? It should just be updating `terminal_windows.go` to use the right method.

**Comment by michaelvlaar** [comment]
I've found a solution to fix this problem.

The package `golang.org/x/crypto/ssh/terminal` can be used to detect if the StdErr is a terminal. I'll send a PR to fix this problem in just a minute.

**Comment by levrik** [comment]
How to fix that temporarily? I'm not able to build a single Go project...

**Comment by AndreKR** [comment]
It's already fixed, update your dependencies.

**Comment by levrik** [comment]
@AndreKR Mhhh already did a `go get -u`. Will try again.
