### ISSUE TITLE
please do not use golang.org/x/sys

### ISSUE THREAD

**Issue by AnotherGoogleFan** [sirupsen/logrus#601]
Because of China GFW, it's very hard to go get anithing from golang.org/x/ .
So it's so hard for us who are in China to use logrus if import  golang.org/x/sys.
Old version without golang.org/x/sys works so ok, why need golang.org/x/sys?
We now have to use old version of logrus. So sad.

**Comment by dmathieu** [comment]
Going back to syslog means we wouldn't be able to get updates of the package, as it's deprecated.
Also, as much as I like china, I don't think technical decisions should be based on a single country's restrictions.

https://golang.org/pkg/syscall/

> NOTE: This package is locked down. Code outside the standard Go repository should be migrated to use the corresponding package in the golang.org/x/sys repository. That is also where updates required by new systems or versions should be applied. See https://golang.org/s/go1.4-syscall for more information.

**Comment by AnotherGoogleFan** [comment]
Yes, I see the reason now. Thanks for answering.
