### ISSUE TITLE
IsTerminal() being private breaks formatters

### ISSUE THREAD

**Issue by AndreKR** [sirupsen/logrus#607]
Since #604 was merged, `IsTerminal()` is no longer exported. This breaks (at least) the [`prefixed`](https://github.com/x-cray/logrus-prefixed-formatter) formatter.

> `src/github.com/x-cray/logrus-prefixed-formatter/formatter.go:147: undefined: logrus.IsTerminal`

At first I was going to open an issue with the formatter, but then I realized that it kind of makes sense for the logging framework to provide the formatter with the information whether it should format for a terminal.

**Comment by dmathieu** [comment]
IsTerminal, if it were still on this repository, would just be an alias to `terminal.IsTerminal`.
Copying it here therefore doesn't make a lot of sense anymore. Fixing that in the formatter would be the way to go.

**Comment by AndreKR** [comment]
Actually it's not just an alias because `terminal.IsTerminal()` only works with file descriptors. So the direct replacement for
```go
f.isTerminal = logrus.IsTerminal(entry.Logger.Out)
```
would be something like this:
```go
import "golang.org/x/crypto/ssh/terminal"

lo, ok := entry.Logger.Out.(*os.File)
if ok && terminal.IsTerminal(int(lo.Fd())) {
	f.isTerminal = true
}
```

However, this is less a question of convenience or breaking things but more a question of API.

If logrus recommends doing it with the above code, it implicitly makes the promise (assuming logrus intends to stop breaking builds with every other merge :stuck_out_tongue:) that `logrus.Entry.Logger.Out` will forever be an `*os.File`. We want to wrap it in a `bufio.Writer`? Too bad, we can't do that without breaking formatters again. It feels like forcing formatter authors to make assumptions about logrus internals.

Please consider this and let me know your opinion before I go around issuing PRs for formatters.

**Comment by AndreKR** [comment]
@sirupsen What's your opinion?
