### ISSUE TITLE
New lines are escaped now

### ISSUE THREAD

**Issue by pkopac** [sirupsen/logrus#608]
Hi!
With a recent update I've noticed that my debug data dumps in logs get fully escaped. Previously, I had _nicely formatted_ data `structs` in output (using [spew](https://github.com/davecgh/go-spew)`.Sdump`), so I could actually read them.

**Code:**
* data is a complex data structure with arrays, pointers, many custom types, optional fields etc.
`log.Debug(spew.Sdump(data))`

And now I get:
`(*pkg.Data)(0xc423e8cb00)({\n UUID: (string) \"\",\n Property:`...

I've browsed through recent updates, but can't find a way to turn this off other then fixing version of logrus to some previous one. Please advise. The data dumps are unreadable now.

**Comment by dmathieu** [comment]
This is probably because we hardened the string escaping with `%q` instead of the previous unsafe escaping.
See #580

I'm afraid there isn't much we can do here. This could actually be considered as a bug which has been fixed. Being able to send new lines in your log could make them harder to read, and actually reduce the purpose of structured logging, where you would only log specific meaningful fields not dump a whole json object.

**Comment by JelteF** [comment]
This makes sense when logging to a log file, but when logging for development this is really annoying. Stack traces that are logged are now unreadable.

**Comment by berniedurfee-ge** [comment]
Yes please on this one. Having a switch of some sort would be very nice.

**Comment by himanshug** [comment]
Another use case I have where I am printing json serialized objects in the debug logs. In the printed json, all double quotes are escaped too making it totally unreadable.

**Comment by reefbarman** [comment]
we have run into the need to print the stack traces in our logs as well and the removal of the new lines on stdout makes them very hard to read, is this going to be considered?

**Comment by hmalphettes** [comment]
For human consumption, I am using https://github.com/antonfisher/nested-logrus-formatter which does not escape the text content.

For example:
```
Mar 18 09:32:26.740 [INFO]  [Content:## Generated by my-tool
# Read the policy
path "sys/policies/acl/a-policy" {
  "capabilities" = [ "read" ]
}

path "secret/*" {
  "capabilities" = ["read","list"]
}
path "auth/token/create/a-role" {
  "capabilities" = ["update"]
  "denied_parameters" = {"*"=[]}
}
] [Environment:dev]
```

I hope this helps.

**Comment by nzt4567** [comment]
A switch would definitely be handy... 

For example LaTeX can use `\n` as a start of custom command very often which makes it quite hard to convert these escaped new lines back to, you know, just new lines. And debugging dynamically generated LaTeX templates without being able to actually look at the generated template is, you know, just sad.

**Comment by Koshmaar** [comment]
Another vote for being able to decide whether the log should escape or not-escape newlines. Come on, this is common sense.

**Comment by naughtyGitCat** [comment]
Why logrus keep line number and new line escape so unconvenient？ This is golang way?

**Comment by ParadiseDS** [comment]
Vote for an option to decide if newline should be escaped in log.
Newline is really more readable when log stack trace.

**Comment by freeformz** [comment]
To be clear everyone is asking for an option that produces this:

```
time="2009-11-10T23:00:00Z" level=info traceField=line 1
line 2
line 3 otherLogField=bar
```

^ assuming a trace that is:
```
line 1
line 2
line 3
```

**Comment by aido93** [comment]
I managed to do that approximately in this way:
```
    if log.GetLevel()==log.DebugLevel {
        strSlice:=strings.Split(str, "\n")
        for _, s := range strSlice {
            log.Debug(s)
        }
    }
```
It's not ideal solution but at least it works somehow... Also it will be called only in development when you set level to DebugLevel. I think there is no need to use debug messages in production. So no need to use multiline output in production. Hope, this code helps someone;)

**Comment by krasoffski** [comment]
Need ability to enable or disable such behavior and ability to configure striping/replacing new lines in message fields.

**Comment by nous23** [comment]
reasonale to enable newline...

**Comment by Frug** [comment]
For all kinds of local testing, this option would be extremely useful.

**Comment by mieubrisse** [comment]
Re-pinging on this to prevent it from getting closed. Right now, the only option that I can tell is `fmt.Fprintf(logrus.StandardLogger().Out, theStr)`

**Comment by bmon** [comment]
We solved this with a custom formatter that looks for traces in a specific field and appends them to the log. Replace `stack` with your field of choice.

```go
func TestMain(m *testing.M) {
        testLogger.SetLevel(logrus.WarnLevel)
        testLogger.SetFormatter(&StackFormatter{})
        os.Exit(m.Run())
}

type StackFormatter struct {
        logrus.TextFormatter
}

// Render a log entry with a TextFormatter - except if there is a `stack` field, print it (with newlines) after the log message.
func (f *StackFormatter) Format(entry *logrus.Entry) ([]byte, error) {
        stack, ok := entry.Data["stack"]
        if ok {
                delete(entry.Data, "stack")
        }
        res, err := f.TextFormatter.Format(entry)
        if stack, ok := stack.(string); ok && stack != "" {
                res = append(res, []byte("stack trace:\n"+stack)...)
        }
        return res, err
}
```

**Comment by krasoffski** [comment]
It is not stale!

**Comment by sunlintong** [comment]
same to me .俺也一样

**Comment by sunlintong** [comment]
I set `ForceColors` `true` to resolve this problem, BUT I don't know why
```go
logrus.SetFormatter(&logrus.TextFormatter{
    ForceColors: true,
})
```

**Comment by zyicy** [comment]
logger.SetFormatter(&logrus.TextFormatter{
    DisableQuote: true,
})
https://github.com/sirupsen/logrus/pull/1134/commits/c7455de10af6bbe2b2bdafee2cb682e813817ed2

**Comment by hdlinh1808** [comment]
> ```
> logger.SetFormatter(&logrus.TextFormatter{
>     DisableQuote: true,
> })
> ```
> 
> [c7455de](https://github.com/sirupsen/logrus/commit/c7455de10af6bbe2b2bdafee2cb682e813817ed2)

It's worked for me! Thanks

**Comment by dablelv** [comment]
为什么不提供一个开关，比如我把日志写入日志文件中，在查看日志的时候，换行缩进显示 JSON 格式的日志将更加可读。Why not provide a switch, for example I write the log to the log file, when viewing the log, it will be more readable to display the log in JSON format with newline indentation.
