### ISSUE TITLE
Log Keys of Structs

### ISSUE THREAD

**Issue by stevejarvis** [sirupsen/logrus#609]
This seems to have been implemented in #209, but since unimplemented. Was that intentional? (And if not, can we get struct keys back in the log when a struct is passed as a field?)

**Comment by oboote** [comment]
Agreed; I was quite surprised to find logs not replacing struct keys. Wasn't the format meant to be compatible with Printf format?

**Comment by chenjie4255** [comment]
+1
It is difficult to tell a field's value without field's name for now.

**Comment by jjjachyty** [comment]
+1
i want log my struct's keys & values

**Comment by Pokerkoffer** [comment]
any updates on this? Fields in the log would be awesome and restores a lot of context, especially with larger structs

**Comment by georgysavva** [comment]
Hi. Is there any update on this?
