### ISSUE TITLE
Failed to compile to windows

### ISSUE THREAD

**Issue by TechnicLab** [sirupsen/logrus#610]
Failed to compile to windows:

GOOS=windows GOARCH=386 go build <project_name>
\# github.com/sirupsen/logrus
../src/github.com/sirupsen/logrus/terminal_windows.go:78: undefined: windows.Syscall

**Comment by AndreKR** [comment]
Duplicate of https://github.com/sirupsen/logrus/issues/599 and already fixed a week ago. Please update your dependencies.

**Comment by TechnicLab** [comment]
I updated my dependencies and problem resolved. Strongly enough i wasn't able to find #599 on google.
