### ISSUE TITLE
Data race when adding hooks to non-default logger

### ISSUE THREAD

**Issue by ChimeraCoder** [sirupsen/logrus#611]
(Similar to #503)

`logrus.AddHook` uses a mutex to guard the standard logger, but when a new Logger is created with `logrus.New()`, there's no corresponding helper function or mutex to guard `Logger.Hooks`.

As a result, we're ending up with a data race in our tests, caused by one goroutine calling `log.Info` and another adding a new hook.

The simplest fix would be to add `func (*Logger) AddHook(hook Hook)` as a safe helper function, which would use an internal mutex to guard the Hooks slice. That doesn't prevent people from accessing `Logger.Hooks` unsafely, but it at least provides a way to write a provably race-free codepath for people who want to.

**Comment by ChimeraCoder** [comment]
I don't mind throwing something together in that shape, but please let me know first if that's the approach you'd like us to take here.

**Comment by dmathieu** [comment]
This will be close by #612. Thank you for the PR.
