### ISSUE TITLE
Incorrect panic msg during log.Panic()

### ISSUE THREAD

**Issue by mkorolyov** [sirupsen/logrus#615]
have:
```
panic: (*logrus.Entry) (0xddc300,0xc42019e700)
```
want
```
panic: some error happened.
```
where `some error happened` is msg that was logged.

**Comment by dmathieu** [comment]
I see you have pushed a fix to your fork. Do you want to add a test case and open a PR?

**Comment by mkorolyov** [comment]
Hi @dmathieu!
If sir @sirupsen will approve proposed solution, i will.

Also we can format original message with logrus Entry to print struct data too if needed.

**Comment by sirupsen** [comment]
@mkorolyov @dmathieu can accept your solution if you open a PR :)

**Comment by dmathieu** [comment]
All right, I've been looking a bit further into this, and your solution doesn't work because we expect an entry to be sent to panic.
https://github.com/sirupsen/logrus/blob/master/example_basic_test.go#L26

This seems to be so that you can recover from the panic and inspect the full entry.
Though I'd agree that panicking with a struct is weird. So I'd be tempted to say that we should always panic the formatted message, not the fully entry.

@seiffert any opinion?

**Comment by mkorolyov** [comment]
sorry guys for delay, leak of time, will add PR with formatted msg a little bit later

**Comment by mkorolyov** [comment]
@sirupsen Hey, could you pls take a look?

**Comment by dgsb** [comment]
Hello you have 2 PRs concerning this issue #742 and #623.
Which one shoudl I look at ?

**Comment by dgsb** [comment]
Ok it seems it is #742

**Comment by dgsb** [comment]
I wonder if this is what we really want to do, it will change the return  value of a `recover` call.

**Comment by dahu33** [comment]
Any update on this?  To me, it doesn't make any sense to pass a logrus Entry to a panic statement. Passing the Entry.Message would be much more meaningful and help debugging. Thanks!

**Comment by dgsb** [comment]
Making this change is an interface break regarding 1.0 api, we can't merge that lightly.
We can also argue that returning a string is better than returning the full entry which contains much more information.

**Comment by nhinds** [comment]
There is a potential middle ground, although it still breaks the current API: if `logrus.Entry` implemented `fmt.Stringer` by removing the `error` return value from its `String()` function then `panic()` would log the message as expected and people who wanted to recover and inspect the `Entry` object could still do so. Implementing `error` would also work, but that would require changing the `Error(...interface{})` function which is probably used more than `String() (string, error)`

I couldn't find any code calling the `String() (string, error)` function inside logrus, but it would still be a breaking change in case other people are calling it.
