### ISSUE TITLE
Different formatter being used

### ISSUE THREAD

**Issue by eberkund** [sirupsen/logrus#617]
I have an issue where in some instances logrus is using `TextFormatter` while in other cases it is using `JSONFormatter`. These calls are happening in different threads so maybe that is the issue but I thought this library was supposed to be thread safe? I did not see any references to the issue I am having in the documentation. Some of the calls are coming from HTTP request handlers if that makes any difference.

**Comment by dmathieu** [comment]
Could you provide us with a simple reproduction of the issue?

**Comment by eberkund** [comment]
I think it was a mistake on my end and I can no longer reproduce it.
