### ISSUE TITLE
when write to file, need to close by myself?

### ISSUE THREAD

**Issue by IIInsomnia** [sirupsen/logrus#619]
```go
file, err := os.OpenFile("logrus.log", os.O_CREATE|os.O_WRONLY, 0666)
if err == nil {
    log.Out = file
} else {
    log.Info("Failed to log to file, using default stderr")
}

logger.Info("hello world")
```

If need to close by myself, when I use log, it needs to open and close frequently in code.

**Comment by dmathieu** [comment]
Could you describe the actual issue you're facing here?
Having to close opened files yourself is a common Go pattern. You shouldn't need to open and close the file every time, just once when you configure the logger and when the program stops.
