### ISSUE TITLE
App Engine broken in v1 (regression)

### ISSUE THREAD

**Issue by ernestoalejo** [sirupsen/logrus#634]
Even if this library is not used directly inside App Engine it is in fact imported multiple times in dependencies we use. It was working previously since #310 added support for it until this commit: e66f22976feaed4e0a6ab43bc2b9226be8b0b979

The only thing standing in the way is `golang.org/x/crypto/ssh/terminal`, which imports `golang.org/x/sys/unix/bluetooth_linux.go` and fails. I refactored the method `checkIfTerminal` to a package private function to add build tags and it works now and tests pass successfully.

**Comment by josegonzalez** [comment]
This can be closed :)
