### ISSUE TITLE
Escape char printing for double quotes

### ISSUE THREAD

**Issue by nat-brown** [sirupsen/logrus#636]
I've been logging, using `WithFields` and `Printf`, strings containing double quotes `"`. The result prints the escape character no matter which format I use. Ex: `\"`, `\x22`, `\042`, etc.

I've searched my code for any sign that this was my doing, but the string looks correct up until the time I call my logger. Only my log file contains the escape character.

Example call: `l.Printf("this is a \" test")`
Example output: `time="2017-09-08T14:02:13-05:00" level=info msg="this is a \" test"`

I can see my request being potentially undesirable since the quotes can confuse machine readability as well as the human eye, but given that json is common and uses double quotes, I think an option to turn off the escape printing might be useful. Or changing the character used for wrapping values in the logger itself.

Regardless, I spent a considerable amount of time searching my own code because I didn't want to assume logrus was causing this "issue." If you think the current behavior is the best solution, it might be worth documenting. (The issue I'm opening now might suffice)

Thank you!

**Comment by RenathoAzevedo** [comment]
Yes, I had the same behavior. Any solution to this ?

**Comment by kirimori** [comment]
I've taken to the incredibly messy use of find/replace for `\"` to `"` when on my IDE. I may someday write a function that cleans up the logs at the end of every test run (these logs are for a test suite), but I haven't thought of a way to solve it in something continuous, like a server log. I still favor the idea of a toggle for the escape printing. 

Even a cleanup function is a terrible idea, imo. You have to list every character that would be escaped and hope it never changes. It's true that it's _unlikely_ to change, but this sort of fix is too clumsy to satisfy me.
