### ISSUE TITLE
JSONFormatter isn't handling functions as Field values

### ISSUE THREAD

**Issue by xandrewrampulla** [sirupsen/logrus#642]
When using the JSONFormatter, if I accidentally pass a function as a Field value, the entire log message is lost.  It would be better if only that one field was lost (even better would be to log that the field couldn't be translated into JSON properly).

Simple example code
```go
package main

import (
	log "github.com/sirupsen/logrus"
)

func myfun() string {
	return ""
}

func main() {

	log.SetFormatter(&log.JSONFormatter{})

	log.WithFields(log.Fields{
		"animal": "walrus",
		"myfunc": myfun,
	}).Info("A walrus appears")
}
```

Current output
```Failed to obtain reader, Failed to marshal fields to JSON, json: unsupported type: func() string```

**Comment by dgsb** [comment]
Indeed this is annoying

**Comment by dimatkach** [comment]
I am still seeing this issue. 

```
      import (
         log "github.com/sirupsen/logrus"
      )
      type Foo struct {
         foo func() string
      }


     func main() {
        foo :=  Foo {
          func () string { return "foo" }
         }
   
        log.SetFormatter(&log.JSONFormatter{})
        log.WithField("foo", foo).Info("Foo!")
      }
```

It looks like the PR referenced above only fixes the case where field _itself_ is a func, but if it is a struct that has a func field somewhere inside of it, there is still a problem. The solution either needs to be more involved, and go recursively inside each of the struct.

**Comment by linnaname** [comment]
I am still seeing this issue  in v1.7.0

Test Code:
`log.SetFormatter(&log.JSONFormatter{})`
 `req,_ := http.NewRequest("POST", "127.0.0.1",nil)`
`log.WithFields(log.Fields{
		"req":    req,
	}).Error("new request failed")`

Output:`Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: func() (io.ReadCloser, error)`

**Comment by oxzi** [comment]
Today I came across the same error for a struct which has a function as a field type. As a workaround, a tag can be added to the field, so that this is not taken into account for the JSON,  `json:"-"`.

**Comment by vishalkanaujia** [comment]
If you are logging HTTP request/response, use `httputil.DumpRequest`/ `httputil.DumpResponse`
