### ISSUE TITLE
add Log() methods to logger that take level as an argument

### ISSUE THREAD

**Issue by skriss** [sirupsen/logrus#646]
I'd like to add methods to the logger like the following:

```
func (logger *Logger) Log(level Level, args ...interface{}) { /* ... */ }

func (logger *Logger) Logf(level Level, format string, args ...interface{}) { /* ... */ }

func (logger *Logger) Logln(level Level, args ...interface{}) { /* ... */ }
```

to allow for easily setting the log-level of a statement at runtime. I envision these being implemented  on top of the existing API, i.e. as switches on the `level` with each case calling the appropriate underlying method. @dmathieu @sirupsen WDYT?

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
