### ISSUE TITLE
The newline characters in the log message are not processed correctly

### ISSUE THREAD

**Issue by ahrtr** [sirupsen/logrus#654]
When there are new line characters or any other special characters are in the log message, then they are just displayed as "\n" directly in the log file.  For example,
time="2017-10-23T17:22:27+08:00" level=warning msg="hello1,\nhello2,\nhello3"

It isn't what I want. The reason is that the new lines characters are escaped by the doube quote.  So I'd suggest to enhance the text_formatter so that the user can decide whether to wrap the log message in double quote or not. 

Another suggestion is add a configuration item for text_formatter to control the key fields(i.e., time, level, msg) as well, so that the user can decide whether to display the leading key fields or not.  For example, the above example would be displayed as below if the user disables the leading key fields,
2017-10-23T17:22:27+08:00 warning hello1,
hello2,
hello3

Actually I have already fixed it in my forked repository as below,
https://github.com/ahrtr/logrus

**Comment by jflyup** [comment]
This so called feature make me go back to std log.

**Comment by qinze118** [comment]
@ahrtr hello,I also encountered this problem.i'm try to use func Println,but not resolved.how to resolved  with you ?

**Comment by qinze118** [comment]
@ahrtr thanks!  I have solved the problem with your code

**Comment by reedwade** [comment]
For what it's worth, it would rate as a bug to me if the current behaviour were to change as it would make the logs unusable except by the humans.

**Comment by jinweizhiyuan** [comment]
> When there are new line characters or any other special characters are in the log message, then they are just displayed as "\n" directly in the log file. For example,
> time="2017-10-23T17:22:27+08:00" level=warning msg="hello1,\nhello2,\nhello3"
> 
> It isn't what I want. The reason is that the new lines characters are escaped by the doube quote. So I'd suggest to enhance the text_formatter so that the user can decide whether to wrap the log message in double quote or not.

How to solve this problem? Is there an example?

**Comment by linrl3** [comment]
Could you try using `DisableQuote` for your logger like this?
```
formatter := &logrus.TextFormatter{}
formatter.DisableQuote = true
logrus.SetFormatter(formatter)
```
It works for me.
