### ISSUE TITLE
why logrus use logrotate(8)  to  log rotation  ?

### ISSUE THREAD

**Issue by rfyiamcool** [sirupsen/logrus#655]
thank U.

**Comment by ahrtr** [comment]
You just need to implement the io.Writer interface,  and then call log.SetOutput(&yourWriter) to set your io.Writer to the log instance. 

I believe the following library is what you want, 
https://github.com/natefinch/lumberjack

**Comment by shlomi-nx** [comment]
I know this has been issue closed a while ago, but I wanted to ask what do you think of http://jdebp.eu./FGA/do-not-use-logrotate.html?

**Comment by rpajak-solarwinds** [comment]
I think that this recommendation is not valid for Windows. Can you confirm?

**Comment by dgsb** [comment]
@rpajak-solarwinds we currently lack of windows competency workforce at maintainer side, so it's going to be hard to answer on that one

**Comment by ZoeShaw101** [comment]
This will work 
```
	"gopkg.in/natefinch/lumberjack.v2"
...
	lumberjackLogger := &lumberjack.Logger{
		Filename:   filepath.ToSlash(operatorSysLogDir),
		MaxSize:    5, // MB
		MaxBackups: 10,
		MaxAge:     30,   // days
		Compress:   true,
	}
	logrus.SetOutput(io.MultiWriter(os.Stdout, lumberjackLogger))
```
