### ISSUE TITLE
DefaultTimestampFormat -> defaultTimestampFormat breaks API backward compatibility

### ISSUE THREAD

**Issue by morriswinkler** [sirupsen/logrus#659]
In 325575f18110626a8fd7f027f899aa8c8f5169c6 you unexported defaultTimestampFormat in formatter.go commenting that you fixed a linter suggestion. 

I know these damn linters, but sometimes you have to keep a strong opinion about your decisions. 

You eventually broke API backward compatibility.  I know of at least one program that suffered from that: github.com/toorop/tmail. Please fix that issue. 

I saw your comment on that PR, and there are two sides to that coin. If people use your code you should prevent breaking their stuff,  regardless if you like or dislike the outcome. 

Linters are not the source of all wisdom.

**Comment by kaedys** [comment]
Petty sure the golint complaint was just that it was an exported value without a comment.  The solution to that is to comment that value, _not_ to unexport a previously exported (and useful) value.

**Comment by dgsb** [comment]
@morriswinkler we have not been very good at doing semver until now, but we are trying to do better. Besides that, this issue is almost one year old with not so many complain. I think we can just move on instead of exporting again an internal constant. wdyt ?

**Comment by kaedys** [comment]
I feel like the cost of re-exporting it is essentially non-existent, no?

**Comment by totemcaf** [comment]
https://github.com/FactomProject/logrustash/releases/tag/0.7.0 is also broken.

**Comment by morriswinkler** [comment]
@dgsb look in 3 days I will have posted that issue one year ago, and since it is still going on. I will give you my 30 cents of personal opinion on the issue.

I personally don't really care if this constant is gone or not, I think golang developers should keep in mind that the original package design strategy was to build stable API's and keep them backward compatible. While the community has moved on and adapted versioning years ago, we still should uphold that goal. 

So please someone take a stand on that issue, either reexport it ( not for me by the way ) or just say you won't and close that issue.
