### ISSUE TITLE
How can I disable logger in test?

### ISSUE THREAD

**Issue by salvador-dali** [sirupsen/logrus#662]
Tried to use a logger in a particular package.
The problem is that when I test the package I get a lot of logs (which I do not need at all). 

Is there a way to disable logging completely in tests? I tried doing something like `logrus.SetLevel(logrus.PanicLevel)` in TestMain, but this only ignores tests below panic level. There is nothing that I have found above the panic level.

**Comment by adelowo** [comment]
```go
logger := logrus.New()
logger.Out = ioutil.Discard
```

**Comment by laverboy** [comment]
For future visitors to this page, like me, I had to to the follow instead:

```
log.SetOutput(ioutil.Discard)
```

**Comment by atz** [comment]
AKA:
```golang
logrus.SetOutput(ioutil.Discard)
```

**Comment by bl-ue** [comment]
@laverboy you should update your great answer with `go` after the opening triple-backtick like this:

      ```go
      logrus.SetOutput(ioutil.Discard)
      ```

**Comment by bl-ue** [comment]
@sirupsen any way we could add this to the readme?  Or make it a new part of the library?

**Comment by shalinlk** [comment]
This has now become 

`logrus.SetOutput(io.Discard)`

`ioutil.Discard` is from `1.16` onwards.
