### ISSUE TITLE
Trace log level

### ISSUE THREAD

**Issue by chackett** [sirupsen/logrus#663]
Hello

I am aware that this has been discussed before. It was also mentioned that Trace was not a common  requirement and this an edge case, further, it would confuse some people. I disagree that this is valid.

My use case is that I am working with a feed of financial data that if logged with Debug would be very verbose.

I would like to log with Trace and only enable Trace if I have a specific problem to find, for everything else, Debug would be fine.

Can we just add a Trace level. For those who don't understand it, just don't need to log to it :)

**Comment by Xiol** [comment]
I did open a [PR](https://github.com/sirupsen/logrus/pull/198) for this a while back and it was rejected.

**Comment by chackett** [comment]
That's unfortunate. Respectfully, the authors rebuttal is not valid - users not knowing how to use log levels effectively isn't a valid argument imho.

Your PR fizzled out.. maybe we should have another go at getting it through.

**Comment by Xiol** [comment]
Seems like someone else has [had a go](https://github.com/sirupsen/logrus/issues/629) more recently as well.

**Comment by dgsb** [comment]
Resolved by #844
