### ISSUE TITLE
How to split logs of different levels to different outputs? 

### ISSUE THREAD

**Issue by bunyk** [sirupsen/logrus#678]
I use logrus and I'm requested to to write info and debug log messages to stdout, and warning, errors fatals and panics to stderr. 

Currently I see no straightforward solutions for this, as `Logger` has only one `Out`. 

I was thinking about writing writer that parses log message and writes to `Stdout` or `Stderr` depending on it's level, but this could break when log formatter is changed.

So I changed my mind thinking about creating `"/dev/null" Writer`, and
```
log.SetOutput(NullWriter{}) // Send all logs to nowhere by default
```
Then write hooks that write logs to stderr and stdout, and register them for appropriate levels. ([Something like this](https://gist.github.com/bunyk/3042863340eeacfa3af9eed87efcec38))

Which lead me to the question why have both `Out` setting and `Hooks`? Hooks alone would be enough with default hook for stderr and possibility to delete and add another hooks. And if there was already hook for standart outputs, my task would be much simpler. (So this could be regarded as a feature request). 

Or what would developer of this library do to solve this?

**Comment by adelowo** [comment]
Quick now, you can use `ioutil.Discard` instead of writing your custom `NullWriter`

**Comment by gytisgreitai** [comment]
@bunyk have you solved this issue?

**Comment by bunyk** [comment]
@gytisgreitai Yes, like I described previously and with tip from @adelowo 

```golang
// WriterHook is a hook that writes logs of specified LogLevels to specified Writer
type WriterHook struct {
	Writer    io.Writer
	LogLevels []log.Level
}

// Fire will be called when some logging function is called with current hook
// It will format log entry to string and write it to appropriate writer
func (hook *WriterHook) Fire(entry *log.Entry) error {
	line, err := entry.String()
	if err != nil {
		return err
	}
	_, err = hook.Writer.Write([]byte(line))
	return err
}

// Levels define on which log levels this hook would trigger
func (hook *WriterHook) Levels() []log.Level {
	return hook.LogLevels
}

// setupLogs adds hooks to send logs to different destinations depending on level
func setupLogs() {
	log.SetOutput(ioutil.Discard) // Send all logs to nowhere by default

	log.AddHook(&WriterHook{ // Send logs with level higher than warning to stderr
		Writer: os.Stderr,
		LogLevels: []log.Level{
			log.PanicLevel,
			log.FatalLevel,
			log.ErrorLevel,
			log.WarnLevel,
		},
	})
	log.AddHook(&WriterHook{ // Send info and debug logs to stdout
		Writer: os.Stdout,
		LogLevels: []log.Level{
			log.InfoLevel,
			log.DebugLevel,
		},
	})
}
```

**Comment by FlorinAsavoaie** [comment]
Could you make a PR? I'd very much like to see this in the core too.

**Comment by bunyk** [comment]
@FlorinAsavoaie I could try, but don't know what @sirupsen will think about this.

**Comment by TennyZhuang** [comment]
Any update here? This feature is very useful

**Comment by bunyk** [comment]
Well, @TennyZhuang  I guess @sirupsen  could put hook described above somewhere to `hooks.go` (I'm not sure where should it be), so you could import it, but right now you could just copypaste that code to your logs configuration.

**Comment by dgsb** [comment]
@bunyk your hook seems practical and simple enough to add it in the core. This is a question which comes quite a lot here, so I think there is a real need here. If you have time to put that in a PR, I would happily merge it.

**Comment by gunnihinn** [comment]
This is funny, I implemented the same solution for the same problem in [another project](https://github.com/miku/metha/commit/7b020513d5a4eddd88391655dc0d1a64158c0409#diff-38d9fd06abc60989bcb1a974bbb35957) yesterday. (And _then_ came to the issue tracker to see if anyone else had better ideas. :/)

Does @bunyk want to create a PR with this? I'd love to drop what I wrote for an official solution.

**Comment by bunyk** [comment]
@gunnihinn @dgsb and everyone, thanks for kind words. :) I finally found some time, and did #924

Any comments, and edit suggestions are welcome, because I have not written in Go for more than 6 month's, so could forget some stuff.

**Comment by NguyenHoaiPhuong** [comment]
@bunyk : The hook does **NOT** work with Debug and Trace levels. Other levels seem fine.

**Comment by bunyk** [comment]
@NguyenHoaiPhuong Could you provide some tests to verify this?

**Comment by bunyk** [comment]
Fixed in https://github.com/sirupsen/logrus/pull/924

**Comment by vikaspushkar** [comment]
wrote a program to split logs into multiple files with multiple fields with lumberjack log ratation here https://github.com/vikaspushkar/logrusIndifferentFiles

**Comment by till** [comment]
I wanted to hide/route certain messages (based on level), so the user doesn't see the line via stdout but so that we can instead use them for troubleshooting. I don't know if this is super obvious, but I had expected that a hook takes over on the logline, but what happens instead is, that the log line is printed twice.

The example above helped me fix this, in other words, setting this on your logrus instance is very important:

```go
log.SetOutput(ioutil.Discard)
```

And then you need two hooks, and not just one.

Otherwise, the log line is printed/output twice.
