### ISSUE TITLE
Logrus logger stops logging and the service hangs when used with syslog hooks

### ISSUE THREAD

**Issue by rparulek** [sirupsen/logrus#683]
I am using golang version 1.8 and logrus package to log to local syslog on my system but I am seeing that after sometime logging stops and the service hangs. Is this a known issue? 

Here is my logger init method:
import (
        "encoding/json"
        "fmt"
        logger "github.com/Sirupsen/logrus"
        logrus_syslog "github.com/Sirupsen/logrus/hooks/syslog"
)

func init() {
            customFormatter := new(logTextFormatter)
            logger.SetFormatter(customFormatter)
            logger.SetLevel(supportedLogLevels[strings.ToLower(Config.LogLevel)])
            logger.SetOutput(ioutil.Discard)
            hook, _ := logrus_syslog.NewSyslogHook("", "", priority, "")
            logger.AddHook(hook)
}

Any pointers to fix this will be greatly appreciated?

**Comment by rparulek** [comment]
@sirupsen is this a known issue or there is something obviously wrong in my logger init?

**Comment by sirupsen** [comment]
Never heard of this before. What steps have you taken at debugging this?

**Comment by rparulek** [comment]
@sirupsen I am not sure on the debugging steps for this issue because this issue occurs very sporadically in 1 of 10 times and is not very consistent and hard to reproduce. In my monitoring service which uses logrus and syslog hooks to log to local syslog, it hangs forever in 1 of 10 deployments as mentioned above. Also, when I restart "rsyslog" service on my machine; my service starts running again and comes out of the hang state which is very weird. 

As a part of my monitoring service; I run a tight for infinite loop which runs every 1 second and makes some computations and reports the values to a remote web server. During this loop, I log info, error logs to local syslog which in turn logs to log file on my system. For logging to local syslog, I am using the hook as I pointed above. I have no channels or go routines as a part of my monitoring service; it is a plain for infinite loop with some function calls.

I found some post online https://www.reddit.com/r/golang/comments/6irpt1/is_there_a_golang_logging_library_around_that/ which says about an issue with logrus locking but not sure this is what I am hitting as well. 

My golang build version : 1.8

Any pointers in this context will be greatly appreciated! Many Thanks!

**Comment by mauricio** [comment]
Could be related to https://github.com/sirupsen/logrus/pull/695

**Comment by rparulek** [comment]
@mauricio @sirupsen Do we have a fix for #695 ? I am suspecting the same as the description on #695 matches exactly what I am seeing wherein my service seems deadlocked/hung.

Thanks for the pointers!

**Comment by mauricio** [comment]
@rparulek yes, my PR has a fix for the issue.

**Comment by mauricio** [comment]
Includes a test as well, if you run the test without the code fix it will deadlock.

**Comment by rparulek** [comment]
@mauricio Is this expected to be merged soon? Also, when the fix gets merged, should I be updating my vendor library to use "master" or a stable tag would be pulled off to include this fix?

Thanks!

**Comment by mauricio** [comment]
I don't know, that's up to @sirupsen .

**Comment by rparulek** [comment]
@sirupsen Can we merge @mauricio fix for the deadlock in logger issue stated above as we are seeing this in our production environments?

**Comment by mauricio** [comment]
@rparulek the fix was already merged.

**Comment by rparulek** [comment]
@sirupsen What specific version of logrus should we be using? Can we use master or some tag needs to be used for a stable version?

@mauricio I incorporated your fix locally in my vendor library for logrus, but my service still hangs in some situations while logging to rsyslog. Any particular logs that would help debug further?

Thanks!

**Comment by sirupsen** [comment]
sorry tagged a new version. v1.0.5 has this.

**Comment by gabiganam** [comment]
Hi,

I just updated to v1.0.5 and it seems that this change **introduced** a deadlock in my case.
I have a hook that writes a log itself, and it's hanging at the entry on the mutex within fireHooks() method.
