### ISSUE TITLE
Email notification subject

### ISSUE THREAD

**Issue by poldim** [sirupsen/logrus#684]
Can you set this as a variable?

**Comment by gguridi** [comment]
What do you mean? Logrus is not able to send email notifications by itself. Are you talking about a hook created by someone else that integrates with Logrus?

**Comment by poldim** [comment]
Yes, watchtower uses lights so I was trying to see if this is an option

**Comment by gguridi** [comment]
The [email hook in watchtower](https://github.com/v2tec/watchtower/blob/05513ddc1e2477ed811f1d94c30e505bf5c86e26/notifications/email.go) is not part of this repository. I'm afraid you will have to open an issue with them regarding how their hook works :S

**Comment by poldim** [comment]
Thanks.
