### ISSUE TITLE
Logrus struct tags for error objects

### ISSUE THREAD

**Issue by fallais** [sirupsen/logrus#686]
Hello,

It could be useful to use struct tags with Logrus. Let me explain.

For example, let's say I use this struct to return error with my API.

```go

type APIControllerResponse struct {
  ErrorID string `json:"error_id"`
  ErrorMessage string `json:"error_message"`
  ErrorDescription string `json:"error_description"`
}

In my API route, I sometimes return this kind of response.

data := protocols.APIControllerResponse{
  ErrorID: "WEATHER/GET/001",
  ErrorMessage: "Error when getting the weather",
  ErrorDescription: err.Error(),
}
```

I also want to use log it with Logrus, so I add this line : `logrus.Errorln("Error when getting the weather :", err)` in my code. I do not want to use the `WithFields` because it is sometimes too long.
But it could be great if I could use this : `logrus.WithStruct(data).Errorln("Error when getting the weather")`

The struct would be declared like this :

```go
type APIControllerResponse struct {
  ErrorID string `json:"error_id" logrus:"error_id"`
  ErrorMessage string `json:"error_message" logrus:"error_message"`
  ErrorDescription string `json:"error_description" logrus:"error_description"`
}
```

Then, this concept would introduce two things :
 - Struct tags for Logrus
 - WithStruct method (or something else)

What do you think ?
Regards.

**Comment by gguridi** [comment]
You can use an intermediary function to retrieve your struct data into log fields:

    func getFields(i interface{}) logrus.Fields {
        b, _ := json.Marshal(i)
        fields := logrus.Fields{}
        json.Unmarshal(b, &fields)
        return fields
    }

    logrus.WithFields(getFields(mystruct)).Info("Something happened")

There's also packages that do that for you. If you generate a map[string]interface{} logrus is not going to complain:

    import github.com/fatih/structs
    logrus.WithFields(structs.Map(mystruct)).Info("Something happened")

**Comment by fallais** [comment]
Hello, thanks a lot. That could do the job !
But I strongly think that my idea could be a great feature for Logrus.

**Comment by fallais** [comment]
But what if I need the exact property names as the JSON tags ?

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
