### ISSUE TITLE
[Question]: output to the STDOUT and File at the same time

### ISSUE THREAD

**Issue by Blogoslov** [sirupsen/logrus#689]
Could you please advise how I can write simultaneously to stdout and log file?
Is it possible? From the description, it is not obvious and I can't find correspondent method.

**Comment by RenathoAzevedo** [comment]
You should try io.MultiWriter

```
mw := io.MultiWriter(os.Stdout, logFile)
logrus.SetOutput(mw)
```

**Comment by Blogoslov** [comment]
Great, thank you very much!!!

**Comment by gibson** [comment]
please add to docs

**Comment by fser** [comment]
The issue is that you have to stick to the same formatter for both files... :(

**Comment by kramer65** [comment]
@fser - I solved having different formatters for stdout and the log file using this snippet: https://github.com/sirupsen/logrus/issues/784#issuecomment-403765306

**Comment by utdrmac** [comment]
@kramer65 How did you accomplish two different formatters using vanilla logrus? (ie: without rotatefilehook)
