### ISSUE TITLE
logrus.Info output different format messages not found black space

### ISSUE THREAD

**Issue by songlong** [sirupsen/logrus#694]
I found the output can not split by black space?
Excepted:  INFO[0000] Started observing beach 12.6 tttt 1111           animal=walrus number=8
output: 	INFO[0000] Started observing beach12.6tttt1111           animal=walrus number=8
       l := logrus.New()
	l.Formatter = new(logrus.Textormatter)
	l.Level = logrus.DebugLevel
	l.Out = os.Stdout
	l.WithFields(logrus.Fields{
		"animal": "walrus",
		"number": 8,
	}).Info("Started observing beach",12.6,"tttt",1111)

**Comment by gguridi** [comment]
You can specify your own message format, with spaces or other separator using the *f methods:

    ).Infof("Started observing beach %f %s %d", 12.6, "tttt", 1111)
