### ISSUE TITLE
Success logging level

### ISSUE THREAD

**Issue by shahidhk** [sirupsen/logrus#699]
For applications like CLI tools, Success is an important logging level, along with Info, Error, Debug and Fatal. I had to implement this using a custom formatter and fields. 

Is there an interest in adding success as a level? I can work on a PR quickly if this is of interest to the communinty.

**Comment by shahidhk** [comment]
Here is the PR: https://github.com/sirupsen/logrus/pull/705

**Comment by dgsb** [comment]
Would not be the Info level a perfect match for this usage ?

**Comment by shahidhk** [comment]
There is not much interest on creating a separate logging level for Success. Hence closing this.
