### ISSUE TITLE
Possibility to delete Hooks?

### ISSUE THREAD

**Issue by phoenix147** [sirupsen/logrus#701]
Hi!

First, thank you for this awesome logging library.

I've implemented my own hook for transmitting logging information via websockets.
This hook, which forwards the log messages into a channel, is only added, if the web application connects to the backend.

I think it would be best to close the channel and delete the hook after the connection is closed, but it seems this isn't implemented. Is this not necessary?
I tried to implement my own RemoveHook method, but since Hooks is a slice, it's rather difficult.

**Comment by jonmchan** [comment]
With the new ReplaceHooks syntax, here is how I went about removing a hook and putting it back in afterwards:

```
				newHooks := make(logrus.LevelHooks)
				for k,v := range logger.Hooks {
					for k2,v2 := range v {
						varType := fmt.Sprintf("%T", v2)

						if varType != "*YOURHOOKNAME" {
							newHooks[k] = append(newHooks[k], v2)
						} else {
							fmt.Printf("Excluding/Removing Hook - %v[%v]: %T\n", k, k2, v2)
						}
					}
				}

				originalHooks := logger.ReplaceHooks(newHooks)
				// Do operation without the hook
				logger.ReplaceHooks(originalHooks)
```

Figure the code might be useful for someone since it took me 15 minutes to come up with it... (or maybe I just am too rusty at golang :P)
