### ISSUE TITLE
Hooks can have data race with formatter when an entry has been created.

### ISSUE THREAD

**Issue by thundercat1** [sirupsen/logrus#703]
When using the default formatter along with hooks that modify entry.Data, you will get race conditions between your hook and [text formatter](https://github.com/sirupsen/logrus/blob/master/text_formatter.go#L137). This crops up if, for example, you create an Entry by attaching a context field to your logger, then pass that Entry into a series of goroutines.

Failing test & proposed fix: https://github.com/sirupsen/logrus/pull/702

**Comment by dgsb** [comment]
Fixed by #702
