### ISSUE TITLE
Who closes the file handler if i use file logger

### ISSUE THREAD

**Issue by paracha3** [sirupsen/logrus#706]
Sorry this is not an issue but rather a question. 
Just curious if i use the file logger (like the one below), does the library auto dispose file handle or do i have to explicity close it? 

```
file, err := os.OpenFile("logrus.log", os.O_CREATE|os.O_WRONLY, 0666)
if err == nil {
    log.Out = file
} else {
    log.Info("Failed to log to file, using default stderr")
}
```

**Comment by paracha3** [comment]
Ops i just saw the following. I guess this should take care of closing file handle.

```
func writerFinalizer(writer *io.PipeWriter) {
	writer.Close()
}
```

**Comment by dgsb** [comment]
This Close is not applied to the Out field of the logger. You should close the file after the associated logger has been released.
