### ISSUE TITLE
Unable to use test.NewLocal in vendored environment

### ISSUE THREAD

**Issue by decibel** [sirupsen/logrus#714]
Go has issues with vendored package references (details below). I suspect that passing in an interface that's equivalent to `Logger` would solve this issue. There's other reasons it'd be nice to have interfaces as well (in my case, I'd like to be able to expose only some `Logger` methods; having decomposed interfaces would make that trivial to do).

Unfortunately, this could not be a drop-in replacement for `Logger` as it exists today, since the public members of `Logger` (`Out`, `Hooks`, etc) would need to become accessor functions.

**Details of problem**
I was trying to do what (on the surface) looks simple:

```
var testLog, hook = func() (*logrus.Logger, *test.Hook) {
                // This is essentially what test.NewNullLogger does, but this way you can
                // leave it recording to stdout for easier debugging.
                var log *logrus.Logger = logrus.New()
                //log.Out=ioutil.Discard
                return log, test.NewLocal(log)
}()
```

That results is this error:

`cannot use log (type *"<my package>/vendor/github.com/sirupsen/logrus".Logger) as type *"github.com/sirupsen/logrus".Logger in argument to test.NewLocal`

more info about the details of that is available [here](https://stackoverflow.com/questions/38091816/packages-type-cannot-be-used-as-the-vendored-packages-type) and [here](https://www.reddit.com/r/golang/comments/49w33f/how_do_you_handle_vendoring_in_libraries/).

**Comment by stevvooe** [comment]
Moving to an interface won't actually solve this problem. The proposed solution would also introduce a massive compatibility break, so I am not sure that it is tenable.

The problem here is that there are two logrus packages visible in the GOPATH. The trick to fixing this is to removing the vendored items from the dependency and move them to the vendored folder of binary target or bring them into GOPATH.

**Comment by decibel** [comment]
Do you have an example of what you mean by "move them to the vendored folder of binary target"?

Simply moving this to GOPATH isn't a viable option; we can't control that in a cloud foundry deployment, so vendoring is our only option.

BTW, this is actually much worse than I originally reported. Even trying to manually do the equivalent of what test.NewLocal does results in an error, because new(test.Hook) doesn't satisfy the interface, since it's methods are using non-vendored types.
