### ISSUE TITLE
Modify/Remove Hook

### ISSUE THREAD

**Issue by sanbornm** [sirupsen/logrus#715]
How do you modify or remove a hook during runtime?

**Comment by tubocurarin** [comment]
Browsing the codebase I couldn't see something that allows to remove or even modify them. But I would like to see that feature too, especially good for proper test-hook cleanup. :+1:

**Comment by phoenix147** [comment]
i'd also like to see this feature to remove hooks during runtime, see #701

**Comment by robertomoutinho** [comment]
+1 for that idea ...
Would be awesome to be able to reload a hook (change its config) without having to restart the application.

**Comment by phoenix147** [comment]
Since there is no easy way to add this without breaking the api, i ended up using a logger instance instead of the package level logger and if a restart is needed, i just recreate it and add needed hooks again.

**Comment by betrok** [comment]
Related(somewhat) pull request: #782
With exposed lock it will be possible to safely modify the Hooks slice.

**Comment by artheus** [comment]
I am writing some unit tests, and I found this method to be useful. Though not a very efficient one if you want to use it in production runtime..

```golang
type LogHook struct {
	enabled bool
	entries []*logrus.Entry
}

func (h *LogHook) Clear() {
	h.entries = []*logrus.Entry{}
}

func (h *LogHook) GetEntries() []*logrus.Entry {
	return h.entries
}

func (h *LogHook) Levels() []logrus.Level {
	return []logrus.Level{logrus.ErrorLevel}
}

func (h *LogHook) Fire(entry *logrus.Entry) error {
	if h.enabled == false {
		return nil
	}

	h.entries = append(h.entries, entry)
	return nil
}

// Make sure hook implements the logrus.Hook interface
var _ logrus.Hook = (*LogHook)(nil)

var logHook *LogHook

func enableLogHook() {
	if logHook == nil {
		logHook = &LogHook{enabled: true}
		logrus.AddHook(logHook)
	}

	logHook.Clear()
}

func getLogHookEntries() []*logrus.Entry {
	if logHook == nil {
		return nil
	}

	return logHook.GetEntries()
}

func disableLogHook() {
	if logHook == nil {
		return
	}

	logHook.enabled = false
}
```
