### ISSUE TITLE
Make logrus.Level implement TextMarshaller and TextUnmarshaller

### ISSUE THREAD

**Issue by nicpottier** [sirupsen/logrus#724]
A small nicety that would allow TOML configuration file that specify logging levels to use a real `logrus.Level` value and automatically get validation that the file is using a proper level. (and saving the user the need to call `ParseLevel` and deal with errors etc..)

Happy to open a PR if it would be accepted, tiny change.

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
