### ISSUE TITLE
Is logrus capable of logging async?

### ISSUE THREAD

**Issue by renathoaz** [sirupsen/logrus#725]
If so, how can I achieve that?

**Comment by gguridi** [comment]
I think currently Logrus doesn't support async logging.

Some hooks, however, have implemented their own version. You can create your own hook based on the [logrus-graylog-hook](https://github.com/gemnasium/logrus-graylog-hook#user-content-asynchronous-logger) for further information.

PS.- If additionally you would like the standard error output to be async as well then the solution gets more complicated.

**Comment by dgsb** [comment]
@RenathoAzevedo did the previous comments answer your question ?

**Comment by raidancampbell** [comment]
> What are the perceived benefits of async logging? What are the use cases for async logging?

Perceived benefit is avoiding the performance penalty from synchronous logging due to IO bottlenecks or any internal computation (i.e. when `SetReportCaller` is set to true)

Use case: I have an application serving very bursty traffic.  To lower the work on the main thread and increase performance, I would like to log asynchronously.

I agree that it's solvable with a wrapper over the logger, but I think it's too valuable to omit from logrus

**Comment by madflojo** [comment]
As commented above the primary benefit is reducing time taken per transaction/request. It’s not uncommon for a service to log messages for each request to a service. When using synchronous logging the time taken to perform the I/O operations are included in the response time.

If using asynchronous logging applications can reply back to a request while the I/O operations happen in the background.

This is a very common practice in high volume and low latency applications.

My primary question is. Is this something that the maintainers have specifically chosen not to do, or is there appetite but it just hasn’t been contributed yet?

**Comment by freeformz** [comment]
I know from *experience* that async APIs are hard to support well and often come with a set of trades offs that end up surprising users of them, so it's not something I'm *personally* interested in adding. That doesn't mean these use cases are invalid or bad either, just that I'm not personally convinced the trade off is worth it. Maybe one of the other maintainers are though.

I'd wager, but can't prove, that the time spent logging is minuscule compared to the time spent communicating with network services like down stream APIs and/or databases.

That doesn't mean it's not a problem for certain types of applications, but there are ways to deal with at least *some* of that already. For instance "async logging" is possible *now* by making a Hook that takes a *copy* of the entry and processes it in an async fashion. We have at least one instances of such a hook in use inside of Heroku (if I'm not mistaken).
