### ISSUE TITLE
How to using log.Info("%s", s) like?

### ISSUE THREAD

**Issue by jinfagang** [sirupsen/logrus#727]
Thanks for this lib, I have a simple question:

```
How to using log.Info("%s", s) like?
```
Does logrus provide this?

**Comment by adelowo** [comment]
Use `Infof` instead

**Comment by dgsb** [comment]
@jinfagang, you can use Infof or any other <Level>f method but the recommended way is to add a field to your entry.
```
logrus.WithField("fieldname", value).Info("my trace")
```
