### ISSUE TITLE
Feature request: discard logger

### ISSUE THREAD

**Issue by jawnsy** [sirupsen/logrus#731]
Hey there,

Thanks for this great library :smile:

My apologies if this was considered and rejected before - I searched the issues but didn't find anything. I wanted to suggest the addition of a new constructor that could create a dummy logger that would discard all logs.

For example, something like:

```go
func Discard() *Logger {
	l := New()
	l.Out = ioutil.Discard
	l.Level = PanicLevel
}
```

Then consuming code could have a reasonable default, e.g.:

```go
logger := logrus.Discard()
if wantLogs {
	logger = logrus.New()
}
```

An alternative is to provide a dummy implementation of `logrus.FieldLogger`, which would probably perform better since it doesn't have to do anything with the input values. It's a small convenience but I think it would be useful to others. These solutions are similar to, but more straightforward than, the suggestion in https://github.com/sirupsen/logrus/issues/662. 

I'm happy to contribute this, but would need some guidance implementing it.

Cheers,

Jonathan

**Comment by gguridi** [comment]
Not sure why the suggestion in [#662](https://github.com/sirupsen/logrus/issues/662) is not enough. I really can't see the value of adding a new constructor in the library when you can do easily:

    logger := logrus.New()
    if !wantLogs {
        logger.Out = ioutil.Discard
    }

**Comment by dgsb** [comment]
Indeed this is quite easy to discard all traces this way, I don't think we need this added constructor
