### ISSUE TITLE
Why not put level, time, message into data fields

### ISSUE THREAD

**Issue by HuKeping** [sirupsen/logrus#734]
Since we will output the key-value pair in `Fields`,  why not put `Message`, `Level` and `Time` into it?

```
type Entry struct {
        Logger *Logger

        // Contains all the fields set by the user.
        Data Fields

        // Time at which the log entry was created
        Time time.Time

        // Level the log entry was logged at: Debug, Info, Warn, Error, Fatal or Panic
        // This field will be set on entry firing and the value will be equal to the one in Logger struct field.
        Level Level

        // Message passed to Debug, Info, Warn, Error, Fatal or Panic
        Message string

        // When formatter is called in entry.log(), an Buffer may be set to entry
        Buffer *bytes.Buffer
}

```

**Comment by gguridi** [comment]
I think `Fields` is intended to store all the fields set by the user. 

However, `Time` is set when the log entry was created automatically, `Level` is specified depending on the method that was called and `Message` is a mandatory string. For me makes sense to separate those three from pure user-defined fields that can be different from one entry to another. When creating a new formatter it's easier to identify the mandatory fields and the custom ones.

But overall I think it was just the approach the developer wanted to follow. Maybe changing it now could potentially break hooks created by third-party developers.

**Comment by HuKeping** [comment]
> For me makes sense to separate those three from pure user-defined fields that can be different from one entry to another. 

It make sense, thanks @gguridi !
