### ISSUE TITLE
Feature Request: batch logging

### ISSUE THREAD

**Issue by skaldesh** [sirupsen/logrus#736]
I would like to know if someone has had the same idea already and what you think of it.  

Image you are running a standard REST API and you want to log some stuff during every request handling. (Let's say, the type of request, the execution time of different parts of the request, the status code, etc. etc.)  
Now, when only 1 request is handled at the same time, the log is coherent and all messages are in sequential order.  
But as soon as we handle multiple requests at the same time, the log messages are written concurrently into the log and get mixed up.  

Now, you could save every log message yourself in the handler in some sort of buffer and print the whole buffer when the request handler is done with its work. But it would be neat if the logger would take care of that and allowed to start a batch log that handles all of this.  

Some pseudocode:  
```go
batchId := log.StartBatchlog()
defer log.WriteBatch(batchId)
...
log.DebugB("incoming Test request", batchId)
...
log.WithFields({"executionTime": time}).DebugB("time for test db func", batchId)
```

What you guys think of this? Is something already there that can do this? Or shouldn't this be a part of the application logger? Let me know

**Comment by dgsb** [comment]
The usual way to gather traces together is to use a field with a unique identifier for a given request.

**Comment by skaldesh** [comment]
@dgsb that would work, but I would like it more if I look into my log file and find all the traces in one consecutive block to avoid jumping around in the logfile.  
Furthermore, this would make it possible to improve performance, since one would delay the writing of logs until the very moment the whole batch should be written. This is likely a place where a request has been handled, or an error occurred (sticking with my server example here)

**Comment by dgsb** [comment]
There are no one size fits all, solution regarding log ordering. this is what structured logging is about, it allows to perform clever filtering/sorting based on the contents of fields.
I'm kind of reluctant to add a new API just to solve a too narrow use case.

**Comment by theaog** [comment]
@skaldesh did you pursue your batch logging idea further after the maintainer rejection?

I'm interested to use batch logging too.

**Comment by skaldesh** [comment]
No, I quit using logrus, but for different reasons
