### ISSUE TITLE
TestLoggingWithHooksRace

### ISSUE THREAD

**Issue by Charleslvn** [sirupsen/logrus#740]
With:
go1.10 linux/amd64
github.com/sirupsen/logrus 1.0.5

Hello,
I try to build and test your project and it fails with :

> Testing: "/builddir/build/BUILD/logrus-1.0.5/_build/src/github.com/sirupsen/logrus/hooks/test"
> + GOPATH=/builddir/build/BUILD/logrus-1.0.5/_build:/usr/share/gocode
> + go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro  '\'''
> time="2018-03-28T00:47:38+02:00" level=error msg="Hello error"
> --- FAIL: TestLoggingWithHooksRace (0.00s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
>   panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5581b42b383d]
> 
> goroutine 6 [running]:
> testing.tRunner.func1(0xc42011e3c0)
>   /usr/lib/golang/src/testing/testing.go:742 +0x29f
> panic(0x5581b456eb40, 0x5581b46d4b50)
>   /usr/lib/golang/src/runtime/panic.go:505 +0x22d
> github.com/sirupsen/logrus/hooks/test.TestLoggingWithHooksRace(0xc42011e3c0)
>   /builddir/build/BUILD/logrus-1.0.5/_build/src/github.com/sirupsen/logrus/hooks/test/test_test.go:54 +0xed
> testing.tRunner(0xc42011e3c0, 0x5581b45c2b38)
>   /usr/lib/golang/src/testing/testing.go:777 +0xd2
> created by testing.(*T).Run
>   /usr/lib/golang/src/testing/testing.go:824 +0x2e2
> exit status 2
> FAIL  github.com/sirupsen/logrus/hooks/test 0.013s
> 

Could you help me please ?

Thanks

**Comment by gguridi** [comment]
If you installed go from the ubuntu repository or from the [official ones](https://github.com/golang/go/wiki/Ubuntu), none of them contain the files needed to check race conditions.

If you want to build and test it, the only solution is to reinstall go from the official downloads page https://golang.org/dl/

**Comment by jcajka** [comment]
For the record, I have been able to reproduce this issue on Fedora 28/29 with go1.10. Also I have observed that if you drop the hardening ld flags(relro&co) the issue goes away. That makes me think that this is issue somewhere in between Go and ld.
@Charleslvn Could you please test that removing the hardening flags makes the issue go away for you?

**Comment by dgsb** [comment]
It seems I've duplicated this issue in #751. No big issue, it was an incorrect use of wait group in the test itself. The fix is in #752 waiting to be merged.

**Comment by anthonyfok** [comment]
@dgsb, thank you for the fix!  We were seeing the same problem in Debian autopkgtest, see https://ci.debian.net/data/autopkgtest/testing/amd64/g/golang-logrus/319614/log.gz
and so I conveniently cherry-picked your fix in #752.

@sirupsen You may probably close this issue too.  :-)
