### ISSUE TITLE
WithFields - Spaces after log message

### ISSUE THREAD

**Issue by inzanez** [sirupsen/logrus#747]
Hi

I'm trying to use the 'WithFields' function to supply fields to the log messages. Somehow this introduces additional spaces after the actual log message ('msg'):
```go
log.WithFields(log.Fields {
    "test": "something"}).Error("DataExchangeClient could not connect server")
```
Which results in:
>ERRO[0000] DataExchangeClient could not connect server   test=something

There are 3 whitespaces after 'server'. Looking at other messages there are even more whitespaces. Is there a reason for this? I didn't find any hint in the documentation...

Regards

**Comment by nianglao** [comment]
Hi @inzanez ,

Logrus default logger "std" use TextFormatter. When output to terminal, TextFormatter will call printColored function in text_formatter.go.
`
fmt.Fprintf(b, "\x1b[%dm%s\x1b[0m[%04d] %-44s ", levelColor, levelText, int(entry.Time.Sub(baseTimestamp)/time.Second), entry.Message)
`
"%-44s" explains your issue.

**Comment by inzanez** [comment]
@nianglao
Perfect, many thanks for that detailed answer! I will take a closer look at that!

**Comment by slashtechno** [comment]
Is there a way to fix this?
