### ISSUE TITLE
release 1.0.5 missing DisableLevelTruncation from text_formatter.go

### ISSUE THREAD

**Issue by jmrodri** [sirupsen/logrus#757]
Release 1.0.5 (and 1.0.4) do not have the `DisableLevelTruncation` attribute in `TextFormatter`. This field was added back in 2016.

Here is the line in master:
https://github.com/sirupsen/logrus/blob/master/text_formatter.go#L56

Notice in the v1.0.5 version of text_formatter.go there it is gone:
https://github.com/sirupsen/logrus/blob/v1.0.5/text_formatter.go#L29-L60

**Comment by dgsb** [comment]
v1.0.6 has been released and contains the required feature
