### ISSUE TITLE
logs are sent through closed hook

### ISSUE THREAD

**Issue by David-hod** [sirupsen/logrus#759]
we have a hook to stackdriver hook: https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/logging
We create logger per request by design!.
since logrus asynchronously. if we write a log and then close the hook (i.e stackdriver client). logrus will try to send the message to the hook while it is closed which means we will not see the log on stackdriver and get an error for writing to a closed channel.

consider this code: 

```
  hook:=CreateHook(...)
  log := logrus.New()
  log.Hooks.Add(hook)
  log.Info("hello world")
  hook.Close()

```
This is a severity A bug! 
There is also no mechanism to flush the log

**Comment by David-hod** [comment]
the issue is in the hook... nevermind

**Comment by dgsb** [comment]
@David-hod did you solve your issue ? Can we close this one ?
