### ISSUE TITLE
How do i know the error information when log to file failure

### ISSUE THREAD

**Issue by MrSong0607** [sirupsen/logrus#760]
when i set the logrus out with a file,and if i close the file,log will fail with "Failed to write to log, write somefile.log: file already closed".
but how can i get the error when logrus write failure,is there have a way like below:
```
if err := logrus.Error("some err");err!=nil{
    //do something
}
```

**Comment by dgsb** [comment]
There are no errors returned from the top level api. If you have an error writer on the out writer a trace on stdout will be issued. You should not close the out file associated with a Logger.

**Comment by MrSong0607** [comment]
in some situation,i need to close the log file,such as i open one log file for each user,i should close the log file when a user's operation done

**Comment by MrSong0607** [comment]
i know i can do it this way , but since there have a error in log function,why not return this error

**Comment by dgsb** [comment]
logrus initially try to keep a compatible interface with the standard log package which does not return error code either. Most of traces also happen while handling, adding an error handling in an error code branch may add too much complexity.
Also I don't see any good reason to handle an error which can be totally avoided.

**Comment by MrSong0607** [comment]
ok,thank you
