### ISSUE TITLE
Default logging format different across architectures

### ISSUE THREAD

**Issue by wsw70** [sirupsen/logrus#763]
`log.Debug("connection OK")` outputs 

- `DEBU[0000] connection OK` when compiled on or for Linux/amd64
- `time="2018-05-30T09:38:26+02:00" level=debug msg="connection OK"` when compiled on Windows 10

Is a different default behaviour between systems for the same code something expected?

(apologies if this is obvious - I am just starting with Go, coming from Python and JS)

**Comment by lepinkainen** [comment]
logrus is not detecting a TTY on Windows, so it defaults to TextFormatter.

**Comment by dgsb** [comment]
@wsw70 would you mind to try that again with a more recent version of logrus (v1.1.0) ? We have recently merged some improvement regarding terminal management on windows.

**Comment by jtnord** [comment]
seen this on the jenkins-x project with logrus 1.4.1

**Comment by jtnord** [comment]
[`this conditional`](https://github.com/sirupsen/logrus/blob/9b3cdde74fbe9443d704467498a7dcb61a79de9b/text_formatter.go#L95) just says screw windows regardless :)

**Comment by cup** [comment]
https://github.com/sirupsen/logrus/issues/306
https://github.com/sirupsen/logrus/issues/379

https://github.com/sirupsen/logrus/issues/763

**Comment by cup** [comment]
It looks like other packages solve this problem with:

https://github.com/mattn/go-isatty

Example:

https://github.com/labstack/gommon/blob/82ef680a/color/color.go#L10

**Comment by cup** [comment]
https://github.com/sirupsen/logrus/pull/957

**Comment by dgsb** [comment]
@wsw70 you may also want to use a JSONFormatter which will valid json for each trace.

**Comment by alex-yust** [comment]
Not only is the default format different across architectures, a Linux worker on Azure Pipelines (Ubuntu 16.04) also outputs JSON by default 8(
May be the reason to this is related to the fact that 'docker login' reports the worker's shell as 'non tty'.

**Comment by arxeiss** [comment]
I think it is related to colors as well.

```
var log = logrus.New()
log.Formatter = &logrus.TextFormatter{
	DisableColors: true,
}
log.Out = os.Stdout

log.Error("Starting the server")
```

Output: `time="2020-10-21T14:14:07+02:00" level=error msg="Starting the server"`

When I comment out the DisableColors
```diff
- 	DisableColors: true,
+ 	// DisableColors: true,
```

Output is: `ERRO[0000] Starting the server` and ERRO is in red color. 
![image](https://user-images.githubusercontent.com/5103109/96718299-17d1f000-13a8-11eb-8bc2-3d0d12b8e1d0.png)

**Comment by matteocontrini** [comment]
Still an issue actually.
