### ISSUE TITLE
About github.com/heirko/go-contrib/logrusHelper dependence

### ISSUE THREAD

**Issue by spiderpoison** [sirupsen/logrus#766]
Why "github.com/heirko/go-contrib/logrusHelper" depends "github.com/heralight/logrus_mate", but not the "github.com/gogap/logrus_mate"?

now i have duplicate logrus_mate, "github.com/heralight/logrus_mate" and "github.com/gogap/logrus_mate". I am confused

**Comment by dgsb** [comment]
Hello @spiderpoison, it seems one is a fork of the other. I don't know why they did switch the dependancy to the forked one. In order to have further information, I suggest you to open an issue in their repository.
