### ISSUE TITLE
I want to change sequence of msg and keys, what should i do?

### ISSUE THREAD

**Issue by spiderpoison** [sirupsen/logrus#767]
TextFormatter will print msg firstly, then print keys.
![default](https://user-images.githubusercontent.com/7857870/41293354-a087c668-6e87-11e8-8e11-25d80a705565.png)

But i want to print keys firstly, what I can do?

**Comment by dgsb** [comment]
Beyond writing you own Formatter there is not much you can do there. You could embed the TextFormatter in your own formatter and just rewrite the Format method

**Comment by dgsb** [comment]
We could solve this issue by implementing #770

**Comment by spiderpoison** [comment]
ok, thanks
