### ISSUE TITLE
How to send logs to elasticsearch?

### ISSUE THREAD

**Issue by wjzhangcsu** [sirupsen/logrus#768]
I want to send logs to elasticsearch. I have attempted to use sohlich/elogrus,but it do not work really.Is there a way to send logs to elasticsearch?

**Comment by bhouse1273** [comment]
You might try https://github.com/tsaikd/gogstash

**Comment by messias72** [comment]
Or if you want to use logrus try this: github.com/interactive-solutions/go-logrus-elasticsearch

**Comment by dgsb** [comment]
You can find a list of hooks which are usable with logrus. There is one to send data to ElasticSearch.
https://github.com/sirupsen/logrus/wiki/Hooks

**Comment by a-h** [comment]
Another approach is to log to stdout or a file and use a standalone log collector to forward the logs on. 

Logstash is commonly used with ElasticSearch, or you could use https://github.com/agnivade/funnel or many other tools.

**Comment by dgsb** [comment]
@wjzhangcsu did you try the logstash hook mentioned in the hooks page ?

**Comment by rmartinus** [comment]
There are a few ways of doing this depending on your setup:
- Use GELF to log to Logstash: https://github.com/Graylog2/go-gelf
- If you use Kubernetes you can use Filebeat: https://www.elastic.co/blog/shipping-kubernetes-logs-to-elasticsearch-with-filebeat
- If you have AWS Lambda, use Functionbeat: https://www.elastic.co/guide/en/beats/functionbeat/

**Comment by wuriyanto48** [comment]
you might want to try this one, https://github.com/telkomdev/go-stash,
this is example with logrus https://github.com/telkomdev/go-stash/blob/master/_example/logrus/main.go

**Comment by ashishtiwari1993** [comment]
Hi, 

You can refer this article https://ashish.one/blogs/shipping-golang-logs-with-elkb-stack/

Writ your logs in JSON format and then ship your logs on Elasticsearch with the help of Filebeat.

**Comment by VictoWork** [comment]
I was using https://github.com/interactive-solutions/go-logrus-elasticsearch now I cant find this in git
