### ISSUE TITLE
Add a custom key sorting function to the TextFormatter

### ISSUE THREAD

**Issue by dgsb** [sirupsen/logrus#770]
Several already have asked for specific position for msg or timestamp in the TextFormatter with respect to the key position. Adding the possibility to give a custom comparison function to sort the keys would allow users to place the way they want any keys in the formatted output.

**Comment by maeglindeveloper** [comment]
@dgsb : Is this feature already in dev, will it be release soon ? :) 
Thanks in advance ! 👍

**Comment by dgsb** [comment]
@maeglindeveloper it has just been merged

**Comment by maeglindeveloper** [comment]
@dgsb perfect, will give it a try right now! thanks for your amazing work ;)
