### ISSUE TITLE
Allow user-defined entry.Time

### ISSUE THREAD

**Issue by sbrisson2** [sirupsen/logrus#778]
Hi,

I'm currently writing a wrapper to go around logrus loggers.  This wrapper stores all logs in memory until it is explicitly flushed, at which point it logs to the underlying logger.  The intended use case is in tests, where I'm only interested in the logs for tests that fail.

The problem I'm having is that I would like the timestamps in the logs to reflect the time at which my program logs to the wrapper, not the time at which the wrapper is flushed.  I thought I could achieve this by modifying the `Time` field of an `entry` object.  However, it turns out that `entry.Time` is always set to `time.Now()` whenever one of the logging methods is called (see [here](https://github.com/sirupsen/logrus/blob/master/entry.go#L93)).

I was hoping that we could avoid overriding `entry.Time` in `entry.log()` if it's nonzero.

**Comment by dgsb** [comment]
For your use case, you can use a dedicated field for your initial timestamp.

**Comment by sbrisson2** [comment]
That is a possible solution, however it also requires us to have special handling for the custom field, either in our formatters, or in our log consumers.  I hope you can see why this is sub-optimal for us.

**Comment by dgsb** [comment]
Fixed by #781
