### ISSUE TITLE
[Question]: Strange output to file in case of io.MultiWriter

### ISSUE THREAD

**Issue by Blogoslov** [sirupsen/logrus#780]
Hello, I use io.MultiWriter to be able to see logs in the console and in the log file.  As a solution, I use this approach which was recommended here.

Here is my example for reproducing:

```
package main

import (
	"github.com/sirupsen/logrus"
	"io"
	"os"
)

func main() {
	log := logrus.New()

	customFormatter := new(logrus.TextFormatter)
	customFormatter.TimestampFormat = "2006-01-02 15:04:05"
	customFormatter.ForceColors = true
	customFormatter.FullTimestamp = true
	customFormatter.DisableColors = false
	log.Formatter = customFormatter

	log.Level = logrus.InfoLevel

	file, _ := os.Create("./tt")
	mw := io.MultiWriter(os.Stdout, file)
	log.Out = mw
	log.Info("This is test")
	log.Error("Error message")

}
```

As a result, I see a nice colored output in the console, but this is what I see in the file:

> [34mINFO[0m[2018-06-28 09:52:15] This is test                                 
> [31mERRO[0m[2018-06-28 09:52:15] Error message      

                          

So I see non-readable strange symbols which wrap the level.

How to avoid this strange behavior?

**Comment by dgsb** [comment]
Those strange are tty escape sequence to produce colors on the terminal. With the current implementation you can not have both color in the terminal and clean output in the file.
If you want to have clean content in your file you should configure your formatter by setting ForColors field to true and DisableColors to false.

**Comment by UnAfraid** [comment]
I've just resolved similar problem https://github.com/sirupsen/logrus/issues/784
