### ISSUE TITLE
Entry from sync.Pool keeps the old data

### ISSUE THREAD

**Issue by soyking** [sirupsen/logrus#795]
In this program I added a hook working in info level, and it add a field:

```
package main

import (
	"github.com/Sirupsen/logrus"
)

type hook struct {
}

func (*hook) Levels() []logrus.Level {
	return []logrus.Level{logrus.InfoLevel}
}

func (h *hook) Fire(entry *logrus.Entry) error {
	println(entry.Message)
	entry.Data["tag"] = "tag"
	return nil
}

func main() {
	logrus.AddHook(&hook{})
	logrus.Info("info")
	logrus.Error("error")
}
```

And the output is:

```
info
time="2018-07-31T17:40:04+08:00" level=info msg=info tag=tag
time="2018-07-31T17:40:04+08:00" level=error msg=error tag=tag
```

But there was still a `tag` field when I print error log. I found that the entry object reused from a pool in https://github.com/sirupsen/logrus/blob/master/logger.go#L79. But it didn't clear Data when it put back in pool or got from the pool. Is it a bug?

**Comment by dgsb** [comment]
If the data is not cleared upon entry release, it is indeed a bug.

**Comment by dgsb** [comment]
The bug is confirmed and is present since at least v1.0.0, thanks a lot for your contribution.
