### ISSUE TITLE
support not escape html char as normal(<,>,&)

### ISSUE THREAD

**Issue by cavanwang** [sirupsen/logrus#797]
Test version:
v1.0.6

TestCode:

import "github.com/sirupsen/logrus"
func main() {                                                                       
  var mylog = logrus.New()                                                          
  mylog.Formatter = &logrus.JSONFormatter{}                                         
  mylog.Errorf("< or > or &")                                                       
}

Output:
{"level":"error","msg":"\u003c or \u003e or \u0026","time":"2018-08-01T15:54:44+08:00"}

Expected:
{"level":"error","msg":"< or > or &","time":"2018-08-01T15:54:44+08:00"}

Other:
I have known about that json's Encoder has support the fun `SetEscapeHTML`(previously, json has no the method).

**Comment by cavanwang** [comment]
golang v1.6 has no new json Method `SetEscapeHTML`

**Comment by siller174** [comment]
How did you fix it?
