### ISSUE TITLE
Default instance of logger

### ISSUE THREAD

**Issue by Soulou** [sirupsen/logrus#8]
To have a similar behavior as the go standard log package, it may be interesting to have a default instance to do something like `logrus.Debug("Something")` directly without instanciating a new logger.

What do you think of that?

**Comment by patrick-motard** [comment]
@sirupsen was this functionality removed? I don't see the documentation added in that PR in master anymore. I would like to pass a logger between packages that doesn't require wrapping logrus in my own logger.

**Comment by dgsb** [comment]
Hello @patrick-motard, we do still have a default logger in the logrus package. You can refer to the api documentation [here](https://godoc.org/github.com/sirupsen/logrus) or through the go doc command line tool.
