### ISSUE TITLE
Caller level diffrence between log.Info and log.Infof

### ISSUE THREAD

**Issue by tamago-cn** [sirupsen/logrus#801]
when I print a line number to a log file，log.Info and log.Infof print diffrent file position, such as

2018-08-11 16:57:26 [proc.go:198] [INFO] info without format
2018-08-11 16:57:26 [demo_log.go:17] [INFO] info with format

I resolved that by modify exported.go like:
// Info logs a message at level Info on the standard logger.
  func Info(args ...interface{}) {
      **func() { std.Info(args...) }()** 
  }

I wonder if there's better solution?

**Comment by dgsb** [comment]
How do you retrieve the file name and line number ?  I guess the error is rather located there.

**Comment by dgsb** [comment]
For your information we do have here a long time pending issue for providing file name and line number directly in logrus #63. We are going to handle this issue soon.
