### ISSUE TITLE
Add canonical import path

### ISSUE THREAD

**Issue by MOZGIII** [sirupsen/logrus#804]
Hello, I'm stumbling upon case issues from time to time, and I'd propose adding a canonical import path to the repo to solve this issue one and for all.

The problem is that the import path can be used with both `github.com/sirupsen/logrus` and `github.com/Sirupsen/logrus`, and for some reason it's not clear which should be used (as various packages importing logrus make their own choices about it).

Specifying the proper canonical import path should solve this issue by enforcing a single import path for everyone.

More info: https://golang.org/doc/go1.4#canonicalimports

**Comment by dgsb** [comment]
I'm worried such a change would break currently working build configuration for some users. I'm not sure either if it's still relevant with the introduction of modules which are going their way.

**Comment by MOZGIII** [comment]
I really don't like this being a wontfix, given the fix is really easy and cheap to deliver.

Existing code won't break, because it's either vendored, or controlled in some other kind of fashion - and people would have to explicitly update to get the canonical import path - or it's not locked, and that means it's ok if canonical import path is added, as it was deployed as long ago as at Go 1.4 and was designed to land that way.

That said, I don't know if I can use modules with the projects that are set up "the old way", I don't think I can. So they won't help there. So, that means the issue is not solved at all for virtually everyone - because modules are not even officially landed, they're in a use-and-fix mode still. I don't mean they won't work at all, but most projects still use the old way.
Waiting for modules to be widely adopted is not a good idea, and it doesn't help with the old setup.
I think it should have had the canonical import path all along since Go 1.4, so it's a big question why it's not still added.

**Comment by dgsb** [comment]
Hello @MOZGIII adding this feature may break any code currently importing the master branch in a different path than the one we would specify in the canonical import path.
Sure the fix is cheap, imho the added value is also low, but we have some risk to break some user build.
If we choose to implement that, we can not release it in a v1 version as it is not expected that an upgrade of a same major release could not produce any build incompatibility.

**Comment by MOZGIII** [comment]
This is solved by `go.mod`.

The canonical import path is `github.com/sirupsen/logrus`.
