### ISSUE TITLE
Logging in hooks creates a deadlock

### ISSUE THREAD

**Issue by haeky** [sirupsen/logrus#807]
**GoVersion**: 1.10
**Version**: 1.0.7

How do you create a log from the same level in a hook?

The example below seems to create a deadlock.

#### main.go
```go
package main

import (
	"fmt"
	"github.com/sirupsen/logrus"
)

func main() {
	logrus.AddHook(NewHook())
	logrus.Info("Something")
}
```

#### hook.go
```go
package main

import (
	"github.com/sirupsen/logrus"
)

type testHook struct {
}

func NewHook() *testHook {
	return &testHook{}
}

func (t *testHook) Fire(entry *logrus.Entry) error {
	entry.Logger.Info("Something")

	return nil
}

func (t *testHook) Levels() []logrus.Level {
	return logrus.AllLevels
}
```

**Comment by dgsb** [comment]
The mutex is used to protect the entry from concurrent access. What are you trying to achieve ? A solution would to perform this log in another goroutine, another would be to use another logger instance. The current implementation does not allow to very easily add a per Entry mutex.

**Comment by dgsb** [comment]
@haeky did you succeed to overcome your issue ?
