### ISSUE TITLE
Asynchronous thread output

### ISSUE THREAD

**Issue by rbcrwd** [sirupsen/logrus#829]
I'll preface this by offering that I may be approaching this problem completely wrong.

When using logrus in goroutines, we lose log output on short-lived applications despite syncing on them and waiting for them to exit. Consider the following example:

```go
package main

import (
	"github.com/sirupsen/logrus"
	"sync"
	"time"
)

func main() {
	l := logrus.WithField("start", time.Now)
	var wg sync.WaitGroup

	l.Info("starting loop")
	for i := 0; i < 10; i++ {
		go func() {
			wg.Add(1)
			defer wg.Done()
			l.WithField("i", i).Info("processing")
		}()
	}
	wg.Wait()
	//time.Sleep(time.Second)
	l.WithField("stop", time.Now()).Info("loop done")
}
```

Most of the time this code produces two log entries; on rare occasions it will produce 12. Uncommenting the call to time.Sleep() reliably produces all 12 expected messages.  This seems an obvious race condition - the application is ending before logrus can flush its output. Although my primary use of logrus is in long-lived daemons that leave plenty of time for logging, sometimes the failures are rapid enough that this swallows important debugging information. Replacing the calls to logrus with similar calls to the core `log` library, of course, results in no log loss.

I'd like a solution to be able to wait on logrus to finish flushing, be it a `Sync()` function or a correction to my thinking.

**Comment by rbcrwd** [comment]
Note: it's worth pointing out that the `time.Sleep` call needn't nearly be that long. Somewhere between 100µs and 500µs on my particular hardware is all it takes to get all expected values

I should also acknowledge that `i` does not do what it would seem to here. That may be because logrus is using a channel under the covers.

**Comment by rbcrwd** [comment]
I just realized where the bug is, and it's between keyboard and chair.

**Comment by dgsb** [comment]
You have moved the wd.Add outside of the go routine ?

**Comment by rbcrwd** [comment]
> You have moved the wd.Add outside of the go routine ?

That is correct, my apologies for making extra noise for you.
