### ISSUE TITLE
Nicely color-coded logs at Jetbrains GoLand

### ISSUE THREAD

**Issue by SergeiVasilenko** [sirupsen/logrus#833]
I would like to see in my Jetbrains GoLand IDE something like this:
![image](https://user-images.githubusercontent.com/1563512/46431710-d16fb100-c74c-11e8-9135-86d2fdd226cb.png)

But found this one:

```text
time="2015-03-26T01:27:38-04:00" level=debug msg="Started observing beach" animal=walrus number=8
time="2015-03-26T01:27:38-04:00" level=info msg="A group of walrus emerges from the ocean" animal=walrus size=10
time="2015-03-26T01:27:38-04:00" level=warning msg="The group's number increased tremendously!" number=122 omg=true
time="2015-03-26T01:27:38-04:00" level=debug msg="Temperature changes" temperature=-4
time="2015-03-26T01:27:38-04:00" level=panic msg="It's over 9000!" animal=orca size=9009
time="2015-03-26T01:27:38-04:00" level=fatal msg="The ice breaks!" err=&{0x2082280c0 map[animal:orca size:9009] 2015-03-26 01:27:38.441574009 -0400 EDT panic It's over 9000!} number=100 omg=true
exit status 1
```

How can I setup properly output in GoLand ?

**Comment by dgsb** [comment]
Coloring is only performed when the output is identified as being a terminal. You can force the coloring output by setting the field `ForceColors` to true, but that will only work if your ide supports usual terminal escape sequence.

**Comment by dgsb** [comment]
@SergeiVasilenko can we close this issue ?

**Comment by SergeiVasilenko** [comment]
> @SergeiVasilenko can we close this issue ?

Yes, it helps
