### ISSUE TITLE
while testing, redirect output to testing.T

### ISSUE THREAD

**Issue by drewwells** [sirupsen/logrus#834]
The testing package has many logging functions that are used for logging only when errors are encountered. It would be beneficial to be able to easily redirect output to this. I can't see a simple way to do this currently besides creating an io.Writer that outputs to testing.Logf.

**Comment by dgsb** [comment]
Hi @drewwells, I've you tried somehow to set the logger.Out field to os.Stdout instead of os.Stderr ? I wonder if the test environment doesn't do something Stdout in order to only have its output upon test failure.

**Comment by pkqk** [comment]
@drewwells it's slightly tricky since you need to get access to the `*testing.T` instance of each test, and it is hardcoded to look back a certain number of stack frames for the calling location.

In one of our projects at work we have this:
```golang
package serenity

import (
	"io"
	"os"
	"testing"
	"github.com/sirupsen/logrus"
)

// LogCapturer reroutes testing.T log output
type LogCapturer interface {
	Release()
}

type logCapturer struct {
	*testing.T
	origOut io.Writer
}

func (tl logCapturer) Write(p []byte) (n int, err error) {
	tl.Logf((string)(p))
	return len(p), nil
}

func (tl logCapturer) Release() {
	logrus.SetOutput(tl.origOut)
}

// CaptureLog redirects logrus output to testing.Log
func CaptureLog(t *testing.T) LogCapturer {
	lc := logCapturer{T: t, origOut: logrus.StandardLogger().Out}
	if !testing.Verbose() {
		logrus.SetOutput(lc)
	}
	return &lc
}
```

But it does mean in every test you need to do:
```golang
func TestFoo(t *testing.T) {
  defer serenity.CaptureLog(t).Release()
  …
}

**Comment by adamcavendish** [comment]
We can use `logrus.SetOutput(ioutil.Discard)` to disable output.

```
import (
	"io/ioutil"
        "testing"
	"github.com/sirupsen/logrus"
)

func TestFoo(t *testing.T) {
	logrus.Info("Logrus in Testing")
}

func TestMain(m *testing.M) {
	logrus.SetOutput(ioutil.Discard)
	os.Exit(m.Run())
}
```

**Comment by SOF3** [comment]
Is it possible to provide this util type by default? This wrapper is better implemented inside logrus itself than in user test packages.

**Comment by drewwells** [comment]
Years later, people are still just discarding logs. Our packages are complicated enough that logs are helpful. I'd just prefer they were ordered correctly in my test runs

**Comment by eriklarko** [comment]
Sorry to revive an old thread, but I've done something like this in the past and it works pretty well. It's not perfect, but it's good.

```go
type TestWriter struct {
	t *testing.T
}
func (t *TestWriter) Write(p []byte) (n int, err error) {
	t.t.Log(string(p))
	return len(p), nil
}

func TestSomething(t *testing.T) {
	logrus.SetOutput(&TestWriter{t: t})
        logrus.Info("Hello!")
}
```
