### ISSUE TITLE
v1.1.0 breaks cross-compiling for solaris

### ISSUE THREAD

**Issue by prymitive** [sirupsen/logrus#836]
https://travis-ci.com/prymitive/karma/jobs/149295747#L593-L594

```
2018/10/02 20:50:53 fatal: There was an error! goos='solaris' goarch='amd64' err='exit status 2' stdout='' stderr='# github.com/prymitive/karma/vendor/github.com/sirupsen/logrus
vendor/github.com/sirupsen/logrus/text_formatter.go:87:4: undefined: initTerminal
```

It looks like there were some changes around `terminal_*.go` between 1.0.6 and 1.1.0 that might cause it. What I'm not so sure about is whenever solaris should be covered by `terminal_linux.go` or `terminal_bsd.go`. Also looking at build tags I think [terminal_linux.go](https://github.com/sirupsen/logrus/blob/master/terminal_linux.go#L6) should be the default file since it has `// +build !appengine,!js`. Either way I'm not 100% sure how to fix it so no PR.

**Comment by dgsb** [comment]
That's annoying, the file terminal_linux.go is skipped in the solaris build due to its name containing the linux os name

**Comment by dgsb** [comment]
I've just merged a fix on master trying to clean up all the build constraints which does not seem make any sense anymore today. Can you check if that fixes you issue ?

**Comment by prymitive** [comment]
Sure, I'll try cross-compiling locally with master and report back. Thanks

**Comment by dgsb** [comment]
I'll release a new label soon so that you don't need to depend on an unlock version. I'll keep this issue until this is done.

**Comment by dgsb** [comment]
@prymitive v1.1.1 has been relased, I'm closing this issue
