### ISSUE TITLE
How to get file/line number ?

### ISSUE THREAD

**Issue by frranck** [sirupsen/logrus#843]
Hello,
Is there an easy way to get file/line number in error ? 
Wouldn't anyone need that as a default ?

**Comment by dgsb** [comment]
duplicate of #63

**Comment by trinhhuong244** [comment]
formatter := runtime.Formatter{ChildFormatter: &log.TextFormatter{
		FullTimestamp: true,
	}}
	formatter.Line = true
	log.SetFormatter(&formatter)
	log.SetOutput(os.Stdout)
	log.SetLevel(log.InfoLevel)
	log.WithFields(log.Fields{
		"file": "main.go",
	}).Info("Server is running...")
Note: import ( 	runtime "github.com/banzaicloud/logrus-runtime-formatter"
	log "github.com/sirupsen/logrus")
