### ISSUE TITLE
[bug] panic is TextFormatter when Caller is nil

### ISSUE THREAD

**Issue by shousper** [sirupsen/logrus#852]
Found myself with this stack:

```
panic(0x19f4ce0, 0x23e7190)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc0002ef540, 0xc000305440, 0xc0003059b0, 0x1, 0xc000305440, 0xc0000f97e0, 0x1073cab)
	/Users/shousper/go/src/github.com/sirupsen/logrus/text_formatter.go:177 +0xad7
github.com/sirupsen/logrus.(*Entry).write(0xc000305440)
	/Users/shousper/go/src/github.com/sirupsen/logrus/entry.go:232 +0x93
github.com/sirupsen/logrus.Entry.log(0xc000305980, 0xc0003225a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/shousper/go/src/github.com/sirupsen/logrus/entry.go:208 +0x194
github.com/sirupsen/logrus.(*Entry).Debug(0xc0003053e0, 0xc0000f9908, 0x1, 0x1)
	/Users/shousper/go/src/github.com/sirupsen/logrus/entry.go:251 +0xae
```

When using the `TextFormatter`. It looks like [this line](https://github.com/sirupsen/logrus/blob/master/text_formatter.go#L177) and maybe [this line](https://github.com/sirupsen/logrus/blob/master/text_formatter.go#L179) might need to check the `Caller` is present first? Perhaps using [HasCaller](https://github.com/sirupsen/logrus/blob/master/entry.go#L175)?

I'm not sure if some other code is checking this first, but definitely where I [found Caller to be set](https://github.com/sirupsen/logrus/blob/master/entry.go#L198) it can [return nil](https://github.com/sirupsen/logrus/blob/master/entry.go#L172) in some cases, but also that setter is conditional as well.

Not sure how you'd like this solved, so raising an issue first 👍

**Comment by dgsb** [comment]
@shousper thanks for reporting this issue. It's weird because this case should be protected there https://github.com/sirupsen/logrus/blob/251d6bf71382da18d56ae619e48a8404728b40b0/text_formatter.go#L128
Can you provide a test case to reproduce this issue ?

**Comment by freman** [comment]
> We're also adding a field "func"

not what I meant when I said I wanted us to context components

**Comment by dgsb** [comment]
Hello @shouspe,r, thanks for your test case, but I do not reproduce the issue whether the report caller is enabled or not.
Can you provide which version you are on ?

**Comment by eschao** [comment]
@dgsb I meet the same problem with the latest logrus. And the same error and same line code is broken.

**Comment by lchanouha** [comment]
I got same issue since i upgraded to go1.11, but only when my app is launched via systemd (syslog output).
Launching it directly with stdout works fine.

**Comment by lchanouha** [comment]
Reverting to tags/v1.1.1 works for me (master branch broken on go 1.9+).

**Comment by dgsb** [comment]
I've still not been able to reproduce the issue on my environment.
Can someone can provide a PR with a unit test which would exhibit the issue on travis CI ?

**Comment by lchanouha** [comment]
Found the issue. Field "file" is now a special field (since commit 251d6bf71382da18d56ae619e48a8404728b40b0 ?)

This code:
```
package main
import (
    "github.com/sirupsen/logrus"
)

func main() {

 initLog := logrus.New();

 initLog.WithFields(logrus.Fields{
        "file": "Hello Word",
 }).Warn("Hell");

 for {
 }
}
```

successfully work with 
$ go build && ./test

but fail with 
$ go build && nohup ./test

**Comment by dgsb** [comment]
Ok, I've reproduced the issue. It's related to the output coloring disabled on the text formatter. I will have a look at asap.
