### ISSUE TITLE
Please add `gh-pages` branch

### ISSUE THREAD

**Issue by loren-osborn** [sirupsen/logrus#853]
Could you please create an empty `gh-pages` branch as target for documentation pull-requests with something like:

```
git checkout --orphan gh-pages
git commit --allow-empty -m "empty documentation branch: pull-request target"
git push -u origin gh-pages
```

I'd ideally like to see the output of `godoc` (and possibly a code-coverage report) end up in that branch.

**Comment by dgsb** [comment]
In go ecosystem we already have godoc. It is a well known place where packages documentation is centralized.

**Comment by loren-osborn** [comment]
Perhaps this is more of a CI/CD discussion, but my concern was ability to easily review godoc (tool) output before the resulting changes got merged into `master`. Similarly, i’d Like to be able to review changes in code coverage before they get merged into `master`. For released versions, I agree that https://godoc.org/github.com/sirupsen/logrus is the best place for that.
