### ISSUE TITLE
Get an Entry from a logger?

### ISSUE THREAD

**Issue by mlsquires** [sirupsen/logrus#856]
I'm importing logrus via 'log "github.com/sirupsen/logrus"' so I can just refer to "log" anywhere in my code. I set some configuration options (e.g., level, formatter) initially and that does the trick for me. I haven't needed to create a custom logger.

I'm migrating my logging from formatted text to field-based logging. I can use log.WithFields and that works well.

What I'd like to do is create an entry with some fields, hold onto it, add more fields, and then do the logging operation. This lets me establish some standard fields and then augment those with fields specific to a situation.

I can do that by "event := log.WithFields(...)" and later "event.WithFields". That all works.

I'd like to generalize my logging functions such that I can pass in an event pointer to each one. If that is nil then get a new event. If it isn't nil then just use that.

It looks like there is no way to just get a fresh event (without added fields) from the current logger. There is a log.newEvent() that would be perfect but it isn't exposed.

Any suggestions?

**Comment by dgsb** [comment]
Instead of using an Entry type has parameter, you could use an interface which holds the needed operations.
The package provides such interface:
`logrus.FieldLogger` or `logrus.Ext1FieldLogger` if you need the new Trace level.

**Comment by dgsb** [comment]
@mlsquires that works indeed. Can I close this issue ?

**Comment by mlsquires** [comment]
yep - thank you
