### ISSUE TITLE
Error marshalling JSON when Panic() is called and JSONFormatter used

### ISSUE THREAD

**Issue by deusnefum** [sirupsen/logrus#858]
I'm using JSONFormatter and calling logrus.Panic("panic msg") which gives me this error:

`Failed to obtain reader, Failed to marshal fields to JSON, json: unsupported type: logrus.exitFunc`

If I add a Marshaler interface for logrus.extFunc that just returns "<func pointer>", it works, but this involves modifying logrus vendor code. This seems related to  #835 and #642. 

I don't really care about handling type-functions as field values in general--I just want to be able to call Panic()--this seems like a bug, but I fully admit I could be missing something and doing something wrong.

**Comment by dgsb** [comment]
Hello @deusnefum, I can't reproduce the issue by just instantiating a logger with a JSONFormatter and calling Panic.
Can you provide a minimum code sample which exhibits the issue ?

**Comment by deusnefum** [comment]
I was correct that I was missing something and doing something wrong. We have generic crash-recovery code and part of that code adds the error object as a field--I think my answer is to just remove the offending field. 

```
	if x := recover(); x != nil {
		delete(x, "Loggger")  // "fix" the problem
		// recovering from a panic; x contains whatever was passed to panic()
		logrus.WithFields(logrus.Fields{
			"error": x,
		}).Info("panic occurred")
```


I'll close the issue, but is there a more generic solution? Anyway to add a JSON marshaller or tell logrus to skip fields it can't marshall?
