### ISSUE TITLE
Colorized output on windows 7 broken

### ISSUE THREAD

**Issue by ceriath** [sirupsen/logrus#862]
When printing output with a TextFormatter to cmd or powershell on windows 7, the control sequences are rendered to the output.

``←[36mINFO←[0m[0000] Replay took: 4.0003ms                         ←[36msource←[0m=Badger``

This was already mentioned in #820 but probably never investigated.

Workaround: Just disable colors with 

```
log.SetFormatter(&logrus.TextFormatter{
		DisableColors: true,
})
```

**Comment by dgsb** [comment]
I do not have any windows test environment, any help on this feature would be greatly appreciated

**Comment by ceriath** [comment]
So i've been investigating a bit and it seems like windows 7 does not support colors on commandlines at all, while windows 10 made it an option (which is off by default) with some update. The easiest solution is probably to just disable it entirely on windows

**Comment by dgsb** [comment]
@ceriath is there a way to detect if coloring is activated or not ?

**Comment by ceriath** [comment]
@dgsb sorry for the late response, totally forgot about it. It seems like you could try and search for a registry key on newer windows, but apparently it's not always there either. so not really a reliable way
