### ISSUE TITLE
Problem see logs in kubernetes

### ISSUE THREAD

**Issue by PeterUherek** [sirupsen/logrus#869]
I want to switch to logrus from standard log package. I have code deployed in azure kuberentes. My problem is that I can not see any logs from running pod if I use logrus. If I use standard log package everything run fine. I do not have any idea where can be a problem. Maybe somehow logrus does not sent logs to standard output ( I only guess).  Do you someone have idea how to troubleshoot this or where can be a problem? Thanks

Here is my code:
``` go
import (
      "github.com/sirupsen/logrus"
}

var log = logrus.New()

func init() {
	// Log as JSON instead of the default ASCII formatter.
	formatter := &logrus.JSONFormatter{
		FieldMap: logrus.FieldMap{
			logrus.FieldKeyTime:  "Time",
			logrus.FieldKeyLevel: "Serverity",
			logrus.FieldKeyMsg:   "Detail",
			logrus.FieldKeyFunc:  "Func",
			logrus.FieldKeyFile:  "File",
		},
	}
	formatter.TimestampFormat = "2006-01-02 15:04:05.000000"
	log.SetOutput(os.Stdout)
	log.SetReportCaller(true)
}

func main() {
        ... initialize and run server ...

	log.Trace("Run server")
}
```

**Comment by richpoirier** [comment]
Hi @PeterUherek. `Trace()` is the finest-grained level so unless you `log.SetLevel(logrus.TraceLevel)`, it won't log anything. You probably want `log.Info("Run server")`.
