### ISSUE TITLE
Unsupported type func ...

### ISSUE THREAD

**Issue by dimatkach** [sirupsen/logrus#871]
Check out #642 for details. 

It seems that PR referenced there only fixes the case when func is the field itself, but the issue still exists when the field is a struct, that has a func field somewhere inside of it. It looks like the conversion to `map` needs to be applied recursively, skipping `func` fields all the way down. 

```
      import (
         log "github.com/sirupsen/logrus"
      )
      type Foo struct {
         foo func() string
      }


     func main() {
        foo :=  Foo {
          func () string { return "foo" }
         }
   
        log.SetFormatter(&log.JSONFormatter{})
        log.WithField("foo", foo).Info("Foo!")
      }
```

**Comment by hcmlinj** [comment]
I add some more codes here: [https://play.golang.org/p/netBf0UwfO-](https://play.golang.org/p/netBf0UwfO-)

Fragment output:
struct with String() func: `"msg":"foo"`
map: `"msg":"map[foo:foo]"`
struct without String() func: `"msg":"{0x4d5ec0}"`

Does it meet your expectations?
Maybe I can try to implement this if your answer is yes.
