### ISSUE TITLE
Problem with JSON

### ISSUE THREAD

**Issue by yossigi** [sirupsen/logrus#873]
The test below illustrates the problem. 
A struct containing a logrus.Level member encodes with JSON,
but decoding results in an error.
(Removing Level's UnmarshalText function seems to solve this issue, though it might be undesirable)

```
func TestJson(t *testing.T) {
       type X struct {
               Level logrus.Level
       }

       var x X
       x.Level = logrus.WarnLevel
       var buf bytes.Buffer
       enc := json.NewEncoder(&buf)
       assert.NoError(t, enc.Encode(x))
       dec := json.NewDecoder(&buf)
       var y X
       assert.NoError(t, dec.Decode(&y))
}

```

**Comment by dgsb** [comment]
We could also implements the TextMarshaller interface to have the encoding and decoding functions.
