### ISSUE TITLE
daily log file

### ISSUE THREAD

**Issue by msAlcantara** [sirupsen/logrus#877]
exist a way of configure logrus to create a daily log file? If not, I think it a good idea to implement...

**Comment by dgsb** [comment]
There is no such thing directly implemented with logrus, but you can either

* use the syslog hook, which is provided with logrus as a sub-package, and then configure as wanted the logrotate service (if you are on unix like platform),
* or use the [lumberjackrus](https://github.com/orandin/lumberjackrus) hook

**Comment by msalcantara** [comment]
I can implement something like that?
```

logrus.SetOutput(logrus.DailyLog{
		Name:       "info",
		Pattern:       "2006-01-02",
	})
```
DailyLog will be a struct that implements io.Writer

**Comment by dgsb** [comment]
What would be the advantage to using lumberjackrus ?

**Comment by msalcantara** [comment]
cool, can be :D

**Comment by dgsb** [comment]
We have another issue #678 which need to require to change the file to use depending on the level, we may think to integrate such a mechanism the same way.
What do you think about implementing about that in a hook rather than a specific writer ?

**Comment by msalcantara** [comment]
I think that could be useful and simple to implement. Do you think a better way to implement that would be in the same struct of example in issue #678 or creating another one?

**Comment by dgsb** [comment]
We have a set of hook which can help implementing such a feature (lumberjack, lfshook).
We don't need to implement something specific for logrus
