### ISSUE TITLE
cant log empty string

### ISSUE THREAD

**Issue by Fengxq2014** [sirupsen/logrus#879]
my format is
```go
log.SetFormatter(&log.TextFormatter{
		QuoteEmptyFields: true,
		FullTimestamp:    true,
	})
```
logrus version is v1.2.0

when i want to print an empty string `""`, but i got 
```base
time="2018-12-29T15:32:03+08:00" level=info msg=true
time="2018-12-29T15:32:03+08:00" level=info
time="2018-12-29T15:32:03+08:00" level=info msg="<nil>"
```

**Comment by dgsb** [comment]
Indeed, the message is not printed. However we can argue whether this is a normal behavious or not as the message is not a field per se.
What would be the usefulness to make appear such empty message ?

**Comment by Fengxq2014** [comment]
Log output should be the same input information，monitoring of a variable, when no msg is strange
