### ISSUE TITLE
Feature Request: Provide own LevelToStringFunc in the TextFormatter struct

### ISSUE THREAD

**Issue by bramstes** [sirupsen/logrus#880]
The TextFormatter is almost perfect for our use case except for one small thingy. We want the levels printed with Capitals and use "WARN" iso "warning". So this request is about adding a function e.g.: LevelToStringFunc as part of the TextFormatter struct where I can provide my own return strings for the different logrus levels (DebugLevel, InfoLevel, ...).
E.g.:
func LogLevelToString(level logrus.Level) string {
	switch level {
	case logrus.DebugLevel:
		return "DEBUG"
	case logrus.InfoLevel:
		return "INFO"
	case logrus.WarnLevel:
		return "WARN"
	case logrus.ErrorLevel:
		return "ERROR"
	case logrus.FatalLevel:
		return "FATAL"
	case logrus.PanicLevel:
		return "PANIC"
	}
	return "UNKNOWN"
}

And in the !isColored() case check whether a function has been provided in the TextFormatter struct for printing the entry.Level.
[text_formatter.go.txt](https://github.com/sirupsen/logrus/files/2720829/text_formatter.go.txt)

**Comment by bramstes** [comment]
[logrus.patch.txt](https://github.com/sirupsen/logrus/files/2724304/logrus.patch.txt)

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
