### ISSUE TITLE
Level in Hooks is subset of SetLevel()

### ISSUE THREAD

**Issue by samsamm777** [sirupsen/logrus#885]
It would appear that Hooks levels is dictated by the logrus.SetLevel(). A hook which Levels() method returns all levels, will not receive Debug logs, if SetLevel() is set to Info.

**Comment by dgsb** [comment]
If this happens, this is indeed a bug, but it has not been observed yet.
If the Levels() method of the hook contains a level it will be fired.
If this does not work I suspect rather a bug in the hook implementation.

**Comment by dgsb** [comment]
Indeed, the behaviour is the one you've described, my mistake.
But this is what is expected by hook implementer.
A hook to be fired, needs to have its associated trace to be triggered.
And the trace is triggered depending on the current level of the logger.
