### ISSUE TITLE
Give the library user a method to customize the reportcaller output

### ISSUE THREAD

**Issue by GAZ082** [sirupsen/logrus#887]
Hey. When I enable it i get an absolute path  to the code line:

`"file":"/home/gabriel/go/src/someprogram/package/subpackage/subpackage.go:303`

I just need the last few charactes, ie: `subpackage.go:303`

You guys know some way to get this that way?

Thanks!

**Comment by richpoirier** [comment]
@GAZ082 unfortunately no, there's no way to do that currently.

**Comment by quancore** [comment]
This definitely needs to implement otherwise, outputs seem very ugly. I am wondering what is hindering you to just truncate last part of caller method path?

**Comment by GAZ082** [comment]
Ignorance? Haha. Have no idea how to work around this.

**Comment by dgsb** [comment]
There is no actual way to do that from a library user standpoint. The formatting is of file data fields is done at the fomatter level which is not customizable.
We need to think how we would like to provide a library user to customize the output of such information.
The usual way is to use a hooks, but it is not feasible with this implementation.

**Comment by GAZ082** [comment]
@dgsb no problem David, than you for being so nice. Looking forward this feature!

**Comment by tossp** [comment]
I submitted a solution(#898 )  that I am using, which is expected to meet your needs, but I did not do performance testing.

**Comment by GAZ082** [comment]
Hey, looks handy! Is there any way I can load this up in my local version of logrus? I'm sure some git command to suck your commit up and merge it in my local version?

**Comment by dgsb** [comment]
@GAZ082 I've added a callback to the json formatter in order to give the user a chance to format the runtime.Frame himself. Would that help you ?

**Comment by dgsb** [comment]
it's here #909

**Comment by dgsb** [comment]
The same customization has been added to the text formatter #911

**Comment by GAZ082** [comment]
Thank you @dgsb ! Been looking into the commit and could not figure it out how to implement it. Any example would be welcomed!

**Comment by dgsb** [comment]
I've added an example in #913 
I'm going to merge that soon
