### ISSUE TITLE
broken format to log file

### ISSUE THREAD

**Issue by quancore** [sirupsen/logrus#888]
I am logging console as well as txt log file.Console output is okay and it is colored however, txt output is broken. Here is the output:
[log.txt](https://github.com/sirupsen/logrus/files/2764677/log.txt)
Here is the code to setup logger:

> // InitLogger setup logger for both printing file and console
func InitLogger(path string, methodname bool) {
	// remove old file if exist
	os.Remove(path)
	// set formatter of logger
	log.SetFormatter(&log.TextFormatter{
		ForceColors:      true,
		DisableTimestamp: true,
	})
	// open logging file
	f, err := os.OpenFile(path, os.O_RDWR|os.O_CREATE, 0666)
	// check error
	CheckError(err)
	// defer f.Close()
	// log both file and console
	wrt := io.MultiWriter(os.Stdout, f)
	// set output
	log.SetOutput(wrt)
	// set whether we log filename as well
	log.SetReportCaller(methodname)
	// log.SetLevel(log.ErrorLevel)
	log.Info("Logger has been initilized.")
}

**Comment by richpoirier** [comment]
Hi @quancore. See these issues: #780 and #784.
