### ISSUE TITLE
Escape code for ANSI colors?

### ISSUE THREAD

**Issue by GAZ082** [sirupsen/logrus#892]
Hey. I want to use `less` for viewing colorized logs generated with logrus but cant find a way to make the \33 work to colorize it.  Tried copy pasting the exact escaping character that works in the console and no luck.

How can i do it? Thanks!

**Comment by dnaf** [comment]
If I'm understanding this issue correctly, `less` just isn't displaying color codes? In that case, all you should need to do is pass `-R` to less, for example: `less -R logs.txt`. `less` suppresses all ANSI escape codes by default, but you can use `-R` to make it display all color sequences, or `-r` to display all sequences, though `-r` can cause `less` to mess up formatting in some cases. (See [less(1)](http://man7.org/linux/man-pages/man1/less.1.html))

Apologies if this isn't what you're asking!
