### ISSUE TITLE
TTY formatting for logrus hooks

### ISSUE THREAD

**Issue by Ferguzz** [sirupsen/logrus#894]
my use case is pretty simple: i want to provide a `--verbose` flag which output all log messages to stderr (without changing the existing logging configuration). the way i understand it, logrus hooks leave the formatting up to the hook writer (i.e. taking a log entry and producing a byte array to write). my question is related to the TTY formatting which is available as part of the TextFormatter. 

here is my 'verbose logging hook':

```
// VerboseLoggingHook writes all log messages to os.Stderr
type VerboseLoggingHook struct {
	Formatter log.Formatter
}

func (hook *VerboseLoggingHook) Fire(entry *log.Entry) error {
	message, err := hook.Formatter.Format(entry)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to format log entry: %v", err)
		return err
	}

	_, err = os.Stderr.Write(message)
	return err
}

func (hook *VerboseLoggingHook) Levels() []log.Level {
	return log.AllLevels
}
```

now, by default, if I create the hook with a default TextFormatter, TTY coloring is not included. this is because the *logger*'s ouput is not attached to a TTY. i get it. so I force coloring by creating the hook with

```
log.AddHook(&VerboseLoggingHook{&log.TextFormatter{ForceColors: true}})
```

and everything is great. HOWEVER, i see from the source code that when we are writing colors to windows terminals, some extra set up is required, which will not get run in this case. is there a better way to achieve what i want without all this palaver?

thanks

**Comment by gguridi** [comment]
I think your case is quite specific and that code looks fine. 

For windows it's recommended to use [go-colorable](https://github.com/mattn/go-colorable) as described in the README file. `colorable.NewColorableStderr()` should give you a writer to use instead of the default stderr.

The hooks can implement a formatter or use the one from logrus. It's the hook implementation who decides that (some of them do, some of them don't).

**Comment by sneko** [comment]
Hi @gguridi ,

By default I see my custom formatter working great (with colors with according parameters). But if I add hooks it doesn't color anything.

I can for sure "force color" so in TTY it works, but then in a standard terminal I will see coloration codes... I could try to get the parameter but properties about color are private https://github.com/sirupsen/logrus/search?q=checkIfTerminal&unscoped_q=checkIfTerminal

What would be the recommend way to use hooks and also get colors?

Thank you,

**Comment by mem-** [comment]
Based on the logrus example https://github.com/sirupsen/logrus/tree/master/hooks/writer

By using the code in: https://github.com/sirupsen/logrus/blob/master/hooks/writer/writer.go
and combine it with:  https://github.com/snowzach/rotatefilehook/blob/master/rotatefilehook.go
I got the following code to work;

`package main

import (
	"io"
	"io/ioutil"
	"os"

	log "github.com/sirupsen/logrus"
)

// FormatterHook is a hook that writes logs of specified LogLevels with a formatter to specified Writer
type FormatterHook struct {
	Writer    io.Writer
	LogLevels []log.Level
	Formatter  log.Formatter
}

// Fire will be called when some logging function is called with current hook
// It will format log entry and write it to appropriate writer
func (hook *FormatterHook) Fire(entry *log.Entry) error {
	line, err := hook.Formatter.Format(entry)
	if err != nil {
		return err
	}
	_, err = hook.Writer.Write(line)
	return err
}

// Levels define on which log levels this hook would trigger
func (hook *FormatterHook) Levels() []log.Level {
	return hook.LogLevels
}

// Use two hooks with different formatting
func main() {
	logFile := "/tmp/writer-log.txt"
	f, err := os.OpenFile(logFile, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0644)
	if err != nil {
		log.Println("Failed to create logfile" + logFile)
		panic(err)
	}
	defer f.Close()

	log.SetOutput(ioutil.Discard) // Send all logs to nowhere by default
	log.SetLevel(log.DebugLevel)
		
	log.AddHook(&FormatterHook{ // Send logs with level higher than info to stderr
		Writer: os.Stderr,
		LogLevels: []log.Level{
			log.PanicLevel,
			log.FatalLevel,
			log.ErrorLevel,
			log.WarnLevel,
			log.InfoLevel,
		},
		Formatter: &log.TextFormatter{
            TimestampFormat: "2006-01-02 15:04:05",
			FullTimestamp:   true,
			ForceColors:     true,
		},
	})
	log.AddHook(&FormatterHook{ // Send info and debug logs to the file
		//Writer: os.Stdout,
		Writer: f,
		LogLevels: []log.Level{
			log.InfoLevel,
			log.DebugLevel,
		},
		Formatter: &log.JSONFormatter{},
	})
	log.Info("This will go to both stdout and stderr")
	log.Warn("This will go to stderr")
	log.Debug("This will go to stdout")
}
`
