### ISSUE TITLE
logrus.Panic() throws away type information

### ISSUE THREAD

**Issue by MMulthaupt** [sirupsen/logrus#900]
In our code base we have this code:
```
type BailInfo struct {
	Message string
}

// Bail is called when the user wants to exit the application.
func Bail() {
	// Use panic() instead of log.Panic() here because log.Panic() wraps the arguments with fmt.Sprintf(), destroying type information.
	panic(&BailInfo{"User requested application exit."})
}
```
In a `defer`-statement, we `recover()` and check for the type of the returned value to match `*BailInfo`:
```
if r := recover(); r != nil {
	_, ok := r.(*BailInfo)
	if !ok { // Only report this to the user if it is of a type other than *BailInfo
		// Show an error dialog box or something
	}
}
```
This works using `panic()`, but fails using `logrus.Panic()`, because Logrus wraps the arguments with `fmt.Sprintf()`. See `entry.go`:
```
func (entry *Entry) Panic(args ...interface{}) {
	if entry.Logger.IsLevelEnabled(PanicLevel) {
		entry.log(PanicLevel, fmt.Sprint(args...))
	}
	panic(fmt.Sprint(args...)) // <- This is a problem
}
```
Should there be a better way to deal with this? Maybe it could make sense to change this to `panic(args[0])` iff `len(args) == 1`?

**Comment by dgsb** [comment]
hi @MMulthaupt, I suspect with the current implementation this `panic(fmt.Sprint(...))` actually never called.
The panic which is called is the one at the bottom of the `Entry.log` mehod and the argument of the panic is the entry itself.
To mitigate your issue you may want to add your object to a field and test the content of this field in the recover defer function

**Comment by dgsb** [comment]
Solution proposed. Closing.
