### ISSUE TITLE
Splunk Hook fails to marshal logrus.Entry

### ISSUE THREAD

**Issue by caddac** [sirupsen/logrus#922]
I'm using https://github.com/caddac/logrus-splunk-hook to try to log to splunk. I've opened an issue on the original repo here https://github.com/Franco-Poveda/logrus-splunk-hook/issues/1 but have gotten no reply, so trying here to see if I can get some help. 
I've setup my hook like 
```
import (
	"github.com/caddac/logrus-splunk-hook"
	log "github.com/sirupsen/logrus"
)
splunkClient := splunk.NewClient(nil, cfg.SplunkUrl, cfg.SplunkToken, cfg.SplunkSource, cfg.SplunkSourcetype, cfg.SplunkIndex)
splunkHook := splunk.NewHook(splunkClient, []log.Level{level})
log.AddHook(splunkHook)
log.Info("Test logging"))
```
and I get error:

```
Failed to fire hook: json: unsupported type: func(*http.Request) (*url.URL, error)
```

The hook fails to JSON marshal the `logrus.Entry` sent into the `Fire()` method. The error is coming from  here: https://github.com/Franco-Poveda/logrus-splunk-hook/blob/5edca16794c6d300ff72b75ca774ec4ec20617c0/splunk.go#L116-L119 

I've dug in a bit, but can't seem to find where this function is coming from on the event. Does anyone have a suggestion or idea about where the real problem lies here?

**Comment by caddac** [comment]
OK, I've fixed this by doing:
```
func (h *Hook) Fire(entry *logrus.Entry) error {
	event := map[string]interface{}{
		"message": entry.Message,
		"time": entry.Time.String(),
		"level": entry.Level.String(),

	}
	for k, v := range entry.Data {
		event[k] = v
	}

	err := h.Client.Log(
		event,
	)
	return err
}
```

**Comment by lavoiesl** [comment]
Does it mean this issue can be closed?

**Comment by caddac** [comment]
I'd be curious to get some feedback about my solution, and if I need to handle the `logrus.Entry.err` field.

**Comment by tskardal** [comment]
I came here looking for solutions to the same problem in the splunk hook library.

> Failed to fire hook: json: unsupported type: func(*http.Request) (*url.URL, error)

For logrus I guess the question is whether or not the Entry struct should be possible to marshall to JSON.
Ie. add annotations to ignore the "non-marshable" parts.

Also, the original splunk hook library has been forked several times to fix this issue. The author seems to have abondned it, so maybe the list of hooks in the documentation should be updated with a forked version?
