### ISSUE TITLE
Support field-specific coloration in TextFormatter

### ISSUE THREAD

**Issue by lthibault** [sirupsen/logrus#925]
# Motivation

When debugging complex applications, it can be hard to group lines of logging output together at a glance.  Furthermore, there may be several meaningful ways to group lines of output, e.g.: 

- by service name
- by process identifier
- by IP
- etc...

Allowing users to define per-field coloration in `logrus.TextFormatter` would give users the tools necessary to create such visual groupings, *without forcing its use*.

# Implementation

As far as I can tell, this can be accomplished in a relatively straightforward way.  I propose the following approach:

### Step 1:  define a `Colorizer` interface

Objects implementing the `Colorizer` interface will be colorized in log output.  In this example, we use [aybabtme/rbgterm](https://github.com/aybabtme/rgbterm), but this can be trivially eschewed in favor of another ANSI color library, if needed.

```go
type Colorizer interface {
    Color() string
}
```

### Step 2:  tweak `TextFormatter.appendValue` to use `Colorizer`

```go
func (f *TextFormatter) appendValue(b *bytes.Buffer, value interface{}) {
        var stringVal string
	switch value.(type) {
	case Colorizer:
		b.WriteString(value.(Colorizer).Color())
		return
	case string:
		stringVal = value.(string)
	default:
		stringVal = fmt.Sprint(value)
	}

	if !f.needsQuoting(stringVal) {
		b.WriteString(stringVal)
	} else {
		b.WriteString(fmt.Sprintf("%q", stringVal))
	}
}
```

Here's an example of an object that will be colorized when logged:

```go
type InstanceID uint64

func (id InstanceID) Color() string {
        return rgbterm.FgString(string(s), uint8(id), uint8(id>>8), uint8(id>>16))
}
```

Note that such functionality is *extremely* tedious to replicate outside of `TextFormatter` itself, and that this is fully backwards compatible.

Given the above, I think this warrants a modification to `TextFormatter`.  I'm happy to contribute the changes myself.

**Comment by dgsb** [comment]
@lthibault it looks interesting, but I wonder if the value of the foreground colour would not dynamically  depend on the background color.
Is the interface you are suggesting enough to be able to do that ?
Is it possible with rbgterm to retrieve the current background colour of the terminal ?

**Comment by lthibault** [comment]
@dgsb The proposed implementation is independent of `rbgterm`.  I'm using it as an example implementation of `Color() string`.

So yes, an implementation could fetch the background color and make appropriate decisions based on that.

**Comment by dgsb** [comment]
@lthibault a pr would be highly welcomed. However, I'd rather have that implemented in a distinct formatter like `ColoredTextFormatter` to avoid any unexpected behavioural change in the existing implementation. You may want to factorize as much as possible between both implementation.

**Comment by lthibault** [comment]
@dgsb Sure, that sounds reasonable.  I have a pretty busy week, but I'll try to find some time this weekend.  Stay tuned 😉

**Comment by lthibault** [comment]
@dgsb PR is available at https://github.com/sirupsen/logrus/pull/931

Creating a separate `ColorizedFormatter` ends up duplicating the entire `TextFormatter` while only effectively changing a couple of lines.  I **really** think these changes are best made to TextFormatter directly; again, `TextFormatter` will continue to work as before unless it is passed structures with a `Color` method.

Also, note the slightly different implementation of `Colorizer`.  This is to gracefully handle quoted values, i.e.:  those for which `needsQuoting` returns `true`.

**Comment by dgsb** [comment]
@lthibault I understand that modifying the TextFormatter would be a better engineering pratice, but our main priority is to not harm our user with incompatible changes.

**Comment by lthibault** [comment]
@dgsb Understood.  My point was that this is a fully backwards-compatible change.  If the type doesn't satisfy the `Colorizer` interface, it is treated by the same code path as before.

I'm happy to create a separate `Formatter` if necessary, but it really does seem like the wrong choice given that:

1. The changes to `TextFormatter` are backwards-compatible
2. This effectively changes 3 lines.

**Comment by renard** [comment]
@lthibault I come long time after the battle however I faced a similar use-case. I came up with a new formatter that support both colors for loglevels and hooks based on field name.

If the default hooks do not suit your need you can still add your own.

Check it out https://github.com/renard/go-cwformatter.

Comments / suggestions are welcome.
