### ISSUE TITLE
Entry WithContext does not seem to work

### ISSUE THREAD

**Issue by VincentKirsch** [sirupsen/logrus#926]
Hi, 

I'm using v1.4.0 and am trying to use the WithContext functionality like so:

```golang
requestLogger := logrus.New()
requestLogger.SetLevel(logrus.DebugLevel)

secondLogger := logrus.New()
secondLogger.SetLevel(logrus.TraceLevel)

requestEntry := requestLogger.WithFields(logrus.Fields{":::::::MySuperKey::::::": r.Header.Get("SuperKey")})
requestContextEntry := secondLogger.WithContext(context.WithValue(context.Background(), ">>>>>MySuperKey<<<<<", r.Header.Get("SuperKey")))
requestLogger.Info("Info")
requestEntry.Info("Entry Info")
requestContextEntry.Info("Context Entry Info")
requestLogger.Debug("Debug")
requestEntry.Debug("Entry Debug")
requestContextEntry.Debug("Context Entry Debug")
```
'r' is an http.Request, and I pass a value in the headers that I'd like to set in a context.
I also added similar code using WithFields that does pretty much the same.

The result is:

```
 1.   time="2019-03-20T16:00:30+01:00" level=info msg=Info

 2.   time="2019-03-20T16:00:30+01:00" level=info msg="Entry Info" 
::::::MySuperKey::::::=TestHttpHeaderValue
 3.   time="2019-03-20T16:00:30+01:00" level=info msg="Context Entry Info"

 4.   time="2019-03-20T16:00:30+01:00" level=debug msg=Debug

 5.   time="2019-03-20T16:00:30+01:00" level=debug msg="Entry Debug" ::::::MySuperKey:::::: =TestHttpHeaderValue

 6.   time="2019-03-20T16:00:30+01:00" level=debug msg="Context Entry Debug"
```
I would expect to see >>>>>MySuperKey<<<<<  in lines 3 and 6 but it's not the case.

Am I doing something wrong?

Thanks.
(Edited for formatting)

**Comment by tgwizard** [comment]
Hi @VincentKirsch!

The only thing `WithContext()` does is to set the context on the log entry. It doesn't pull any values out of the context. I believe it's impossible to iterate over all keys in the context, and in most cases not desirable either.

The purpose of `WithContext()` is to be able to propagate the context from the log point to any hooks and their processing.

Does that answer your question?

**Comment by dgsb** [comment]
@VincentKirsch the context is just added  in order to be available if neede by some hooks.

**Comment by lavoiesl** [comment]
You can look at how https://github.com/Shopify/goose/tree/master/logger wraps logrus to extract context keys and how https://github.com/Shopify/goose/tree/master/logrusbugsnag register hooks

**Comment by VincentKirsch** [comment]
Thanks everyone, huess I just mimsunderstood the purpose. It would be a nivea feature though :)

**Comment by VincentKirsch** [comment]
Hi again,

So I gave it a try with a hook. In the Fire() function for the hook, the entry's context is void.

I launched a debug session to see where it could go wrong, and it looks like the WithContext() function (entry.go) is not doing what it's supposed to:
`// Add a context to the Entry
func (entry *Entry) WithContext(ctx context.Context) *Entry { 
 entry.Context = ctx 
 return entry 
 }`

ctx is correct:
 `ctx
   <context.Context>
   data: <*context.valueCtx>(0xc000343890)
     : <context.valueCtx>
    Context: <context.Context>
     data: <*context.emptyCtx>(0xc00005c118)
      : 0
   key: <interface {}>
     data: "MySuperKey"
  val: <interface {}>
    data: "TestHttpHeaderValue"`

But after the assignation in the code above, entry still has an empty context:
`<*github.com/sirupsen/logrus.Entry>(0xc0000c2af0)
: <github.com/sirupsen/logrus.Entry>
Logger: <*github.com/sirupsen/logrus.Logger>(0xc0014e6180)
Data: <github.com/sirupsen/logrus.Fields> (length: 0)
Time: <time.Time>
Level: InfoLevel
Caller: nil <*runtime.Frame>
Message: "Context Entry Info"
Buffer: nil <*bytes.Buffer>
Context: <context.Context>
data: <*context.valueCtx>(0xc000343890)
: <context.valueCtx>
Context: <context.Context>
key: <interface {}>
data: ""
val: <interface {}>
data: ""
err: ""
Failed to eval expression:  {
 "Expr": "*(*interface {})(824637143200)",
 "Scope": {
  "goroutineID": -1,
  "frame": 0
 },
 "Cfg": {
  "followPointers": true,
  "maxVariableRecurse": 1,
  "maxStringLen": 64,
  "maxArrayValues": 64,
  "maxStructFields": -1
 }
} 
`

As you can see (sorry for the formatting, I can't seem to have github's editor to format things nicely) key and value are empty.

Would you have a working example of this feature?

Thanks!

**Comment by VincentKirsch** [comment]
OK I tried it with a hook and it works.

Thanks!
