### ISSUE TITLE
terminal_check_solaris.go doesn't have a build tag and is breaking the build on AppEngine

### ISSUE THREAD

**Issue by Hexcles** [sirupsen/logrus#947]
https://github.com/sirupsen/logrus/blob/9b3cdde74fbe9443d704467498a7dcb61a79de9b/terminal_check_solaris.go#L1

I think this file should have a build tag like:
```go
// +build solaris
```
similar to https://github.com/sirupsen/logrus/blob/9b3cdde74fbe9443d704467498a7dcb61a79de9b/terminal_check_unix.go#L1

I believe this is the reason logrus currently fails to build on AppEngine standard projects (where we can't use `golang.org/x/sys/unix`).

**Comment by dgsb** [comment]
I don't fix it will fix the build break because the _<platform_name>.go is an implicit +<platform_name> build constraint.
You can try that fix anyway and we will see what happens.

**Comment by dgsb** [comment]
Just curious how do you build for appengine ? Cross-compile from a linux host ?

**Comment by Hexcles** [comment]
@dgsb sorry, looks like my proposed fix wouldn't solve the problem, but bisecting led me to the real culprit that is also related to `terminal`: #943 , which moved `terminal` package into the root `logrus` package.

My AppEngine project imports the `github.com/sirupsen/logrus` package but not `terminal`. Before #943 my project deploys fine but once I check out past #943 I'm seeing this error:
```
2019/04/05 08:35:03 go-app-builder: Failed parsing input: parser: bad import "unsafe" in golang.org/x/sys/unix/affinity_linux.go
```

I'm not exactly familiar with the underlying implementation of AppEngine Go. The SDK actually bundles in a special go toolchain to build the binary. Any `unsafe` stuff (for example in `golang.org/x/sys/unix`, which is imported by various `terminal_check*.go`) can't be used on AppEngine. Previously things worked since the `terminal` package was separate and I never import it.
