### ISSUE TITLE
Is it possible to use CRLF line endings rather than LF? 

### ISSUE THREAD

**Issue by marioarizaj** [sirupsen/logrus#951]
Hello, I am using logrus in a few projects and I am wondering if there is a setting to switch from LF line endings to CRLF for a better log output in windows. 
Thank you

**Comment by dgsb** [comment]
Hello @marioarizaj, it seems that mostly the go standard library does not handle the specific windows line termination.
However we may add that specifically in logrus somehow, but we need to check what would be the impact first.

**Comment by reedwade** [comment]
I've found that I want it sometimes when logging in Windows but not always so I hope the current behaviour doesn't change. I'm using this with good results:

```
import "github.com/andybalholm/crlf"

if runtime.GOOS == "windows" {
  logger.SetOutput(crlf.NewWriter(logger.Out))
}
```

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
