### ISSUE TITLE
Goland/Docker output is incorrect

### ISSUE THREAD

**Issue by skliarovartem** [sirupsen/logrus#952]
When I run app in Goland or Docker I see logs like:
{"level":"info","msg":"1. Init Keys...","time":"2019-04-15T10:21:00+03:00"}
But when I run the same app in terminal (MacOS) it works properly
I was trying to use different formatters but it is always looks wrong
Is it possible to fix it somehow? It is difficult to read logs in such way
thanks!

**Comment by dgsb** [comment]
I don't see anything strange in your trace sample, what would expect ?
Can you provide both output sample to see what is the difference ?

**Comment by skliarovartem** [comment]
I've found how to get expected result. It is `ForceColors: true` parameter of TextFormatter. Now it looks readably. Issue can be closed.
Many thanks!
