### ISSUE TITLE
[Feature Request] Add an pad option log level text

### ISSUE THREAD

**Issue by lynncyrin** [sirupsen/logrus#959]
### What

~I would like a `TextFormatter` option that outputs in a 5 character / 4 character + 1 padding space output mode. I'm tentatively calling it `FourAndFiveCharacterTruncation` (feedback requested on that name)~

Taking in the feedback provided in the comments, I would instead like a `TextFormatter` option that outputs the level text with padding up to the max length. I'm tentatively calling it `PadLevelText`. It would look like so

```
INFO    some information
WARNING some warning
DEBUG   some debug information
```

### Why

The above example is in contrast to the current default behavior of

```
INFO some information
WARN some warning
DEBU some debug information
```

And the `DisableLevelTruncation` behavior of

```
INFO some information
WARNING some warning
DEBUG some debug information
```

(`FATAL`, `PANIC`, and `TRACE` not explicitly mentioned above for the sake of conciseness, they would all output at 5 characters just like `DEBUG`)

### Who

This feature request is essentially the "pad" option that mentioned in https://github.com/sirupsen/logrus/pull/407#issuecomment-274781317

I intend to create the PR for this myself, if you all don't mind ^^ Haven't had an OSS contribution in a too-long now. I'll start on that if I get >=1 👍 react from a Contributor

**Comment by lynncyrin** [comment]
@dgsb, @sirupsen, @lavoiesl would any of you happen to have an opinion about this feature request? I'd love to help out with this package!

**Comment by dgsb** [comment]
Indeed the truncated level looks weird to me.
But rather than pad to an arbitrary value and truncate beyond, why not pad to the largest level string representation ?
wdyt ?

**Comment by lynncyrin** [comment]
Padding to the largest level string representation would look good and be less work to implement. I'm for it! @dgsb 👍

---

(_tangentially:_ I think my ideal end state would be pad to the largest string representation and change the cli text of `WARNING` to `WARN`. But the warn change is a different matter, and possibly a breaking change, so I'll consider that separately.)

**Comment by lynncyrin** [comment]
For the sake of completeness, here's what a pad option would look like

```
INFO    some information
WARNING some warning
DEBUG   some debug information
```

I'll edit the OP to reflect this instead (...)

**Comment by gauravaditya** [comment]
Hi,

Just wondering if the "PadLevelText" option on text formatter is not yet released, though the docs say it is usable. Let me know if i am missing something.
Thanks

**Comment by lynncyrin** [comment]
@gauravaditya my PR merged on [`July 1st`](https://github.com/sirupsen/logrus/pull/977) and the most recent release is [`May 18`](https://github.com/sirupsen/logrus/releases). So no, it has no been released. The docs reflect `master`, not the most recent release. If you want to view the documentation for the most recent release, that's available here => https://github.com/sirupsen/logrus/tree/v1.4.2

In related news, @dgsb & @sirupsen this package could use more maintainers, IMO 🙂. I recently helped push out release 2.0 for https://github.com/urfave/cli/, and would be available to help out here! Let me know if you're interested, either here or via ✉️ `lynncyrin@gmail.com`
