### ISSUE TITLE
Color for earlier Windows versions

### ISSUE THREAD

**Issue by ghost** [sirupsen/logrus#965]
Color is supported with Windows 10 like this:

~~~go
package main
import "github.com/sirupsen/logrus"
func main() {
   logrus.SetFormatter(&logrus.TextFormatter{ForceColors: true})
   logrus.Info("aaaaa bbbbb")
}
~~~

However this does not work with earlier Windows versions. For earlier Windows,
the current suggestion is to add another import:

https://github.com/sirupsen/logrus#formatters

Example:

~~~go
package main
import "github.com/mattn/go-colorable"
import "github.com/sirupsen/logrus"
func main() {
   logrus.SetFormatter(&logrus.TextFormatter{ForceColors: true})
   logrus.SetOutput(colorable.NewColorableStdout())
   logrus.Info("aaaaa bbbbb")
}
~~~

However I noticed that other packages do not have this requirement:

https://github.com/labstack/gommon

This works with earlier Windows versions:

~~~go
package main
import "github.com/labstack/gommon/color"
func main() {
   color.Enable()
   color.Println(color.Green("aaaaa bbbbb"))
}
~~~

because the **go-colorable** package is imported internally:

https://github.com/labstack/gommon/blob/82ef680a/color/color.go#L9

Could something like this be done with Logrus so that code can be written more
portably?

**Comment by cup** [comment]
https://github.com/sirupsen/logrus/pull/822

**Comment by cup** [comment]
https://github.com/sirupsen/logrus/pull/957
