### ISSUE TITLE
Enable or disable a contextlogger

### ISSUE THREAD

**Issue by Wisse1996** [sirupsen/logrus#967]
Hi there, 

We have a project with multiple packages i would like to implement a context logger for each package. I was wondering if it is possible to disable a logger so that the logs will not apear. Or is there another way to achieve this. 

thanks in advance.

**Comment by dgsb** [comment]
If you want to discard all logs, you can replace the Out field of the logger with a ioutil.Discard or implements your own io.Writer which does nothing on the Write method.
Beware that the `panic` and `Fatal` call will still respectively panic and call os.Exit

**Comment by kennykarnama** [comment]
Add an example, simply beside using ioutil.Discard, you could use bytes.Buffer
```
silentLog := logrus.New()
var b bytes.Buffer
silentLog.SetOutput(&b)
```

**Comment by dgsb** [comment]
Using a bytes.Buffer will consume your memory

**Comment by kennykarnama** [comment]
@dgsb thanks for mentioning it. actually, i am really new in go programming. Big thanks

**Comment by Wisse1996** [comment]
Thanks for the reply setting the loggers Out to ioutil.Discard solves the problem!
