### ISSUE TITLE
log empty msg 

### ISSUE THREAD

**Issue by chinfuyang** [sirupsen/logrus#971]
Hi, guys.
I am logging text formatter withFields to console.
And I only want to log the fields to console.
When I do `log.withFields(&logrus.Fields).Info()`. 
There is message space padding output to console.

Please help me to find out the solution. Thank you.

- My envirnment:
    logrus version : v1.4.1
    go version : 1.12
    os : windows 10

English is not my native language; please excuse typing errors.

- For Example

    - my format

        ```go
        log.SetFormatter(&logrus.TextFormatter{
                    ForceColors:     true,
                    FullTimestamp:   true,
                    TimestampFormat: "2006-01-02 15:04:05",
                })
        ```

    - my code

        ```go
        log.WithFields(logrus.Fields{
                "Method":       r.Method,
                "URI":          r.RequestURI,
                "Status Code":  responseWriter.Status(),
            }).Info()
        log.Debug("test")
        ```

    -  got

        ```
        INFO[2019-05-23 01:04:15]                                               Method=GET Status Code=401 URI="test"
        DEBU[2019-05-23 01:04:15] test
        ```
        
    - expected

        ```
        INFO[2019-05-23 01:04:15] Method=GET Status Code=401 URI="test"
        DEBU[2019-05-23 01:04:15] test
        ```

**Comment by zhaogaolong** [comment]
@YangChinFu  How to raise a good question
>https://www.zhihu.com/question/62887673

**Comment by YangChinFu** [comment]
Sorry.
English isn't my native language.
I will revise my issue.

**Comment by dgsb** [comment]
This how the TextFormatter displays text when output color mode is activated.
See here https://github.com/sirupsen/logrus/blob/2a22dbedbad1fd454910cd1f44f210ef90c28464/text_formatter.go#L246
the `%-44s' is the reason of the padding.
It's been there since the first implementation of the TextFormatter.
If you disable the output color mode you will have no padding.

**Comment by YangChinFu** [comment]
Thanks for your reply!
But when I disable the output color mode, I got the output below

```
time="2019-05-26 22:12:52" level=info Method=GET Service Time=0.0005 Status Code=200 URI=/test
```

but I want to get

```
INFO[2019-05-26 22:12:52] level=info Method=GET Service Time=0.0005 Status Code=200 URI=/test
```

Is there any possibility to add pretty mode option?
example  `outputFormat : stblib or pretty`

Thank you.

**Comment by pradykaushik** [comment]
You can register your own [Formatter](https://github.com/sirupsen/logrus/blob/master/formatter.go#L26) like shown below.
```go
type MyFormatter struct {}
func (f MyFormatter) Format(entry *logrus.Entry) ([]byte, error) {
    // Use the information from entry and create the log message in the format that you want.
    // Cast to a []byte and return.
}

l := &logrus.Logger{
    Formatter: MyFormatter,
}
l.Log(logrus.InfoLevel, "test message")
```
