### ISSUE TITLE
Need caller skip

### ISSUE THREAD

**Issue by dongshimou** [sirupsen/logrus#972]
```
	if entry.Logger.ReportCaller {
//  		entry.Caller = getCaller()
		entry.Caller = getCaller(entry.Logger.CallerSkip)
	}
```
```
func getCaller(skip int) *runtime.Frame {
...
		if pkg != logrusPackage {
			if skip!=0 {
				skip--
				continue
			}
			return &f
		}
}
```
I can skip custom deep.

**Comment by dongshimou** [comment]
#973

**Comment by dgsb** [comment]
I agree the current implementation doesn't match all needs, however I'm not sure skipping an arbitrary number of frames is flexible enough.

**Comment by dongshimou** [comment]
@dgsb skip some package? like `if pkg != logrusPackage`.
i think we need a method to skip some package.

**Comment by Turing-Chu** [comment]
+1

**Comment by sepehrmm** [comment]
@dgsb I think skipping is a good idea (for my use case) but if another solution is preferable for some other use cases then we can add it later and prioritize them or the second method which is called can overwrite the first one.

**Comment by starudream** [comment]
+1

**Comment by freeformz** [comment]
Can the use cases for providing some sort of flexibility wrt fram skipping be detailed here? I don't quite follow them. My general question is why do people need this? Is there something else we can change so that you don't need to wrap logrus?

**Comment by tech-a-go-go** [comment]
@freeformz 

> My general question is why do people need this?

I'm wrapping logrus with lumberjack to rotate log files as following code.
However, the caller always points this code so logrus.SetReportCaller(true) is basically not working... (it's working but useless. I cannot figure out who calls this code's Infof, Debugf...)
That's the reason I'd like to set my custon getCaller function.

`
package foo

import (
　　　　"github.com/sirupsen/logrus"
　　　　"gopkg.in/natefinch/lumberjack.v2"
　　　　"os"
)

const (
　　　　envProduction  = "production"
　　　　envStaging     = "staging"
　　　　envDevelopment = "development"
)

func init() {
　　　　var environment string
　　　　switch os.Getenv("GO_ENV") {
　　　　case envProduction, envStaging, envDevelopment:
　　　　　　　　environment = os.Getenv("GO_ENV")
　　　　default:
　　　　　　　　environment = envDevelopment
　　　　}

　　　　logrus.SetFormatter(&logrus.JSONFormatter{})
              logrus.SetReportCaller(true)

　　　　if environment == envProduction {
　　　　　　　　logrus.SetLevel(logrus.InfoLevel)
　　　　} else {
　　　　　　　　logrus.SetLevel(logrus.DebugLevel)
　　　　}

　　　　if environment == envDevelopment {
　　　　　　　　logrus.SetOutput(os.Stdout)
　　　　} else {
　　　　　　　　logrus.SetOutput(&lumberjack.Logger{
　　　　　　　　　　　　Filename:  "log/" + environment + ".log",
　　　　　　　　　　　　MaxAge:    365,
　　　　　　　　　　　　LocalTime: true,
　　　　　　　　　　　　Compress:  true,
　　　　　　　　})
　　　　}
}

func Fatal(args ...interface{}) {
　　　　logrus.Fatal(args...)
}

func Fatalf(format string, args ...interface{}) {
　　　　logrus.Fatalf(format, args...)
}

func Error(args ...interface{}) {
　　　　logrus.Error(args...)
}

func Errorf(format string, args ...interface{}) {
　　　　logrus.Errorf(format, args...)
}

func Info(args ...interface{}) {
　　　　logrus.Info(args...)
}

func Infof(format string, args ...interface{}) {
　　　　logrus.Infof(format, args...)
}

func Debug(args ...interface{}) {
　　　　logrus.Debug(args...)
}

func Debugf(format string, args ...interface{}) {
　　　　logrus.Debugf(format, args...)
}
`

**Comment by freeformz** [comment]
@tech-a-go-go I don't understand why you are wrapping Fatal/Fatalf/Error/etc.
The example package is configuring the global logrus instance, why don't you use `logrus.Fatal` and the like in your code directly?

**Comment by sepehrmm** [comment]
@freeformz Makes it easier for later swapping of a dependency with another one without changing every use case code, you just need to change the wrapper package.

**Comment by didrocks** [comment]
Another use-case is to be able to log to multiple places. For instance:
* log in the current daemon
* under some conditions, send as well the log to the client (like, via a grpc stream connection).

Note that daemon and client don't necessarily have the same verbosity level request (so using 2 loggers). The daemon can run with -debug and the client without it for instance (only showing warning/errors)
The wrapper does the dispatch and will be the one reported in the call frame. Skipping a package sounds like a good way to solve this.

**Comment by freeformz** [comment]
fair enough, although IMO loggers should be injected, not sourced from a global.

**Comment by tech-a-go-go** [comment]
@freeformz

Thank you for the reply.
> I don't understand why you are wrapping Fatal/Fatalf/Error/etc.

That is because I might substitute the underlying logging system.

> The example package is configuring the global logrus instance, why don't you use logrus.Fatal and the like in your code directly?

True. It's fine for now. so I follow the way you said.

Thank you!

**Comment by byates** [comment]
One other reason to wrap logrus is to force standard log message forms across many applications. I would be happy with a list of packages to skip.

**Comment by freeformz** [comment]
@byates I'd recommend doing that by creating a package that returns a properly configured logrus logger instead of wrapping logrus. This will give you the "standard log message" forms w/o having to wrap logrus. What am I missing that this method doesn't cover?

**Comment by hellastorm** [comment]
@freeformz When I say "standard log message" I mean we have specific methods for each error message that enforce the same text and variable layout for a message. This is in addition to adding some consistent JSON fields. Since the user is calling one of our methods to do the logging (and passing in the arguments) this puts the frame stack in our code, not in logrus.

**Comment by byates** [comment]
@freeformz When I say "standard log message" I mean we have specific methods for each error message that enforce the same text and variable layout for a message. This is in addition to adding some consistent JSON fields. Since the user is calling one of our methods to do the logging (and passing in the arguments) this puts the frame stack in our code, not in logrus.

**Comment by freeformz** [comment]
@byates I'm still not sure I *completely* understand the use case. Can you give a semi complete code example?

**Comment by byates** [comment]
This is a work in progress and I'm happy to here about better ways to do this.

```
package` hellalog

import (
	"runtime"

	"github.com/natefinch/lumberjack"
	"github.com/sirupsen/logrus"
)

// Event stores messages to log later, from our standard interface
type Event struct {
	id      int
	message string
}

// LogObj enforces specific log message formats
type LogObj struct {
	log     *logrus.Logger
	Version string
}

// Default log object to be used by imported packages
var Default = NewLoggerStdOut("")

func callerPrettyfier(f *runtime.Frame) (function string, file string) {

	return f.Function, "test"
}

// NewLoggerStdOut initializes the standard logger
func NewLoggerStdOut(version string) *LogObj {
	var baseLogger = logrus.New()
	var TheLog = &LogObj{baseLogger, version}
	TheLog.log.Formatter = &logrus.JSONFormatter{
		// Override the timestamp to add milliseconds to the standard RFC3339 format.
		TimestampFormat: "2006-01-02T15:04:05.999999Z07:00",
		// Override the CallerPrettyfier to shorten the file name.
		CallerPrettyfier : callerPrettyfier}
	// False until logrus is patched to allow a list of packages to skip (or a count).
	TheLog.log.SetReportCaller(false)
	return TheLog
}

// NewLoggerFile initializes the standard logger
func NewLoggerFile(version string, filename string, maxSize int, maxAge int, maxBackups int) *LogObj {
	var baseLogger = logrus.New()
	var TheLog = &LogObj{baseLogger, version}
	TheLog.log.Formatter = &logrus.JSONFormatter{}
	TheLog.log.SetReportCaller(true)
	TheLog.log.SetOutput(&lumberjack.Logger{Filename: filename, MaxSize: maxSize, MaxAge: maxAge, MaxBackups: maxBackups})
	return TheLog
}

// Declare variables to store log messages as new Events
var (
	genericTraceMessage               = Event{1, "%s"}
	genericDebugMessage               = Event{2, "%s"}
	genericInfoMessage                = Event{3, "%s"}
	genericWarnMessage                = Event{4, "%s"}
	genericErrorMessage               = Event{5, "%s"}
	badOptionsMessage                 = Event{6, "Error parsing options: %s"}
	invalidLogPath                    = Event{7, "Log path '%s' does not exist"}
	invalidLogLevel                   = Event{8, "Log level (%s) is not valid"}
	invalidArgMessage                 = Event{9, "Invalid arg: %s"}
	invalidArgValueMessage            = Event{10, "Invalid value for argument: %s: %v"}
	missingArgMessage                 = Event{11, "Missing arg: %s"}
	unableToConnectToNatsMessage      = Event{12, "Unabled to connect to nats server at '%s'"}
	natsPubFailedMessage              = Event{13, "NATS pub to '%s' failed with message '%s'"}
	natsSubFailedMessage              = Event{14, "NATS sub to '%s' failed with message '%s'"}
	hsBlobGetFailedMessage            = Event{15, "HsBlobStore Get from '%s' failed with message '%s'"}
	azureUploadFailedMessage          = Event{16, "Azure upload to '%s' failed with message '%s'"}
	azureCreateContainerFailedMessage = Event{17, "Azure create container (%s) account '%s' failed with message '%s'"}
	azureRemoveContainerFailedMessage = Event{18, "Azure remove container (%s) account '%s' failed with message '%s'"}
	jsonUnmarshalFailedMessage        = Event{19, "JSON parsing error '%s' on data: '%s'"}
	jsonDecodeFailedMessage           = Event{20, "JSON parsing error of file '%s'"}
	unknownObjMessage                 = Event{21, "'%s' is not a valid value for type '%s'"}
	configFileNotFoundMessage         = Event{22, "Config file not found at '%s'"}
)

// SetLevel sets the logger level.
func (l *LogObj) SetLevel(sLvl string) error {
	lvl, err := logrus.ParseLevel(sLvl)
	if err != nil {
		return err
	}
	l.log.SetLevel(lvl)
	return nil
}

// stdFields adds standard fields to entry
func (l *LogObj) stdFields(id int) *logrus.Entry {
	e := l.log.WithFields(
		logrus.Fields{"ver": l.Version, "id" : id})
	return e
}

// GenericInfo is a standard info message
func (l *LogObj) withStdFields(id int, fields logrus.Fields) *logrus.Entry {
	e := l.stdFields(id).WithFields(fields)
	return e
}

// GenericTrace is a standard info message
func (l *LogObj) GenericTrace(argumentName string) {
	l.stdFields(genericTraceMessage.id).Tracef(genericTraceMessage.message, argumentName)
}

// GenericDebug is a standard info message
func (l *LogObj) GenericDebug(argumentName string) {
	l.stdFields(genericTraceMessage.id).Debugf(genericDebugMessage.message, argumentName)
}

// GenericInfo is a standard info message
func (l *LogObj) GenericInfo(argumentName string) {
	l.stdFields(genericTraceMessage.id).Infof(genericInfoMessage.message, argumentName)
}

// GenericWarn is a standard warning message
func (l *LogObj) GenericWarn(argumentName string) {
	l.stdFields(genericTraceMessage.id).Infof(genericWarnMessage.message, argumentName)
}

// GenericError is a standard error message
func (l *LogObj) GenericError(argumentName string) {
	l.stdFields(genericTraceMessage.id).Infof(genericErrorMessage.message, argumentName)
}

// InvalidOptions is a standard error message for when options can't be parsed
func (l *LogObj) InvalidOptions(parserErr string) {
	l.stdFields(genericTraceMessage.id).Errorf(badOptionsMessage.message, parserErr)
}

// InvalidLogPath is a standard error message when log path doesn't exist
func (l *LogObj) InvalidLogPath(logDir string) {
	l.stdFields(genericTraceMessage.id).Errorf(invalidLogPath.message, logDir)
}

// InvalidLogLevel is a standard error message when log level is not valid
func (l *LogObj) InvalidLogLevel(logLevel string) {
	l.stdFields(genericTraceMessage.id).Errorf(invalidLogLevel.message, logLevel)
}

// InvalidArg is a standard error message
func (l *LogObj) InvalidArg(argumentName string) {
	l.stdFields(genericTraceMessage.id).Errorf(invalidArgMessage.message, argumentName)
}

// InvalidArgValue is a standard error message
func (l *LogObj) InvalidArgValue(argumentName string, argumentValue string) {
	l.stdFields(genericTraceMessage.id).Errorf(invalidArgValueMessage.message, argumentName, argumentValue)
}

// MissingArg is a standard error message
func (l *LogObj) MissingArg(argumentName string) {
	l.stdFields(genericTraceMessage.id).Errorf(missingArgMessage.message, argumentName)
}

// UnableToConnectToNats is a standard error message
func (l *LogObj) UnableToConnectToNats(serverAddr string) {
	l.stdFields(genericTraceMessage.id).Errorf(unableToConnectToNatsMessage.message, serverAddr)
}

// NatsPubFailed is a standard error message
func (l *LogObj) NatsPubFailed(channel string, why string) {
	l.stdFields(genericTraceMessage.id).Errorf(natsPubFailedMessage.message, channel, why)
}

// NatsSubFailed is a standard error message
func (l *LogObj) NatsSubFailed(channel string, why string) {
	l.stdFields(genericTraceMessage.id).Errorf(natsSubFailedMessage.message, channel, why)
}

// HsBlobStoreGetFailed is a standard error message
func (l *LogObj) HsBlobStoreGetFailed(uri string, why string) {
	l.stdFields(genericTraceMessage.id).Errorf(hsBlobGetFailedMessage.message, uri, why)
}

// AzureUploadFailed is a standard error message
func (l *LogObj) AzureUploadFailed(account string, why string) {
	l.stdFields(genericTraceMessage.id).Errorf(azureUploadFailedMessage.message, account, why)
}

// AzureCreateContainerFailed is a standard error message
func (l *LogObj) AzureCreateContainerFailed(container string, account string, why string) {
	l.stdFields(genericTraceMessage.id).Errorf(azureCreateContainerFailedMessage.message, container, account, why)
}

// AzureRemoveContainerFailed is a standard error message
func (l *LogObj) AzureRemoveContainerFailed(container string, account string, why string) {
	l.stdFields(genericTraceMessage.id).Errorf(azureRemoveContainerFailedMessage.message, container, account, why)
}

// JSONUnmarshalFailed is a standard error message
func (l *LogObj) JSONUnmarshalFailed(data string, why string) {
	limited := data
	if len(limited) > 40 {
		limited = limited[0:40] + "..."
	}
	l.stdFields(genericTraceMessage.id).Errorf(jsonUnmarshalFailedMessage.message, why, limited)
}

// JSONDecodeFailed is a standard error message
func (l *LogObj) JSONDecodeFailed(fileName string) {
	l.stdFields(genericTraceMessage.id).Errorf(jsonDecodeFailedMessage.message, fileName)
}

// UnknownObjMessage is a standard error message
func (l *LogObj) UnknownObjMessage(objName string, unknownValue string) {
	l.stdFields(genericTraceMessage.id).Errorf(unknownObjMessage.message, unknownValue, objName)
}

// ConfigFileNotFound is a standard error message for a file of some type doesn't exist
func (l *LogObj) ConfigFileNotFound(path string) {
	l.stdFields(genericTraceMessage.id).Errorf(configFileNotFoundMessage.message, path)
}
```

**Comment by freeformz** [comment]
@byates Thanks! Let me make sure I understand how this is intended to be used:

```go
hellalog.Default.InvalidArgValue("config","blahblahblah")
// -> {"id":10,"level":"error","msg":"Invalid value for argument: config: blahblahblah","time":"...","ver":""}

// and

l := hellalog.NewLoggerStdOut("12")
l.InvalidArgValue("config","blahblahblah")
// -> {"id":10,"level":"error","msg":"Invalid value for argument: config: blahblahblah","time":"...","ver":"12"}
```

Correct ?

If so does this exemplify what others a looking for ? If not, please detail how your use case varies.

Thanks!

**Comment by uzuku** [comment]
> Can the use cases for providing some sort of flexibility wrt fram skipping be detailed here? I don't quite follow them. My general question is why do people need this? Is there something else we can change so that you don't need to wrap logrus?

@freeformz I'm using logrus wrapped by virtual-kubelet/virtual-kubelet so i need skip some extra caller frames, as it provides more convenient way to handle log fields, that is, storing the fields in context, and the fields can be used many times after declaring only once, and can be removed from context by calling an `End` method.

I also saw there are many different wrappers above to achieve different goals.

IMO it is beyond logrus's scope to support the utils provided by all these wrappers, just like log rotate utility, off-load the util to some wrapper is quite reasonable. And even logrus can finally find a decent solution for all the wrappers, a **quick** workaround is necessary for people like me to use logrus in a quite urgent project. Now this issue has been opened for 5 months with multiple prs while no essential progress is made. Skipping some frames is not so bad as a quick workaround, please consider it.

Thanks.

**Comment by tech-a-go-go** [comment]
@freeformz 

> fair enough, although IMO loggers should be injected, not sourced from a global.

Actually it's difficult to be injected because logrus uses global functions such as Info, Infof, ... so it's impossible to use Interfaces.

**Comment by byates** [comment]
@freeformz Your example of use of our `hellalog` wrapper is correct.

**Comment by freedemster** [comment]
Hi,

Are there any updates on this issue?

**Comment by Blquinn** [comment]
I'm having an issue where I only see the logrus entry code being logged as the caller. 
```
{"file":"entry.go:314","func":"github.com/sirupsen/logrus.(*Entry).Logf()","message":"foobar"}
```
Makes the caller logging useless even though I'm not wrapping the logger.

**Comment by ranglust** [comment]
@Blquinn I'm seeing the same issue, though, when running the code from within an IDE the caller parsing works as expected. 
did you manage to overcome this issue?

**Comment by Blquinn** [comment]
@ranglust This issue was fixed [here](https://github.com/sirupsen/logrus/pull/1102) so just updating to latest logrus should fix it.

**Comment by exgalibas** [comment]
maybe this can help u guys https://github.com/exgalibas/logrus-filename

**Comment by jlearman** [comment]
I think that questioning "why wrap <my nifty package>" is missing the boat.  There are many reasons to wrap any package, and this isn't the place to discuss it.

My reason for wrapping it could be solved by adding a feature: I want warnings and errors to increment warning/error counters.

Regardless, a useful package should be designed so that it can be wrapped, rather than expecting the package to meet every possible use case.  Adding `SetCallerSkip()` is the right fix.

**Comment by jlearman** [comment]
> I agree the current implementation doesn't match all needs, however I'm not sure skipping an arbitrary number of frames is flexible enough. We need to provide a practical API which would be usable for everyone

Zerolog has this feature, and I can confirm from experience that it allows wrapping Zerolog.

Please reopen this, and rather than waiting for some solution that fits unknown possible future use cases, implement a simple fix that meets known use cases.

I suggest `SetCallerReportSkipFrames()` or something like that.  Calling it would imply `SetCallerReport()`.
