### ISSUE TITLE
Log every X logs, or atMost

### ISSUE THREAD

**Issue by aclowkey** [sirupsen/logrus#975]
Hi,
I wanted to ask if there is support for periodic logging, such log at most once, in 10 seconds or log every X logs.

This is useful for getting a "snapshot" of what was logged, without logging too much.Similar to what flogger has

Thanks

**Comment by dgsb** [comment]
There is nothing builtin logrus for doing that, however that can be easily implemented by a specific writer you can set in the `Out` field of the logger.
