### ISSUE TITLE
Bolt Hook

### ISSUE THREAD

**Issue by kennykarnama** [sirupsen/logrus#976]
Hi guys, i found that in the wiki page indicating hooks availaible for logrus not including [bolt](https://github.com/boltdb/bolt).
in fact, there are two hooks available for bolt

1. https://github.com/trK54Ylmz/logrus-boltdb-hook
2. https://github.com/kennykarnama/logrus-bolt-hook

Just wondering, could you mention it in the wiki page ? 😃 
Thanks.

**Comment by freeformz** [comment]
Done. Thanks!
