### ISSUE TITLE
Race condition when growing the buffer

### ISSUE THREAD

**Issue by kunshah** [sirupsen/logrus#978]
There seems to be race condition when growing buffer and another go-routing reading from it

==================
WARNING: DATA RACE
Write at 0x00c4201e7730 by goroutine 59:
  bytes.(*Buffer).grow()
      /usr/local/go/src/bytes/buffer.go:146 +0x235
  bytes.(*Buffer).Write()
      /usr/local/go/src/bytes/buffer.go:174 +0x14f
  ../vendor/github.com/sirupsen/logrus.(*Entry).write()
      /../vendor/github.com/sirupsen/logrus/entry.go:259 +0x26d
  ../vendor/github.com/sirupsen/logrus.Entry.log()
      /../vendor/github.com/sirupsen/logrus/entry.go:231 +0x2fd
  ../vendor/github.com/sirupsen/logrus.(*Entry).Log()
      /../vendor/github.com/sirupsen/logrus/entry.go:268 +0x137
  ../vendor/github.com/sirupsen/logrus.(*Entry).Info()
      /../vendor/github.com/sirupsen/logrus/entry.go:285 +0x5e
  ../vendor/github.com/sirupsen/logrus.(*Entry).Print()
      /../vendor/github.com/sirupsen/logrus/entry.go:281 +0x56
  ../vendor/github.com/sirupsen/logrus.(*Logger).Print()
      /../vendor/github.com/sirupsen/logrus/logger.go:211 +0x6d

Previous read at 0x00c4201e7730 by goroutine 119:
  ../tasks.TestPayments()
      /usr/local/go/src/bytes/buffer.go:66 +0xa616
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:777 +0x16d

Goroutine 119 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:824 +0x564
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1063 +0xa4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:777 +0x16d
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1061 +0x4e1
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:978 +0x2cd
  main.main()
      _testmain.go:106 +0x324

**Comment by dgsb** [comment]
Can you provide a unit test which would exhibit this issue ?

**Comment by manebih** [comment]
Please help me get my phone secure and remove remotes tags patterns Bluetooth bootloader etc. I need 2 be debugged

**Comment by johnrengelman** [comment]
I've seen this error and it was because I was creating by own byte buffer in a test, setting it as the output for logrus, and then trying to read the contents of the buffer in the test.
I fixed it by using the `Logger.Hooks.Add(Hook)` method  to create a callback to watch for the messages I cared about.

**Comment by dgsb** [comment]
can we close this issue @johnrengelman ?

**Comment by johnrengelman** [comment]
I would think so. The OP looks to be doing a test so using the Hooks would be the right way
