### ISSUE TITLE
Omit empty string values

### ISSUE THREAD

**Issue by fallais** [sirupsen/logrus#980]
Hi,

Is there a way to omit empty string values ? To avoid displaying `value=""`.
Like the JSON `omitempty` feature.

Thanks.

**Comment by manebih** [comment]
Please help me get my phone secure and remove remotes tags patterns Bluetooth bootloader etc.

**Comment by pradykaushik** [comment]
Are you talking about the value in `logrus.Field`?

**Comment by fallais** [comment]
Yes

**Comment by pradykaushik** [comment]
I see. I don't think there's a straightforward way of doing that. One way (probably the only way now) is by implementing your own Formatter and registering that with the Logger. That way, you have all the freedom to filter out fields when logging.

However, this wouldn't be too difficult to add as a feature to the existing Formatters. I seem to have found a way to add this feature in. I will keep you posted :)

**Comment by pradykaushik** [comment]
Working on the feature addition for this. You can follow it [here](https://github.com/pradykaushik/logrus/tree/issues/logemptyvalues).

**Comment by fallais** [comment]
Thanks a lot !

**Comment by pradykaushik** [comment]
You can now follow pull request [Field Filters](#1011).

**Comment by freeformz** [comment]
Direct link to my example: https://play.golang.org/p/bampaVhZMmf
