### ISSUE TITLE
text log should remove trailing space

### ISSUE THREAD

**Issue by crquan** [sirupsen/logrus#99]
current code is generating every log line with a trailing space, which is not good and should be eliminated

``` go
tf := &TextFormatter{DisableColors: true}
byts, _ := tf.Format(&Entry{Message: "msg content"})
fmt.Printf("%q\n", string(byts))
```

``` text
"time=\"0001-01-01T00:00:00Z\" level=panic msg=\"msg content\" \n"
```

**Comment by crquan** [comment]
since #100 is reverted, should this be open again?

**Comment by Sirupsen** [comment]
I'll take a look later this week

**Comment by crquan** [comment]
@Sirupsen what else changes do you want to see in this set?
https://github.com/crquan/logrus/compare/patch-1

**Comment by stevvooe** [comment]
@crquan @Sirupsen Is this still an issue?
