### ISSUE TITLE
custom key sort function not called when colors are enabled

### ISSUE THREAD

**Issue by apmattil** [sirupsen/logrus#994]
custom key sort function not called when colors are enabled.
is this a bug or functionality ?

**Comment by dgsb** [comment]
It should be called IIRC. Can you provide a simple code sample which would exhibit the issue ?

**Comment by dgsb** [comment]
There may be some fixed fields which are never sorted (like timestamp, level, ...) the sorting function may only be called on user specific field.

**Comment by Zach593** [comment]
It's weird that no one cares about this.

![image](https://user-images.githubusercontent.com/19605723/89605195-8d491c80-d89f-11ea-9319-7678a82e8fa0.png)
 
```
package main

import (
	"bytes"
	"fmt"
	"runtime"
	"sort"

	log "github.com/sirupsen/logrus"
)

func initLogger() {
	log.AddHook(new(GoIDFieldHook))
	log.SetFormatter(&log.TextFormatter{
		SortingFunc: SortingFunc,
	})
}

type GoIDFieldHook struct{}

func (h *GoIDFieldHook) Levels() []log.Level {
	return log.AllLevels
}

func (h *GoIDFieldHook) Fire(e *log.Entry) error {
	e.Data["go_id"] = fmt.Sprint(goID())
	return nil
}

var routinePrefix = []byte("goroutine ")

func goID() string {
	buf := make([]byte, 32)
	runtime.Stack(buf, false)
	return string(bytes.Fields(bytes.TrimPrefix(buf, routinePrefix))[0])
}

var fieldSeq = map[string]int{
	"time":  0,
	"level": 1,
	"go_id": 2,
}

func SortingFunc(fields []string) {
	fmt.Println(fields)
	sort.Slice(fields, func(i, j int) bool {
		if fields[i] == "msg" {
			return false
		}
		if iIdx, oki := fieldSeq[fields[i]]; oki {
			if jIdx, okj := fieldSeq[fields[j]]; okj {
				return iIdx < jIdx
			}
			return true
		}
		return false
	})
	fmt.Println(fields)
}

func main() {
	initLogger()
	log.Info("something")
}
```

**Comment by idcooldi** [comment]
> It's weird that no one cares about this.
> 
> ![image](https://user-images.githubusercontent.com/19605723/89605195-8d491c80-d89f-11ea-9319-7678a82e8fa0.png)
> 
> ```
> package main
> 
> import (
> 	"bytes"
> 	"fmt"
> 	"runtime"
> 	"sort"
> 
> 	log "github.com/sirupsen/logrus"
> )
> 
> func initLogger() {
> 	log.AddHook(new(GoIDFieldHook))
> 	log.SetFormatter(&log.TextFormatter{
> 		SortingFunc: SortingFunc,
> 	})
> }
> 
> type GoIDFieldHook struct{}
> 
> func (h *GoIDFieldHook) Levels() []log.Level {
> 	return log.AllLevels
> }
> 
> func (h *GoIDFieldHook) Fire(e *log.Entry) error {
> 	e.Data["go_id"] = fmt.Sprint(goID())
> 	return nil
> }
> 
> var routinePrefix = []byte("goroutine ")
> 
> func goID() string {
> 	buf := make([]byte, 32)
> 	runtime.Stack(buf, false)
> 	return string(bytes.Fields(bytes.TrimPrefix(buf, routinePrefix))[0])
> }
> 
> var fieldSeq = map[string]int{
> 	"time":  0,
> 	"level": 1,
> 	"go_id": 2,
> }
> 
> func SortingFunc(fields []string) {
> 	fmt.Println(fields)
> 	sort.Slice(fields, func(i, j int) bool {
> 		if fields[i] == "msg" {
> 			return false
> 		}
> 		if iIdx, oki := fieldSeq[fields[i]]; oki {
> 			if jIdx, okj := fieldSeq[fields[j]]; okj {
> 				return iIdx < jIdx
> 			}
> 			return true
> 		}
> 		return false
> 	})
> 	fmt.Println(fields)
> }
> 
> func main() {
> 	initLogger()
> 	log.Info("something")
> }
> ```

DisableColors: true
