### ISSUE TITLE
NullLogger

### ISSUE THREAD

**Issue by jpastoor** [sirupsen/logrus#996]
Hello,

When writing tests I often want to inject a logger that is a no-op. This is an alternative to the more verbose conditional logging. (Or having to write the a helper function or multi-line logger initialization in the tests). 

Would you be interested in a small PR that adds some syntactic sugar to make it easier to initialize such a logger, i.e.
```
// Creates a logger instance that discards all output
func NullLogger() *Logger {
	log := New()
	log.SetOutput(ioutil.Discard)
	return log
}
```
(similar in naming and function as PHP's `Psr\Log\NullLogger`)

**Comment by gguridi** [comment]
I think a specific constructor for this was discarded some time ago #731

**Comment by markphelps** [comment]
Closing per the project being put into [maintenance mode](https://github.com/sirupsen/logrus/commit/4ecd9a62bd57b6533e0d87ae23a6b10adc32b5ce)
