### ISSUE TITLE
Writer() wraps with INFO level 

### ISSUE THREAD

**Issue by c-bg** [sirupsen/logrus#997]
***What I did*** 
```go
log.SetLevel(log.DebugLevel)
stdoutLogger := log.New()
stdoutLogger.SetOutput(os.Stdout)
stdoutLogger.SetLevel(log.DebugLevel)
log.SetOutput(stdoutLogger.Writer())
log.Debug("asdf")
```
***Expected behavior***
Same or at least similar as after
```go
log.SetLevel(log.DebugLevel)
log.Debug("asdf")
```
 i.e. 
`DEBU[0000] asdf`

***Actual behavior*** 
In reality, this results in 
`INFO[0000] time="2019-08-02T11:59:19+02:00" level=debug msg=asdf `

**Comment by pradykaushik** [comment]
I'm guessing it's something to do with the [formatter](https://github.com/sirupsen/logrus/blob/5bd5a315a50f7f5663063a3f608757fdca721f7f/formatter.go#L26)?

**Comment by freeformz** [comment]
use `log.SetOutput(stdoutLogger.WriterLevel(log.DebugLevel))` instead of `log.SetOutput(stdoutLogger.Writer())`

See also: https://github.com/sirupsen/logrus/pull/1017
