### ISSUE TITLE
Stamping milliseconds to the log line

### ISSUE THREAD

**Issue by abhay8nitt** [sirupsen/logrus#998]
I have been using logrus for a while now.. The log messages log the following timestamp
time="2019-08-02T14:58:01Z" level=info
How do I stamp the milliseconds to it something like this?

2019-08-02T14:58:48.623Z

Apologies.. I could not apply label to the issue to question

**Comment by freeformz** [comment]
By default, logrus uses [Go's RFC3339](https://golang.org/pkg/time/#pkg-constants) format: 

```go
RFC3339     = "2006-01-02T15:04:05Z07:00"
```

So, create a [TextFormatter](https://godoc.org/github.com/sirupsen/logrus#TextFormatter) and set it's `TimestampFormat` like so:

```go
f := sirupsen.TextFormatter{
  TimestampFormat: "2006-01-02T15:04:05.000Z07:00",
  ...
}
```

This will (or should) give you lines like so (.076 ms):
```
time="2019-08-02T14:58:01.076Z" level=info
```

PS: The RFC3339Nano format may be acceptable for your use case, although provide even higher precision. If so, then use:

```go
f := sirupsen.TextFormatter{
  TimestampFormat: time.RFC3339,
  ...
}
```

Read the constant section linked above to understand more about Go's time package formatting.

**Comment by abhay8nitt** [comment]
Sure thank you @freeformz would try this out

**Comment by freeformz** [comment]
@abhay8nitt Did this resolve your issue?
