### ISSUE TITLE
How to generate Log file in XML/HTML format?

### ISSUE THREAD

**Issue by sandeepmeenuga** [sirupsen/logrus#999]
How to generate Log file in XML/HTML format? 
So, we can open it in browser.

**Comment by freeformz** [comment]
I believe you would need to create your own [Formatter](https://github.com/sirupsen/logrus/blob/master/formatter.go#L26).

While my search wasn't exhaustive, I did look around for one that exists, but didn't find any.

**Comment by dgsb** [comment]
Nothing is provided by logrus, a custom formatter needs to be implemented.
